### ISSUE TITLE
3.5 Beta - PlayerCommands

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#100]
`PlayerCommands` in /aach list references to `CommandAchievements`.

![aach1](https://cloud.githubusercontent.com/assets/13700636/20637762/4c2445fe-b391-11e6-9c09-dd5f32a9a1d0.png)
![aach2](https://cloud.githubusercontent.com/assets/13700636/20637763/4d42c596-b391-11e6-9ff4-a5795020c0e1.png)

Default config, Spigot 1.10.2

**Comment by Platinteufel** [comment]
`PlayerCommands` = Paper
`Commands` = Bookshelf

**Comment by PyvesB** [comment]
Hello,

Good catch, will be fixed in a minute as well!

Cheers,

Pyves
