### ISSUE TITLE
3.5 Beta - Lava and waterbucket

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#101]
Please think about adding a short delay (let's say 10 seconds) between each count for `lavabucket` and `waterbucket`. Otherwise those categories are senseless since you can spam them by holding your right mouse key. ;-)

**Comment by PyvesB** [comment]
Hello,

I've implemented the cooldown you requested; it also covers categories Beds, MusicsDiscs and Brewing, which are the ones that can most easily be abused without doing any "costly" action. The cooldown time as well as an action bar message are configurable. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Great, thank you! If there are no more issues don't hesitate to release the new version, it contains some awesome features! ;-)
