### ISSUE TITLE
4.0 - Commands Entered

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#103]
Hey Pyves,

first of all: **Thank you** for this update and your hard work!

Just found a little bug in 4.0:
If I type `/aachbook` the command counts for ...

```
PlayerCommands:
  'aachbook':
    '10':
      Message: Obtain 10 achievement books!
      Name: playercommand_aachbook_10
      DisplayName: Reader
```
.. but of course the server will say "Unknown command". 

I don't know how it's handeld if the aach book is on cooldown `TimeBook: 900`, does it count anyway?

**Comment by PyvesB** [comment]
Hello,

You're right, it's so simple I didn't even think about someone entering /aach book. Will see how I can manage to deal with that. ;-)

Cheers,

Pyves
