### ISSUE TITLE
TPing counts for walking distance

### ISSUE THREAD

**Issue by PsychoGrogan** [PyvesB/AdvancedAchievements#104]
Hi, I have a little issue.

I have achievements for distance walked.

But I have an essentials warp to a different place which is over 10000 blocks away. It triggered the 10000 walking distance achievement without moving a single block.

**Comment by Platinteufel** [comment]
Are you running the latest version of AdvancedAchievements (4.0)?

**Comment by PsychoGrogan** [comment]
Yes, I'm using 4.0

**Comment by PyvesB** [comment]
Hello,

I will look into it, it has always been a painful bug to track down and fix. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
I can't reproduce it anymore. I'm sure there was a ticket a long time ago.
#26

**Comment by PyvesB** [comment]
This was indeed supposed to have been fixed a while ago, and I am also unable to reproduce the described bug after some testing. Which Essentials plugin are you using? What version? How is the warp triggered (signs, commands, etc.)?

**Comment by PsychoGrogan** [comment]
I'm using EssentialsX latest version, and it's triggered via signs and
commands like /spawn.

**Comment by PyvesB** [comment]
I have not been able to reproduce with the latest version of EssentialsX, either via signs or commands. What version of Minecraft are you using? Are you using Spigot or Bukkit? Have you got a recently compiled version?

Could you pleaseshow me your EssentialsX configuration on Gist or Pastebin?

Are you using any other plugin that could mess up with teleportations (possibly a protection plugin for instance)?
