### ISSUE TITLE
Language file inconsistency

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#106]
![unbenannt](https://cloud.githubusercontent.com/assets/13700636/20776954/fdc8787c-b763-11e6-8095-1c46d71ddd2d.PNG)

list-**milk**buckets: "Buckets filled with **Water**!"

Not a big issue, just a little typo. It works anyway. ;-)

**Comment by PyvesB** [comment]
Thanks for the typo report!

Cheers,

Pyves
