### ISSUE TITLE
RestrictCreative doesn't work for LavaBucket & WaterBucket

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#108]
RestrictCreative doesn't affect the categories LavaBucket & WaterBucket. The statistic increases also if I'm in gamemode creative.

**Comment by PyvesB** [comment]
Hello,

I was assuming the behaviour would be the same as with milk buckets, which can't be filled in creative mode. This will be fixed in a minute.

Cheers,

Pyves
