### ISSUE TITLE
Treasure Hunter

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#109]
I'm just wondering if this is the intended behaviour for `Treasure Hunter`.

https://youtu.be/2R68zSwV6wg

Cheers ;-)

**Comment by PyvesB** [comment]
Hello,

I had no idea you could do this with a fishing rod, thank you for pointing it out! I'll disable this behaviour and fix the bug reported in #110 in a couple of minutes. 

Cheers,

Pyves
