### ISSUE TITLE
Players receiving the same achievements multiple times

### ISSUE THREAD

**Issue by mwester01** [PyvesB/AdvancedAchievements#1094]
Been setting up this plugin over the last few days, and I am a huge fan, however there is this one issue that keeps stopping me in my path. I know this has been an issue for some time as several other users have brought it up as well in the past, but as of today, NOV 1, 2021 there is still this bug where having multiple achievements under the same 'type' category will give the player a previously earned achievement over and over again. This is incredibly frustrating when trying to create different tiers of achievements under the same category. 

I think it would be better to create groups of achievements by defining a name of a group, and then in each achievement node defining the type of achievement it would be, rather than have all achievements grouped by their type.

**Comment by PyvesB** [comment]
Hello @mwester01 ! 👋🏻 

As announced a few weeks ago, this project is no longer maintained (see #1083 or spigotmc.org for more information), so I'll unfortunately not be able to provide support. The repository will be archived soon. Enjoy configuring new achievements on your server!
