### ISSUE TITLE
Early 1.9 Support

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#11]
Hey, 
according to this thread in spigot forums
 https://www.spigotmc.org/threads/minecraft-1-9-more-info.124273/ 
Spigot/Bukkit 1.9 will be released at Feb 26th. The 1.9 API should be already available on git. Is it possible to support early builds in time? That would be awesome, I really like your work. :)

**Comment by PyvesB** [comment]
Hello,

Thanks for the piece of news! I'll wait a bit longer before I start working on it, there seem to be a huge number of pulls and changes going on currently. The support via a new 2.4 release will be provided around the 26th, I will just eventually need some help from bug reporters once the new version is actually released. ;-)

**Comment by SgtLegoTown** [comment]
i'am willing to help test (1 thing i'am good at is breaking things)

**Comment by PyvesB** [comment]
The Spigot update has been delayed until next week, we will unfortunately have to wait a little while longer.

**Comment by Platinteufel** [comment]
Maybe we'll see a release today or tomorrow, I would also like to test the 2.4 (pre)version then. :)

**Comment by SgtLegoTown** [comment]
still need help testing beta version ?

**Comment by PyvesB** [comment]
Hello,

I have released version 2.4 which includes fixes to all the bugs I found with Minecraft 1.9, so feel free to download it and open reports for any problems you may encounter. ;-)
