### ISSUE TITLE
New categories don't increase

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#112]
Well, seems like some issues are only found after installing the plugin on my main server. Sorry. ;-)

https://github.com/PyvesB/AdvancedAchievements/pull/111
Cheers

**Comment by PyvesB** [comment]
Hello,

Indeed, completely missed out most of the new permissions. These things are really hard to track down as I generally test as Operator with full permissions... Thanks for the pull request!

Cheers,

Pyves
