### ISSUE TITLE
Idea: Catagories!

### ISSUE THREAD

**Issue by melerpe** [PyvesB/AdvancedAchievements#113]
If you have a server like a themepark server where you can get achievements by going on rides or finding a  new area. It is nice to have some sort of button to switch between the ride and area achievements!

**Comment by PyvesB** [comment]
Hello,

I do not really understand what you are asking for. Could you please be more specific?

Cheers,

Pyves

**Comment by Dolzur** [comment]
Actually there are categories. They're called "Entites killed' etc.

**Comment by PyvesB** [comment]
I have really got no idea of what is happening here, I'm therefore closing this issue.
