### ISSUE TITLE
Custom rewards description

### ISSUE THREAD

**Issue by Dolzur** [PyvesB/AdvancedAchievements#114]
Hello there! It would be great to add an option to set a custom reward description. I actually dont like what it is now: item, money etc.

I'd rather see it like: "You will get a 5000$", or even more, "you will be able to fly!" or "You will be called Reaper" (like in the Fable lol). So that it will be more self-explanatory and not just an "item" or "custom"

And little additon: how about to make a custom-item reward which consumes itself after usage and executes a command? For example: after completing an achievement user gets a slimeball or nametag which executes /pex user PLAYER prefix <prefix> and then dissapears. It will need also a permission on use.

**Comment by PyvesB** [comment]
Hello,

I will add optional AMOUNT and ITEM variables in the corresponding reward messages in the language file in the next update. ;-)

You can already define custom rewards or commands by using something similar to the following:
```
Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
```

You can directly add your /pex command as a reward for instance.

Cheers,

Pyves

**Comment by Dolzur** [comment]
I mean the description of reward, when you hover the achi in the GUI. It says "item", "other" etc. And I want it to have an option which lets me write my own description of the reward.

**Comment by Dolzur** [comment]
And for /pex command

U see, the problem is I want my players to get custom tags on completing some achievements, but I want to let them choose if they want to change their prefix or not. If you advice me the resolution for this one, I will appreciate it very much

**Comment by PyvesB** [comment]
What I had in mind was the following:
- have an AMOUNT variable in the list-reward-money language file parameter. For instance if you specify  "You will get AMOUNT", the plugin will automatically change that as "You will get 5000$" in the /aach list command.
- similarly have an ITEM variable in the list-reward-item parameter, and let the plugin automatically determine and insert the name of the item.

Having a custom message for each single achievement will make the configuration file more complicated and harder to set up. Furthermore it would require structural changes that would probably make all current configurations no longer valid, or at least force me to implement clumsy workarounds to keep old configurations compatible. I don't think it's a good idea. Nevertheless if you want to add more personalised information about the outcome of an achievement, you can use the "Goal" parameter in the config (and for instance put "you will be able to fly!" inside), and let the reward section display more precise information as mentioned above.

I don't know how /pex command works, but can't you give your players a permission to change their prefix, or give them access to a command that resets their prefix if they are not happy with it?

Cheers,

Pyves

**Comment by Dolzur** [comment]
Well, that sounds smart as well. Am I able to use multipl lines in goal section?

**Comment by PyvesB** [comment]
If you put an "\n" in the "Goal" message, you may be able to break lines. Nevertheless, if this works, this would probably make the progress bars take the length of the whole text.
