### ISSUE TITLE
4.0.2 - Smelting

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#115]
Welcome to a new episode of "Is this intended?" ;-)

https://youtu.be/kuFlkqf9vdU

Well, just joking, but it seems like the `Smelting` category needs some additional checks, so that only items from the furnance output slot will be counted.

Cheers ;-)

**Comment by PyvesB** [comment]
Hello,

Will be fixed in the next update, thanks! ;-)

Cheers,

Pyves
