### ISSUE TITLE
Using Player class in getPlayerAchievementsAmount(Player p) method (SQLDatabaseManager.java)

### ISSUE THREAD

**Issue by ristolah** [PyvesB/AdvancedAchievements#116]
Hello, I'm Rsl1122, currently developing Plan (Player Analytics) and I'm trying to hook into this plugin.
Unfortunately the method that gives data in your plugin uses Player instead of OfflinePlayer to access the UUID - and so, my plugin can not retrieve the data from players who are offline.
I had the same issue with Factions, but they had another method that used UUID, and I could circumvent the issue.

Is there another method that returns the same data but takes UUID or OfflinePlayer as input?

Thanks,
Rsl

**Comment by PyvesB** [comment]
Hello,

Indeed, I see why the current implementation is blocking you. I'll investigate whether I can come up with a solution that uses Java Reflection, otherwise I'll simply add the method you have requested.

Looking forward to trying your plugin. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hi again,

I have attempted to use some Relection features to directly access the concrete CraftBukkit and Minecraft classes, but there doesn't seem to be any easy workaround to create a simple object that implements the Player class.

I've therefore added a method using an UUID string. As this will only be released in version 4.0.3, earlier versions of the plugin will not be able to support offline players, so you should add some sort of version checking or error handling and ask your users to use the latest version of Advanced Achievements (which is highly recommended anyway) if they want the full range of features.

Another solution to avoid this problem would have been to write some sort of "dummy" implementation of the Player interface, but this has other drawbacks.

Let me know if you need anything else. ;-)

Cheers,

Pyves

**Comment by Rsl1122** [comment]
Hey, thanks for the update on such a short notice!
Is there a way for me to download version 4.0.3 jar anywhere as my coding environment doesn't let me compile the code without having the proper method visible for it. ("String cannot be converted to Player")
Also, since it is using the string, is it just UUID.toString() that works with it?

-Rsl

**Comment by PyvesB** [comment]
Why don't you simply clone this repository and recompile Advanced Achievements? You can also wait for the official update, will probably come out sometime tomorrow if nothing comes up on my side.

**Comment by Rsl1122** [comment]
Ah of course :D
Thanks. :)

**Comment by PyvesB** [comment]
_Normally_ those are warnings, they should not prevent you from running "mvn install". ;-)

**Comment by Rsl1122** [comment]
Apparently it did build it but it was in a different folder than what I was used to and didn't say "Build Successful". So yeah, maybe one shouldn't code at 1 am :D
