### ISSUE TITLE
add custom command reward?

### ISSUE THREAD

**Issue by Diddyer** [PyvesB/AdvancedAchievements#119]
can add option to reward custom command like this?

/give @p minecraft:stone 1 0 {display:{Name:"Example Name"}}

Example

Kills:
  zombie:
    '1':
      Message: 'The Walking Dead!'
      DisplayName: 'ZombiesTime'
      Name: kills_1_zombie
      Reward:
        Money: 1000
        Item: diamond 3
        **CUSTOMCOMMAND**: /give @p minecraft:stone 1 0 {display:{Name:"Example Name"}}

**Comment by Platinteufel** [comment]
As you can see in the default config that's already implemented. ;-)

  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: break_1_stone
      DisplayName: Cobble!
      # Use semicolons for multiple command rewards. PLAYER will be replaced by player's name.
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5

**Comment by Diddyer** [comment]
rewrite question,

this option:

CUSTOMCOMMAND: /give @p minecraft:stone 1 0 {display:{Name:"Example Name"}}

**Comment by Platinteufel** [comment]
Yes, that's already possible. ;-)

Reward
.     Command: give PLAYER minecraft:stone 1 0 {display:{Name:"Example Name"}}
