### ISSUE TITLE
1.9 Error

### ISSUE THREAD

**Issue by Elumis** [PyvesB/AdvancedAchievements#12]
I'm sure your probably working on this since 1.9 like just updated but ehh its an error and thought I'd post it :)

http://hastebin.com/nurumujesi.avrasm 

Awesome plugin cant wait for 1.9 update!

[23:13:06 INFO]: Plugins (15): WorldEdit, DeluxeTags, PlaceholderAPI, DeluxeMenus, DeluxeJoin, PermissionsEx, NametagEdit, ActionAnnouncer, Vault, Essentials, AdvancedAchievements, MarriageMaster, Towny, EssentialsSpawn, DeluxeChat

**Comment by Sprungente** [comment]
On my Testserver runs the plugin not fine. When I take an achievement than i get the achievements (for example travel with a boat for 200m) all time every 3 seconds.

**Comment by PyvesB** [comment]
Hello Elumis,

I do not seem to be able to access your paste, could you please upload it again?

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello again,

This issue is normally resolved in the two latest versions of the plugin. Please download version 2.4.1. Feel free to open a new issue if ever you encounter any other problems with the plugin, and feel free to star the project. ;-)
