### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by Imothep80** [PyvesB/AdvancedAchievements#120]
Hi,

Signs for viewing top/global/weekly/monthly stats.
i.e.:
1. Line: [aach]
2. Line: top
3. Line: 1

Shows the first top ranked Player. If you place a skull above they can Show his skull.

i.e.:
1. Line: [aach]
2. Line: weekly
3. Line: 4-6

Shows the place 4 to 6 from the week.

**Comment by PyvesB** [comment]
Hello,

I don't really find this feature interesting, signs in Minecraft are in general not a good way to display information and in this case you will only have room for at most one player name displayed on the sign, provided the name of the player is short enough to fit within a line. ;-)

Cheers,

Pyves

**Comment by Imothep80** [comment]
Thx :)
Btw. Great work!
