### ISSUE TITLE
webstats

### ISSUE THREAD

**Issue by elstringer** [PyvesB/AdvancedAchievements#121]
Ability to display statistics as well as successes on are site that would be well

**Comment by PyvesB** [comment]
Hello,

I have little knowledge in web development. This would require a huge amount of work for only a small benefit, as most of the statistics can already be seen in game.

Cheers,

Pyves

**Comment by elstringer** [comment]
I can contribute to the project if you wish! I currently create my site, I can share my source!
https://minecraft.tec.network/?id=ELstringer

**Comment by PyvesB** [comment]
Well I think the best here would be for you to fork the project and integrate either some sort of webserver directly in the plugin (like Dynmap), or develop an independent module based on the database schema. We could then somehow merge it back into the main project, or keep it as an independent add-on you publish to the Bukkit/Spigot resources pages. But again, I unfortunately don't have the knowledge nor the time to drive such a development. ;-)
