### ISSUE TITLE
Kingdoms

### ISSUE THREAD

**Issue by Loonyy** [PyvesB/AdvancedAchievements#122]
Hey, I'm getting this error:
http://pastebin.com/MjU1b6vb

It's with Kingdoms, when doing /k home (to teleport to the Kingdoms home) and it seems it breaks the feature, they never teleport.

Is this issue with your plugin or Kingdoms?
https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-11.11833/

**Comment by PyvesB** [comment]
Hello,

As I do not own a copy of that plugin, there is little I can do to try and reproduce the error and investigate further. I'll just give a few thoughts based on the content of the logs.

Based on the error log, it seems as if either the player is not in a world or is in a world which hasn't got a name. This is non standard Bukkit behaviour, which may be introduced by the Kingdoms plugin.

In all cases Advanced Achievements is not modifying any teleportation events, it only monitors things to get statistics, it seems as if Kingdoms is failing independently of that.

Cheers,

Pyves
