### ISSUE TITLE
Idea - Delete prefix in messages

### ISSUE THREAD

**Issue by MENSOZO** [PyvesB/AdvancedAchievements#123]
Hi, I want to remove the prefix in the messages, but can not do it, because this function does not exist. Please add this feature.

**Comment by PyvesB** [comment]
Hello,

I do not see such a feature as beneficial for the mainstream user. I try to give a consistent, unique and nice visual aspect to all my plugins, just removing completely the prefix would go against this. I you really want to do it, simply clone the project and alter the value of the _chatHeader_ field in the _AdvancedAchievements.java_ class, then recompile your custom version of the plugin. All instructions are provided in the repository's README. ;-)

Cheers,

Pyves
