### ISSUE TITLE
A couple of newbie questions

### ISSUE THREAD

**Issue by EvanWells** [PyvesB/AdvancedAchievements#124]
1) How can I edit how the chat message looks. It says "PLAYER received achievement xxxxx"
I would love the change the color of that from dark grey to something else. Where is this located and is it easily changed?
2) Do any of y'all know where I can find an already made list of achievements I can add to my server? Like a bunch of stuff to really appeal to the Achievement Hunters on my server. Thanks in advance for any help!

Evan

**Comment by PyvesB** [comment]
Hello,

1. Change the value of _achievement-received_ in the _lang.yml_ file. To change the colour put a _§_ at the beginning of this message followed by the colour code you want.

2. Well there are quite a few ideas in the default configuration. You've also got an old configuration file shared by RobinTrevize [here](https://www.spigotmc.org/attachments/config-txt.113290/). It will need updating to cover all the new achievement categories and configuration parameters and possibilities, but it can give you some extra ideas. ;-)

Cheers,

Pyves
