### ISSUE TITLE
Brewing cooldowns

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#125]
The cooldown for instance `Brewing` should be improved. A lot of players are confused because they brew 3 potions at a time, take out the first potion and the other 2 potions don't count because of the cooldown. 
Well, I think you want to prevent that players put a potion back into the brewing stand output slots and remove it again, so that they spam this achievement. This is an issue we have to deal with. But in my opinion you should be able to take out 3 potions till the cooldown for the next triple starts. ;-)

**Comment by PyvesB** [comment]
Hello,

I will look into that. ;-)

Cheers,

Pyves
