### ISSUE TITLE
It is possible add groups to achievements?

### ISSUE THREAD

**Issue by desquiciado** [PyvesB/AdvancedAchievements#127]
Hello! Excelent plugin :)
I think if is posible add groups to your plugin, example:
Player[level1] (need break a dirt to level up)
Player[level1] = group
Player[level2] (need kill a zombie to level up)
Player[level3] (need make a workbench to level up)

Exmaple config of your plugin:
Breaks: 
  dirt:
    '1':
      Message: '&1The first dirt!'
      Name: break_1_dirt
      DisplayName: Dirt!
      group: Player[level1]
      Reward:
        Command: /pex user %user% promote
Kills:
  zombie:
    '1':
      Message: '&8The first time you killed a zombie!'
      DisplayName: The Walking Dead
      Name: kills_1_zombie
      group: Player[level2]
      Reward:
        Command: /pex user %user% promote
Crafts:
  workbench:
    '1':
      Message: The first time you crafted a workbench!
      Name: craft_1_workbench
      DisplayName: Builder
      group: Player[level3]
      Reward:
        Command: /pex user %user% promote

Example of pex config:

groups:
  Player[level1]:
    options:
      prefix: '&2&lPlayer[level1]&f'
      default: true
      rank: '3000'
    permissions:
    - permissions.here
  Player[level2]:
    options:
      prefix: '&2&lPlayer[level2]&f'
      default: true
      rank: '2999'
    permissions:
    - permissions.here
  Player[level3]:
    options:
      prefix: '&2&lPlayer[level3]&f'
      default: true
      rank: '2998'
    permissions:
    - permissions.here

That was mi idea. If you can do, and you are interested do it please :P

**Comment by PyvesB** [comment]
Hello,

I do not understand what the group would be used for in the plugin. You can already set _/pex_ commands to change the rank of players as achievement rewards, and you can also set specific permissions for achievement categories or sub-categories. ;-)

Cheers,

Pyves

**Comment by desquiciado** [comment]
Thanks bro!
