### ISSUE TITLE
Per World Achievements?

### ISSUE THREAD

**Issue by agentroop** [PyvesB/AdvancedAchievements#129]
Could it be possible to add a parameter to an achievement that makes it so that progress towards that achievement can only be gained in a certain world? I'm running a multiverse server that has a Creative world, and I want to allow players to get achievements for placing a certain number of blocks on creative, but I don't want players to be able to earn other achievements such as crafting through the creative server. 
How can I separate these?

**Comment by PyvesB** [comment]
Hello, 

This is a very specific feature that has never been requested before. Implementing it would not benefit many users and would make the configuration more complicated and tedious for most.  The simplest for you would be to fork the project and to add a non configuration dependent check to the categories you want to limit to some specific worlds or game modes. 

Cheers, 

Pyves
