### ISSUE TITLE
java.sql.SQLException: Incorrect integer value

### ISSUE THREAD

**Issue by Feeriix** [PyvesB/AdvancedAchievements#13]
Using version 2.4.
http://pastebin.com/V61qNQj9

**Comment by PyvesB** [comment]
Hello,

I think I know what went wrong here. It will be corrected in the next update, for now just don't use the Craft achievements. Thank you for your report! ;-)

**Comment by PyvesB** [comment]
Hello again,

This issue is normally resolved in the two latest versions of the plugin. Please download version 2.4.1. Feel free to open a new issue if ever you encounter any other problems with the plugin, and feel free to star the project. ;-)
