### ISSUE TITLE
Stats reset?

### ISSUE THREAD

**Issue by LucasDane** [PyvesB/AdvancedAchievements#131]
Hi, I got a small question.. Is it possible to reset the progress in Achievements?
So.. if u mined 5 out of 10 stone, and reset the progress.. its 0 out of 10?

Lucas Dane,

**Comment by PyvesB** [comment]
Hello,

No, this is not possible, unless you manually update your database entries. The entries are in the _breaks_ table with _blockid_ equal to _stone_.

Cheers,

Pyves
