### ISSUE TITLE
NPE on world change

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#133]
Currently I'm using two commandblocks that give my players a special command-achievement and teleport them back into my main world immediately. In fact of this teleport there's a NPE in console:
http://pastebin.com/f5UvfZ6h
`Errors while trying to display achievement screen title. Is your server up-to-date?`

Cheers. 
Thank you for your amazing support and frequently updates! ;-)

**Comment by PyvesB** [comment]
Hello Platinteufel,

I'm not sure why this could be happening. Could you please give the attached version a try? It includes some additional logging, could you paste the two lines that should appear before the exception is thrown in the console?

[AdvancedAchievements-4.1.3.zip](https://github.com/PyvesB/AdvancedAchievements/files/733130/AdvancedAchievements-4.1.3.zip)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Well, shouldn't be hard to reproduce. 
I'll set up a server with Essentials, Multiverse & Advanced Achievements. Then I'll set the spawn to the main world. I'll create a new world with Multiverse and place two linked commandsblocks there. The first one will give the player a command-achievement, the second one will teleport him back to spawn (just in the same second). I will try it with your version now. ;-)

**Comment by Platinteufel** [comment]
I'm sorry, it was not because of the world change. 
As you can see in my logs http://pastebin.com/eT2dgqkL I used "" in my title for _Adventuremap "The Dropper"_. It seems like that's the reason for my exception.

**Comment by PyvesB** [comment]
Yes, this is the reason. The quotations marks are breaking the JSON format used to create the title. Try to escape the quotations by using \"The Dropper\" instead.

**Comment by Platinteufel** [comment]
Thank you, now it works as expected.

**Comment by PyvesB** [comment]
I will leave this issue opened for now, I will implement a small fix to handle the escaping automatically. ;-)
