### ISSUE TITLE
Specific player kills?

### ISSUE THREAD

**Issue by SwedishVikingMC** [PyvesB/AdvancedAchievements#134]
Is there a way to add a specific player kill achievement? e.g 
Kills:
  notch:
    '1':
      Message: '&8Kill the creator of minecraft!'
      DisplayName: Officially a murderer
      Name: kills_1_notch
      Reward:
        Money: 100 
If there is not, maybe it would be a cool feature to add especially for kitpvp servers :)

**Comment by PyvesB** [comment]
Hello,

This is not currently possible, you can only track player kills as a whole. I'll keep your idea in mind for a future update. ;-)

Cheers,

Pyves
