### ISSUE TITLE
New /aach toggle command

### ISSUE THREAD

**Issue by Hannaaw** [PyvesB/AdvancedAchievements#135]
Hello.

This is a feature request, very simple and wanted by our community. Would it be possible to add a command called '/aach toggle', just so players could turn all the completed achievement messages off and only see their own? I get that there is an option to turn all of them off in the config but some players want to see them and some don't. This would be extremely helpful.

Thanks :)

**Comment by PyvesB** [comment]
Hello,

Shouldn't be too hard to add. Will be implemented in a future update. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
This has been implemented in the commit mentioned above. The effect of /aach toggle lasts until the plugin has been reloaded or the server restarted. Please tell me if you find any issues. ;-)
