### ISSUE TITLE
Achievements not all saving on Restart

### ISSUE THREAD

**Issue by OwningProds** [PyvesB/AdvancedAchievements#137]
When I restart my server not all achievements save for some reason.
Please let me know on how possibly I can go about fixing this.

- Andrew

**Comment by Platinteufel** [comment]
Some more information would be nice for PyvesB. ;-)

Server version? Plugin version? Storage options (sqlite, mysql, ..)? Does it also reset some stats?

**Comment by PyvesB** [comment]
Hello,

No new for over 10 days, assuming the issue has been fixed and closing it.

Cheers,

Pyves
