### ISSUE TITLE
ADD more features

### ISSUE THREAD

**Issue by CronusMaker** [PyvesB/AdvancedAchievements#138]
add boton for back and next archviments

add custon variables formore functions exemple 
special_login for login day especial 

Connections:
  '1':
    Message: bem vindo ao servidor!
    Name: connect_1
    DisplayName: Premio de login diario 1 dia
    Money: 1
    Reward:
      Command: give PLAYER 264 1; give PLAYER 265 5
  '1':
    Message: One year of server
    Name: Special_day_1
    DisplayName: this is one day especial
    Money: 1
    Reward:
      Command: give PLAYER 264 1; give PLAYER 265 5

**Comment by Platinteufel** [comment]
For those special achievements you should create Command-Achievements and run /aach give myAchievement playername. ;-)

**Comment by CronusMaker** [comment]
I wanted the login system even when the player logged in the game he won the prize without the ness of having to use the command to be able to get the prize so that I would have to configure the delay and even then the exentials would not manage right The time of one prize and another

**Comment by PyvesB** [comment]
Hello,

I do not understand what's going on here.

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Well he's interested in a _"login on a special day"_ category, for example "Login at christmas", "Login at eastern", "Login on our 1 year anniversary". 
I told him to make command achievements for that.

**Comment by PyvesB** [comment]
Yes and it is an easy thing to set up, many plugins can run commands on connection. I do not understand what the "boton for back and next archviments" is about, nor what the "special_login" variable is about.

**Comment by Platinteufel** [comment]
I think the "special_login" variable is the "login on a special day" thing and he's asking for buttons to switch to the next/previous category without going back to /aach list main menu.

**Comment by PyvesB** [comment]
No news for two weeks, closing this obscure issue.

Regards,

Pyves
