### ISSUE TITLE
.bak

### ISSUE THREAD

**Issue by UltimateNetworks** [PyvesB/AdvancedAchievements#14]
Whenever I reload the plugin the config turns into config.yml.bak, and there is another config generated that hardly has anything in it, just

CheckForUpdate: true
RetroVault: false
Firework: true
Sound: true
Icon: â
ChatNotify: false
BookSeparator: ''
RestrictCreative: false
MultiCommand: true
DatabaseBackup: true
ExcludedWorlds: []
TopList: 5
AdditionalEffects: true
FireworkStyle: BALL_LARGE
ObfuscateNotReceived: true
HideNotReceivedCategories: false
TitleScreen: true
Color: '5'
TimeBook: 900
TimeList: 0
AsyncPooledRequestsSender: true

**Comment by PyvesB** [comment]
Hello,

Could you please provide me with me a version of the configuration you're trying to set, on pastebin.com if possible?

Cheers,

Pyves

**Comment by PyvesB** [comment]
I'm assuming you solved your problem, as it has been more than one week, so I'll close this issue.

Cheers,

Pyves
