### ISSUE TITLE
Playtime still tracked with restrict set to true

### ISSUE THREAD

**Issue by VerumUK** [PyvesB/AdvancedAchievements#140]
Even though I have "RestrictCreative: true" my admins are still having their playtime tracked while in creative and spectator mode, is this a bug? I assumed it was since daily logins isn't tracked unless you switch to survival.

Aach: 4.1.5
MC: 1.11.2

Edit: Just noticed it does indeed say PlayTime shouldn't be tracked in the config.

**Comment by Platinteufel** [comment]
Hm, in creative mode the statistics shouldn't increase (this check doesn't effect spectator gamemode, but that could be useful too).
https://github.com/PyvesB/AdvancedAchievements/blob/11afc3267c3f116dc9d1d8d3ed3ece4860f14485/src/main/java/com/hm/achievement/runnable/AchievePlayTimeRunnable.java#L82

**Comment by VerumUK** [comment]
Ah if there's a permission to bypass it then that explains why my playtime is going up (I'm opped), must just be the spectator mode that's been doing it for my admins, would be useful if you could add that too :)

**Comment by Platinteufel** [comment]
It's not my project, I just try to help people here. :)
We need to wait for @PyvesB, maybe he will extent RestrictCreative to RestrictCreativeSpectator. ;-)

**Comment by VerumUK** [comment]
Ah yeah, didn't realise that, haha.

Side note for Pyves, I got my admin to stay in gamemode 1 for a while, it added another 2 hours to his playtime in a 3-4 hour period. They don't have any permissions to do with aach.

**Comment by PyvesB** [comment]
Hello,

Thank you for your help Platinteufel!

Lines 47 to 50 of _AchievePlayTimeRunnable.java_ are supposed to take care of this, I am surprised it is not working for you. I will do some extra testing at the beginning of the week. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Unfortunately I can't reproduce the increasing playtime in creative mode. After one hour online my statistics didn't increase at all.

**Comment by PyvesB** [comment]
After some quick testing, I am also not able to reproduce the described bug.

Could you please paste your entire plugin configuration on Github Gist or on Pastebin? Also, could you make sure that you are using the latest Spigot build?

**Comment by VerumUK** [comment]
Config: http://pastebin.com/ttH7peJX
Current Spigot version: git-Spigot-b4417b8-a1d3777 (MC: 1.11.2)

Spigot may be a few days out-dated but nothing major. I do tend to swtch between spectator and creative quite often, so perhaps during check A I was in spectator mode, switched to creative for X time then back to spectator mode by check B, so it simply counted the whole time, maybe?

**Comment by PyvesB** [comment]
I don't see anything unusual in your configuration. 

The plugin runs a scheduled task for _PlayedTime_ achievements, in your case every minute. If you are in spectator mode when the task runs, it will add one minute to your play time count. If you are in creative mode, it will not increase the statistic. If you were switching on a regular basis, then it makes sense that the statistic would increase. ;-)

**Comment by PyvesB** [comment]
By the way, if you want to avoid statistics increasing in spectator mode, there is a new _RestrictSpectator_ parameter in version 4.2 of the plugin.
