### ISSUE TITLE
NPCs getting achievements

### ISSUE THREAD

**Issue by Namnodorel** [PyvesB/AdvancedAchievements#141]
Hey,
I noticed that (player) NPCs created using Citizens can get achievements, too. Good for them, but I don't want them to, especially because players get confused due to the particles. 

Implementeing a check for NPCs is quite easy: https://wiki.citizensnpcs.co/API#Checking_if_an_entity_is_a_Citizens_NPC

Have a good day!

**Comment by PyvesB** [comment]
Hello,

I never realised this was possible. Will be fixed shortly and released officially in the next update. Thank you for your report! ;-)

Cheers,

Pyves
