### ISSUE TITLE
Default Vanilla Achievements

### ISSUE THREAD

**Issue by Corcustos** [PyvesB/AdvancedAchievements#142]
Is it possible to create improved versions of the default achievements? I know I'm able to create a separate achievement for the vanilla achievements that require crafting, eating, traveling, and the basic stuff, but am I able to recreate stuff such as The End? which would require the plugin detecting a player entering a world, 
repopulation which tracks breeding, diamonds to you which tracks me dropping a diamond and another player picking it up, and Sniper duel which detects a skeleton being killed from a distance with a certain weapon? If not, consider this a suggestion. I wasn't able to find any documentation to specify if every vanilla achievement is possible, or if there are any extra variables. I'm wanting to give rewards for the vanilla achievements and keep all of the server achievements consistent with eachother. 

Also, I'm not able to remove the brackets for the plugin icon. I'm wanting to use a word without brackets, but I can only change the content inside of the brackets, and not if they exist or not. 

Hopefully I'm just missing something. I would assume that a plugin like this would have some sort of workaround or feature for this, specially since it's a 2 year old plugin. Either way, if I am missing something then could somebody please direct me on how to do what I'm wanting to accomplish? Is there perhaps a weapon and distance variable for the Kills category, or a variable to detect the other things that I'm trying to do? Any help is much appreciated. Thanks.

**Comment by PyvesB** [comment]
Hello,

Vanilla-type achievements are not currently supported, but most of them are reproducible with the 45 achievement categories or with the _Commands_ category (for instance run an achievement command when you enter the End world).

If you want to change the header beyond the possibilities currently offered by the configuration file, I recommend you simply clone the project and alter the value of the _chatHeader_ field in the _AdvancedAchievements.java_ class, then recompile your custom version of the plugin. ;-)

Cheers,

Pyves

**Comment by Corcustos** [comment]
Do you know if vanilla achievements will ever be supported through this plugin? Also, how would I run a command upon entering the End World? What string of variables would I use, etc. I think I may be missing something here.

**Comment by PyvesB** [comment]
No idea, a lot of the remaining Vanilla achievements are quite boring and not really repeatable, but some might eventually make their way through.

A lot of plugins handle commands when entering worlds or regions, simply set up one of them to trigger a _Commands_ achievement. ;-)
