### ISSUE TITLE
aach list enhancement

### ISSUE THREAD

**Issue by SlimeDog** [PyvesB/AdvancedAchievements#143]
Please implement

> aach list <playerName>

with appropriate permissions. Ops (and console) would find this useful.

**Comment by PyvesB** [comment]
Hello,

The /aach list command is already implemented and has permissions associated with it. Please refer to the documentation. This is also a GUI-related command, so not available via the console. ;-)

Cheers,

Pyves

**Comment by SlimeDog** [comment]
Perhaps my request was too subtle. Please implement a console version.
