### ISSUE TITLE
Add the possibiliy to set some achievements as a "Secret Achievement" ?

### ISSUE THREAD

**Issue by Xemnasiyc** [PyvesB/AdvancedAchievements#145]
Hi there,
What I mean about "Secret Achievement" ?
When you configure some achievements there's an option to set some of them hide if the player hasn't find them or didn't success the previous one. 
But in my case, I just want to hide the last ultimate hardcore achievement (Don't pay attention to the language ^^', just take a look for the '&'s) : 
```
AnvilsUsed:
  '1':
-----
  '15':
-----
  '50':
-----
  '125':
    Goal: '&aUtilisez l''enclume 125 fois'  (Succes = LightGreen)
    Message: '&7Vous avez utilisé votre enclume 125 fois !' (Success = LightGray)
    Name: anvilused_125
    DisplayName: '&6&lForgeron' (Success = Orange Bold)
  '500':
    Goal: '&kEnclumez 00 fois' **(Success = I CAN'T SEE ANYTHING )**
    Message: '&7Vous avez utilisé votre enclume 500 fois !' **(Success = LightGray, it appears only once.. We cannot check a second time what was the objective..)**
    Name: anvilused_500
    DisplayName: '&5&l A Thor et à travers !' (Success = Purple Bold)
    Reward: {}
```

The idea would be : Add an option (True/False) to hide a success (like above ^), but when it's succeeded the text is clear in the /aa list and also in the /aa book.
It would be great, I just spend a lot of time in your plugin and my team and I had had fun to configure it

(I hope my english isn't to bad to read and understand ^^')

Xem' :)

**Comment by PyvesB** [comment]
Hello Xemnasiyc,

Why note simply drop the _Goal_ parameter for that specific achievement and write a quite vague  _Message_? Making something appear once and only once in the GUI would be complicated, as it would require storing additional information in the database. ;-)

Cheers,

Pyves
