### ISSUE TITLE
lang.yml

### ISSUE THREAD

**Issue by xyblues** [PyvesB/AdvancedAchievements#146]
Hello, I really like this plugin, this plugin is great.
I'm sorry for my bad English, I do not know if you can understand what I mean.

![image](https://cloud.githubusercontent.com/assets/15712089/23549445/498209be-0047-11e7-9526-c9b4a9544fc8.png)

I want to add a prefix like this: '&7time:&b&l Mar 3,2017 10:57 AM'

**Comment by PyvesB** [comment]
Hello,

You cannot directly append a prefix to the date. Nevertheless you can either modify the `list-reception` parameter in _lang.yml_, or modify parameters such as `DateLocale` or `DateDisplayTime` in _config.yml_ to change the displaying of the data and make it best suit your needs. ;-)

Cheers,

Pyves

**Comment by xyblues** [comment]
But it can't meet my needs.
Can you add a date prefix parameter in the lang.yml?

**Comment by PyvesB** [comment]
I don't see the point of what you're trying to do. You already have a customisable "Reception date:" field, and you want to add a redundant "time" prefix on the next line; this doesn't even make sense as a full date follows it and not just a time... I doubt this would be useful to many users of the plugin and has actually never been asked, I recommend you modify the code on line 834 of _ListCommand.java_ and recompile a custom version of the plugin. ;-)
