### ISSUE TITLE
Issue with MySql

### ISSUE THREAD

**Issue by Zaneconwell** [PyvesB/AdvancedAchievements#148]
Issue with MySql not sure exactly whats happening.
http://pastebin.com/zNtPwdbS

**Comment by PyvesB** [comment]
Hello,

Thank you for you report, I think I know what is going wrong. Will attempt to fix this shortly.

Cheers,

Pyves

**Comment by PyvesB** [comment]
Could you give this version a try? Backup your database beforehand, just in case. ;-)
[AdvancedAchievements-4.2.zip](https://github.com/PyvesB/AdvancedAchievements/files/828820/AdvancedAchievements-4.2.zip)

**Comment by Zaneconwell** [comment]
Everything looks good, no errors. If any come up i'll let you know.
