### ISSUE TITLE
Console Spamming Error

### ISSUE THREAD

**Issue by PressurePlates** [PyvesB/AdvancedAchievements#149]
http://pastebin.com/12ussTSL
Server Version: PaperSpigot 1.7.1.0
Please help I have no idea what is causing this error.

**Comment by PyvesB** [comment]
Hello,

Please set *RestrictSpectator* to false, that should do the trick. I have updated the installation instructions for Minecraft 1.7.9-1.7.10 accordingly. ;-)

Cheers,

Pyves
