### ISSUE TITLE
Is there a way to delete all achievements earned by a player?

### ISSUE THREAD

**Issue by c0wg0d** [PyvesB/AdvancedAchievements#150]
Something like /aach delete * c0wg0d or /aach delete all c0wg0d?

**Comment by PyvesB** [comment]
Hello,

No, there is currently no in-game command to delete all achievements earned by a given player (apart from running _/aach delete_ several times in a row). I recommend deleting all entries for the corresponding player UUID in the _achievements_ database table directly.

Cheers,

Pyves

**Comment by c0wg0d** [comment]
It would be a nice feature to have, if you could add it.  Thanks for considering.

**Comment by PyvesB** [comment]
This would be a dangerous command and it would most likely cause issues in most use cases. Deleting an achievement from a player does not reset the corresponding statistic in the database. As most categories are awarded only when the exact statistic threshold is met, this would be an easy way to break the link between the config and the database.

**Comment by c0wg0d** [comment]
Ah, okay.  I had planned on a system where achievements get wiped when a player dies so they have to re-earn them, but I'll figure something else out.  Feel free to close this if you are never going to add it.
