### ISSUE TITLE
Add particles and sound effects for achievements

### ISSUE THREAD

**Issue by c0wg0d** [PyvesB/AdvancedAchievements#151]
My players do not like having fireworks go off when earning achievements (it's too scary if your volume is up and you aren't expecting it), but it would be nice to be able to play a sound effect (like the XP level up sound) and get some particles when you earn an achievement.  I see you have these options for top list, but can we get them for achievement awards too?

**Comment by PyvesB** [comment]
Hello,

It does make sense. I'll see if I can find some cool particles and sound effects to go with achievements instead of the fireworks. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Done, here's a test version if you want to try it out. `Firework` must be set to false in the configuration, and `SimplifiedReception` to true. I suggest you use this version on a test server as it includes other work that lacks a bit of testing, unless you're in a beta tester mood!

[AdvancedAchievements-4.2.1.zip](https://github.com/PyvesB/AdvancedAchievements/files/859093/AdvancedAchievements-4.2.1.zip)
