### ISSUE TITLE
GUI Design Suggestion :)

### ISSUE THREAD

**Issue by Chuncunmaru** [PyvesB/AdvancedAchievements#152]
Yo man, whats up?
I have some free time to do some nice GUI design...

See:
http://chuncunmaru.imgur.com/all/

**Comment by PyvesB** [comment]
Hello,

Looks nice! Is there some code available somewhere to try it out?

Cheers,

Pyves

**Comment by Chuncunmaru** [comment]
No :'(

**Comment by PyvesB** [comment]
Not really sure what I should do with this issue?
