### ISSUE TITLE
Beta testing version 5.0

### ISSUE THREAD

**Issue by PyvesB** [PyvesB/AdvancedAchievements#155]
Hello all,

@Platinteufel  and anyone who's interested, work on version 5.0 is mostly complete and some extra testing would be appreciated! Here is a beta version (still labelled 4.1.2, version number will be changed when released officially):
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/876947/AdvancedAchievements.zip)

The new version will hopefully be released by the end of the week. The changelog is as follows:
* **New:** added _gui.yml_ file to allow to tune the GUI items as wanted.
* **New:** implemented _/aach reset_ command to reset the statistics for an achievement category.
* **New:** added support for _BungeeTabListPlus_, with _achievement_count_ placeholder to display the player's number of achievements in the tab.
* **New:** added _SimplifiedReception_ config option to activate simpler effects and a calm sound when a player receives an achievement.
* **New:** provided API so that third-party software can more easily pair with Advanced Achievements.

* **Improvement:** removed chat header completely if no icon is set in the configuration.
* **Improvement:** improved the overall stability and user experience of the plugin.
* **Improvement:** enhanced performance.
* **Improvement:** refactored large parts of the project to make it more maintainable and facilitate contributions.
* **Improvement:** achievements are now driven by Bukkit Events so that third-party plugins can detect when they are awarded.

* **Fix:** fixed broken permissions for sub-categories making use of metadata (_Breaks_, _Places_ and _Crafts_ achievements).

* **Other:** removed MCStats Metrics, as project is abandoned.
* **Other:** removed _AsyncPooledRequestsSender_ configuration option, plugin can no longer be set to run in single threaded mode.

**Comment by Platinteufel** [comment]
Hey PyvesB,

I will do some testing this evening. ;-)

Cheers
Platinteufel

**Comment by Platinteufel** [comment]
Some thoughts here:

1.) Maybe you should throw a warning on startup/after reload if an item is used twice in gui.yml.
... tbc ...

**Comment by PyvesB** [comment]
Hello Platinteufel,

1.) Honestly, bad luck for the user if he puts a same _Item_ and _Metadata_ pair twice in _gui.yml_. It's clearly stated in the header of that configuration file, and he will immediately notice  when typing /aach list. I don't think it's worth any extra effort.
2.) Well the reset command resets only the statistic, not the achievements. You can use /aach delete to delete the corresponding achievements separately.
3.) Brilliant idea! I've included TAB auto-completion for the /aach give, /aach reset, /aach check and /aach delete commands! If the list of possibilities is too long, I just truncate it; the user can type a few extra letters to narrow down the possibilities. ;-)

Thanks for your help! Here's a version with today's fixes and additions:

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/880418/AdvancedAchievements.zip)

**Comment by Platinteufel** [comment]
Hello,

All reported bugs seems to be fixed, thanks a lot!

TAB-complete works like a charm, wow! There's only one minor thing I've noticed: 
Type `/aach check` and press TAB. The first suggestion you'll get is `and 1 more... `. If you press time a second time, just the `more...` will be replaced.
Not a big issue for me, but maybe it's possible to change it. ;-)

**Comment by PyvesB** [comment]
1. It seems as if your Spigot/PaperSpigot version reorders the elements in the list, hence "and 1 more..." appearing first. It does not do the same on my version. I would have to add special characters first to make sure it appears last, and the spaces are also making this painful. I'll just put suspension points instead.
2. Unfortunately I can't really do anything about this, this is how the API is implemented. Users using fairly recent versions of the plugin should not have spaces in the Name parameters anyway. For older versions, I've sort of implemented a workaround, tell me what you think!

[AdvancedAchievements-4.2.1.zip](https://github.com/PyvesB/AdvancedAchievements/files/883378/AdvancedAchievements-4.2.1.zip)

**Comment by Platinteufel** [comment]
Wow, thank you again! Very sneaky workaround! ;-)

I will do some final tests tomorrow. It's the least I can do for that amazing support.
