### ISSUE TITLE
5.0 - Exception on disable

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#160]
Just got this exception after stopping my server. Seems to be very randomly, I can't reproduce it a second time. I'm going to report it anyway.

https://pastebin.com/2MLzdbAQ

**Comment by PyvesB** [comment]
This is probably not specific to version 5.0, you most likely got unlucky while testing. I don't think Advanced Achievements is to blame here, I would rather say Bukkit's way of handling scheduled tasks on shutdown is not very clean, but this would need some digging into the scheduler implementation. Anyway, I have added some handling to avoid this from happening in the future.
