### ISSUE TITLE
Added a new achievement that some players already qualify for, but they don't get it

### ISSUE THREAD

**Issue by agentroop** [PyvesB/AdvancedAchievements#163]
I've added some new achievements to my server, but the issue is that players that qualified for the achievements before they were added can't get the new achievement.

For example, I added an achievement that is unlocked when a player uses 100 ender pearls. Some players have used over 200 ender pearls, so they aren't able to get this achievement anymore. Any idea how to fix this?

**Comment by PyvesB** [comment]
Hello,

This is comprehensively documented in the Wiki, please refer to question 4 of the FAQ.

Cheers,

Pyves

**Comment by agentroop** [comment]
Thank you, I didn't see that! Sorry about asking a question that's been asked before. It would be great if a solution could be made for this that doesn't require resetting a player's data, but that answers all my questions. :)
Thanks again!

**Comment by PyvesB** [comment]
You're welcome! ;-)
