### ISSUE TITLE
Bug with achievement "Player Commands"

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#164]
J'ai un petit souci, le succès "Player Commands" fonctionne seulement pour les op, je ne comprends pas trop pourquoi et c'est le seul qui pose ce problème. 
La barre de progression stagne à 0 pour un joueur même s'il fait la commande contrairement à l'op pour qui tout se passe bien.
J'utilise PaperSpigot et la dernière version du plugin.
Au niveau de la config voilà ce que j'ai mis pour ce succès :

I have a problem, the success "Player commands" only works for op, I do not understand why and this is the only one that is a problem.
The progress bar remains at 0 for a player, unlike the op for which everything works.
I use PaperSpigot and the last version of the plugin.
Here is what I put in the config :

https://pastebin.com/2tBTMwTQ

**Comment by PyvesB** [comment]
Hello,

This has already been fixed by commit 3bcf9ee59db5540c30c3c9b3133b27e37f39580c, and will be available in next release. Thanks for the report though! ;-)

Cheers,

Pyves
