### ISSUE TITLE
Hi! Please creatore, help me!!

### ISSUE THREAD

**Issue by nickylmbo** [PyvesB/AdvancedAchievements#165]
Hi! Your plugin is very useful (Advanced Achievements)!
I really love it because its simple and its so good! But i set up like 71 achievements of the kill entities category but it seems i need more space, how can i add another same category in the /aa list GUI?  or i can just modify another category existing? sorry my english but i really dont know how to do it!
Thank you!

**Comment by PyvesB** [comment]
Hello,

Each category supports up to 98 achievements in the GUI, so normally everything should show up if you have only set 71. ;-)

Cheers,

Pyves
