### ISSUE TITLE
Named sheep do not increment Shear achievements when sheared

### ISSUE THREAD

**Issue by c0wg0d** [PyvesB/AdvancedAchievements#168]
If you have named a sheep with a nametag, your "Shear" stat does not go up when you shear it.

**Comment by PyvesB** [comment]
Hello,

Really? That's interesting, I will look into that. Have you noticed this behaviour with any other categories (eg. milking cows)?

Cheers,

Pyves

**Comment by c0wg0d** [comment]
The bug does not occur for milking cows.  I haven't had a chance to try out the others yet.

**Comment by PyvesB** [comment]
An issue caused by a clumsy line of code that was probably introduced in the very first version of the plugin. Good catch! ;-)
