### ISSUE TITLE
New categories :)

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#17]
Hey PyvesB,
I just have some suggestions for new categories for your really awesome plugin. :)

#When a distance is traveled by elytra.
**DistanceElytra:**
'1000': [...]

#When an enderpearl is thrown.
**Enderpearl:**
'1000': [...]

#When a cake is eaten.
**EatenCakes:**
'1': [...]

#When the player has jumped
**Jumps:**
'100': [...]

#Music Discs played
**MusicDiscs:**
'1': [...]
'12': [...]
Maybe it's possible to count only the different music discs here, so that you have to use ALL discs to get the highest achievement.

I want to install this plugin on my main server later this week. Should I install the current version or should I wait for an update with even more features if there's an update planned in time? ;)

**Comment by PyvesB** [comment]
Hello Platinteufel,

Thank you for your ideas. I will definitely implement some of them in a future update. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Thank you! :)
Is there any chance to remove the &5 color-code before AMOUNT? I'm currently translating the lang.yml into German and changed _money-reward-received: '&2Du hast AMOUNT $ erhalten!'_. (&2=green), but it seems like AMOUNT resets the color to &5 again:

![2016-04-20_02 59 39](https://cloud.githubusercontent.com/assets/13700636/14660259/1a3e56a0-06a4-11e6-8188-aef70678bc50.png)

**Comment by PyvesB** [comment]
I'll look into that. ;-)

**Comment by PyvesB** [comment]
Hello again,

The bug with the colours is normally fixed in version 2.5. I've also implemented the categories for ender pearls, elytra distances and music discs. I'll keep the cake one in mind for a future update, but jump doesn't really seem like a good idea from my point of view (and it would likely not be easy to implement). ;-)

Thanks for your feedback,

Pyves

**Comment by Platinteufel** [comment]
Nice to hear, thank you! :)

**Comment by Platinteufel** [comment]
Seems like you can do the DJ achievement with a single music disc. It is not possible to count only the different music discs (1-12), is it? ^^

**Comment by PyvesB** [comment]
The plugin only monitors the action of inserting a disc into a jukebox:
- it would be significantly more complicated to do what you are suggesting.
- it would be confusing for many users, I can already imagine some of them setting 100 for MusicDiscs and not understanding why the statistic never gets above 12.
