### ISSUE TITLE
Support PlaceholderAPI

### ISSUE THREAD

**Issue by BiGUNMAN** [PyvesB/AdvancedAchievements#170]
Instead of just using the built in achievement options, we could use placeholder API to create others based on different plugins placeholders. --- I can provide more info if this is too vague.

**Comment by PyvesB** [comment]
Hello,

Basically, I'm giving the same answer as in question 10 of the FAQ. I know nothing about PlaceHolderAPI, and do not use it on my servers. I will therefore probably not add support for this third-party plugin myself, but nothing prevents another developer with a better understanding to take care of it. ;-)

Cheers,

Pyves

**Comment by xyblues** [comment]
https://www.spigotmc.org/resources/placeholderapi.6245/
I want PlaceholderAPI support, too.
Just like this:
%AdvancedAchievements_Received_<Achievement Name>% 
- return true if player has received the achievement, false otherwise.

%AdvancedAchievements_Received_ItemBreaks%

**Comment by BabelSolea** [comment]
Want PlaceholdersAPI support!!! add this

WTF URE IGNORE IT????

PlaceHolderAPI same plugin like Vault - utility that make possible to use data from AACH in all other plugins

why the hell author dont wanna look and understand what that hard usefull popular and effective desigion!

**Comment by PyvesB** [comment]
I am definitely even less enthusiastic at adding PlaceholderAPI support now. User blocked and reported.

**Comment by BiGUNMAN** [comment]
Lol, good reason, but tbh, I highly recommend looking into it, even if it's
just using if for your own private server, as it's an extremely useful
plugin.

**Comment by supertassu** [comment]
Yeah, would be a good addiction.
Except a PR soon™:)

**Comment by PyvesB** [comment]
@supertassu : any progress on the Placeholder API side? ;-)

**Comment by supertassu** [comment]
@PyvesB PlaceholderAPI doesn't like my custom placeholders. Nope.
