### ISSUE TITLE
Problems with configuration

### ISSUE THREAD

**Issue by HLF-Raideer** [PyvesB/AdvancedAchievements#171]
Hello!

We got an error while trying to configure the plugin:
https://pastebin.com/PzibJbqV

Can you help me please? :)

**Comment by PyvesB** [comment]
Hello,

The file you pasted states the following:

> Invalid item reward for achievement "place_50_grass". Please specify a valid Material name.

"rail" does simply not exist, I'm guessing you actually mean "rails". Carefully follow the names [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html). ;-)

Cheers,

Pyves

**Comment by HLF-Raideer** [comment]
Thank you!
