### ISSUE TITLE
Problem - Brewing Stand and Empty Bottle

### ISSUE THREAD

**Issue by NicolasDelahaigue** [PyvesB/AdvancedAchievements#172]
It seems there is a problem with the achievement **Brewing**.
You can put 3 stacks (3*64) of empty bottles in a Brewing Stand and when you get them back there are all count in the achievement Brewing.

Can you exclude empty bottles of the achievement **Brewing** ?

**Comment by PyvesB** [comment]
Hello,

Thank you for the report, I will look into it. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
The referenced commit also handles cases with plain water bottles.

**Comment by NicolasDelahaigue** [comment]
Perfect ! Thanks a lot :)
