### ISSUE TITLE
Certain PlayerCommands commands are not unlocking achievements

### ISSUE THREAD

**Issue by seedie** [PyvesB/AdvancedAchievements#173]
Hello and thank you for your help with my previous issue. Certain plugins allow you to create custom commands such as https://www.spigotmc.org/resources/customgui-25-off-easter-sale-completely-customizable.7386/ to open GUIs. Sorry that I could not find any other examples at the moment (excluding a 'mycommand' one which I found a way around), I only just started using the PlayerCommands achievements. GUIs are a huge part of my server so it would be lovely to reward players for using them. 

Any suggestions?

Thank you for reading this and I hope you have a nice day.

**Comment by PyvesB** [comment]
Hello,

I'm not sure I understand. Can players decide the name they give to their commands?

Cheers,

Pyves

**Comment by seedie** [comment]
yes they can have it so that you type a command to open a gui, which is the issue with that command not unlocking the playercommand achievement.

**Comment by PyvesB** [comment]
Can't you arrange for all the commands created by that plugin to have a common prefix? _PlayerCommands_  does support command prefixes (for instance "aach stats" will map with an "aach" _PlayerCommands_  sub-category). If the command specified by the player can be completely random, I'm afraid there is not much I can do on my end.

**Comment by seedie** [comment]
I can decide the command name within the plugins config file, for example "/house" might open up an interface where the player select a house to view from the choices provided. so i can change the name of any command if this helps, example: "/view house".

**Comment by PyvesB** [comment]
Why not just specify "house" in the _PlayerCommands_ section of Advanced Achievements' configuration?

**Comment by seedie** [comment]
I have done, but no matter how many times its typed it wont unlock, even for myself.

**Comment by PyvesB** [comment]
Okay, does this happen only for this specific plugin?

**Comment by seedie** [comment]
Ive only tested it with two plugins that allow you to create custom commands, and it sort of worked with 'mycommand' as in commands which ran a different command would not unlock acheivements, where as custom commands that did other things would unlock achievements. This isn't a problem because the commands that ran a different command could have that command specified in the advanced achievements config instead.

**Comment by PyvesB** [comment]
Could you please provide me with a simple example so that I can reproduce this (for instance a simple _MyCommand_ configuration with only one custom command that isn't picked up properly by Advanced Achievements)?

**Comment by seedie** [comment]
add the following to commands.yml https://pastebin.com/hsRBCjtA

then to advanced config: https://pastebin.com/aE3JQA7r

neither value nor worth unlock an achievement. instead of using RUNCOMMAND with mycommand, you can use other options such as TEXT which do unlock achievements, alternatively in advanced achievements if you set the playercommand to worth rather than value it will unlock when somebody types value. (which is the desired effect for this particular plugin). I just hope the reason value isn't unlocking is the same reason other custom commands don't seem to.

**Comment by PyvesB** [comment]
Thank you for the configuration snippets.

MyCommand seems to cancel the event corresponding to the command "value". Therefore Advanced Achievements ignores that event, and only sees the second one coming through corresponding to, "worth". Unfortunately there is nothing much I can do my side. Command aliases should be handled properly by MyCommand with a _PluginCommand.setAliases_ call rather than monitoring, cancelling and creating new events as the current implementation seems to do it.

**Comment by seedie** [comment]
Thank you for investigating this for me. Is there anyway for me to send you a file?

**Comment by seedie** [comment]
Thank you for investigating this. I have sent you an email message containing a testing config.

**Comment by PyvesB** [comment]
A similar problem occurs with this plugin: CustomGUI monitors _PlayerCommandPreprocessEvents_, makes a call to open the GUI and cancels the event, regardless of whether it was really cancelled (for instance no permissions) or whether it was in fact performed. Advanced Achievements therefore ignores it.

These plugins are using the Bukkit API incorrectly. As stated in the [documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerCommandPreprocessEvent.html), "Examples of incorrect uses are: using this event to run command logic.". This is exactly was is done here: the command is handled as a side-effect of the preprocessing event, and is never actually processed.

**Comment by seedie** [comment]
Thanks again for all the time you spent looking into this. As there isn't anything that can be done your end, I will close the issue.

**Comment by PyvesB** [comment]
No problem, please feel free to open a new issue if you encounter any problems in the future. I recommend raising an issue in the CustomGUI thread, it should not have such serious flaws and ignore API guidelines, especially regarding the fact that it's a "premium" resource. ;-)
