### ISSUE TITLE
Feathure request

### ISSUE THREAD

**Issue by Helomi** [PyvesB/AdvancedAchievements#174]
Hello, its possible add something like this?
/aach see "player_name"
Ty.

**Comment by Platinteufel** [comment]
You could ask the player for his /aach book.

**Comment by Helomi** [comment]
I mean something like gui.

**Comment by Helomi** [comment]
I think this is for player easier and little more useful.

**Comment by PyvesB** [comment]
Hello,

I don't find this command very interesting for players. It takes out the RP spirit brought by sharing books as stated by Platinteufel. It would also be complicated to implement and would probably have poor performance, as statistics for two players would have to be cross-referenced and processed to correctly support the _ObfuscateNotReceived_, _ObfuscateProgressiveAchievements_ and _HideNotReceivedCategories_ configuration parameters. ;-)

Cheers,

Pyves
