### ISSUE TITLE
Feathure request

### ISSUE THREAD

**Issue by Helomi** [PyvesB/AdvancedAchievements#175]
Its possible add own categories? For example with placeholders.

Your achievement:
```
Breaks: 
  sand:1:
    10:
      Message: "&cYou have collected 10 red sand blocks!"
      Name: break_10_sand1
      DisplayName: Red Sand Fan
```

with placeholder use:

```
Skyblock: (some custom name)
  %askyblock_level%:
    50:
      Message: "&cYou have reached 50 level on your island!"
      Name: skyblock_level_50
      DisplayName: Novic
```

**Comment by PyvesB** [comment]
Hello,

I've got no clue what "Skyblock" is or what you  %askyblock_level% placeholder is about. If it's some sort of exotic plugin, please refer to Question 10 of the FAQ. You've also got the "Implementing new categories" of the Developers documentation that shows you how to simply add your own categories. ;-)

Cheers,

Pyves
