### ISSUE TITLE
getPlayerAchievementsList(UUID) is not static

### ISSUE THREAD

**Issue by EverMineServer** [PyvesB/AdvancedAchievements#177]
How can i use it if it is not static?
http://prnt.sc/eztiku

**Comment by PyvesB** [comment]
Hello,

Have you gone through the [Developers Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers)? :-)

Cheers,

Pyves

**Comment by EverMineServer** [comment]
AdvancedAchievementsAPI advancedAchievementsAPI = AdvancedAchievementsBukkitAPI.linkAdvancedAchievements();
solved :D
