### ISSUE TITLE
A problem with the GUI [SOLVED]

### ISSUE THREAD

**Issue by xPix3l** [PyvesB/AdvancedAchievements#178]
When I use /aach list and I try to open DistanceFoot category's GUI it doesn't open. How can I Fix?

**Comment by PyvesB** [comment]
Hello,

No idea. Any exceptions in the console? How have you configured the category in _gui.yml_ and _config.yml_? 

Cheers,

Pyves

**Comment by xPix3l** [comment]
I was wrong, this problem is for the category HoePlowings. Unfortunately there aren't errors in the logs files. You can find this problem even when you use the default file **guy.yml** and **config.yml**, so this problem is also present when you use the default configurations.

**Comment by EverMineServer** [comment]
I can confirm that the problem exist:
http://prntscr.com/f0jgtl

**Comment by xPix3l** [comment]
To able DistanceFoot category's GUI I removed DistanceTaskInterval form DisabledList but I have no Idea what to do with this problem. I'm waiting for your reply.

**Comment by xPix3l** [comment]
Ok, I've solved. I've done an error in **config.yml** file.

**Comment by PyvesB** [comment]
Awesome, I'm therefore closing this issue. ;-)
