### ISSUE TITLE
Show your current progress

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#18]
With /aach list you can see which achievements you can get and which you already have. It would be awesome if you could also see your current progress, so that you know how many stones you have to break (just an example) for the next achievement.

**Comment by PyvesB** [comment]
Hello,

I'll keep this suggestion in mind. Nevertheless, it would require some heavy work and might affect the plugin's performance, so I won't guarantee I'll implement it any time soon. ;-)

**Comment by Platinteufel** [comment]
Okay, but the plugin saves all values to database, right? If there would be a command like /aach progress EnderPearls, why it would cost performance to pick the value out of the database and show it in chat?

**Comment by PyvesB** [comment]
Yes, it does cost to retrieve a value from the database; the value may be cached by the buffer manager of the database system, or by Advanced Avhievements' pools, but if it isn't, retrieving the value can be an expensive operation, especially if you are running a server using hard disk drives and not solid state disks. In the case of HDD, reading a value that is not cached from the database can take several milliseconds; as you're reading many values as the same time as in /aach list, the command could take several hundreds milliseconds with a naive approach.

**Comment by PyvesB** [comment]
Hello,

The beta with the new GUI is finally here! You can download it just here:
[AdvancedAchievements-2.6-Beta.zip](https://github.com/PyvesB/AdvancedAchievements/files/342383/AdvancedAchievements-2.6-Beta.zip)

Please give me feedback about:
- any bugs you may encounter.
- any performance issues you may have with the command.
- what you think about the work, and eventually ideas to improve it.

All the config options are normally functional with the new command, except ListItemSeparator which does not have any effect anymore.

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Hey, looks good, but why you've changed "Distance Elytra" to a bedrock in /aach list gui? :D

**Comment by Platinteufel** [comment]
It would be nice if there are also digits (like 27/100) instead of only progress bars. :)

**Comment by Platinteufel** [comment]
Oh, and if you want to go back to the "main gui", you have to close it and type /aach list again. Maybe there's an easy solution for a back button. ;-)

**Comment by PyvesB** [comment]
Hello,

I've corrected the Elytra bug, thanks for reporting. I also implemented a back button. I'm not adding any digits for now, I want to see how the people feel about the progress bars in general. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Thanks, could you compile a new jar for further tests? :)

**Comment by PyvesB** [comment]
Sure, here it is: https://mega.nz/#!RkQCABRQ!TzzyWg4RvMPR5MgdepWqEx12eUm7jo_CB9wgZ4FZdDM

This is the full Beta of version 3.0, so many things have changed; be sure to do a full backup of your Advanced Achievements files beforehand. ;-)

**Comment by Platinteufel** [comment]
In my opinion you should not change the main gui, it's nice to have an overview about the categories and the reacheable achievements there.

**Comment by PyvesB** [comment]
Well the main GUI is now lighter to generate in terms of performance impact. People were also complaining about display issues (too long lists which would not show up entirely, etc.), so I think it's better getting rid of it completely and not duplicating the information. ;-)

**Comment by Platinteufel** [comment]
Hm okay, I was quite familar with the old main GUI, because you could see all information there, but maybe you're right. But well, if it's possible to make it configurable like "old-main-menu:true", it would be awesome! ;-)

I really like the back-button, good job! Updating on my testserver worked without any problems.
