### ISSUE TITLE
Suggestion: Inspect feature

### ISSUE THREAD

**Issue by freak-dk** [PyvesB/AdvancedAchievements#182]
Hello

I was wondering if you would consider adding a command that would allow someone to open up another players aach GUI and through that see their progress?

I know the book is there, but this would allow every one and admins to easily inspect a players achievement for which there is no way to do so right now.

Also I believe this wouldn't be too much work to implement? 
Hopefully you can have a look at it, thanks!

Regards

**Comment by PyvesB** [comment]
Hello,

This will probably not be done. Please refer to my answer in #174. ;-)

Cheers,

Pyves

**Comment by freak-dk** [comment]
@PyvesB 
Appreciate your answer.
I'll have my dev develop a custom solution instead which is fine aswell.

On another note however, as I stated in the Spigot thread it seems Leaderheads nolonger works with aach, but I am not sure if that is something the author of Leaderheads needs to fix?

**Comment by PyvesB** [comment]
If ever you have _ObfuscateNotReceived_, _ObfuscateProgressiveAchievements_ and _HideNotReceivedCategories_ all set to false, it will be extremely easy to implement the custom version for online players.

I don't know anything about Leaderheads, I didn't even know it supported Advanced Achievements. I modified quite a lot of things in version 5.0 of the plugin, I guess the author will have to update his plugin to use the recently added API. ;-)

**Comment by freak-dk** [comment]
I do have all those settings set to false :-) My dev said it wasn't such a big deal either if those parameters were false.
He's trying to import your project as we speak.

Though so about LH, will keep nagging the dev!

**Comment by PyvesB** [comment]
Awesome! I will close this issue for now, but please feel free to open new ones if you need anything else!
