### ISSUE TITLE
Classify the types of items

### ISSUE THREAD

**Issue by thebastien007** [PyvesB/AdvancedAchievements#183]
Hey,
I purpose to add on option  (or not) for classify the types of items (the material name) in GUI menu.
In example, in places blocks menu, classified the types of blocks by columns.
Because actually, it's a mess in under menus.
Thank's

(Sorry for my bad english)

**Comment by PyvesB** [comment]
Hello,

Well actually the blocks are already classified, all items for a given sub-category appear next to each other in the GUI. They are also ordered in the order you listed them in _config.yml_. ;-)

Cheers,

Pyves
