### ISSUE TITLE
Can't get the rewards to work

### ISSUE THREAD

**Issue by LangeDraak** [PyvesB/AdvancedAchievements#184]
Hi, I'm all new to this, but I'm trying to create a reward system in my private MC Server.
I want to get for example, 10 EXP Bottles for every achievement. The achievement is working, but I'm not receiving the reward.

# When a cow is milked.
Milk:
  1:
    Message: Just milked a cow!
    Name: milk_1
    DisplayName: First Milk	
  15:
    Message: You're a milk addict!
    Name: milk_15
    DisplayName: Milk Addict
    Reward:
        money: 1
        item: exp_bottle 10

**Comment by PyvesB** [comment]
Hello,

Always pay attention to how the default configuration file is written! "money" and "item" must start with capital letters, otherwise the plugin cannot parse the corresponding YAML sections. ;-)

Cheers,

Pyves
