### ISSUE TITLE
Question about update

### ISSUE THREAD

**Issue by IvanMankov** [PyvesB/AdvancedAchievements#185]
Hi! I updated AA to new version but configs are old. Do I need to remove them? I have my own translation and settings. How can I transfer it fast to new version?

**Comment by PyvesB** [comment]
Hello, 

Please refer to the [Updating the plugin](https://github.com/PyvesB/AdvancedAchievements/wiki/Updating-the-plugin)  sectionner the Wiki. I highly recommend reading the other sections as well. ;-) 

Cheers, 

Pyves

**Comment by IvanMankov** [comment]
Ok, as I understood, I don't need to remove configs. Plugin will be write updates in the end of files. Right?

**Comment by PyvesB** [comment]
Yes indeed! Just do a backup just in case.
