### ISSUE TITLE
Doubt creating achievements

### ISSUE THREAD

**Issue by Drashk** [PyvesB/AdvancedAchievements#186]
Hi, i'm new in this so i have a question, i'm trying to create a achievement like "Kill a Skeleton with Arrows"
but i try and try but it doesn't work,could someone help me?,thanks for your time, nice work keep it up! 

(Sorry bad english)

**Comment by PyvesB** [comment]
Hello,

THis is simply not possible. ;-)

Cheers,

Pyves

**Comment by Drashk** [comment]
Oh ok,thanks
