### ISSUE TITLE
Bug : Achievement Fireworks

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#187]
Hi,

By making a simple right click with a firework on a chest (so the fireworks is not used) it is counted as fireworks launched in the achievement "Fireworks".

_I use Paper Spigot 1.11.2 and the last version of the plugin (5.1)_

Thank you in advance.

**Comment by PyvesB** [comment]
Hello,

Thank you for the bug report. I will look into it. ;-)

Cheers,

Pyves

**Comment by c0wg0d** [comment]
I have verified that this is a bug.

**Comment by PyvesB** [comment]
I have started looking into this, and it seems as if I will have to implement a quite "hackish" fix. But will get there eventually!
