### ISSUE TITLE
Problem with mob killed

### ISSUE THREAD

**Issue by MrExeggo** [PyvesB/AdvancedAchievements#188]
Hi, I have a problem with this kind of aach:
Kills:
  Zombie:
    '625':
      Goal: Uccidi 625 Zombie.
      Message: '&bHai ucciso 625 Zombie!'
      Name: kills_625_zombie
      DisplayName: '&3The Walking Dead!'
      Reward:
        Command: update-aach PLAYER
Users when they kill mobs are not counted

**Comment by PyvesB** [comment]
Hello,

Put "zombie" in lower case. This indication disappeared from the configuration file at some point, I will add it again. ;-)

Cheers,

Pyves
