### ISSUE TITLE
Suggestion: disable achievements for adventure mode?

### ISSUE THREAD

**Issue by seedie** [PyvesB/AdvancedAchievements#189]
I've allowed people to enter game mode 2 in order to interact with peoples creative mode builds. Currently, people are unable to gain achievements in creative mode which is great. Is it possible to get the same option for adventure mode? I'm mainly worried about the crafting achievements in which a creative player can give an adventure player all the required materials.

**Comment by PyvesB** [comment]
Hello,

I will add a _RestrictAdventure_ option in the next update. ;-)

Cheers,

Pyves

**Comment by seedie** [comment]
thanks!

**Comment by PyvesB** [comment]
Keep this issue opened so I won't forget about it. I'll close it via a commit. ;-)
