### ISSUE TITLE
Enchanted items as reward

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#19]
Just a quick question: Is it possible to give a enchanted pickaxe as reward? 
I've also tried to give named items (e.g. Pickaxe of the stone god NAME) as trophy, but it breaks my config.

**Comment by PyvesB** [comment]
Hello,

Enchanted and named items can be given, but through a command reward. For instance:
Reward:
      Command: give PLAYER minecraft:diamond_shovel 1 0 {display:{Name:"YourName",Lore:["Lore of the item"]},ench:[{id:34,lvl:1},{id:32,lvl:2}]}

Be sure to use the usual parser yaml-online-parser.appspot.com to check the syntax is correct, depending on what you put in the command you might need to add additional apostrophes. ;-)

**Comment by Platinteufel** [comment]
Thank you for the fast support :)
