### ISSUE TITLE
Achievement categories in the list display when they shouldn't be

### ISSUE THREAD

**Issue by seedie** [PyvesB/AdvancedAchievements#192]
Hello, hope you are well...

After updating to the latest version achievements specified in my lang.yml file with '' appear in the achievement list (so the whole list is populated). I didn't change anything since updating and downgrading makes it work correctly. On 1.11.2 if this helps, Example of lang:

list-deaths: ''
list-arrows: Arrows Shot
list-snowballs: Snowballs Thrown
list-eggs: Eggs Thrown

Deaths should not be displayed after updating (as it isn't before updating) however this is not the case.

**Comment by PyvesB** [comment]
Hello,

Sorry about that. Will commit a fix in a few minutes.

Cheers,

Pyves
