### ISSUE TITLE
Problem whith rewards

### ISSUE THREAD

**Issue by Araviinn** [PyvesB/AdvancedAchievements#193]
Hello, I've tried to add some rewards when a success is obtained. I wanted to put xp bottles (xp_bottle or ID) but it doesn't work.  Have you a special word for it? 
Thanks in advance for replying
Aravinn

**Comment by PyvesB** [comment]
Hello,

Please refer to question 3 of the [FAQ](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)).

Hint: how about trying exp_bottle? ;-)

Cheers,

Pyves

**Comment by Araviinn** [comment]
Thx :)
