### ISSUE TITLE
hide categories if player does not have permission

### ISSUE THREAD

**Issue by biffamc** [PyvesB/AdvancedAchievements#196]
Hello PyvesB!
first of all I want to thank you for the fantastic plugin which is a great addition in my educational server.
On our server children get the specific category count permission based on their homeworks (e-learning platform). I was wondering if there is a way to show in the GUI just the categories and achievements the player has the count permission for. The problem is that by showing all categories and achievements children get confused, not knowing what they just unlocked and what is still to be unlocked.
I tried to hide not received categories but there is no possibility to give an achievement not in the command category to "unlock" that category.
I hope you will consider this issue since I think it could be a great improvement to the "user friendlyness" of the plugin, otherwise I would be really intrested to know if you have any workaround.
On a sidenote, my company has a developer who could probably fix this, if you think it's a good idea we could get in touch.
Sorry if my english is not perfect, I'm italian.
Thank you for your awesome work :)

**Comment by PyvesB** [comment]
Hello,

I've implemented a new `HideNoPermissionCategories` configuration parameter, which should do what you asked for. This will officially be available in the next update, but feel free to build the plugin to get a beta test version. 

I'm happy to hear that the plugin is used for educational purposes, and that you're enjoying using it! ;-)

Cheers,

Pyves
