### ISSUE TITLE
Bug : /aa stats after /aa reload

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#197]
Hi,

Just to point out a small bug :
When you do /aa reload the number of achievements in the /aa stats is multiplied by 2, then by 3 if you do a second reload, etc...
To fix the problem just reboot the server.

An image to better understand (I have 242 achievements) :

https://sandbox.fr/images/uploads/original/1496001692.png

_I use PaperSpigot 1.11.2 and the last version of the plugin (5.1.1)._

**Comment by PyvesB** [comment]
Hello,

Fixed in aforementioned commit, thanks! ;-)

Cheers,

Pyves
