### ISSUE TITLE
enhancement, customizable gui ?

### ISSUE THREAD

**Issue by Daxxas** [PyvesB/AdvancedAchievements#198]
Hello,

I was thinking about by example : 
- Choose the item for an achievements when it's validated or not, like this : 
http://puu.sh/w3W2p/7a7c44cb0f.png
Change the green hardened clay to what I what, same for the orange/Red one.

Be able to organize the HUD too ?

**Comment by PyvesB** [comment]
Hello,

May add that option at some point, although probably not a priority at the moment. ;-)

Cheers,

Pyves
