### ISSUE TITLE
AdvancedAchievementsAPI#getPlayerTotalAchievements(UUID) slow when AA has no data about the player

### ISSUE THREAD

**Issue by Rsl1122** [PyvesB/AdvancedAchievements#199]
Hello,
I have ran into a problem using the API, possibly in a way it was not intended to be used - To get all amounts of achievements for every player on the server.

Here is my code:
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/data/additional/advancedachievements/AdvancedAchievementsTable.java

Problem appears when a player's uuid is given, but the player has no data on the plugin (plugin was installed & player never logged in while the plugin was installed)

It is not a problem for small amount of players, but for 1097 players takes a long time:
```
[12:36:34 INFO]: [Plan] [DEBUG] Source AdvancedAchievements_achievementstable took 136604 ms
```
I suggest a simple query for all UUID/Ids to cache who is in the database (Takes 8ms on my database)

**Comment by PyvesB** [comment]
Hello,

I will look into this and see what I can do for you. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
I've implemented a new API method `public Map<UUID, Integer> getPlayersTotalAchievements()`. Please tell me if it helps. ;-)

Do a check using `getAdvancedAchievementsVersionCode` to ensure compatibility with older versions of the plugin. The new version will probably be released tomorrow, with version code 520.

**Comment by Rsl1122** [comment]
Alright,  cheers!

**Comment by Rsl1122** [comment]
Version 5.1 vs 5.2

```
[12:34:17] [INFO]: [Plan] [DEBUG] Source AdvancedAchievements_achievementstable
[12:36:34] [INFO]: [Plan] [DEBUG] Source AdvancedAchievements_achievementstable took 136604 ms

[11:28:33] [INFO]: [Plan] [DEBUG] Source AdvancedAchievements_achievementstable
[11:28:36] [INFO]: [Plan] [DEBUG] Source AdvancedAchievements_achievementstable took 3458 ms
```

**Comment by PyvesB** [comment]
Awesome!

I had a very quick look at your implementation. You might be able to slightly speed things up by modifying bits of code similar to the following
```
 if (totalAchievements.containsKey(uuid)) {
    return totalAchievements.get(uuid);
}
```
to something like this:
```
Integer value = totalAchievements.get(uuid);
 if (value != null) {
    return value;
}
```

Basically, instead of doing two lookups in the _Map_, you only do one. ;-)

**Comment by Rsl1122** [comment]
Good spot! 

I've been using this mainly because I don't like having != null everywhere :)
