### ISSUE TITLE
How do I change the color of the ">" divider?

### ISSUE THREAD

**Issue by AndGK** [PyvesB/AdvancedAchievements#201]
Hey. I couldn't find anywhere where I can change the color of ">" divider between command and what it does in the /aach. Is it even possible to do so?

**Comment by PyvesB** [comment]
Hello AndGK,

Modifying the colour of that divider is not currently possible via the configuration file. I recommend directly editing _HelpCommand.java_ and recompiling your own custom plugin version in order to do so. ;-)

Cheers,

Pyves

**Comment by AndGK** [comment]
I figured that but would be nice if you added such a feature. Thankf anyways.
