### ISSUE TITLE
Achievement suggestion

### ISSUE THREAD

**Issue by Mavhill** [PyvesB/AdvancedAchievements#202]
Would it be possible to add a travel to specific coordinates achievement? or find the coordinates. could be used for treasure hunts, low or high altitude achievements , difficult to find areas, etc...,

**Comment by PyvesB** [comment]
Hello Mavhill,

Quite a few users already do similar things with Advanced Achievements. I suggest using World Guard, and any add-ons that you may find useful, and run a command awarding a _Commands_ achievement when a player enters a specific World Guard region. ;-)

Cheers,

Pyves
