### ISSUE TITLE
Is it possible to remove this menu?

### ISSUE THREAD

**Issue by seedie** [PyvesB/AdvancedAchievements#203]
Hello, hope you are well.

http://i.imgur.com/Epl4pdC.jpg The problem is you can hover over achievements not yet obtained. Can this setting in the config also apply to this menu if it is not possible to remove it:

ObfuscateNotReceived: true

Thank you.

**Comment by PyvesB** [comment]
Hello seedie,

Unfortunately, even though Vanilla advancements look great on paper, they are quite limited behind the scenes, and I have to cope with that. Basically, advancements must be fully defined at the server level, and all the players see exactly the same tree in the advancements UI, a part from the colour corresponding to whether they have completed the advancement or not. I cannot obfuscate or hide some advancements, or alter the shape of the tree depending on a particular player's progress. ;-)

Cheers,

Pyves

**Comment by seedie** [comment]
Ah thank you for the information. Do you know of a way to remove the whole tree displayed when a player presses L?

**Comment by PyvesB** [comment]
If you want to hide the tree completely but still keep the advancement notifications, you can go to your server's world folder and navigate to _data/advancements/advancedachievements_. Open _advanced_achievements_parent.json_ and delete the entire "display" JSON object. It should look similar to this:
`{"criteria": {"aach_handled": {"trigger": "minecraft:impossible"}}, "requirements": [["aach_handled"]]}`

Run `/minecraft:reload`, or restart your server.

**Comment by seedie** [comment]
Thanks very much, it worked great. I wanted certain achievements to be unlocked naturally or without help from the achievement information so this has solved my issue :D.

**Comment by PyvesB** [comment]
Awesome! Might add this as a configuration option directly in the plugin in a future update. ;-)
