### ISSUE TITLE
Plugin attempted to register task while disabled [Console Error]

### ISSUE THREAD

**Issue by Yhenko** [PyvesB/AdvancedAchievements#204]
1.8.8 server spigot, last version plugin 5.2.1

12.06 01:49:48 [Server] WARN Exception in thread "Timer-4" 
12.06 01:49:48 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
12.06 01:49:48 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
12.06 01:49:48 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141)
12.06 01:49:48 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115)
12.06 01:49:48 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98)
12.06 01:49:48 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.update(AdvancedCoreHook.java:709)
12.06 01:49:48 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$4.run(AdvancedCoreHook.java:407)
12.06 01:49:48 [Server] WARN at java.util.TimerThread.mainLoop(Unknown Source)

**Comment by PyvesB** [comment]
Hello Yhenko,

This stack trace has nothing to do with Advanced Achievements. You should probably contact @Ben12345rocks from the [VotingPlugin](https://github.com/Ben12345rocks/VotingPlugin) project. ;-)

Cheers,

Pyves
