### ISSUE TITLE
Crafting achievement flood

### ISSUE THREAD

**Issue by tomcraft** [PyvesB/AdvancedAchievements#206]
Hi, I got an issue on my server with Crafting achievements, they can be easily succeed.

You just have to have a full inventory, prepare the craft in the workbench, place your cursor at the recipe result and flood-press a key from the hotbar (like 1 or 5). It count  as a real craft even if this didn't happened.

I temporarly disabled Crafts category.

Regards

(sorry if my english is approximative)

**Comment by PyvesB** [comment]
Hello tomcraft,

Thanks for your report, I will look into it.

Cheers,

Pyves

**Comment by tomcraft** [comment]
thx guy <3 when do you plane an update ?

**Comment by PyvesB** [comment]
Next Thursday maybe. If you can't wait until then, you can recompile the plugin yourself, it's fairly easy to do. ;-)
