### ISSUE TITLE
Issue with ConsumedPotions section

### ISSUE THREAD

**Issue by tomcraft** [PyvesB/AdvancedAchievements#208]
Hello (again) !

I report you a new problem/suggestion. In this case, this is normal but it causes some too easy achievements.

The "ConsumedPotions" section consider the Water Bottle as a potion and the players just have to take an empty bottle, go under the sea and spam-right-click, it will fill the bottle, the player drink, it re-fill, he drink-agin, etc ....

This section is too easy to complete. I suggest you to check if the consumed potion has a PotionEffect on the item, otherwise it makes no sense.

Thanks you again !

We love your plugin <3

**Comment by tomcraft** [comment]
I saw on your code that you already do a check if the Potion is a Water Potion, but I think this check doesn't work :/

**Comment by PyvesB** [comment]
Hello,

What version of the plugin are you using? What Minecraft version is your server running?

Cheers,

Pyves

**Comment by tomcraft** [comment]
I use the latest built version, and I use Paper 1.10.2

**Comment by PyvesB** [comment]
The plugin does not officially support Paper, and I do not have any server nor setup to test it in such an environment. I am not able to reproduce this using the latest Spigot 1.10.2 build. I have also successfully tested it on a range of other Spigot versions. I suggest you try updating your Paper version, but as far as I am concerned I will probably not be able to provide much help. ;-)
