### ISSUE TITLE
look and feel useful from support placeholderAPI!!! STOP FUKIN CLOSE ISSUE LINKING FAQ#10

### ISSUE THREAD

**Issue by BabelSolea** [PyvesB/AdvancedAchievements#210]
example how many ther plugins and what placeholders they make:
https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/

Placeholders allows using AACH data in hundreds and hundreds other plugins

read and add that feature PLEASE

your link to #10 FAQ is bullshit! in that situation cuz that help to YOUR plugin BE BETTER not to placaholderAPI.

if ure still DONT wanna add support PlaceholderAPI

i ask to add featue to show to player her current and max achievements in scoreboard! and update it when player get new achievements.
and show same info my customGUI plugin statistic menu what i created with CustomGUI plugin for my players.

**Comment by PyvesB** [comment]
User blocked and reported.
