### ISSUE TITLE
Block Break not recording, achievements not being given.

### ISSUE THREAD

**Issue by jakichan77** [PyvesB/AdvancedAchievements#211]
I'm not getting any errors in the console, players are just not receiving achievement command rewards, and block break achievements are not working at all in terms of receiving data on what blocks they've destroyed (ie, player destroys 100 iron ore, but nothing comes up as progress in the achievement)

List of plugins: http://prntscr.com/fnkikf

Config for AA: https://pastebin.com/PHy7UpTc

Thank you.

**Comment by jakichan77** [comment]
okay may have solved this myself, I wasn't putting spaces in between commands with ; at the end.

**Comment by PyvesB** [comment]
Hello,

Okay, if you've solved your problem, I'm closing this issue. ;-)

Cheers,

Pyves
