### ISSUE TITLE
Command Execute on Achievement?

### ISSUE THREAD

**Issue by UnrealPixel** [PyvesB/AdvancedAchievements#212]
Hi short question, is there a way I can let the plugin execute a command upon getting an achievement?

**Comment by PyvesB** [comment]
Hello UnrealPixel,

Yes - please refer to the default configuration:
```
 Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
```

Cheers,

Pyves

**Comment by UnrealPixel** [comment]
Thanks for your quick response, this helped me out a lot.

**Comment by UnrealPixel** [comment]
Also, the color codes are not working for me in the message part of an achievement. This is for all of them

`    '10000':
      Message: "&rUpon making &l10.000 &rkills you will receive an &d&lEnder Staff!"
      DisplayName: "&4&lSkull Crusher"
      Name: kills_10000_player`

[In-Game](https://gyazo.com/63577f47d8c8f82be241269dc85156d7)

**Comment by PyvesB** [comment]
What do you mean "not working"? Please be more specific and share a screenshot.

**Comment by UnrealPixel** [comment]
A screenshot is under the "In-Game link.

**Comment by UnrealPixel** [comment]
The plugin doesn't pick up the color codes, even though it is between double quotes

**Comment by PyvesB** [comment]
You have not yet received that achievement, therfore colours will not appear. ;-)

**Comment by UnrealPixel** [comment]
OOhhhhhh, okay, I thought the message would set the colors in the description when the achievement is not received too. Thanks :D

**Comment by PyvesB** [comment]
No problem. Please open a new issue if you encounter any other problems, and feel free to star the repository. ;-)
