### ISSUE TITLE
Block Break achievements not working

### ISSUE THREAD

**Issue by jakichan77** [PyvesB/AdvancedAchievements#213]
Hey! I opened up an issue before and thought I had it fixed, but I really had only fixed the rewards not being given for ANY achievements, and that was due to me having the wrong format for command rewards :P

For this...

I'm not getting any errors in the console, block break achievements are not working at all in terms of receiving data on what blocks they've destroyed (ie, player destroys 100 iron ore, but nothing comes up as progress in the achievement)

List of plugins: http://prntscr.com/fnkikf

Config for AA: https://pastebin.com/HciKsyH6

Thank you.

**Comment by PyvesB** [comment]
Hello,

I will look into it. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
I am unable to reproduce this behaviour, using your configuration file with the latest version of Advanced Achievements and the latest Spigot 1.12 build.

What Minecraft version are you using? Are your permissions set correctly ? You have a lot of plugins, most of which I don't know at all. There could well be something messing up, but it's probably going to be difficult for me to provide much help. ;-)

**Comment by jakichan77** [comment]
I am using Spigot 1.8.8 R01 release build, is there a version of AdvancedAchievements better suited for 1.8?

I don't have any issues on my factions server regarding block breaks, I even compared the configurations.
Could it be because on the prison server, I have unsafe enchantments enabled? Maybe it doesn't count blocks broken too fast? But I don't know if that is true because I have tried without any enchantments on my pickaxe as well, and nothing works.

So when you use my config, everything works fine for you?

**Comment by PyvesB** [comment]
The latest version of Advanced Achievements is supposed to work properly on any Minecraft version between 1.7.9 and 1.12. I've just tried your exact configuration on a Spigot 1.8.7 build, and yes, everything is working fine for me.

**Comment by jakichan77** [comment]
I'll see if I can just get a block break rewards plugin or something on the side of AACH :P

If anything comes to light, let me know, and I'll do the same :) Thanks.

**Comment by PyvesB** [comment]
Maybe you should temporarily remove all other plugins one by one. As soon as _Breaks_ achievements start working correctly again, you will now the last plugin you removed is the culprit. ;-)
