### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by WhatsTheBadNews** [PyvesB/AdvancedAchievements#215]
`01.07 12:13:13 [Server] ERROR [AdvancedAchievements] SQL error while retrieving achievement names: 
01.07 12:13:13 [Server] INFO com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 271,352,410 milliseconds ago.  The last packet sent successfully to the server was 271,352,410 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
01.07 12:13:13 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at com.hm.achievement.db.SQLDatabaseManager.getPlayerAchievementNamesList(SQLDatabaseManager.java:280) [AdvancedAchievements.jar:?]
01.07 12:13:13 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener.awardAdvancements(AchieveConnectionListener.java:155) [AdvancedAchievements.jar:?]
01.07 12:13:13 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener.access$100(AchieveConnectionListener.java:33) [AdvancedAchievements.jar:?]
01.07 12:13:13 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener$1.run(AchieveConnectionListener.java:101) [AdvancedAchievements.jar:?]
01.07 12:13:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
01.07 12:13:13 [Server] INFO Caused by: java.net.SocketException: Broken pipe (Write failed)
01.07 12:13:13 [Server] INFO at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_112]
01.07 12:13:13 [Server] INFO at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
01.07 12:13:13 [Server] INFO ... 16 more`

**Comment by WhatsTheBadNews** [comment]
I am using the latest version of spigot and the latest version of Advanced Achievements.

**Comment by PyvesB** [comment]
Hello WhatsTheBadNews,

One user was having a similar issue a long time ago, could you please refer to #67 and see if the links I posted there help you out?

Cheers,

Pyves
