### ISSUE TITLE
AutoSell / Advanced Achievements issue with block breaks

### ISSUE THREAD

**Issue by jakichan77** [PyvesB/AdvancedAchievements#216]
I figured out the problem. Autosell's fortune blocks feature is messing with the count of the blocks broken - is there a way you can add compatibility?

Fortune blocks means when you break blocks and they automatically go into your inventory, it gives you multiple blocks.

let me know if you need more info, but I definitely found the culprit :)

**Comment by PyvesB** [comment]
Hello jakichan77, 

That seems to be payed software and I don't own a copy myself, so I won't be able to look into it. You should maybe try contacting its author directly, and explain that some of its features break other plugins. ;-) 

Cheers, 

Pyves
