### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by mmuziek** [PyvesB/AdvancedAchievements#217]
hey man im working on some problems since yesterday and i did not get it working once.
here is the current error : 
https://pastebin.com/pCce9PnE
here is my config:
https://pastebin.com/6Qmyj289
if you need other files tell me but i did not touch the other files at all...
i found out that i do need to place "" around  all text for description and display names to get it to move past step 1 at startup and now i get this but i cannot seem to find the problem...

**Comment by PyvesB** [comment]
Hello mmuziek,

Replace the [] by {} for disabled categories (empty structures, and not empty arrays). ;-)

Cheers,

Pyves
