### ISSUE TITLE
Jobs Integration

### ISSUE THREAD

**Issue by Wipie** [PyvesB/AdvancedAchievements#219]
Hi, I wanted to ask you if it was possible to make an integretion with JOBS https://www.spigotmc.org/resources/jobs-reborn.4216/

So we can create sucess by reaching as exemple Miner Level 100 

( Sorry for my bad english I'm french :X  )

**Comment by supertassu** [comment]
Please refer to Question 10 at FAQ.

https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)#other

**Comment by Wipie** [comment]
I understand =/ Thanks for the answer I will look with our server dev for this than :D

**Comment by PyvesB** [comment]
Hello Wipie, 

@supertassu already gave the answer, but I would be glad to integrate any contribution from your developer into the project. That's the point of open-source after all. ;-) 

Cheers, 

Pyves
