### ISSUE TITLE
Maximum level reached.

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#22]
> # Maximum level reached.    
MaxLevel:  
  '10':
    Message: Level 10 reached!
    Name: '&4Rookie' 
> 

In some modes it is possible to maintain the experience and then type it again from the places of storage in the player. This achievement is given each time you get level 10.
For example: I need to enchant an item. I dialed previously stored experience and get the achievement. Then I again enchant items and then take the experience from the repository. Again, I get an achievement. Every time I get the 10 level achievement given me.
Perhaps to make a record in the database, only 1 time of the receipt of this achievement. When I get the 10 level again, it should no longer be given to achieve this, the way I got it for a long time.

**Comment by LLIaMMaH** [comment]
Strange. The following experiments to obtain level 10 did not give this achievement.

**Comment by PyvesB** [comment]
Hello,

I'm not exactly sure about what's going on here. What do you mean by storing experience and taking it from the repository?

**Comment by LLIaMMaH** [comment]
For example:
Experience Obelisk
http://wiki.enderio.com/Experience_Obelisk

**Comment by PyvesB** [comment]
Oh, this is a mod, it could make sense I guess; unfortunately I do not provide support for mods, it's already difficult enough to keep up with Minecraft 1.7/1.8/1.9 on both Bukkit and Spigot. Nevertheless, I will review my code to see if I can add some non-performance hitting sanity checks to handle non standard behaviour. 

Cheers, 

Pyves
