### ISSUE TITLE
Config lookup during events

### ISSUE THREAD

**Issue by fabianwennink** [PyvesB/AdvancedAchievements#220]
Hello, I was fooling around with the code a bit and noticed that when some events are called (e.g. [BlockBreakEvent](https://github.com/PyvesB/AdvancedAchievements/blob/master/src/main/java/com/hm/achievement/listener/AchieveBlockBreakListener.java#L70)), there's a config lookup to see if the blockName exists in a category _(in this case the Break category)_.

This config lookup _(with just 4 subcategories under the Break category)_ takes somewhere from 15.000 nanoseconds to 40.000 nanoseconds.

As a test, I created a String List and inserted around 100 strings into it. I then replaced the config lookup with a simple `.contains(blockName)` call. This call compared to the config lookup only took around 3000 - 5000 nanoseconds.

So I was wondering; Is there any particular reason why you use the config lookup instead of just caching the subcategories?

**Comment by PyvesB** [comment]
Hello fabianwennink,

No, there is no specific reason not to cache the subcategories for multiple achievements, as long as the `extractConfigurationParameters` is overridden properly. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hey there,

Commit 4b870ecf2127ecfd1c45f3c166953a12ad5ff6c4 removed an old class that was no longer of any use, and that was actually slowing configuration lookups down significantly.

I also did some work around the distance and played time runnable classes, which I think benefit the most from caching and pre-parsing some of the configuration data. Commit ecd943511d1d2ec176539114ce04086c817d7106 should also have a positive effect on performance.

I think things are good enough as they are now and will close this issue. ;-)

Thanks,

Pyves
