### ISSUE TITLE
Add pagination to /aach list

### ISSUE THREAD

**Issue by Wipie** [PyvesB/AdvancedAchievements#222]
When you reach more than 53 succes in a category, the back option goes and the "GUI" is completely bugging 

Is it possible to make an option like to go "Page 2" or "next page" "previous page" navigation system?

**Comment by Wipie** [comment]
http://prntscr.com/fwhzdm

Screenshot of the issue

**Comment by PyvesB** [comment]
Hello Wipie,

The GUI can handle up to 98 achievements per category, but due to Minecraft limitations that specific line becomes buggy as you have noticed. I guess adding pagination would be a good thing to do at some point. ;-)

Cheers,

Pyves

**Comment by Wipie** [comment]
Merci :) ( Je prend la peine de te répondre en français :P Est-ce une chose prévu pour bientôt ou plutôt éventuellement ^^?

**Comment by PyvesB** [comment]
Je ne sais pas. C'est quelque chose de relativement compliqué à faire proprement, et j'ai pas mal d'autres occupations en ce moment. Donc on va dire éventuellement, mais ça n'empêche pas quelque d'autre d'y jeter un coup d'œil et de s'en charger. ;-)

**Comment by playfrite** [comment]
@PyvesB si je te paie pour faire la pagination, ça te motiverai assez? bonne journée

**Comment by Wipie** [comment]
Je suis pas concernée mais ça serait super :DD

**Comment by PyvesB** [comment]
Pagination implemented in the latest commit. Here's a test version that anyone can try (and in particular @Wipie and @playfrite)! Please tell me if you encounter any bugs! :wink:

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1405299/AdvancedAchievements.zip)
