### ISSUE TITLE
Custom Category!

### ISSUE THREAD

**Issue by evanmcclan** [PyvesB/AdvancedAchievements#223]
Can you please add a way to make our own custom categories that can then contain achievements in them (weather its action - command - or player commands).... I dont like seeing just the commands category and i'd like to be able to classify some of my command achievements differently, but with the current system its always under commands category.

**Comment by PyvesB** [comment]
Hello evanmcclan,

Would probably be complicated to integrate with the current code basis and would be confusing for th user to set up in the configuration file. I'm sorry to say that this will likely not be done. ;-)

Cheers,

Pyves
