### ISSUE TITLE
Request: put not done yet achievement into database

### ISSUE THREAD

**Issue by kingdcreations** [PyvesB/AdvancedAchievements#226]
Hi, we started to use your plugin recently and absolutly love it! 
Here is an example of what we done with the database feature: http://asgard-mc.fr/profil/?pseudo=KingDiams
We would love to make achievement not done yet appear in our profiles pages.
Thank you!

**Comment by PyvesB** [comment]
Hello kingdcreations,

I don't think this would be a good idea. 
- it would considerably increase the size of the database. The plugin would need to store potentially hundreds of records in the database corresponding to all the achievements never received, even if a player joins the server for two minutes and never comes back again. On my server, this would make a table of about 100k records grow to almost 4 million!
- it would hurt performance when a player first joins, as the plugin would have to write all these records to the database.
- it would slow down the overall performance of the plugin, as it would have to perform lookups and operations on a significantly larger database table.

Maybe you could try to link your website to the configuration file, so you can figure out which achievements were not received without relying on the database? ;-)

Cheers,

Pyves

**Comment by kingdcreations** [comment]
Oh, I see, thank you for your quick answer! :)
