### ISSUE TITLE
Blocks broken not showing

### ISSUE THREAD

**Issue by TWSSYesterday** [PyvesB/AdvancedAchievements#229]
https://hastebin.com/uleqavonib.makefile
Version 1.12, latest Paper Spigot
Version 5.2.5 not working, everything loads up normally, no errors.
Everything works apart from blocks broken.
Using a plugin that moves blocks instantly to inventory on block break (i.e. autosell)
Let me know what I can do.

**Comment by PyvesB** [comment]
Hello TWSSYesterday,

Yes, this has previously been pointed out, Autosell plugin seems to mess up with Bukkit's _BlockBreakEvent_. Nevertheless, as mentioned in #216, there is not much I can do:

"That seems to be payed software and I don't own a copy myself, so I won't be able to look into it. You should maybe try contacting its author directly, and explain that some of its features break other plugins. ;-)"

Cheers,

Pyves

**Comment by TWSSYesterday** [comment]
Contacted via email

**Comment by PyvesB** [comment]
I will look into it. ;-)

**Comment by TWSSYesterday** [comment]
I'm getting lag from the plugin also, it sounds like it could be to do with this. See screenshot below:
http://i.imgur.com/wLuMmx0.png

**Comment by PyvesB** [comment]
I looked into the Autosell issue with the configuration you sent me. The plugin seems to be somehow messing with the Bukkit API. When Advanced Achievements receives a _BlockBreakEvent_, the server systematically indicates that the block just broken was "air", which is obviously wrong. This behaviour from Autosell is quite troublesome, and can break a lot of plugins relying on a proper usage of the _BlockBreakEvent_. I would recommend contacting its author.

For the performance issues you are facing, you can try increasing the values of _PlaytimeTaskInterval_ and _DistanceTaskInterval_ in the configuration file. Also check your database settings, and try out a different database type to see if it improves performance. ;-)
