### ISSUE TITLE
Suggestion - add option to ignore AFK  PlayedTime

### ISSUE THREAD

**Issue by Amiroslo** [PyvesB/AdvancedAchievements#230]
Can you add a config so it does not calculate time spent playing if the person is afk? Because rn if the player is afk, it still calculates it as time played

**Comment by PyvesB** [comment]
Hello,

Here's a version with the new feature implemented (_IgnoreAFKPlayedTime_ configuration option). Could you please test it and confirm that everything is working as expected?

Cheers,

Pyves
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1220526/AdvancedAchievements.zip)
