### ISSUE TITLE
Probleme

### ISSUE THREAD

**Issue by jere62smi** [PyvesB/AdvancedAchievements#231]
Hello, we have a problem with achievement. Indeed, we have players who do not get their achievement while they have carried out all the actions. Is it possible to add check that verify the player's stats in order to automatically give it achievement.

http://prntscr.com/g9u387

**Comment by PyvesB** [comment]
Hello,

Please refer to question 4 of the [FAQ](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)). ;-)

Cheers,

Pyves
