### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by AlpacatheGreat** [PyvesB/AdvancedAchievements#232]
Hello!
When I do /aach list, only the xp bottle and the clock is showing correctly. All the other icons have changed to barrier for some reason. I have not used tab instead of space bar. 
I also get this error from the console when I do /aach generate: "18:33:15 CONSOLE: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 188 path $.display.title
18:33:15 CONSOLE: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 188 path $.display.title"
I have checked line 1 column 188 in all 3 of the yml files but nothing is at the mentioned place. 
My server is running 1.12.1 and all other features are working correctly at the moment. Please help with this issue as I really want to add this awesome plugin to my server.
Thanks!

**Comment by PyvesB** [comment]
Hello AlpacatheGreat,

Regarding /aach list, you have probably enabled this behaviour by changing the default configuration and setting _HideNotReceivedCategories_ to true.

Regarding /aach generate, I would need to have a look at you configuration file, could you please paste in Gist or Pastebin?

Cheers,

Pyves

**Comment by AlpacatheGreat** [comment]
The /aach list is working now!
I have inserted the config here as a script
`<script src="https://gist.github.com/AlpacatheGreat/8035c621404e928f25d7c7dc86eab9e5.js"></script>`

**Comment by PyvesB** [comment]
You're welcome! Feel free to star the project. ;-)
