### ISSUE TITLE
Help with colour and spaces

### ISSUE THREAD

**Issue by blijgozertje** [PyvesB/AdvancedAchievements#237]
When changing the icon setting to "" It just gets a space please add or tell me how to disable this icon thing.

 Set the icon of the plugin (default: shamrock, \u2618).

Icon: ""

Also in the GUI you can see the Goal and progress you can edit the word goal and progress but not the actual goal or progress text/bar colors because &8 is very ugly on my server

thx

**Comment by PyvesB** [comment]
Hello,

Regarding the icon, are you using the latest version of the plugin?

Regarding the colours, have you tried adding a string such as "§3" in front of the relevant messages in **lang.yml**?

Cheers,

Pyves

**Comment by blijgozertje** [comment]
Yes, I am using the latest version.

I have colored them but it doesn't show.

**Comment by PyvesB** [comment]
Can you provide me with a screenshot showing the space in place of the icon?

**Comment by blijgozertje** [comment]
Screenshots of space icon:
https://imgur.com/a/pUslj

The part of the config:
# Set the icon of the plugin (default: shamrock, \u2618).
Icon: ""

Screenshots of menu coloring:
https://imgur.com/a/0VbrT
https://imgur.com/a/WQJ9f

That part of the config:
Breaks: 
  sand:1:
    10:
      Message: "&fYou have collected 10 red sand blocks!"
      Name: break_10_sand1
      DisplayName: Red Sand Fan
  stone:
    1:
      Message: "&fThe first time you went mining!"
      Name: break_1_stone
      DisplayName: Cobble!
      # Use semicolons for multiple command rewards. PLAYER will be replaced by players name.
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5

**Comment by blijgozertje** [comment]
How can I change those colors and space?

**Comment by PyvesB** [comment]
As far as the spaces are concerned, you must have specified some in the _ListAchievementFormat_ configuration parameter, you should remove them from there.

In _/aach list_, the colours only appear once the achievement has been completed. When the achievement is in progress, they are ironed out and replaced by the grey colour. If you don't like grey, I suggest you recompile the plugin and modify the _ListCommand_ implementation.
