### ISSUE TITLE
Brewing category behaviour

### ISSUE THREAD

**Issue by vkolasa** [PyvesB/AdvancedAchievements#239]
There might be a bug with advanced achievements with the brewing category, I had a player recently put potions acquired from an end city in a brewing stand , wait 10 seconds then place them back and it ticks the counter. maybe its just my config? I dunno, but I figured I would tell you just in case it isnt me. Thanks.

**Comment by PyvesB** [comment]
Hello vkolasa,

Unfortunately, as far as I know there is no way to properly detect when a player has finished brewing a potion and comes to collect it using the Bukkit API. Therefore I can only check whether a player removes a potion from a brewing stand inventory. If a player puts an already brewed potion back and retrieves it after the cooldown delay, this will count as a new action. ;-)

Cheers,

Pyves
