### ISSUE TITLE
"DateLocale" - Error

### ISSUE THREAD

**Issue by R4zzer** [PyvesB/AdvancedAchievements#240]
I have in the config this:
"DateLocale: de"

the date on the server is right, but the time not
I use the LATEST version.

**Comment by PyvesB** [comment]
Hello R4zzer,

Could you be more specific about how the time isn't right?

Cheers,

Pyves

**Comment by R4zzer** [comment]
Example: 7:00 PM is on the server 00:00 Uhr (German Time)

**Comment by PyvesB** [comment]
I've tested this myself, and it seems to work fine both in _/aach book_ and _/aach list_.

Are you using the latest version of the plugin? Which database type are you using? Have you set _DateDisplayTime_ to true in the configuration? Also bear in mind that any achievements received with a plugin version prior to 4.1 will automatically show as 00:00.
