### ISSUE TITLE
aach list

### ISSUE THREAD

**Issue by playfrite** [PyvesB/AdvancedAchievements#241]
Hello,

here, I would like to know if it is possible to make several pages for a type of action.

My current problem is that there are 70 achievements in the category places and when I do / aach list it is completely illegible

What can I do?

Thank you and good day

**Comment by R4zzer** [comment]
I think @PyvesB can add a small gui with "Achievements done" and "not done".
This is a better solution for the /aach list gui.

**Comment by playfrite** [comment]
I was thinking about a page system and how do I contact @PyvesB?

thank you

**Comment by R4zzer** [comment]
Spigot-Discussion

**Comment by PyvesB** [comment]
Hello playfrite,

This has already been suggested by #222. I haven't yet looked into it. Anyone else can also feel free to contribute, as the plugin is open-source. ;-)

Cheers,

Pyves
