### ISSUE TITLE
Achievement Description (Book)

### ISSUE THREAD

**Issue by R4zzer** [PyvesB/AdvancedAchievements#242]
The description doesn't change in the book.

Config: https://goo.gl/B6oNnh
Book: https://goo.gl/rtdchD

**Comment by PyvesB** [comment]
Hello R4zzer,

As stated in the [FAQ](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)), the `Message` parameter gets stored in the database. The _/aach book_ command relies on the database to get all its data. You therefore need to change the relevant database entries if you decide to change the `Message` parameter after players have received the achievement.

Cheers,

Pyves

**Comment by R4zzer** [comment]
I can not speak English so well. Can you give me a short version? xD

**Comment by PyvesB** [comment]
Well you have to modify the messages in the database table (_achievemenst.db_ if you are using SQLite, default database of the plugin).

**Comment by R4zzer** [comment]
But i use mysql

**Comment by PyvesB** [comment]
The same stands. ;-)
