### ISSUE TITLE
/aach list - Icon

### ISSUE THREAD

**Issue by R4zzer** [PyvesB/AdvancedAchievements#243]
Maybe you can add a option in the config.yml to change every icon in the /aach list GUI?

**Comment by PyvesB** [comment]
Hello R4zzer,

This has already been suggested by #198.  I haven't yet looked into it. Anyone else can also feel free to contribute, as the plugin is open-source. ;-)

Cheers,

Pyves

**Comment by R4zzer** [comment]
this is already availabe in gui.yml, sorry.
