### ISSUE TITLE
Own Categories

### ISSUE THREAD

**Issue by R4zzer** [PyvesB/AdvancedAchievements#245]
Maybe you can add a function to add own categories or placeholders (barriers in the GUI without letters)
and a function to change the location of single categories in the /aach list GUI?
P.S: A page-system would be good for that

**Comment by PyvesB** [comment]
Hello,

If you want to add new categories, you should refer to the [developers](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers) guide.

I'm not convinced letting people randomly place the items in the GUI would be really useful, especially regarding the fact that no one has ever asked for this.

Cheers,

Pyves

**Comment by R4zzer** [comment]
can you add this in the config?

**Comment by PyvesB** [comment]
Please refer to my answer above. Feel like I'm waiting my time here.
