### ISSUE TITLE
Console Spam/Error

### ISSUE THREAD

**Issue by Droodzur** [PyvesB/AdvancedAchievements#246]
Hello I am getting this error spamming my console 24/7

`27.09 09:17:28 [Server] WARN [AdvancedAchievements] Task #456693 for AdvancedAchievements v5.2.9 generated an exception 27.09 09:17:28 [Server] INFO java.util.concurrent.RejectedExecutionException: Task com.hm.achievement.db.SQLWriteOperation$1@2a259e07 rejected from java.util.concurrent.ThreadPoolExecutor@303d600b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] 27.09 09:17:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_121] 27.09 09:17:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_121] 27.09 09:17:28 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_121] 27.09 09:17:28 [Server] INFO at com.hm.achievement.db.SQLWriteOperation.executeOperation(SQLWriteOperation.java:33) ~[AdvancedAchievements.jar:?] 27.09 09:17:28 [Server] INFO at com.hm.achievement.db.SQLDatabaseManager.updateAndGetConnection(SQLDatabaseManager.java:681) ~[AdvancedAchievements.jar:?] 27.09 09:17:28 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener.handleConnectionAchievements(AchieveConnectionListener.java:120) ~[AdvancedAchievements.jar:?] 27.09 09:17:28 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener.access$200(AchieveConnectionListener.java:33) ~[AdvancedAchievements.jar:?] 27.09 09:17:28 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener$1.run(AchieveConnectionListener.java:103) ~[AdvancedAchievements.jar:?] 27.09 09:17:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 27.09 09:17:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by PyvesB** [comment]
Hello Droodzur,

This is surprising. Could you please update to the latest Spigot build? Are there any errors or warning messages when the plugins start up? When this error happens, does Advanced Achievements still seem to work in game (commands, achievements, etc.)? Have you tried restarting (not reloading) your server?

Cheers,

Pyves
