### ISSUE TITLE
disconnect on achievement earned 

### ISSUE THREAD

**Issue by c00ldude1oo** [PyvesB/AdvancedAchievements#248]
When a player earns an achievement it will cause them to disconnect from the server

I am using 1.12.2 spigot and bungeecord latest and the latest version of AA

**Comment by c00ldude1oo** [comment]
Here is a image of what happens 
![20171024_115314](https://user-images.githubusercontent.com/15677803/31978761-e0b9e540-b910-11e7-9e74-93c7b6603a79.png)

**Comment by PyvesB** [comment]
Hello c00ldude1oo,

Could you please post the full error message as text?

Could you also try disabling the _Firework_, _AdditionalEffects_, _Sound_, _CooldownActionBar_ and _TitleScreen_ configuration parameters, and see whether the problem persists?

Cheers,

Pyves
