### ISSUE TITLE
Can't change "Time played" in lang.yml

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#25]
Unfortunately there's no possibility to translate "Time played" into another language in lang.yml.

![aach](https://cloud.githubusercontent.com/assets/13700636/14990342/768dd2ba-115c-11e6-9dd5-4ef99b5448e2.png)

**Comment by PyvesB** [comment]
Hello,

This is odd, an entry seems to be missing in the default language file; you have to add a section called "list-playedtime:", and give it the value you want, that should do the trick. ;-)

**Comment by Platinteufel** [comment]
Worked for me, thank you. :)

**Comment by PyvesB** [comment]
Great. I'll mark this issue as close. ;-)
