### ISSUE TITLE
MySQL (DEFAULT CHARSET=utf8), (utf8)

### ISSUE THREAD

**Issue by DaNseRYT** [PyvesB/AdvancedAchievements#252]
1. Please add a line when creating the database - https://hastebin.com/redebeyopi.pas
2. Please add a line when connecting to the database - https://hastebin.com/apiyigijot.erl

**Comment by PyvesB** [comment]
Hello DaNseRYT,

How will this affect current users of the plugin, who have already generated their database without the `utf8` parameter set? Would you like to submit a pull request with these changes? :wink:

Cheers,

Pyves

**Comment by DaNseRYT** [comment]
Yes! Who really need to recreate the database. I have to, I from Russia (And a bundle in the database(MySQL) look like this: '??????????????? ??????? ???????'

**Comment by DaNseRYT** [comment]
![screenshot_1](https://user-images.githubusercontent.com/33249522/32271374-9d393cb2-bf0a-11e7-9e1d-1cb2619378d8.png)
![screenshot_2](https://user-images.githubusercontent.com/33249522/32271375-9d56fa7c-bf0a-11e7-94e4-40e83640117d.png)

**Comment by DaNseRYT** [comment]
Excuse me, but when will you add this to the code?

**Comment by DaNseRYT** [comment]
Excuse me, but when will you add this to the code?

**Comment by DaNseRYT** [comment]
Excuse me, but when will you add this to the code?

**Comment by PyvesB** [comment]
> Yes! Who [...].

I'm assuming this was a response to my only yes-no question, "Would you like to submit a pull request with these changes?", but you don't seem to have actually submitted any pull request yet.

> How will this affect current users of the plugin, who have already generated their database without the utf8 parameter set?

I am still unclear about this and how a seamless update can be provided for existing users and databases.

**Comment by DaNseRYT** [comment]
For those who have already created the database, does not affect. But all the same, who needs it, they will recreate the base (like me). Please, just add this in the next update

**Comment by PyvesB** [comment]
I'll see what I can do.
