### ISSUE TITLE
Plowing Ground bug

### ISSUE THREAD

**Issue by dniym** [PyvesB/AdvancedAchievements#254]
If you have a plow ground achievement set up all a player needs to do is find a grass block in a place they do not have permission to build and hold down the right mouse button.     Ground does not get plowed but they do get credit for tilling 1 soil per click.

**Comment by PyvesB** [comment]
Hello dniym,

What building permission plugin are you using? If it's World Guard, you may have misconfigured it, please refer to the discussions in #117. 😉 

Cheers,

Pyves

**Comment by aurel85** [comment]
Hi,

The same for me with RedProtect and WorldGuard.

**Comment by PyvesB** [comment]
Same answer as above: try setting `interact: deny` in your region configuration, it should do the trick!

**Comment by PyvesB** [comment]
Same answer as above: try setting `interact: deny` in your region configuration, it should do the trick!

**Comment by aurel85** [comment]
I let interact on true voluntarily, so too bad ^^.
