### ISSUE TITLE
Suggestion : Remove the cooldown once the achievement is over

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#255]
Hi,

I was wondering if it would be possible to remove the cooldown and its message set up on some achievements only when the player has validated all the achievements of this category ?

Because this cooldown and its message are good ideas, but it can be a little disturbing when you fill water buckets several months after you have finished the achievement.

It's detail but it would be cool.

**Comment by PyvesB** [comment]
Hello aurel85,

Seems like a reasonable idea, I'll look into it!

Cheers,

Pyves

**Comment by PyvesB** [comment]
Here's a test version. Would you like to give it a try?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1443129/AdvancedAchievements.zip)

**Comment by aurel85** [comment]
I tested everything is ok. No errors to report. Thank you !
