### ISSUE TITLE
About HideNotReceivedCategories

### ISSUE THREAD

**Issue by prozhong** [PyvesB/AdvancedAchievements#258]
I remember inv5.2.5 when set this to true, the gui didn't show the category at all.
But now its a BARRIER instead.

Is it due to some bug or planned

**Comment by PyvesB** [comment]
Hello prozhong,

This is the intended behaviour, there may have been a bug in some of the earlier versions of the plugin. You have an associated `list-category-not-unlocked` configuration option in _lang.yml_. I'll update `config.yml` to avoid any confusion in the future. ;-)

Cheers,

Pyves
