### ISSUE TITLE
"Big walker" and respawn

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#26]
I've just noticed that you can use a warp that is a long way from your home and if you die there and respawn at home the distance will be count for "Big Walker" (DistanceFoot), so this achievement is not usable for me atm. :/

**Comment by PyvesB** [comment]
Hello,

Interesting, I had not thought about this rather simple use case, and it was never reported in the past. Thanks for the report, it will likely be fixed in the next update! ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Thanks. If I install the plugin before the next update, I need to disable the DistanceFoot category, so that it doesn't collect any data here. Could you tell me how I can do that? :)

**Comment by PyvesB** [comment]
You can simply wait until the next update, I'll try to issue it by the end of the week. ;-)

**Comment by Platinteufel** [comment]
Okay, thank you for your hard work. :)
Would you recommend using MySQL or is sqlite also fine for a medium-sized server? (~30-40 online)

**Comment by PyvesB** [comment]
No problem with using SQLite, it's a database system that has very good performance (but limited functionality and scalability). I run a server with a similar number of players, Advanced Achievements accounts for about 0.01% of CPU usage, with 136 achievements, all categories enabled and a database that has been collecting stats for more than one year now; in comparison, we have several other popular plugins that take significantly more than 1% of the CPU time each. Nevertheless, bear in mind that having a SSD and not an HDD does help boost the performance of any database plugin. ;-)

**Comment by Platinteufel** [comment]
Okay, I will use sqlite as soon as the update is available. :)

**Comment by Platinteufel** [comment]
Do you know if you can fix this till tomorrow? My players are very excited :D

**Comment by PyvesB** [comment]
The update is on its way. ;-)

**Comment by Platinteufel** [comment]
Wow, thank you very much! :)

**Comment by PyvesB** [comment]
Have fun! Issue closed. ;-)

**Comment by Platinteufel** [comment]
Nice update, I'm just missing some spaces, but that's not really imporant :)

![unbenannt](https://cloud.githubusercontent.com/assets/13700636/15084097/9113839c-13d1-11e6-899c-7ff87d905e0d.png)

**Comment by PyvesB** [comment]
Add them in the language file. ;-)

**Comment by Platinteufel** [comment]
Thanks! :)

**Comment by Platinteufel** [comment]
Seems like "Big Walker" still counts the distance between death- and respawn point, but I think I can ignore that because my world isn't that big. ^^

**Comment by PyvesB** [comment]
Actually I seems that I may have have confused the different events occuring when a player days. I will rework on that in a future update. ;-)

**Comment by Platinteufel** [comment]
Fixed in the new version. ;-)
