### ISSUE TITLE
Lag server

### ISSUE THREAD

**Issue by masterolos09** [PyvesB/AdvancedAchievements#260]
Screenshots timings:
https://scr.hu/NYeNV3
https://scr.hu/nwmV2Z

**Comment by PyvesB** [comment]
Hello masterolos09,

The counts of monitored events are really low (1, 2, etc.) and are therefore not really meaningful. You should allow the Java Virtual Machine to properly start up (see [just-in-time compilation](https://en.wikipedia.org/wiki/Just-in-time_compilation) if you're up for some technical reading) and let the plugin build up its internal cache.

Also ensure that:
- you are using the most up-to-date version of the plugin (5.3.2).
- your Spigot version is the latest to date.
- your system is up-to-date. In particular the database drivers and Java versions should be updated.
- you have configured your database correctly. For inexperienced users, I recommend letting the plugin handle SQLite on its own.

Hope this helps! :wink:

Cheers,

Pyves

**Comment by masterolos09** [comment]
I am using mysql database
As I have uploaded AdvancedAchievments on the server are lag, and as it usune it has no lag
Linux is the latest . :(
PHPMyAdmin is also the latest

**Comment by PyvesB** [comment]
> Linux is the latest

This does not mean much, as Linux is a family of operating systems.

> PHPMyAdmin is also the latest

PHPMyAdmin is a web interface for administrating databases, having it up-to-date or not will not influence performance whatsoever.

> Java 8

This is vague, your Java may be up to almost 4 years old.


You have ignored several of the recommendations in my previous answer. Please go through the effort of setting up your system, server and database properly. If you lack the skills, use SQLite and let the plugin handle things on its own. Having a response time ranging from several hundreds of milliseconds to several seconds for simplistic queries on an empty MySQL database is not Advanced Achievements' fault. 😉
