### ISSUE TITLE
Kills?

### ISSUE THREAD

**Issue by TSGPwner** [PyvesB/AdvancedAchievements#262]
So with the achievements for Entity kills : http://prntscr.com/herdsc : I am not able to get it to track for the pigman kills, I'm not really sure what I could be doing wrong, but I would love some feed back! Thank you so much!

**Comment by PyvesB** [comment]
Hello TSGPwner,

Please refer to [this page](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html) for entity names. Switching from` zombie_pigman` to `pig_zombie` should do the trick. 😉 

Cheers,

Pyves

**Comment by TSGPwner** [comment]
I am so greatly angered because I thought that would work and I didn't...
God.

**Comment by PyvesB** [comment]
Haha, it happens. Feel free to open a new issue if you encounter any other problems!
