### ISSUE TITLE
Custom Reward Display

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/AdvancedAchievements#263]
Is there a way display a custom command reward? As in, stead of it auto interpreting the reward from vanilla, I can put custom text as the displayed reward. 

[CODE]  3:
    Message: Level 3 reached!
    Name: maxlevel_3
    DisplayName: "&4Newbie"
    Reward:
      Command: jobs editpoints add PLAYER 5; give PLAYER 126 5
[/CODE]

Shows up as "other" for reward

**Comment by PyvesB** [comment]
Hello BobbyMere,

This is currently not possible. @supertassu had implemented similar support for item rewards in #214, maybe this is something he can pick up as well? Alternatively it would be nice to a general approach to be able to modify reward display names regardless of the reward type. 😉 

Cheers,

Pyves

**Comment by supertassu** [comment]
Thanks for the tag @PyvesB; i'll take a look to it later today.

**Comment by BobbyMere** [comment]
thank you for looking into it and seeing if it's a possible future update

**Comment by PyvesB** [comment]
Here's a test version if you want to give the new feature a try before the official release. I'm sure @supertassu would appreciate some user feedback! 😉 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1523038/AdvancedAchievements.zip)

**Comment by BobbyMere** [comment]
I can't get that plugin to load. Says there an error while loading config.yml file and disables itself.

**Comment by PyvesB** [comment]
D'oh! @supertassu, we missed out the quotes around `say §cALERT: §7PLAYER is now a statistician`!

**Comment by supertassu** [comment]
You said to remove them

**Comment by PyvesB** [comment]
There was a misunderstanding, I only meant that for `Become the Stone God` which didn't need them as it does to contain any special characters. ^^

**Comment by supertassu** [comment]
Oopsie. On phone, can't make a pr now..

**Comment by BobbyMere** [comment]
How do you get custom command to show a custom reward? Putting it after the final quantity after the command don't work. Is there another section for it? Otherwise, it still shows up as "other."

  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: break_1_stone
      DisplayName: Cobble!
      Reward:
        Command: give PLAYER 158 10 testing 

reward comes up as "other"

**Comment by supertassu** [comment]
```
Reward:
  Command: 
    Execute: command here
    Display: REWARD NAME HERE
```

**Comment by PyvesB** [comment]
Here's a version with a fixed default configuration file:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1524636/AdvancedAchievements.zip)

**Comment by BobbyMere** [comment]
Amazing job. Thank you for adding it.

**Comment by supertassu** [comment]
Woo!

**Comment by BobbyMere** [comment]
Why would this work: 

  3:
    Message: Level 3 reached!
    Name: maxlevel_3
    DisplayName: "&aNewbie"
    Reward:
      Command:
        Execute: jobs editpoints add PLAYER 1
        Display: 1 Job point

But this not work:

  5:
    Message: Level 5 reached!
    Name: maxlevel_5
    DisplayName: "&6Novice"
      Command:
        Execute: jobs editpoints add PLAYER 5
        Display: 5 Job point

The second one gets this message:
03.12 06:25:32 [Server] INFO Message: Level 5 reached!
03.12 06:25:32 [Server] INFO in 'string', line 619, column 5:
03.12 06:25:32 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
03.12 06:25:32 [Server] ERROR Verify your syntax by visiting yaml-online-parser.appspot.com and using the following logs:
03.12 06:25:32 [Server] ERROR Error while loading config.yml file, disabling plugin.

**Comment by PyvesB** [comment]
You are missing the `Reward:` section in the second one.

**Comment by supertassu** [comment]
Pro tip: read the error message

**Comment by BobbyMere** [comment]
I read it. I don't know what block end meant besides it meaning it was end of that line code. I have no idea what to look at to fix it as they both looked exactly the same. Well, the same besides "reward" missing

**Comment by BobbyMere** [comment]
Anyways, thanks again. It works now
