### ISSUE TITLE
Id for pigman zombie?

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/AdvancedAchievements#265]
What's the id for pigman zombie?

Zombie Pigman
(minecraft:zombie_pigman)

Both of these don't work

Zombie_Pigman:
10000:
Message: Kill 10000 zombie pigman
DisplayName: Bone crusher
Name: kills_10000_zombie_pigman

**Comment by BobbyMere** [comment]
What's the id for pigman zombie?

Zombie Pigman
(minecraft:zombie_pigman)

Both of these don't work

  Zombie_Pigman:
    10000:
      Message: Kill 10000 zombie pigman
      DisplayName: Bone crusher 
      Name: kills_10000_zombie_pigman

**Comment by supertassu** [comment]
pig_zombie

**Comment by BobbyMere** [comment]
Thank you. Is there a list some where for all the mob id's and reward options?

**Comment by supertassu** [comment]
mob ids: https://hub.spigotmc.org/javadocs/spigot/index.html?org/bukkit/entity/EntityType.html
item ids: https://hub.spigotmc.org/javadocs/spigot/index.html?org/bukkit/Material.html

**Comment by PyvesB** [comment]
Hey there,

Thanks for your help supertassu!

Funnily enough the exact same question was asked this week in #262. I recommend reading the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) and the information in the headers of the configuration files. 😉 

Cheers,

Pyves
