### ISSUE TITLE
Suggestion : Add placeholders to see players data

### ISSUE THREAD

**Issue by Phoetrix** [PyvesB/AdvancedAchievements#268]
Hi! Is it possible to add a compatibility with PlaceholderApi?

You say in the FAQ that you are not interested to working with other plugins. So if I add the compatibility in your plugin, you will add my class in a next update or not?

If you are okay with that, I would like to ask some questions to you and I have an error with the file "PlayerAdvancedAchievementListener.java" on the "listener" package in Eclipse, is it normal?

**Comment by supertassu** [comment]
a) If it's good, it will most likely be added
b) What error?

**Comment by PyvesB** [comment]
Hello Phoetrix,

As pointed out by @supertassu, if you come up with a nice implementation, open a pull request so it can be reviewed and merged! :wink:

To import the package in Eclipse, have you followed the steps outlined in the [Developers Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers)?

Cheers,

Pyves

**Comment by Phoetrix** [comment]
Ok thank you! I don't known for the error. I get at first line of the class "PlayerAdvancedAchievementListener" => "The type com.google.common.collect.ImmutableList$Builder cannot be resolved. It is indirectly referenced from required .class files"

And Eclipse don't like these following lines: 
`plugin.getCacheManager().getReceivedAchievementsCache().put(uuid, event.getName());
			plugin.getCacheManager().getNotReceivedAchievementsCache().remove(uuid, event.getName());`

And I never use Maven in Eclipse, I try to do a build but I don't known how to get the jar. In the target folder, I have just the last version of the plugin in your Spigot page but not my version so I can't do tests. :(

**Comment by Phoetrix** [comment]
Ah, it's good! I have a build now but the plugin reacts badly because I have errors on Eclipse with "PlayerAdvancedAchievementListener". I will send you all problems that I encounter if it persists.

**Comment by Phoetrix** [comment]
Ok so I follow steps on the Developper Wiki and do directly a build to test and I have these errors:

`03.12 18:00:37 [Server] ERROR Could not load 'plugins/AdvancedAchievements.jar' in folder 'plugins'
03.12 18:00:37 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems: 
03.12 18:00:37 [Server] INFO The import com.google.common.collect.Multimap cannot be resolved
03.12 18:00:37 [Server] INFO The import com.google.common.collect.MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
03.12 18:00:37 [Server] INFO Caused by: java.lang.Error: Unresolved compilation problems: 
03.12 18:00:37 [Server] INFO The import com.google.common.collect.Multimap cannot be resolved
03.12 18:00:37 [Server] INFO The import com.google.common.collect.MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO MultimapBuilder cannot be resolved
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO Multimap cannot be resolved to a type
03.12 18:00:37 [Server] INFO at com.hm.achievement.db.DatabaseCacheManager.<init>(DatabaseCacheManager.java:10) ~[?:?]
03.12 18:00:37 [Server] INFO at com.hm.achievement.AdvancedAchievements.<init>(AdvancedAchievements.java:202) ~[?:?]
03.12 18:00:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
03.12 18:00:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_111]
03.12 18:00:37 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
03.12 18:00:37 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
03.12 18:00:37 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_111]
03.12 18:00:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1248]
03.12 18:00:37 [Server] INFO ... 6 more`

**Comment by PyvesB** [comment]
Could you please try adding the following to the dependencies in `pom.xml`, and see whether it helps with your issues in Eclipse?

```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <scope>compile</scope>
    <version>20.0</version>
</dependency>
```

**Comment by Phoetrix** [comment]
Thank you very much PyvesB! Now it's work perfectly! :D

So I will begin my tests, see you later! ;)

**Comment by PyvesB** [comment]
Awesome! I have committed the fix to the `master` branch to avoid any problems in the future. 😉

**Comment by Phoetrix** [comment]
Ok I have finish my implementation of PlaceholderAPI in the plugin, everything work great but how can I send to you my class?

I see that we can commit our work on "Pull requests" but I don't understand how does it work... Haha my bad... :(

**Comment by PyvesB** [comment]
Have you had a look at the [GitHub documentation](https://help.github.com/articles/creating-a-pull-request/) regarding pull requests? It should provide some help. ^^

**Comment by Phoetrix** [comment]
Thank you, it's ok! :)

**Comment by PyvesB** [comment]
Pull request #269 was merged. I have attached a test version so that anyone interested in PlaceholderAPI support can try it out. I'm sure @Phoetrix would appreciate some additional feedback before the official release. 😉 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1528860/AdvancedAchievements.zip)

**Comment by PyvesB** [comment]
Pull request #269 was merged. I have attached a test version so that anyone interested in PlaceholderAPI support can try it out. I'm sure @Phoetrix would appreciate some additional feedback before the official release. 😉 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1528860/AdvancedAchievements.zip)
