### ISSUE TITLE
Random reward from the kit

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#27]
How difficult it is to make the award of the sets?

bundle.yml

> WoodenBundle:
> ...
> StoneBundle:
>     Item: stone_sword
>         Name: '&eStone Sword Novice'
>         Amount: 1
>         Chance: 0.7 (1 = 100%)
>     Item: stone_pickaxe
>         Name: '&eStone Pickaxe Novice'
>         Amount: 1
>         Chance: 0.6 (1 = 100%)
>     Item: stone_pickaxe
>         Name: '&eStone Pickaxe Novice'
>         Amount: 1
>         Chance: 0.6 (1 = 100%)
> ...
>     Item: stone_hoe
>         Name: '&eStone Hoe Novice'
>         Amount: 1
>         Chance: 0.2 (1 = 100%
> IronBundle:
> ...
> GoldenBundle:
> ...
> DiamondBundle:
> ...
> 
>     Item: {itemid} or {gunpowder} or {<ore:barsIron>} or {<EnderIO:itemMaterial:8>} or {<TwilightForest:tile.TFSapling:*>}

config.yml

> Kills:
>   zombie:
>     '1':
>       Message: '&cТвоё первое убийство зомби!'
>       Name: Ходячие мертвецы
>       Reward:
>         {Money: 1         
>         Item: diamond 1}
> or
>         Bundle: StoneBundle
>         Amount: 3 (Number of random items from the set)

**Comment by PyvesB** [comment]
Hello,

For rewards, please follow the examples in the default configuration file.

Cheers,

Pyves

**Comment by LLIaMMaH** [comment]
To them I now use. I would like to issue a random reward, and not always in the number one subject. By creating a set and specifying how many items you need to give each player would have received a unique award for himself from the set.

**Comment by PyvesB** [comment]
This is not possible in the plugin; you might be able to use a custom kit plugin and give command rewards though.

**Comment by LLIaMMaH** [comment]
I understand that it is very difficult to read the file sets and sets of randomly selected items from said set.
Only the specific items or a set of commands is the easiest way to give to all the same award.
