### ISSUE TITLE
[15:47:35 INFO]: 1 <- Giving me this in console

### ISSUE THREAD

**Issue by zAnonimo** [PyvesB/AdvancedAchievements#271]
Hello guys, thanks for help and keeping this awesome project at first!
I just installed the plugin, and it works flawless, but in my console I get something that triggers me. Every single time someone kill a mob, or cut a wood, or mine a stone, or whatever action the user does, in console I get:
`[15:47:35 INFO]: 1`

Any idea? It's not an error at all, but it seems to spam my console a lot. Thanks!

**Comment by PyvesB** [comment]
Hello zAnonimo,

Are you sure this is coming from Advanced Achievements? Are you using version 5.4? I did a quick search through the code and didn't notice any leftover logging statements. I'm intrigued. :frowning:

Cheers,

Pyves

**Comment by zAnonimo** [comment]
Hey, thanks for helping. Yes, I did various check with and without the Advanced Achievements. It was the last plugin I added, so I knew it was. Anyways, I checked to do these steps I listed in the main ticket, and it didn't say in console, so it had to be the plugin. I'll list you my actual Plugins.
`[18:11:20 INFO]: Plugins (47): FunnyFilter, CrazyCrates, Essentials, ClearLag, AutoMessage, CommandsXL, MDCQuestioner, Votifier, Arconix, FastAsyncWorldEdit, EssentialsProtect, EssentialsGeoIP, EssentialsChat, PermissionsEx, RelayItToDiscord, EpicWorldGenerator, elyby-skinsystem, mcMMO, ViaVersion, TreeFeller, Vault, Optica, ViaBackwards, EssentialsSpawn, FastAsyncVoxelSniper, ProtocolLib, LibsDisguises, Citizens, SignColors, ChatItem, AdvancedAchievements, VoxelSniper, KitPreview, CrazyAuctions, Shop, WorldEdit, FastLogin, AuthMe, Towny, WorldGuard, TownyChat, MythicMobs, Quests, TownyNameUpdater, Jobs, DungeonsXL, SilkSpawners
`

**Comment by PyvesB** [comment]
Interesting. I'll have a closer look into this tomorrow. Thanks for the additional information!

**Comment by zAnonimo** [comment]
No worries, I'll be waiting. Thanks, PyvesB!

**Comment by PyvesB** [comment]
Could you please send me your configuration?

**Comment by zAnonimo** [comment]
`#==============================O==============================#
# I---------------------------------------------------------I #
# |     Advanced Achievements 5.4 configuration - Readme    | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# You can use Minecraft chat colors in Message|DisplayName|Goal, but include double quotes around the whole text: "&4Color".
# Only spaces, NO tabs. Don't forget the indents (2 spaces per indentation level), plugin won't work otherwise!
# To check syntax errors in your file, use: yaml-online-parser.appspot.com
# Do NOT delete any top level (= not indentented) sections in the configuration file.
# Possible items for rewards/Crafts/Places/Breaks: hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Possible mobs for the Kills section:    hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Default config.yml file:  github.com/PyvesB/AdvancedAchievements/blob/master/src/main/resources/config.yml
# Visit the wiki for some valuable additional documentation: github.com/PyvesB/AdvancedAchievements/wiki

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#

# Time in seconds between each /aach book (unless user has permission achievement.*).
TimeBook: 900

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Set to true to activate firework effects when a player receives an achievement.
Firework: true

# Choose BALL_LARGE, BALL, BURST, CREEPER, STAR or RANDOM.
FireworkStyle: BALL_LARGE

# Set to true to activate simpler effects and a calm sound when a player receives an achievement.
# Ignored if Firework setting is set to true.
SimplifiedReception: false

# Number of players displayed in /aach top, week and month commands.
TopList: 5

# Set to true to activate particle effects when performing /aach book, /aach stats with all achievements and
# /aach top, week or month when ranked in the top list.
AdditionalEffects: true

# Set to true to activate sounds when performing /aach book, /aach stats with all achievements and
# /aach top, week or month when ranked in the top list.
Sound: true

# Set the icon of the plugin (default: shamrock, \u2618).
Icon: \u2618

# Set the color of the plugin (default: 5, dark purple).
Color: 5

# Notify other connected players when an achievement is received.
# Default behaviour, a player can override what he sees by using /aach toggle.
NotifyOtherPlayers: false

# When NotifyOtherPlayers is enabled, notifications are done using action bars when ActionBarNotify is true.
# When ActionBarNotify is false, chat messages are used.
ActionBarNotify: true

# Display achievement Name and Message as screen titles. No effect if using Minecraft 1.7.9 or 1.7.10.
TitleScreen: true

# When a player receives an achievement, the Name, Message and rewards of the achievement are displayed in
# the chat. If HoverableReceiverChatText is true, a single hoverable text will be displayed to the receiver.
# Otherwise texts will be displayed one after the other.
HoverableReceiverChatText: false

# Separator between name, description and date on a book page.
BookSeparator: ""

# Set the format of the achievement name in /aach list (default: "%ICON% %NAME% %ICON%").
ListAchievementFormat: "%ICON% %NAME% %ICON%"

# Set the format of the header used for most chat messages (default: "&7[%ICON%&7]").
ChatHeader: "&7[%ICON%&7]"

# Stop all stats from increasing when player in creative mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-creative mode.
RestrictCreative: false

# Stop all stats from increasing when player in spectator mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-spectator mode.
# No effect if using Minecraft 1.7.9 or 1.7.10.
RestrictSpectator: true

# Stop all stats from increasing when player in adventure mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-adventure mode.
RestrictAdventure: false

# Stop all stats from increasing when player in a specific world, including PlayedTime (delete the [] before adding values).
# Connection achievements will only be handled once a player enters a non-excluded world.
ExcludedWorlds: []
#  - yourWorld1
#  - yourWorld2

# Ignore vertical dimension (Y axis) when calculating distance statistics.
IgnoreVerticalDistance: false

# Don't show these categories in the achievement GUI or in the stats output (delete the [] before adding values).
# Also prevent obtaining achievements for these categories and prevent stats from increasing.
# If changed, do a full server restart, and not just /aach reload.
DisabledCategories: []
#  - PetMasterGive
#  - PetMasterReceive
#  - DistanceLlama
#  - DistanceGliding

# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: false

# For categories with a series of related achievements where the only thing changing is the number of times
# the event has occurred, show achievements that have been obtained and show the next obtainable achievement,
# but obfuscate the additional achievements. For example, under Places, stone, the first achievement could have a
# target of 100 stone, the second 500 stone, and the third 1000 stone.  When ObfuscateProgressiveAchievements
# is true, initially only the 100 stone achievement will be readable in the GUI.  Once 100 stone have been placed,
# the 500 stone achievement will become legible.
ObfuscateProgressiveAchievements: false

# Hide categories with no achievements yet received in /aach list by marking them as locked.
HideNotReceivedCategories: false

# Completely hide categories for which the player does not have the corresponding count permissions.
HideNoPermissionCategories: false

# Hide the reward display in /aach list.
HideRewardDisplayInList: false

# Display precise statistic information in the /aach list progress bars.
EnrichedListProgressBars: true

# Annotate each achievement displayed in a /aach list category with a number.
NumberedItemsInList: false

# Sort pages of the book in chronological order (false for reverse chronological order).
BookChronologicalOrder: true

# Do not take into account items broken with Silk Touch for the Breaks achievements.
DisableSilkTouchBreaks: false

# Do not take into account ores broken with Silk Touch for the Breaks achievements.
# DisableSilkTouchBreaks takes precedence over this. Not applicable to iron or gold ores.
DisableSilkTouchOreBreaks: false

# Name of the language file.
LanguageFileName: lang.yml

# Time in seconds between each statistic count for the following categories. 
# LavaBuckets, WaterBuckets, Beds, Brewing, MusicDiscs.
StatisticCooldown: 10

# Display action bar message when player performs an action while in the cooldown period.
# No effect if using Minecraft 1.7.9 or 1.7.10.
CooldownActionBar: true

# Locale used to format dates in /aach book and /aach list. You must select an ISO 639 language code.
# The list of possible language codes can be found at www.loc.gov/standards/iso639-2/php/code_list.php
DateLocale: en

# Display time of reception of achievements in /aach book and /aach list in addition to the date. For achievements
# received in plugin versions prior to 3.0, the precise time information is not available and will be displayed as midnight.
DateDisplayTime: true

# Register advancements with a description corresponding to the Goal parameter of each achievement.
# If changed, run /aach generate to regenerate advancements with the new parameter value taken into account.
# No effect if using Minecraft versions prior to 1.12.
RegisterAdvancementDescriptions: true

# If true, hide advancements from the advancement GUI. Advancement notifications will still appear when receiving achievements.
# No effect if using Minecraft versions prior to 1.12.
HideAdvancements: false

# If true, PlayedTime will no longer increase when the player is AFK. Requires Essentials to work.
IgnoreAFKPlayedTime: false

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#

# Make a daily backup of your local database (if sqlite).
DatabaseBackup: true

# Database type, sqlite, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: sqlite

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ""
  
# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8".
AdditionalConnectionOptions: ""

# Settings to link with MySQL database (ignored if sqlite or postgresql).
MYSQL:
  Database: "jdbc:mysql://localhost:3306/minecraft"
  User: root
  Password: root
  
# Settings to link with PostgresSQL database (ignored if sqlite or mysql).
# Refer to https://github.com/PyvesB/AdvancedAchievements/wiki/Installation to set up PostgreSQL.
POSTGRESQL:
  Database: "jdbc:postgresql://localhost:5432/minecraft"
  User: root
  Password: root
  
#============================OO=OO============================#
# IV-------------------------------------------------------IV #
# |                  Performance settings                   | #
# 4---------------------------------------------------------4 #
#============================oo=oo============================#

# DO NOT CHANGE THE FOLLOWING UNLESS YOU ARE AN EXPERIENCED USER. The intervals are in seconds. 
# If any of the performance settings are changed, do a full server restart, and not just /aach reload.
# Frequency of play time checks for players. Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 60

# Calculates distance traveled by players. Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 5

# Frequency of some statistics writes to the database.
PooledRequestsTaskInterval: 10

#============================OOOOO============================#
# V---------------------------------------------------------V #
# |                  Action  achievements                   | #
# 5---------------------------------------------------------5 #
#============================ooooo============================#

# When a player connects during the day; statistic increases at most once per day.
Connections:
  1:
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice

# When a specific block is placed (specify material name, lower case).
Places:  
  smooth_brick:
    500:
      # Used in /aach list when achievement not yet received, and in advancements.
      Goal: Place 500 stone bricks.
      # Description; displayed when receiving achievement, and in /aach book and /aach list.
      Message: "&4You have placed 500 stone bricks!"
      # Database name, must also be used in /aach delete and /aach check.
      Name: place_500_smooth_brick
      # Name; displayed when receiving achievement, and in /aach book and /aach list.
      DisplayName: Stone Brick Layer
    2500:
      Goal: "Place 2500 stone bricks."
      Message: "&4You have placed 2500 stone bricks!"
      Name: place_2500_smooth_brick
      DisplayName: Stone Brick Architect
  stone:
    100:
      Message: "&4One hundred placed stones!"
      Name: place_100_stone
      DisplayName: Stone Addict
    1000:
      Message: "&4One thousand placed stones!"
      Name: place_1000_stone
      DisplayName: Stone God
      Reward:
        Command:
          Execute: "say Â§7ALERT: Â§4PLAYERÂ§7 has become the Â§4STONE GODÂ§7!"
          Display: Become the Stone God!

# When a specific block is broken (specify material name, lower case).
# Below, the notation sand:1 means sand item with metadata 1 (red sand).
Breaks: 
  sand:1:
    10:
      Message: "&cYou have collected 10 red sand blocks!"
      Name: break_10_sand1
      DisplayName: Red Sand Fan
  stone:
    1:
      Message: "&1The first time you went mining!"
      Name: break_1_stone
      DisplayName: Cobble!
      # Use semicolons for multiple command rewards. PLAYER will be replaced by players name.
      Reward:
        Command:
          Execute: give PLAYER 158 10; give PLAYER 126 5
              
# When a specific mob is killed.
# Use an Entity name or poweredcreeper, in lower case.
# Use player to track player kills as a whole.
# Use specificplayer- followed by player UUID to track how many times a specific player has been killed.
Kills:
  zombie:
    1:
      Message: "&8The first time you killed a zombie!"
      DisplayName: The Walking Dead
      Name: kills_1_zombie
      Reward:
        Money: 1         
        Item: diamond 1
  specificplayer-56c79b19-4500-466c-94ea-514a755fdd09:
    1:
      Message: You killed the author of the plugin!
      DisplayName: No More DarkPyves
      Name: kills_1_darkpyves
      Reward:
        IncreaseMaxHealth: 1
          
# When a specific item is crafted (specify material name, lower case).
Crafts:
  diamond_sword:
    1:
      Message: The first time you crafted a blade!
      Name: craft_1_blade
      DisplayName: Blacksmith Apprentice
      Reward:
        Money: 2
      
# When the player dies.
Deaths:
  1:
    Message: The first time you died!
    Name: deaths_1
    DisplayName: Rest in Peace
    Reward:
        # Text after the material and quantity is interpreted as a custom name, shown in /aach list and when receiving the reward.
        Item: stone 5 Tombstone
    
# When an arrow is shot.
Arrows:
  50:
    Message: 50 arrows shot!
    Name: arrows_50
    DisplayName: Arrows Around the Place
    
# When a snowball is thrown.  
Snowballs:
  1000:
    Message: 1000 snowballs thrown. That's the spirit!
    Name: snowballs_1000
    DisplayName: Winter Addict 
    Reward:
        # 30 corresponds to one bubble in the oxygen bar.
        IncreaseMaxOxygen: 30
    
# When an egg is thrown.  
Eggs:
  1000:
    Message: 1000 eggs thrown!
    Name: eggs_1000
    DisplayName: Omelet Addict 
    
# When a fish is caught. 
Fish:
  1:
    Message: The first time you caught a fish!
    Name: fish_1
    DisplayName: Time for Fish and Chips
    
# When a treasure is caught with a fishing rod.
Treasures:
  1:
    Message: Your first treasure from the sea!
    Name: treasure_1
    DisplayName: Treasure Hunter

# When a tool/armor/weapon is broken.  
ItemBreaks:
  1:
    Message: You broke your favorite tool!
    Name: itembreaks_1
    DisplayName: "&4Clumsy Guy"

# When an item is eaten (excludes potions and milk).
EatenItems:
  1:
    Message: Just had a snack!
    Name: eatenitems_1
    DisplayName: First Snack  
    
# When a sheep is sheared.
Shear:
  100:
    Message: 100 sheep sheared!
    Name: shear_100
    DisplayName: "&1Wool Addict"

# When a cow is milked.
Milk:
  1:
    Message: Just milked a cow!
    Name: milk_1
    DisplayName: First Milk
    Reward:
      Experience: 100
    
# When a bucket is filled with lava.
LavaBuckets:
  10:
    Message: 10 buckets filled with lava!
    Name: lavabuckets_10
    DisplayName: Pyroman
    
# When a bucket is filled with water.
WaterBuckets:
  15:
    Message: 15 buckets filled with water!
    Name: waterbuckets_15
    DisplayName: Fireman    
    
# When a trade with a villager is made.
Trades:
  1:
    Message: Doing business with your first villager!
    Name: trades_1
    DisplayName: First Trade    
    
# When an anvil is used.
AnvilsUsed:
  1:
    Message: You just repaired your first item!
    Name: anvilsused_1
    DisplayName: First Repair 
    
# When an enchantment is performed.
Enchantments:
  5:
    Message: 5 objects enchanted!
    Name: enchantments_5
    DisplayName: "&5Wizard"
    
# When a bed is entered. 
Beds:  
  5:
    Message: You entered a bed 5 times!
    Name: bed_5
    DisplayName: Sleepy Guy 
    
# Maximum level reached.    
MaxLevel:  
  10:
    Message: Level 10 reached!
    Name: maxlevel_10
    DisplayName: "&4Rookie"
    
# When a potion is consumed.
ConsumedPotions:
  100:
    Message: Drinking weird beverages all the time...
    Name: consumedpotions_100
    DisplayName: Alcoholic 
    
# Amount of time played on the server (in hours, use integers).
PlayedTime:
  1:
    Message: You played during one hour on the server!
    Name: playedtime_1
    DisplayName: First Hour
    
# When a distance is traveled by foot.
DistanceFoot:
  1000:
    Message: You traveled 1000 blocks by foot!
    Name: distancefoot_1000
    DisplayName: Big Walker 
    
# When a distance is traveled on a pig.
DistancePig:
  100:
    Message: You traveled 100 blocks on a pig!
    Name: distancepig_100
    DisplayName: Carrot on a Stick Master
    
# When a distance is traveled on a horse.
DistanceHorse:
  500:
    Message: You traveled 500 blocks on a horse!
    Name: distancehorse_500
    DisplayName: The Avener
    
# When a distance is traveled in a minecart.
DistanceMinecart:
  100:
    Message: You traveled 100 blocks in a minecart!
    Name: distanceminecart_100
    DisplayName: Carting Fan

# When a distance is traveled in a boat.
DistanceBoat:
  200:
    Message: You traveled 200 blocks in a boat!
    Name: distanceboat_200
    DisplayName: Great Sailor

# When a distance is traveled with elytra.
# Ignored on Minecraft versions prior to 1.9, add it to DisabledCategories list.
DistanceGliding:
  100:
    Message: You traveled 100 blocks with elytra!
    Name: distancegliding_100
    DisplayName: Angel
    
# When a distance is traveled on a llama.
# Ignored on Minecraft versions prior to 1.11, add it to DisabledCategories list.
DistanceLlama:
  50:
    Message: You traveled 50 blocks on a llama!
    Name: distancellama_50
    DisplayName: Llama Rider

# When an item is dropped on the ground.
ItemDrops:
  15:
    Message: You're killing the planet!
    Name: itemdrops_15
    DisplayName: Polluter
    
# When an item is picked up from the ground.
ItemPickups:
  40:
    Message: You're saving the planet!
    Name: itempickups_40
    DisplayName: Environmentalist
    
# When soil is plowed with a hoe.
HoePlowings:
  10:
    Message: You plowed the ground 10 times!
    Name: hoeplowings_10
    DisplayName: Farmer
    Reward:                 
        Item: cookie 15
    
# When bone meal is used to fertilise plants.
Fertilising:
  15:
    Message: You used bone meal on plants 15 times!
    Name: fertilising_15
    DisplayName: Gardener
    
# When an animal is tamed.
Taming:
  1:
    Message: You tamed your first animal!
    Name: taming_1
    DisplayName: Tamer

# When animals breed (specify an entity name, lower case).
Breeding:
  sheep:
    100:
      Message: You bred your first animal!
      Name: breeding_1
      DisplayName: Breeder

# When a potion is brewed.
Brewing:
  1:
    Message: You brewed your first potion!
    Name: brewing_1
    DisplayName: Alchemist
    
# When a firework is launched.
Fireworks:
  10:
    Message: You launched 10 fireworks!
    Name: fireworks_10
    DisplayName: Pyrotechnist
    Reward:
      Experience: 200

# When a music disc is played.
MusicDiscs:
  1:
    Message: One jukebox used!
    Name: musicdiscs_1
    DisplayName: DJ

# When a player teleports with an enderpearl.
EnderPearls:
  10:
    Message: 10 teleportations with ender pearls!
    Name: enderpearls_10
    DisplayName: Teleport Man
    
# When a player gives a pet to another player (requires Pet Master plugin version 1.4 or above).
PetMasterGive:
  3:
    Message: 3 pets given to friends!
    Name: petmastergive_3
    DisplayName: Donator

# When a player receives a pet from another player (requires Pet Master plugin version 1.4 or above).
PetMasterReceive:
  10:
    Message: 10 pets received from friends!
    Name: petmasterreceive_10
    DisplayName: Receiver
    
# When an item is smelt in a furnace.
Smelting:
  250:
    Message: 250 items smelt in a furnace!
    Name: smeltitems_250
    DisplayName: The Smelter
    
# When a player enters a specific command (specify command prefixes in lower case without initial slash).
# For instance a command /awf add world from the AntiWorldFly plugin matches with subcategory 'awf add'.
# Aliases of a given command will also be taken into account.
PlayerCommands:
  aach stats:
    10:
      Message: Run the stats command 10 times!
      Name: playercommand_aachstats_10
      DisplayName: Statistician
      Rewards:
        Commands:
          Execute: "say Â§cALERT: Â§7PLAYER is now a statistician"
          Display: Broadcast
    
#===========================OOO=OOO===========================#
# VI-------------------------------------------------------VI #
# |                  Command achievements                   | #
# 6---------------------------------------------------------6 #
#===========================ooo=ooo===========================#
    
# Let achievement commands be given several times.
MultiCommand: true
    
# A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
# yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
Commands:
  yourAch1:
    Message: You took part in the special event!
    Name: yourAch1
    DisplayName: Special Event Achievement!
    
#===========================OOOOOOO===========================#
# VII-----------------------------------------------------VII #
# | Parameters in future plugin versions will  appear here  | #
# 7---------------------------------------------------------7 #
#===========================ooooooo===========================#`

**Comment by PyvesB** [comment]
I double-checked the code again, I didn't notice anything unexpected. I have just compiled the latest Spigot build and tried it with your configuration, I am not able to reproduce the issue.

Logs emitted by Advanced Achievements should all have a header, unless they do a direct call to `System.out.println` which I do not do in the plugin. For instance all of Advanced Achievements' logs will look like:
`[23:21:39 INFO]: [AdvancedAchievements] Launching scheduled tasks...`

Advanced Achievements has listeners registered to the server and gets notified by events such as the ones you described. Maybe the server/some other plugin is tracking these events and logs when it sees one happening. I would suggest creating a test server with its default configuration + Advanced Achievements as a plugin, and progressively adding your other plugins with their configurations. You should be able to see at which point the unwanted logging starts again. 😉

**Comment by PyvesB** [comment]
@zAnonimo: any luck with the above?

**Comment by zAnonimo** [comment]
@PyvesB Hey, I'm sorry. Didn't test it without any other plugins because I'm almost opening my server and that would be a lot of lose time that I don't really have :cry:. It keeps happening tho, without any issue atm.

**Comment by PyvesB** [comment]
Okay, maybe just try without ViaVersion/Backwards and ProtocolLib. They seem like the most likely to be conflicting after a quick read through your plugin list. ^^

**Comment by zAnonimo** [comment]
Finally I had time to test. It's not a problem of AdvancedAchievement, thanks for your support and your amazing plugin!
