### ISSUE TITLE
Question about colours

### ISSUE THREAD

**Issue by bjunited** [PyvesB/AdvancedAchievements#272]
Hello!

I just had a general question as to if there is anyway to change the colour from the grayed out style? As I find it quite hard to read. I notice that there is an option to change the default purple to aqua, but I was wondering if there was similar to change the dark gray. I seem to have a custom colour for the rewards display name, but nothing else.

Thank you for taking your time to look at this, have yourself a great weekend!
- Ben

**Comment by PyvesB** [comment]
Hello bjunited,

There is no option to change that colour, but I can easily add one. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Implemented! Here's a test version if you want to give it a try:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1544553/AdvancedAchievements.zip)

**Comment by bjunited** [comment]
You are awesome! Thank you so much, I will give it a try now :)

**Comment by bjunited** [comment]
Am I correct in thinking the Title for the achievement is changed to Red and the other text is changed to white?

**Comment by bjunited** [comment]
Also, when I do the "&b" for a rewards display name, it shows it as aqua in the GUI, and then in dark gray with the &b in chat in front of the rewards name.

**Comment by bjunited** [comment]
Hello!

Also, another question. Do you have a list of all the mob names for the Kill achievement, I am trying to do zombie pigman and have tried a lot of different combinations for the name and can't get it to recongnise it. 

Thank you again! :)

**Comment by supertassu** [comment]
PIG_ZOMBIE

**Comment by bjunited** [comment]
That doesn't seem to work

**Comment by PyvesB** [comment]
Here's a new version, providing fixes to some of the things you pointed out:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1546177/AdvancedAchievements.zip)

For mobs, get the list [here](hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html) and specify the mob name in lower case. ^^

**Comment by bjunited** [comment]
Amazing, thank you so much! :) Still a few things that could be changed (Gray chat messages), but for the most part it's excellent. I really appreciate your help with this. Thank You.

**Comment by PyvesB** [comment]
No problem! Feel free to open any new issues in the future or star the repository! 😉
