### ISSUE TITLE
BungeeCord Support

### ISSUE THREAD

**Issue by AngelStoyanov3** [PyvesB/AdvancedAchievements#273]
Do Advanced Achievements support BungeeCord? I really need multi-server achievements!

**Comment by PyvesB** [comment]
Hello AngelStoyanov3,

No, there is no BungeeCord support, as it would probably not bring many benefits to the plugin. Why not simply use a MySQL or PostgreSQL database to share achievements between servers? 😉 

Cheers,

Pyves
