### ISSUE TITLE
Advancement (Question)

### ISSUE THREAD

**Issue by Sprungente** [PyvesB/AdvancedAchievements#275]
Hi people before someone closing it, i will a answer that's works

When I want AACH with the minecraft Advancement i use /aach generate 
After them i restarted the server. 

Now when i get an achievement no Advancement will giving me. 

My question: Have i forget something?

Use aach V 5.4 
CraftBukkit version git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Bungeecord build 1282

config options to Advancement:
RegisterAdvancementDescriptions: true
HideAdvancements: false

Thanks for helping

**Comment by PyvesB** [comment]
Hello Sprungente,

I do not really understand your message. Have all the plugin's advancements disappeared once you have restarted your server?

Cheers,

Pyves

**Comment by Sprungente** [comment]
hi

No. It works fine but when I want to work with minecraft advancement player can earn a aach but nothing will happen on the minecraft advancement

**Comment by PyvesB** [comment]
What do you mean by "but nothing will happen on the minecraft advancement"? Does the player not get the advancement corresponding to the received achievement?

**Comment by Sprungente** [comment]
Yes



Am 12.12.2017 um 22:28 schrieb Pyves <notifications@github.com<mailto:notifications@github.com>>:


What do you mean by "but nothing will happen on the minecraft advancement"? Does the player not get the advancement corresponding to the received achievement?

**Comment by PyvesB** [comment]
Were there any errors/warnings in the server's log when you ran _/aach generate_? What about when a player receives an achievement?

**Comment by Sprungente** [comment]
I'm sorry. the problem was, that 2 achievements have the same name. 

It was my mistake and I have fixed for me.

https://pastebin.com/DsJgcGwD

**Comment by PyvesB** [comment]
Glad it's fixed! Have fun using the plugin!

**Comment by supertassu** [comment]
@PyvesB It should display a message instead of giving  stack trace to end user. I can make a PR about this, just wouldn't mark it solved.

**Comment by PyvesB** [comment]
@supertassu : well the `parseAchievementsAndDisplayNames` already checks and warns about duplicate achievements on startup. If the user does not pay attention to the console after setting a new plugin or ignores warning/error messages, they should be ready to face the consequences. ^^

**Comment by Sprungente** [comment]
One question i have at the end

Why are the progress from aach advancement (not aach itself) away after restart?


Am 15.12.2017 um 23:16 schrieb Pyves <notifications@github.com<mailto:notifications@github.com>>:


@supertassu<https://github.com/supertassu> : well the parseAchievementsAndDisplayNames already checks and warns about duplicate achievements on startup. If the user does not pay attention to the console after setting a new plugin or ignores warning/error messages, they should be ready to face the consequences. ^^

**Comment by Sprungente** [comment]
https://pastebin.com/jMJ1ytnY

After Restart, configchange or others what i'm changing with aach will make broken my aach. Every time my custom achievement are the problem.

https://pastebin.com/jMJ1ytnY

vote for reopen

**Comment by PyvesB** [comment]
I suggest we continue the discussion in #281, as it seems to be a similar issue. ^^
