### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by JohOply** [PyvesB/AdvancedAchievements#276]
Hi

I have some questions and suggestions about cooldown:

1. Why is there a cooldown on the brewing achievement? I don't see what is the possible abuse 
2. Could you add a cooldown on the milk achievement? I think it is too easy without cooldown (like water or lava bucket)
3. Instead of a global cooldown, is it possible to add a per-achievement cooldown? (only for some categories like currently bed, waterbucket, etc.)
> For instance, I think a 10sec cooldown is too high for brewing achievement, and not enough for sleep achievement
4. Is it possible to add a new feature: a largest **period of time** for **x amount** of a statistic

> For instance1: i define in config "cooldown of 30sec for waterbucket achievement" AND an "amount of 10 (buckets)", it means that player is able to fill 10 buckets in 30sec before cooldown is enable. I think it is better than "3sec of cooldown between each filling action"

> For instance2: In the same time (with point 3), i define a "cooldown of 90sec for bed achievement" for an "amount of 1", it means plugin will count 1 sleep for a player every 90sec and not more

Thank you for reading!

**Comment by PyvesB** [comment]
Hello JohOply! 😉 

1. A player could put the potion back into the brewing stand, take it again, and so on and so forth. There is no `PlayerBrewEvent` or similar event in the Bukkit API, so Advanced Achievements can only detect simple interactions with the brewing stand inventory. Does this make sense?
2. The player needs to first drink the milk bucket or have multiple empty buckets in his action bar inventory. Doesn't this slow him down enough without the cooldown? But it could easily be added to `Milk` achievements if you really think it's useful.
3. This would be easy enough, I (or some other contributor) could implement this.
4. This would be a more involved piece of work and may in fact confuse users in the configuration file. I don't think this will be added to the plugin.

Cheers,

Pyves

**Comment by PyvesB** [comment]
Here's a test version covering point 2 and 3 above. Enjoy!

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1575841/AdvancedAchievements.zip)
