### ISSUE TITLE
Custom Nametag

### ISSUE THREAD

**Issue by Blackdigits** [PyvesB/AdvancedAchievements#278]
Can you add it so that people can choose to show the Achievement they have successfully earned in their nametags? 

Just like this, https://www.spigotmc.org/resources/animatednames.2175/
so they can add it under it, with a new command like /aach title achievementname

**Comment by Phoetrix** [comment]
Hi! 

You can only show a statistic of an achievement by install the plugin PlaceholderAPI on your server and set in the config of AnimatedNames an achievement placeholder.  Here is the list: https://github.com/PyvesB/AdvancedAchievements/pull/269

Example:
`name-below:
  # Set to false to disable the name under name (REQUIRES RESTART)
  enabled: true
  # A list to create animations
  # Make sure that the placeholder is numeric!
  # You have to put a number or numeric placeholder in the beginning
  # or else you will get a "0" in front.
  # This also means you can't have colors in front. The number is a set
  # color you can't change.
  frames:
  - '{aach_connections} Connections'
  - '{aach_deaths} Deaths'
  # Animation interval in ticks (20 ticks = 1 sec)
  interval: 60`

But all players will have "Connections" and "Deaths" in the name tag with my example.
I think that Advanced Achievement don't need to have a preference feature to show a custom category selected by your player.

It would be better that Maximvdw add support on Animated Names to set up custom frames with a custom permission or group and then you switch (with a plugin that allow the creation of custom command like DeluxeCommands) the permission/group of players depending of their preferences to show a frame list catched by player permission/group.

**Comment by PyvesB** [comment]
There hasn't been any news on this issue for over a week, I'm assuming @Phoetrix has answered to everything and therefore closing it! 😉 

Cheers,

Pyves
