### ISSUE TITLE
Idea : Achievement based on permission's group

### ISSUE THREAD

**Issue by JohOply** [PyvesB/AdvancedAchievements#28]
Hi guys

I use a permission plugin (PermissionsEx). Is it possible to add creation of achievements based on groups ? When the plugin detect a rank change, player take achievement (have to work with other permissions plugins if possible)

Thanks for reading :)

**Comment by PyvesB** [comment]
Hello,

Unfortunately, I don't see any simple way to do that. There is no Minecraft event such as "onPlayerRankhange", and I'm not even sure that PermissionsEx or other plugins provide any in their APIs. Nevertheless, on your side of things, you could maybe run a Command achievement when you change the rank of your players. ;-)

Cheers,

Pyves

**Comment by JohOply** [comment]
I understand!

Do you speak about this command: "/aach give yourAch1 <player>" ? Is this command stored in achivements table? (i don't see it currently)

**Comment by PyvesB** [comment]
Yes, I'm talking about /aach give; once executed, the achievement is registered in the "achievement" database table. ;-)

**Comment by JohOply** [comment]
Finally it is OK, just need a little time to be added in database :)

Thank you for your help!
