### ISSUE TITLE
Random Achievement

### ISSUE THREAD

**Issue by Provensis** [PyvesB/AdvancedAchievements#283]
Hey, first off I wanna say the plugin looks incredible, nice work!
Well, now my questions.
Is there a way to give my players 2 random achievements. Then when they completed a achievement, they will get a new one?
And maybe a Weekly achievement too. A category where they only get 1 achievement every week? Random for every player here too. :)

**Comment by PyvesB** [comment]
Hello @Provensis ,

Advanced Achievements does not currently support random achievements or achievements awarded on a scheduled basis (each week for instance).

Yes, when an achievement is completed they could get a second one. You can use the _Commands_ category (or soon the _Custom_ category added in #277) and as a reward for the first achievement you can specify an _/aach give_ command which will award the second one. Some Spigot plugins support random commands as well, so you could probably fire a command that randomly awards another achievement as a reward of a first one. :wink:

Cheers,

Pyves

**Comment by Provensis** [comment]
Hello, thank you for the comment, I appreciate it a lot!

That might actual work, good idea. :)

Btw. is the achievements stored in a database or something? Might be able to do a cron job or something in the database for all players each week.

**Comment by PyvesB** [comment]
@Provensis : received achievements are stored in the database, `achievements` table. The schema is the following for SQLite:
````
CREATE TABLE `achievements` (
	`playername`	char ( 36 ),
	`achievement`	varchar ( 64 ),
	`description`	varchar ( 128 ),
	`date`	DATE,
	PRIMARY KEY(`playername`,`achievement`)
);
````
