### ISSUE TITLE
Code improvement: getPluginLang().getString calls could be cleaned up

### ISSUE THREAD

**Issue by Rsl1122** [PyvesB/AdvancedAchievements#288]
In the current implementation path and default value are specified every time a call for a message is made.

Code can be cleaned up by introducing an enum containing paths and default messages

For example:
`plugin.getPluginLang().getString("aach-tip", "&lHINT &8You can &7&n&ohover &8or &7&n&oclick &8on the commands!"));` would become `plugin.getPluginLang().getString(Msg.AACH-TIP)`
```
enum Msg

AACH-TIP( "&lHINT &8You can &7&n&ohover &8or &7&n&oclick &8on the commands!");

Msg(String defaultValue)

public String getPath() return name().toLowerCase()

public String getDefaultMsg()   return defaultValue
```
getPluginLang would return an object that extends the existing implementation

```
getString(Msg message)
    return getString(message.getPath(), message.getDefaultMsg())
```

What do you think? :)

**Comment by PyvesB** [comment]
Hello @Rsl1122,

Indeed, this seems like a good idea. The calls to read values from the configuration are unnecessarily chatty. 😉 

Cheers,

Pyves

**Comment by Rsl1122** [comment]
Messages can be split to multiple categories with multiple enums implementing a Msg interface similar to `Category`
