### ISSUE TITLE
2.5.2: Don't get item rewards

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#29]
Since 2.5.2 I don't get Item Rewards if they are defined in config. Also with the default config I didn't get a diamond for "The Walking Dead". I'm sorry to bother you again. :/

**Comment by Platinteufel** [comment]
A possible fix for me is to change an Item- into a Command-Reward.

**Comment by Platinteufel** [comment]
Edit: Last working version with Item-Rewards is 2.4.4

**Comment by PyvesB** [comment]
You're absolutely right, no one had noticed in ten days time! Should be working in version 2.5.3. ;-)

**Comment by Platinteufel** [comment]
Works, thank you for the fast fix :)
