### ISSUE TITLE
[BUG] Help for the Advanced Achievement MineCraft Plugin

### ISSUE THREAD

**Issue by GameCraft27** [PyvesB/AdvancedAchievements#292]
Hello (I'm Frensh, sorry for the bad langage)
I have recently have a bug with the Advanced Achievement plugin.
I have translate and config this on the lang and config files and when I have reload, the bug spawned !
[This is the console log of the bug, please help me :( ...
](https://image.noelshack.com/fichiers/2018/01/2/1514915515-aach.png)

**Comment by PyvesB** [comment]
Hello @GameCraft27 ,

Please use the latest version of the plugin (your version is almost 8 months old) and please attach your configuration files if still encounter issues. 😉 

Cheers,

Pyves

**Comment by GameCraft27** [comment]
Thanks you very much !
I make that now.
And your plugin is very cool ! :)

**Comment by PyvesB** [comment]
@GameCraft27 : is everything okay on your side now?
