### ISSUE TITLE
[BUG] Advanced Achievements isn't working for me, my config is broken ):

### ISSUE THREAD

**Issue by sawyerwd** [PyvesB/AdvancedAchievements#293]
Hi,

My config is currently broken and when I restart the server and do /aach, it has "An internal error."

My config: https://pastebin.com/eeSv5Wre

**Comment by PyvesB** [comment]
Hello @sawyerwd,

I've spotted the following issues with your configuration:
- you must specify mob names for the `Breeding `category, as shown in the default configuration. 
- the indentation of the `Reward` section of the _place_500_smooth_brick_ achievement is incorrect. 
- you have duplicated the `Name` parameter of some of the achievements (the plugin logs will indicate which ones).

Hope this helps! 😉 

Cheers,

Pyves
