### ISSUE TITLE
Statistics not counting on survival

### ISSUE THREAD

**Issue by HotelMakar** [PyvesB/AdvancedAchievements#294]
when i break blocks on creative it gives me the first time mining achivement but when i use another acc to mine in survival the stats didn't even count i checked /aach list on that acc and its 0 blocks broken

**Comment by PyvesB** [comment]
Hello @HotelMakar,

I am unable to reproduce. Are you using the latest version of the plugin with a recent Spigot build? Are there any warnings, error messages or stack traces in the server's logs? If the issue persists, please share your configuration file. 😉 

Cheers,

Pyves

**Comment by HotelMakar** [comment]
https://pastebin.com/QGAHDDR2

**Comment by PyvesB** [comment]
I am not able to reproduce with your configuration. Please refer to my questions above.

**Comment by HotelMakar** [comment]
theres no error (at least i didn't see any) and im using latest version ;-;

**Comment by PyvesB** [comment]
There must be a plugin conflict. Can you give me a list of all the ones on your server, I'll see if I spot anything fishy.

**Comment by HotelMakar** [comment]
sry 4 late reply https://gyazo.com/247b7fb66176677c68d581dd90cbd306

**Comment by PyvesB** [comment]
That's a lot of plugins, the vast majority I don't know at all. I suggest you remove all plugins except Advanced Achievements, check that _Breaks_ statistics increase as expected, and progressively add your other plugins again. You should find a point at which Advanced Achievements stops working properly, which will indicate the plugin causing issues. 😉

**Comment by HotelMakar** [comment]
i think it doesn't work because there is autopickup enabled i deleted the autopickup plugin and used another autopickup plugin and it stopped working again

**Comment by PyvesB** [comment]
AutoPickup possibly cancels or messes around with the server's _BlockBreakEvent_. Therefore Advanced Achievements has no way of telling that the player has actually broken a block, and statistics don't increase in Survival game mode. In Creative game mode, breaking blocks does not trigger any block drops, and AutoPickup is probably inactive in that case.

**Comment by HotelMakar** [comment]
how to fix it D:

**Comment by PyvesB** [comment]
Well either stop using such pickup plugins/use a different one or submit a report to the relevant author.
