### ISSUE TITLE
Rewards when all achievements are received

### ISSUE THREAD

**Issue by iKingM** [PyvesB/AdvancedAchievements#297]
Hi, just some quick question :
Is it possible to execute a command when a player has completed all the achievements ?
  
Is it possible to disable a category of achievement ?

how can I check if a player has completed all the achievements ?

**Comment by PyvesB** [comment]
Hello @iKingM,

No, it is currently not possible to execute a command when a player has completed all the achievements.

You can disable a category by adding it to the `DisabledCategories` list in the [configuration file](https://github.com/PyvesB/AdvancedAchievements/blob/e873eee9ff0d46ce688da8c9d7bd8bfcf676bdea/src/main/resources/config.yml#L105).

**Comment by iKingM** [comment]
> No, it is currently not possible to execute a command when a player has completed all the achievements.

Do you think it is a good idea to add this to your plugin or to create a command to see the stats of others players. For example /aach stats (players) ?

**Comment by PyvesB** [comment]
Rather than just executing a command, I think it's better to let the user choose rewards as usual. Something configurable, like this:
````
AllAchievementsReceivedRewards:
  Money: 2
  Experience: 100
  Command:
    Execute: give PLAYER 158 10
````

**Comment by iKingM** [comment]
"AllAchievementsReceivedRewards" already exists ?
Because this is exactly what I want.

**Comment by PyvesB** [comment]
Well no, as per my initial message, there is no way of currently doing so. Nevertheless I'm adding this new feature, the implementation should soon be ready. ^^

**Comment by iKingM** [comment]
Ok thanks :)

**Comment by PyvesB** [comment]
Here's a test version, would you like to give it a try?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1629681/AdvancedAchievements.zip)

**Comment by iKingM** [comment]
I added a command to execute when all achievements are received and I get this error : 
https://pastebin.com/wMkSggHs

**Comment by iKingM** [comment]
I added a command to execute when all achievements are received but when I get the last achievement the command is not executed.

Log : https://pastebin.com/2D5gi6Gs
Config : https://pastebin.com/cmm6SBir

**Comment by PyvesB** [comment]
You config show the achievement _itemdrops_25_, but you have only received _itemdrops_20_. Are you sure you have received all the achievements? Also, are you testing with a fresh database? What does _/aach stats_ display?

**Comment by iKingM** [comment]
I cleared the database and restarted the server to try again.
The command /aach stats displayed 0% so it was good.

I completed the 3 itemdrops achievements

After the command /aach stats displays 100% : http://prntscr.com/i0fk9r
but the command executed when all the achievements are received is not executed.

The config is the same and the log : https://pastebin.com/RZjEbqVC

**Comment by PyvesB** [comment]
Okay, I think the problem boiled down to the fact that the plugin was expecting all achievements to be received, even the ones in disabled categories, and I did not spot this whilst testing. Here's an updated version, hopefully it will work as expected!

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1629855/AdvancedAchievements.zip)

**Comment by iKingM** [comment]
This is good !
Thanks you're the best ;)

**Comment by PyvesB** [comment]
Awesome, thanks for helping out with the testing! I'll try to release this officially sometime this week, please give me a shout if you spot anything unexpected before then. 😉
