### ISSUE TITLE
New suggestion to add to the plugin.

### ISSUE THREAD

**Issue by EncryptSL** [PyvesB/AdvancedAchievements#299]
Hello PyvesB, i have new suggestion for this plugin.
You can add like progress in achievements.
Like this example:

Progress:
 item: SIGN
 name: '&5Information'
 description:
 - '&f Actual Page: %current_page%/ (%current_missions_on_page%)'
 - '&fTotal count page: %count_pages%/(%total_count_missions%)'
 - '&fYou did not finish %no_finish_ach%'
 - '&fFinished Achievements - %missions_complete%/%total_count_missions% '

Example img this image from CZ/SK Server.

Like this.
https://imgur.com/a/tVFr8

**Comment by PyvesB** [comment]
Hello @EncryptSL,

This would be quite involved work, I'm not keen on diving into the GUI again at this point. Also, I don't think it's a good idea to copy another plugin's GUI, Advanced Achievements should stick to its own style. 😉 

Cheers,

Pyves
