### ISSUE TITLE
/aach give

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#30]
For some reasons /aach give doesn't work for me. I've just typed _/aach give Cobble! MyName_, but it tells me that the specified achievement was not found. If the achievement has spaces like "The Walking Dead" _/aach give The Walking Dead MyName_ only shows me the aach help site.

**Comment by PyvesB** [comment]
Hello,

As both stated in the plugin's FAQ and in the configuration file, /aach give is only for Commands achievements. There is no point of giving other achievements by command, this would only mess up and interfere with statistics collection. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Uhm okay, sorry. But then /aach delete also doesn't make sense for the "normal" achievements, because you can never reach it again. ^^

**Comment by PyvesB** [comment]
Well, some users requested it for admin purposes or in order to get rid of an achievement completely. ;-)
