### ISSUE TITLE
Suggestion: An /ticket command

### ISSUE THREAD

**Issue by Sprungente** [PyvesB/AdvancedAchievements#300]
/aach ticket
Sounds funny but should be helpful for you and should give you many information to help
Maybe you can include in this command and generate automativally a hastebin (link or data) with for example this information:
- What kind of plugins are on the server 
- Your Pluginversion
- Spigotversion
- Any useful information that you can help more efficient. 

When for example i wanna open a Issue then I can run /aach ticket first, copy the hastebin link and post it here, write a useful description of my issue and then you can read it, open the file, see all information :)

(i saw this from other plugins)

**Comment by PyvesB** [comment]
Hello @Sprungente ,

There already are simple commands that allow you to retrieve that information (_/aach info_, _/pl_ and _/version_), I'm not sure it would actually be useful to have a unique command that prints out the same information. Often, the plugin's configuration is the most useful piece of information needed in tickets. 😉 

Cheers,

Pyves
