### ISSUE TITLE
Add support for MythicMobs + locations + WorldGuard

### ISSUE THREAD

**Issue by NelsonHD** [PyvesB/AdvancedAchievements#301]
Would you like to add the support for MythicMobs and locations ?
e.g 
MythicMobs_kill;
     '10':
          Message: 'You killed 10 x Mega Slime Boss !'
          Name: MM_10_Kill
          DisplayName: 'Slime Lover'
          Reward:
               Item: slime_ball 1 name:"&eI_wont_forgive_you" lore:"&6Can_you_hear_that_?
                       |&6They_are_crying...:('

**Comment by PyvesB** [comment]
Hello @NelsonHD ,

I'm assuming you've read [question 10](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)#10-can-the-dev-add-support-for-mcmmo-mythicmobs-or-any-other-exotic-plugin) of the FAQ, and therefore you or another developer you know is going to submit a pull request?

Cheers,

Pyves

**Comment by PyvesB** [comment]
It's been dead silence for about a month now, therefore closing this issue.
