### ISSUE TITLE
Rewards don't work

### ISSUE THREAD

**Issue by iKingM** [PyvesB/AdvancedAchievements#302]
Hi @PyvesB 

This post follow this one : https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards

The reward for all achievement works but the reward for a simple achievement doesn't work. The command is not executed when a player received one of the achievement.

**Comment by supertassu** [comment]
Could you share your config? Thanks.

**Comment by PyvesB** [comment]
Hello @iKingM ,

I will look into that. @supertassu, probably not a configuration issue, I think I messed up some refactoring performed as part of #297, which would make sense as @iKingM is using a test build of the plugin. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
More luck with the following version?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1632804/AdvancedAchievements.zip)
