### ISSUE TITLE
A small detail

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#306]
Hi,

With the last version (5.6) I have this small display error when i am doing /aa reload : 

![capture](https://user-images.githubusercontent.com/24486147/35162285-27d4224e-fd43-11e7-8943-5d78d336780e.PNG)

I am using the latest version of the FR translation file.
Nevertheless the command works correctly.

Thank you in advance.

**Comment by PyvesB** [comment]
Hello @aurel85 ,

Thanks for the report. This was introduced in #296 and will be fixed shortly. 😉 

Cheers,

Pyves
