### ISSUE TITLE
[Error]NPE with empty command categories

### ISSUE THREAD

**Issue by jiongjionger** [PyvesB/AdvancedAchievements#307]
Plugin version: 5.6
Server version: 1.12.2

I have empty commands categories and disable commands. 
However, the Commands category is still displayed in the GUI, and an error occurs when I click the commands category button.

error log:
https://paste.ubuntu.com/26418572/

**Comment by PyvesB** [comment]
Hello @jiongjionger ,

Is this problem solved?

Cheers,

Pyves
