### ISSUE TITLE
BatchUpdateException in AsyncCachedRequestsSender

### ISSUE THREAD

**Issue by EncryptSL** [PyvesB/AdvancedAchievements#309]
I found new error in plugin.
Version plugin: 5.6.1
And two days function is normal without error.

Error in this log:
https://pastebin.com/e6j7g8bp

**Comment by PyvesB** [comment]
Hello @EncryptSL ,

I will look into this. Doesn't seem too serious as you state it only happened once in two days and it seems to affect the batch updater (which will retry its operations later on). 😉 

Cheers,

Pyves

**Comment by EncryptSL** [comment]
Thx for answer.

**Comment by PyvesB** [comment]
I have attempted a fix, hopefully the error should not happen again. Here is a test version:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1661277/AdvancedAchievements.zip)

Please come back to me if the problem persists.

**Comment by EncryptSL** [comment]
I think with this fix plugin working. 
Good job.

I will watch the plugin and its working on server.

**Comment by PyvesB** [comment]
Awesome! I've deployed this in version 5.6.2, please don't hesitate if you get any new database errors. ^^
