### ISSUE TITLE
Enderpearls doesn't work

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#31]
Seems like the EnderPearls category doesn't work. I'm spamming EnderPearls and can't reach any achievement here. ;-)

**Comment by PyvesB** [comment]
Hello,

Are you sure the category isn't disabled in DisabledCategories?

**Comment by Platinteufel** [comment]
Yes, absolutly. Is this category working on your server?

**Comment by PyvesB** [comment]
I've tested both on my local test server and my real server, they do seem to be working. I've also gone through my code quickly, I don't see anything wrong in there either. Have you got any errors in the console? Are you running a recent Build of Spigot 1.9.2? Another one of your plugins may also be conflicting, and may prevent the event from being monitored by other plugins.

**Comment by Platinteufel** [comment]
Seems like "Shear" and "Enderpearl" don't increase if you are not op, but I will test it again now.

**Comment by Platinteufel** [comment]
Uhm yes, after my tests on my local server I can say that these 2 categories only increase if you are OP or have permissions I don't know about.

**Comment by Platinteufel** [comment]
I've added achievement.count.shear to the permissions, but it still not work. After adding achievement.* shear increases again. lol

**Comment by PyvesB** [comment]
I'll check the permission system and issue an update if need be. Are here any other achievements that are causing problems?

**Comment by Platinteufel** [comment]
The other permissons seem to be fine, but I've tested it just about a hour.

**Comment by Platinteufel** [comment]
After adding achievement.count.* it seems working for me. Can I give this permission to my players?

**Comment by Platinteufel** [comment]
My users reported that MusicDiscs (DJ) also doesn't work with the default permissions. I've just tested it and can confirm this.

**Comment by PyvesB** [comment]
Patience, I will look into all this in the next update. ;-)

**Comment by Platinteufel** [comment]
Okay, thank you! Could you just tell me if I can give achievement.count.* without getting into trouble? It works for me then. ;-)

**Comment by PyvesB** [comment]
No, it won't get you into trouble.

**Comment by PyvesB** [comment]
Hello again,

I've worked on a new version which should fix the permission issues and the distance miscalculations on player death. Could you please test it and check out it everything is also working well on your side? I'm planning on issuing an official update in a few hours time, Thursday evening. ;-)

[AdvancedAchievements-2.5.3.zip](https://github.com/PyvesB/AdvancedAchievements/files/260311/AdvancedAchievements-2.5.3.zip)

**Comment by Platinteufel** [comment]
Thank you, I will test it and come back again tomorrow. :)

**Comment by Platinteufel** [comment]
Just tested it, seems to work fine for me. Thanks!
