### ISSUE TITLE
Advancement issue

### ISSUE THREAD

**Issue by ToXiCHaZe541** [PyvesB/AdvancedAchievements#312]
When doing /aach generate it throws up a internal server error and gives the error below in console. Also when pressing 'L' to open the advancement menu it will very rarely show the book for the advancements and when it does all the icons are sitting on top of each other.

Error:
https://hastebin.com/erexuripac.vbs

**Comment by PyvesB** [comment]
@ToXiCHaZe541 : is your issue solved?

**Comment by ToXiCHaZe541** [comment]
I got it to work by deleting the advancements in the world folder and restarting the server but I'm not sure if it's a permanent fix yet. I closed the ticket because I seen it was reported before and seen that you weren't able to do much due to the lack of proper API from spigot. I didn't notice until I already made a ticket.

**Comment by PyvesB** [comment]
Okay, thanks for the feedback! If ever you find a way to properly reproduce this error, please comment on #281 as this would help us out. 😉

**Comment by ToXiCHaZe541** [comment]
@PyvesB Yea after the server restarted the advancements went away on the advancement menu. Also when you complete achievements they dont come up as completing the advancement. I tried doing /aach generate and the same error comes up in console.

**Comment by ToXiCHaZe541** [comment]
Now they are randomly back... This seems to be a very inconsistent problem.
