### ISSUE TITLE
I found Bug in custom category

### ISSUE THREAD

**Issue by EncryptSL** [PyvesB/AdvancedAchievements#313]
Hello PyvesB,
i think, in plugin is bug.
I'll give an example by entering /aa add 1 Custom.votes EncryptSL

When the player reaches the finish Votes in custom category not finished.

This part is for Votes in AACH.
`  votes:
    '10':
      Goal: Vote 10x for server
      Message: custom_hlas_1
      DisplayName: Lets Go Fans I
      Reward:
       Experience: 100
       Command:
         Execute: givesp PLAYER 250;eco give PLAYER 1550`

**Comment by EncryptSL** [comment]
I found another bug.
In Category DistanceGliding: Same bug,
Traveling with the elytra is counted together, and thus it does not finish the task.

Screenshot:
https://ctrlv.cz/Zauc
https://ctrlv.cz/USxc

Config:
https://pastebin.com/6tkjD3bF - Part Only DistanceGliding.

**Comment by PyvesB** [comment]
Hello @EncryptSL ,

I am not able to reproduce. Have recently changed the achievement thresholds in your configuration? Are there any errors in the console?

Cheers,

Pyves

**Comment by EncryptSL** [comment]
Hello dear, PyvesB.

when player vote plugin GaListeners call command /aa add 1 Custom.votes EncryptSL and 
plugin give this error. ;). Plugin GaListener are working without problem with another commands.

Error:
https://pastebin.com/WS3jGwBF

Screen:
https://ctrlv.cz/ujLG

Category Votes is completed but no locked.

**Comment by PyvesB** [comment]
It seems like you omitted the `Name` parameter for the achievement "Lets Go Fans", am I right?

**Comment by PyvesB** [comment]
@EncryptSL : have you managed to solve your issue? ^^

**Comment by EncryptSL** [comment]
Thx for help :). solved.
