### ISSUE TITLE
I can't make rewards

### ISSUE THREAD

**Issue by iceyy** [PyvesB/AdvancedAchievements#314]
Hi, I'm new to this plugin and I love it! But there's one thing..
I did this:

Connections:
  1:
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice
      Reward:
        Money: 5000

and the plugin broke and gave me this error:
[18:14:13 ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it

What did I do wrong? Thanks,
iceyy

PS: I'm using essentials and vault

**Comment by PyvesB** [comment]
Hello @iceyy!

Are than any stack traces or other messages in the logs? Could you please show me your full configuration file?

Cheers,

Pyves

**Comment by iceyy** [comment]
My config is at https://pastebin.com/f5TBXvUp
and the error is https://pastebin.com/cmhE0y22

**Comment by PyvesB** [comment]
On line 255 in your configuration, you have indented the `Reward` section too much. It should be at the same level as `DisplayName` for instance, as shown in the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards). 😉

**Comment by iceyy** [comment]
oops! 😝 thanks! by the way, this plugin is great!

**Comment by PyvesB** [comment]
Haha, you're welcome! Feel free to star the repository! ^^
