### ISSUE TITLE
Suggestion about rewards when all achievements are received

### ISSUE THREAD

**Issue by iKingM** [PyvesB/AdvancedAchievements#315]
This suggestion follows on from this post : https://github.com/PyvesB/AdvancedAchievements/issues/297

My idea would be to add a new type of achievement based on the other achievements.
For example, the achievement would be: achieve 50% of the total number of achievements.

**Comment by PyvesB** [comment]
Hello @iKingM,

This is actually similar to #82 and has been on the projects backlog for quite some time. We need more contributors! 😃 

Cheers,

Pyves
