### ISSUE TITLE
Idea - A test command

### ISSUE THREAD

**Issue by aaroonung** [PyvesB/AdvancedAchievements#317]
I think a test command would be nice. While configuring it would be very useful to be able to test what would happen when you get a certain achievement. You wouldn't have to manually get the achievement to test it. Hope this gets added!

**Comment by PyvesB** [comment]
Hello @aaroonung!

Why not simply use the _/aach add_ command to meet achievement thresholds directly? You'll be easily able to test all achievements without going through the hassle of catching a thousand fish for instance. 😉 

Cheers,

Pyves

**Comment by aaroonung** [comment]
Ahh, that helps. Thank you! :D
