### ISSUE TITLE
Idea Mythicmobs

### ISSUE THREAD

**Issue by eot13** [PyvesB/AdvancedAchievements#318]
Hello
Could you add the mythicmobs support: (killed mobs) please?

**Comment by PyvesB** [comment]
Hello @eot13 !

Closing this as duplicate of #301. Also please refer to the [contributing guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md), which would have pointed you both to that issue and to the Wiki. 😉 

Cheers,

Pyves
