### ISSUE TITLE
/aach reset returns wrong argument

### ISSUE THREAD

**Issue by aaroonung** [PyvesB/AdvancedAchievements#319]
If incorrect the command should return "Breaks" if I'm not mistaken. But it returns the player name. 
![image](https://user-images.githubusercontent.com/14830826/36343371-15eccd34-13d1-11e8-8617-e21b6b7d9d50.png)

**Comment by PyvesB** [comment]
Hello @aaroonung !

Thanks for reporting this issue. I have just committed a fix. 😉 

Cheers,

Pyves
