### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#32]
I'm getting this NPE sometimes and I'm wondering if it causes issues.

http://pastebin.com/vciPAaWt
http://pastebin.com/BKXKSkAk

`[...] Caused by: java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[patched_1.9.2.jar:git-Paper-724]
	at com.hm.achievement.AchievementRewards.getItemReward(AchievementRewards.java:50) ~[?:?]
	at com.hm.achievement.AchievementRewards.checkConfig(AchievementRewards.java:155) ~[?:?]
	at com.hm.achievement.listener.AchieveBlockBreakListener.onBlockBreak(AchieveBlockBreakListener.java:51) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor424.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-724]
	... 18 more`

**Comment by PyvesB** [comment]
Hello,

Could you please show me your configuration file?

**Comment by Platinteufel** [comment]
Sure, is it possible to contact you on skype? I don't want to make it public. ;-)

**Comment by PyvesB** [comment]
Send me the link on Spigot or Bukkit via PM, it will be simpler. ;-)

**Comment by Platinteufel** [comment]
Done via SpigotMC :)

**Comment by PyvesB** [comment]
According to the above errors, the issues are coming from block breaks or eaten items/consumed potions. You have quite a few achievements, do you know which specific ones are causing this issue (it will help me out)?

**Comment by Platinteufel** [comment]
Uhm, there are a lot of players that doing a lot of achievements during the day. But you will get another message on spigot in a few minutes. ;-)

**Comment by PyvesB** [comment]
I think I discovered what's going wrong while scanning through your config. As stated at the beginning of the file and in the plugin's FAQ, you must use the material names, with eventually metadata for item rewards. For instance glistering_melon is not a valid Material name, hence the errors. ;-)

**Comment by Platinteufel** [comment]
Oh you're right, I've changed it to speckled_melon, thanks! That would explain the errors with 'Fresssack', but also the others?

**Comment by Platinteufel** [comment]
Seems like the other errors are also caused by this, so I've changed iron_shovel to iron_spade now. That was my own fault, sorry. :/

**Comment by PyvesB** [comment]
Well similarly, nametag is not valid. ;-)

No problem, glad to could have helped.

Cheers,

Pyves
