### ISSUE TITLE
Cauldron 1.7.10 NoClassDefFoundError

### ISSUE THREAD

**Issue by kaliflowerx3** [PyvesB/AdvancedAchievements#321]
When I launch with AA v5.6.4 installed, I get this error:

https://pastebin.com/TXdxVph2

I understand that KCauldron isn't really supported, but all of the AA versions on Bukkit are listed as compatible for CB-1.7.9, which is the version of plugins I usually go to. Which version of AA might work with my version (keeping in mind the error I got above)?

**Comment by PyvesB** [comment]
Hello @kaliflowerx3 !

After a bit of reading through various GitHub issues and Caudron-related threads, it seems like a problem with the Cauldron custom class loader, which doesn't fully support plugins compiled with Java 8. Try following [these steps](https://github.com/games647/FastLogin/issues/111#issuecomment-272331347), they will hopefully solve your issue.

Some users have also worked around the issue by setting the following in _cauldron.yml_:
```
plugin-settings:
  default:
    remap-plugin-file: false
    custom-class-loader: false
```
Nevertheless this may have other unwanted side-effects, so try the first solution first.

Hope this helps! 😉 

Cheers,

Pyves

**Comment by kaliflowerx3** [comment]
The first solution worked! Thanks so much, and sorry for not knowing what to google to fix this (seemingly common-ish) problem! <3

**Comment by PyvesB** [comment]
Haha, no worries, feel free to open a new issue if you need more help in the future!
