### ISSUE TITLE
Option to costumize achievement titles and &o

### ISSUE THREAD

**Issue by Tyloonie** [PyvesB/AdvancedAchievements#324]
Hello!

Very nice plugin. Would be nice if I could make a custom format for the achievements themselves inside the GUI menu just like the gui items. (ListAchievementFormat: '')

I also noticed that the descriptions etc. are all force-printed with &o - could you add an option to just keep the text plain?

**Comment by Tyloonie** [comment]
I see! Managed to configurate a nice style I like anyways, so it suits me anyways.

I do have another question however... Is it possible to for example under "Breaks" to add a section with "*" to mark any block possible? I want to create an achievement that includes mining 10,000 blocks of any kind.

**Comment by PyvesB** [comment]
Unfortunately `*` is not either currently possible, see #92 for a related issue. ^^
