### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MatinDark** [PyvesB/AdvancedAchievements#325]
Hello I Write all achievement and all work fine and player get achievements but they didn't receive any reward !
https://hastebin.com/atijedodiy.rb

**Comment by PyvesB** [comment]
Hello @MatinDark !

For which achievement in particular? Did they get any reward messages in their chat? Were there any errors in the server's console?

Cheers,

Pyves

**Comment by MatinDark** [comment]
all of them and no there is no error and there is no reward message i use latest paper spigot

**Comment by PyvesB** [comment]
Oh, actually I think the problem is simply due to the fact that you used `Commands` instead of `Command`. More information can be found [here](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards). 😉

**Comment by MatinDark** [comment]
yes that was for that reason and sry for waste your time for this but there is another issue this time it say you receive your reward and try to give me reward but i think plugin write player name incorrect 

> [07:09:45 INFO]: [KitPVP] Couldn't find that player online, looking up the database...
> [07:09:45 INFO]: [AdvancedAchievements] Player Matin_Dark received the achievement: snowballs_128 (Winter Addict)

**Comment by MatinDark** [comment]
I Found Solution that was For Color Codes Behind Them And Thanks for your nice support and sry again for waste your time that was my own mistake !

**Comment by PyvesB** [comment]
Awesome, glad it's solved!
