### ISSUE TITLE
Extend GUI customisation possibilities

### ISSUE THREAD

**Issue by iKingM** [PyvesB/AdvancedAchievements#326]
Hello,

I would like to offer you an idea of improving the plugin. My idea is to be able to make several menu that would be accessible with the commands / aach list 1, / aach list 2, ... and in which we could choose the achievements to add.
For each menu, there would be a big reward to get if the players realize all the achievements of this menu.

**Comment by PyvesB** [comment]
Hello @iKingM!

I'm doing quite a bit of code reorganisation in the project at the moment, I'm lacking time to look into any _/aach list_ enhancements. Maybe someone else wants to help out and give this suggestion some thought? 😉 

Cheers,

Pyves

**Comment by OMarseille13** [comment]
Up ;)

**Comment by PyvesB** [comment]
As mentioned in #452, rather than adding new layers of categorisation in the GUI which will make navigation harder, we should think about ways on how to improve the layout in the existing menus. Let's track progress in that issue instead!
