### ISSUE TITLE
[Feature Request] Multiple types of mobs

### ISSUE THREAD

**Issue by Leomelonseeds** [PyvesB/AdvancedAchievements#328]
This is a much requested feature by the community of my server.
Make it so that you can list more than one mob/block that counts towards an achievement.
Also add mob categories: Passive for passive mobs, Monsters for aggressive mobs.

Thanks in advance!

**Comment by PyvesB** [comment]
Hello @Leomelonseeds !

Please refer to issue #92, which is currently on standby. 😉 

Cheers,

Pyves
