### ISSUE TITLE
Plugin is being disabled

### ISSUE THREAD

**Issue by ToXiCHaZe541** [PyvesB/AdvancedAchievements#329]
It seems on server start up the plugin disables it self. I tried re enabling it then doing the /aach command it it puts the error down below in my console and gives a internal server error in chat. In the error it says its disabling itself but I dont understand why. I am running the latest version of the plugin and latest version of spigot as of this issue being reported. I even tried previous versions of the plugin which used to work so I am not sure what the issue is.

https://hastebin.com/imiyojenaz.sql

**Comment by PyvesB** [comment]
Hello @ToXiCHaZe541 !

The previous log lines should tell you what is wrong with your configuration. 😉 

Cheers,

Pyves

**Comment by ToXiCHaZe541** [comment]
@PyvesB I don't understand what you mean. Are you saying its a config issue?

**Comment by PyvesB** [comment]
Well look at all server messages starting with `[AdvancedAchievements]`, they will tell you what's wrong with your configuration. ^^

**Comment by ToXiCHaZe541** [comment]
@PyvesB Well I don't get any messages from it besides the error I put above when running the command. As of messages in game all I get is an internal server error.

**Comment by PyvesB** [comment]
Please post your full server log.

**Comment by PyvesB** [comment]
I'm really unsure why this is causing confusion, the plugin is clearly stating what is wrong and why it is being disabled:

> [02:36:29] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
> com.hm.achievement.exception.PluginLoadError: Duplicate achievement Name (breeding_10). Please ensure each Name is unique in config.yml.

**Comment by ToXiCHaZe541** [comment]
Sorry I didn't see that one line out of many. What was causing the confusion is nothing changed no achievements were added it just randomly started disabling itself. Thanks for the help though....
