### ISSUE TITLE
Beta test future release 5.7

### ISSUE THREAD

**Issue by PyvesB** [PyvesB/AdvancedAchievements#330]
Hello there!

I have done quite a bit of work on the plugin internals in order to reduce the technical debt, improve maintainability and try new things out. Most of the changes should be transparent to the end users, but I would appreciate some additional testing to assert that the plugin is still doing what it is supposed to do and is running smoothly. There are also a few functional improvements, for instance `DisabledCategories` can now be refreshed just by performing _/aach reload_. @hxykatycolf, @iceyy, @EncryptSL, @aurel85, @kaliflowerx3, @iKingM would any of you like to give this beta build a try? 😃 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1800201/AdvancedAchievements.zip)

---

@Rsl1122 , @Phoetrix , @supertassu , @TheCodeCrafter you might be interested in having a quick look at the code. I've introduced [Dagger](https://github.com/google/dagger), a popular dependency injection framework widely used in the industry. It helps decouple different parts of the code, removes boilerplate such as `new` object instantiations all around the place and reduces the temptation from having big centralised manager classes with loads of getters or static instances.

_AdvancedAchievements.java_ shows how I manage to bind the `JavaPlugin` instance created by Bukkit/Spigot; in effect this builds the whole dependency graph. In other classes I simply use the `@Inject` annotation so that Dagger knows how to construct an instance of that class. For more complex objects, I use `@Provides` methods in the `module` package. If your interested in using the framework, the [documentation](https://google.github.io/dagger/users-guide) is concise and well written, and actually only the first half would be more than enough to get you started. Let me know if you have any questions! 😉 

Cheers,

Pyves

**Comment by supertassu** [comment]
I'll take a look later today.

**Comment by aurel85** [comment]
Hi,

I did some basic tests (especially with DisabledCategories and / aa reload) and I did not find any bug (just a small detail but it is already present in the version 5.6.5 so I'm going to open a new issue directly). But otherwise everything is ok at first glance, further tests will confirm or not.

**Comment by supertassu** [comment]
I'd prefer if the new code would be in a PR so we could use GitHub's natural reviews, however thanks for tagging the releases so we can get the diff anyways.

Mostly looks good, however there are a few things that I noted:

- Is there a reason for [this change](https://github.com/PyvesB/AdvancedAchievements/compare/5.6.5...master#diff-ad2fe3b4e41a1bc00540dd61caee4fbbL238)? It's clearer when text and e are in the same line in my opinion.
- Again, are [these changes](https://github.com/PyvesB/AdvancedAchievements/compare/5.6.5...master#diff-c63c0af53d0f61f86e53fafbfe8aa147) necessary? Again, clearer when key and value are in same line.
- Could [this](https://github.com/PyvesB/AdvancedAchievements/compare/5.6.5...master#diff-72f623acf554b071b3fbd59499f2db1bL39) be injected as well?
- A mention about Dagger/inject would be great in CONTRIBUTING.md.

**Comment by PyvesB** [comment]
Thanks to both of you for your feedback!

@supertassu sorry about the absence of pull request, I had initially only anticipated asking for testing feedback. ^^

* I used slightly more pedantic formatter settings whilst cleaning up the project. I'll revert that and let the Maven formatter plugin do its job. 😉 
* Same here.
* What exactly did you have in mind? The method is static, I'm not sure much can be done unless we introduce a static field. ^^
* Done.

**Comment by supertassu** [comment]
Sorry, didn't realize it was static. Mainly looks good now, however contributing now has 2 number 3s in it.

**Comment by TheCodeCrafter** [comment]
Anything I can help with?

**Comment by PyvesB** [comment]
@TheCodeCrafter nothing in particular you can help with, this is more like a "if you're interested in using dependency injection in your own plugin/projects, here's one way to do it". 😄
