### ISSUE TITLE
Little bug (fill a bucket in creative game mode)

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#331]
Hi,

I discovered a small bug, not very disturbing but it's still a bug. When I'm in creative play mode and try to fill a bucket with water it's impossible. The plugin must prevent to do this because in my config success is not realized in creative game mode. But, it's totally impossible to fill the bucket with water in creative play mode. Nothing serious since you can give yourself the water bucket directly but I report it anyway.

I use the last version of the plugin (5.6.5) and Paper 1.12.2.

**Comment by PyvesB** [comment]
Hello @aurel85 !

Actually I believe this is standard Vanilla behaviour, introduced in an [old Beta version](https://minecraft.gamepedia.com/Beta_1.9_Prerelease_5) of the game. Advanced Achievements does not  actually try preventing any user actions, except when you're using the _/aach list_ interface. 😉 

Cheers,

Pyves

**Comment by aurel85** [comment]
I did not do a solo test, it would have needed ^^. Thank you for the speed and sorry for the inconvenience ;)
