### ISSUE TITLE
Command Setup

### ISSUE THREAD

**Issue by aztecwalker** [PyvesB/AdvancedAchievements#332]
Hello.. I would like to add custom command as a reward per achievement.. But mine desn't seems to work..
Could you help?
Here's one of my configurations :
    2500:
      Goal: "Place 2500 stone bricks."
      Message: "&4You have placed 2500 stone bricks!"
      Name: place_2500_smooth_brick
      DisplayName: Stone Brick Architect
      Rewards:
        Commands:
          Execute: points give PLAYER 250

**Comment by supertassu** [comment]
Isn't it `Command`, not `Commands`?

**Comment by PyvesB** [comment]
I believe @supertassu has given all useful information, therefore closing this issue.
