### ISSUE TITLE
Bug with 5.7.0 and mysql

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#333]
Hi,

During my tests on my test server I was in sqlite and yesterday I wanted to pass my principal server in 5.7.0 and the difference that it is mysql. And it does not work at all, there is no error in the logs but no way to have the achievements of the database while in the config nothing has moved. In the meantime I had to put back the previous version.

I use PaperSpigot 1.12.2.

Thank you in advance !

**Comment by PyvesB** [comment]
Hello @aurel85,

Thanks for spotting this! Is the below version any better?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1826607/AdvancedAchievements.zip)

Cheers,

Pyves

**Comment by aurel85** [comment]
Everything is ok thank you !
