### ISSUE TITLE
MythicMob Support

### ISSUE THREAD

**Issue by NevendyND** [PyvesB/AdvancedAchievements#335]
Sorry i don't understand the Pull requests...

i can't create one

I don't own MythicMob it's just a Question whether it would be possible to bring in support for MythicMob

**Comment by PyvesB** [comment]
Hello @NevendyND !

A pull request is a code contribution to an open source repository, often made by a developer who is not the main maintainer of the project. See #301 and #318 for related issues. 😉 

Cheers,

Pyves

**Comment by NevendyND** [comment]
When a MythicMobs Dev ask you ? then its ok :o?
