### ISSUE TITLE
InventoryClickEvent Bug

### ISSUE THREAD

**Issue by EncryptSL** [PyvesB/AdvancedAchievements#337]
Hello PyvesB, i have small problem with Commands Category.
When Player Click on Category Other Achievements.
Plugin call error: https://pastebin.com/JpTLdF0V
Config is Validate with YAML.
Version of Plugin 5.7.1.

Thx for your answer.

**Comment by PyvesB** [comment]
Hello @EncryptSL !

Could you please show me your current configuration file?

Cheers,

Pyves

**Comment by EncryptSL** [comment]
Yeah, Configuration this: https://pastebin.com/fvvwBikK

**Comment by PyvesB** [comment]
The category is called `Commands`, not `Command`. 😉

**Comment by EncryptSL** [comment]
Thx for Answer I love you men. <3. Problem solved.

**Comment by PyvesB** [comment]
You're welcome ! I might add some more validation when the plugin loads to cover these errors in the future. ^^
