### ISSUE TITLE
Problem with block-break

### ISSUE THREAD

**Issue by WarnDangerous** [PyvesB/AdvancedAchievements#338]
Hey ! I have a problem, I want to make achievement "block-break" but for any block, but impossible to do that, I must set an item that player have to break ! Pleaz help me
The configuration that I did :

Places:
  '2000':
    Goal: Placer 2000 blocs.
    Message: '&4Tu as placé 2000 blocs!'
    Name: Placer_2000_blocs
    DisplayName: Buildeur I
    Reward:
      Command:
        Execute: crate givekey PLAYER mineur 1
        Display: Buildeur I !
  '4000':
    Goal: Placer 4000 blocs.
    Message: '&4Tu as placé 4000 blocs!'
    Name: Placer_4000_blocs
    DisplayName: Buildeur II
    Reward:
      Command:
        Execute: crate givekey PLAYER mineur 1
        Display: Buildeur II !

**Comment by WarnDangerous** [comment]
Any solution ? Pleaz help me

**Comment by PyvesB** [comment]
Hello,

Duplicates #92, #154, #167, #238, #270 and probably more. The default configuration file also highlights this.

Cheers,

Pyves
