### ISSUE TITLE
Unable to track bed placement in 'Places' category.

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#339]
AdvancedAchievements v5.7.1

It seems you are unable to track bed placement in the places category.
```
  bed:
    '5':
      Goal: Place 5 beds.
      Message: '&4You have placed 5 beds!'
      Name: place_5_beds
      DisplayName: No Place Like Home
```

Do beds go under a different material name perhaps?

**Comment by PyvesB** [comment]
Hello @mibby !

Please try `bed_block` instead and tell me whether it helps. 😉 

Cheers,

Pyves
