### ISSUE TITLE
API Doesn't allow modification of statistics

### ISSUE THREAD

**Issue by Gaurav99** [PyvesB/AdvancedAchievements#345]
We used to use the API (cache manager) to edit the statistics internally with the plugin (we're not sure what version this was on).  This is what we did:

`ach.getCacheManager().getAndIncrementStatisticAmount(NormalAchievements.SMELTING, uuid, amt);`

With the latest version, there is no longer a way to do this as far as I can see.  Am I missing something?  If not, could you add something like this back?

**Comment by PyvesB** [comment]
Hello @Gaurav99 !

The cache manager was never part of the public API, you were using the plugin's internals in an unsafe manner.

I'm unsure why you would want to alter the statistics in a standalone and direct way like this, as no threshold checks to award the achievements will actually happen. You're just modifying database values in an opaque way. If you really want to do such a thing, you could use a tiny bit of reflection going though the public API, but I would advise against it. 😉 

Cheers,

Pyves

**Comment by Gaurav99** [comment]
How would you recommend doing what I want to achieve, then?

**Comment by PyvesB** [comment]
Well:

> you could use a tiny bit of reflection going though the public API

Another alternative would be to simply fork the repository and tune the plugin's code to best suit your needs.
