### ISSUE TITLE
A good idea

### ISSUE THREAD

**Issue by Wrohi** [PyvesB/AdvancedAchievements#346]
Sorry for bad english :) Make that so you need to get an achievment so you can /rankup 1 time then again and again, short: you can't /rankup if you didint achieve achievment

**Comment by PyvesB** [comment]
Hello @Wrohi !

Why not simply use a [custom command](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards#custom-commands) reward? 😉 

Cheers,

Pyves
