### ISSUE TITLE
Idea: Prefix in database

### ISSUE THREAD

**Issue by JohOply** [PyvesB/AdvancedAchievements#35]
Hi guys

Is it possible to add a configurable prefix in config for database's tables (mysql) ? (if '' no prefix, like currently)
Because it is hard to find this tables with many others plugins' tables :)

Thanks for reading :)

**Comment by PyvesB** [comment]
Hello,

Why not simply create a new database and call it "achievements" or whatever you like? It's quite simple to do in MySQL through the PhpMyAdmin interface; you just have to modify the address in the plugin's configuration afterwards. ;-)

**Comment by JohOply** [comment]
Unfortunatly i can't do that : my host allows me only to create once database, i can't create more ^^
All french hosts work like that

**Comment by PyvesB** [comment]
Ah, je ne savais pas que c'était comme ça pour les hôtes Français. :-)

I'll keep the suggestion in mind, and add it in a future update (not the upcoming one though, which are more critical fixes oriented).

**Comment by JohOply** [comment]
Thank you :)

**Comment by PyvesB** [comment]
Hello,

This was implemented in the latest commit, and will be published in the next update. It still requires a bit of extra testing on my side, but seems mostly functional and even features an automatic renaming system (only if you come from the default table names). ;-)

Cheers,

Pyves

**Comment by JohOply** [comment]
Thank you, good luck to fix :p
