### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by S3nS3IW00** [PyvesB/AdvancedAchievements#350]
Hello PyvesB!

Make custom categoryes to GUI, or another GUI :D

Hope you like it!

**Comment by PyvesB** [comment]
Hello @S3nS3IW00 !

This is in essence quite similar to #326. Would you like to give it a try and submit a pull request? 😄 

Cheers,

Pyves

**Comment by S3nS3IW00** [comment]
I don't know what is the pull request :D

**Comment by PyvesB** [comment]
A pull request is a code contribution to an open source repository, often made by a developer who is not the main maintainer of the project.

**Comment by S3nS3IW00** [comment]
Oh ok, I don't want to make pull request, only give an idea to you :D

**Comment by PyvesB** [comment]
Fair enough, nevertheless as this is an open-source project, there's no guarantee that your idea will ever be implemented. I'll close this issue and we can track progress in #326 directly, as it really comes down to the same idea. ^^
