### ISSUE TITLE
Reset the mission when completed - Suggestion

### ISSUE THREAD

**Issue by blijgozertje** [PyvesB/AdvancedAchievements#354]
Hey,

I would like to see a new feature on the plugin which is an option to reset the mission when it has been completed.

For example, if I set a reward for mining 100 blocks and someone mines 100 blocks he will complete the mission but it will also reset so that when he mines another 100 blocks the player will get the same reward as well.

This of course with all the possible missions.

**Comment by PyvesB** [comment]
Hello @blijgozertje !

I believe you can already do this. Simply set an `/aach reset` command as a command reward for the achievements you want to reset. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
What do you mean by "doesn't seem to work"? Are there any errors in the console? Are the statistics not being reset correctly?

**Comment by blijgozertje** [comment]
The statistics don't reset at all they just stay the same. No errors in console.

**Comment by PyvesB** [comment]
> statistics don't reset at all

Are you sure about this, have you actually checked in the database?

Are you using the latest version of the plugin? Please share your _config.yml_ file.

**Comment by PyvesB** [comment]
Oh, I just realised, you also have to delete the achievement using _/aach delete_ as resetting the statistic on its own won't change whether the achievement was received or not. 😉

**Comment by blijgozertje** [comment]
Thanks!

**Comment by PyvesB** [comment]
You're welcome! Feel free to open a new issue if you encounter any other problems or star the project to keep a closer eye on future development! ^^
