### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by ToXiCHaZe541** [PyvesB/AdvancedAchievements#356]
Hey so I know this plugin has issues with properly using the advancement system and linking the plugins challenges to them. I found this API this guy made and maybe yall could team up to make this feature work better?

https://www.spigotmc.org/resources/crazy-advancements-api.51741/

**Comment by PyvesB** [comment]
Hello @ToXiCHaZe541 !

Thanks for the suggestion, but after a quick look into it I don't think this is a good idea:
* it isn't available as a Maven dependency.
* it requires users to install an additional plugin on their server.
* it isn't open source, so harder to make contributions or pick up development if the author no longer maintains it.
* it seems to call Minecraft and CraftBukkit internals directly underneath the hood, which means it will break and require updating each time a new version of Minecraft/CraftBukkit is released.

On the plus side, it does seem well documented and the support on Spigot seems decent so far, but this is outweighed by the points mentioned above. 😉 

Cheers,

Pyves
