### ISSUE TITLE
CMI AFK integration

### ISSUE THREAD

**Issue by Feeriix** [PyvesB/AdvancedAchievements#357]
As CMI being an Essentials alternative and much more, could you support this plugin for AFK checks as well?

API:
https://github.com/Zrips/CMI-API

**Comment by PyvesB** [comment]
Hello @Feeriix !

Maybe @Zrips would like to look into this and make a contribution? 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
No news for over a month, closing this issue.
