### ISSUE TITLE
Update PlaceholderAPI

### ISSUE THREAD

**Issue by PyvesB** [PyvesB/AdvancedAchievements#358]
The current version of the PlaceholderAPI dependency used in Advanced Achievements is 2.8.2, but the latest available is 2.8.7. I tried bumping the version number up, but noticed that some methods had since then been deprecated.

@Phoetrix , as you're our PlaceholderAPI expert, would you like to look into this and see whether you can upgrade to the latest version? 😃

**Comment by Phoetrix** [comment]
Oh yes! :)
I will return to Minecraft around mid-June so I will check that at this moment.
Don't hesitate to remind me if I forget. ;)

**Comment by TheSenseiNL** [comment]
*remind*

**Comment by PyvesB** [comment]
@TheSenseiNL I don't think there's any rush here, as it's only about keeping things up-to-date and easy to maintain rather than adding brand new functionality. ^^

**Comment by PyvesB** [comment]
@TheSenseiNL would you like to test the updated implementation? I can compile the plugin with the latest changes if you want.

@Phoetrix you may be interested with issue #365, as @supertassu has completed work on this issue! :wink:

**Comment by Phoetrix** [comment]
Oh sorry I forgot ! :o 
I was very busy on June. ^^'

But ok nice! Good job @supertassu ! :)

**Comment by TheSenseiNL** [comment]
Hi, sorry I couldn't respond faster but I've been very busy. I will install it in a bit and give it a day or 2 to test it :-)
I'll let you know asap

**Comment by supertassu** [comment]
Thanks @TheSenseiNL!

**Comment by PyvesB** [comment]
Here's a compiled version for you:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2177944/AdvancedAchievements.zip)
