### ISSUE TITLE
Timer with GUI

### ISSUE THREAD

**Issue by eot13** [PyvesB/AdvancedAchievements#359]
Hello, could you add a timer a half-second timer when opening the GUI?
(Can be changed in the config)
Thank you

**Comment by PyvesB** [comment]
Hello @eot13 !

To be honest, I find this request slightly strange. Why would you want to delay the opening of the GUI?

Cheers,

Pyves

**Comment by eot13** [comment]
Because if I use it with the plugin ChestCommands which allows to make GUIs and that I add the command "/ aa list", the interface opens then closes directly, I imagine that the ChestCommands plugin calls the event 2 times.

I'm sorry for my bad English.
Have a nice day.

**Comment by PyvesB** [comment]
I see. On the plugin's [homepage](https://dev.bukkit.org/projects/chest-commands), they seem to recommend using the Scheduled Commands plugin, have you tried that solution?

**Comment by PyvesB** [comment]
@eot13 any luck with my above suggestion? ^^

**Comment by eot13** [comment]
I think I will do the plugin myself because it is no longer updated. Thank you for your reply!
