### ISSUE TITLE
Display Names aren't displaying correctly

### ISSUE THREAD

**Issue by Fancepants** [PyvesB/AdvancedAchievements#363]
I am currently working on my own config file for Advanced Achievements. I have 0 errors from what I am seeing in console but I have run into an extremely annoying one I cant seem to fix. 

When I reload the plugin after putting in my config I get this displayed in the gui

![image](https://user-images.githubusercontent.com/20112780/40879639-1e430ca8-6671-11e8-9190-70fa43889d63.png)

https://pastebin.com/RZDZv60E  

Here is a link to the config file I am using. I am currently on 1.12.2 and there are 0 console errors so its extremely hard to tell where I am going wrong.

Thanks!

- Fance

**Comment by PyvesB** [comment]
Hello @Fancepants !

Try changing the following line in the configuration:
````
ListAchievementFormat: "%ICON% %Name% %ICON%"
````
By this one:
````
ListAchievementFormat: "%ICON% %NAME% %ICON%"
````
The comment just above this parameter seems to have changed in your configuration as well, I'm assuming afind/replace may have messed the casing of the variable? 😉 

Cheers,

Pyves

**Comment by Fancepants** [comment]
Oh my goodness! I was looking at this for hours! Thank you so much. My poor brain can rest!

**Comment by PyvesB** [comment]
You're welcome, feel free to open another issue if you encounter any new problems! :+1:
