### ISSUE TITLE
Custom Commands Reward with more variables.

### ISSUE THREAD

**Issue by MXKhronos** [PyvesB/AdvancedAchievements#366]
Hello, first of all, great plugin. Keep up the good work.

I want to suggest more variables for the Custom Commands Rewards part. Currently we have PLAYER which refers to the player name. I wanted to use AdvanceAchievement to spawn a MythicMob boss when they acquire an achievement however I couldn't seem to find WORLD, X, Y, and Z variables of the player to use in the command.

It would be great to have those and use them for custom command rewards.
Thanks in advance,
MXKhronos

**Comment by PyvesB** [comment]
Hello @MXKhronos !

This sounds like a good suggestion, let's try to add it to the plugin at some point! 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
I have added the following variables: `PLAYER_WORLD`, `PLAYER_X`, `PLAYER_Y`, `PLAYER_Z`. This will be available in the next update (probably Advanced Achievements 5.9.2). Thanks for your ideas!
