### ISSUE TITLE
Text obfuscation issue

### ISSUE THREAD

**Issue by digital-r** [PyvesB/AdvancedAchievements#367]
Unfortunately, symbols from cyrillic codepage are not obfuscated and still readable even if obfuscation option sets in config. You can add this example string "_Тестовая строка_" to achievement description for testing. Only spaces are being obfuscated. It seems, there is a bug with minecraft "Magic" text modifier realisation.

**Comment by PyvesB** [comment]
Hello @digital-r !

I believe this is a Minecraft/Spigot limitation (see for instance [MC-41410](https://bugs.mojang.com/browse/MC-41410), and unfortunately there's nothing much I can do about it. I suggest switching off obfuscation when cyrillic characters are used. 😉 

Cheers,

Pyves

**Comment by digital-r** [comment]
Is possible to slightly change obfuscation mechanic?
As example, if string must be obfuscated - replacing it by predefined constant string (something like '§kObfuscatedText')

**Comment by PyvesB** [comment]
@digital-r this has now been implemented and will be released as part of Advanced Achievements 5.9.1. I have implemented this in more clever way than just using a default text, the obfuscation will preserve spaces and players should see exactly the same regardless of whether the text contains cyrillic characters or not. 😉
