### ISSUE TITLE
Bug with Connections category

### ISSUE THREAD

**Issue by kforbro** [PyvesB/AdvancedAchievements#368]
I disabled the category connections, but when player first join to the server he get achievements "Good Choice.

**Comment by PyvesB** [comment]
Hello @kforbro,

Good spot, this seems to be a bug with the plugin. I will fix it shortly. 😉

Cheers,

Pyves

**Comment by kforbro** [comment]
Thanks

ср, 13 июня 2018 г. в 18:03, Pyves <notifications@github.com>:
