### ISSUE TITLE
Support for DiscordSRV

### ISSUE THREAD

**Issue by Siiriiks** [PyvesB/AdvancedAchievements#370]
I use another plugin called DiscordSRV on my server to link the minecraft chat and discord chats together. Player achievements come through on Discord once they earn them for the default Minecraft achievements but not for AdvancedAchievments... Would it be possible to add support to DiscordSRV in this plugin so people in Discord can see when you get AdvancedAchievments?

**Comment by PyvesB** [comment]
Hello @GadgetGamer !

Would you like to submit a pull request adding this support?

Cheers,

Pyves

**Comment by PyvesB** [comment]
No news for well over a month, closing this issue.
