### ISSUE TITLE
Question about customizing certain things.

### ISSUE THREAD

**Issue by FTOtter** [PyvesB/AdvancedAchievements#371]
Hi, I looked through the wiki but did not see the following addressed. Feel free to direct me to where this info is if I missed it!

I am wondering if/how I can customize some of the achievements further. For example, how could I make an achievement for throwing coal into water, or breaking a block with a certain item in hand? Is this possible at all, or am I limited to just essentially counting things? 

I am also wondering if there is a way to award an achievement based on number of achievements completed. I would like to base ranks on my server based on achievement completion, but I'm not finding support for this plugin in any of the rank plugins. (If someone knows one, feel free to point me that way as well.)

Thanks for the assistance!

**Comment by PyvesB** [comment]
Hello @FTOtter !

Unfortunately there is currently no support for throwing items into water or breaking blocks with a certain item in hand. There is also no support for awarding achievements based on the number of achievements completed. 😉 

Cheers,

Pyves

**Comment by FTOtter** [comment]
Darn, that's disappointing. Thanks for the response though!

**Comment by PyvesB** [comment]
You're welcome! This plugin already has a quite impressive set of features, but obviously there's always room for improvement and new ideas. There's only so much I can do on my own with the occasional external contribution, but feel free to send interested developers to this repository. ^^
