### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by KriticalPvP1** [PyvesB/AdvancedAchievements#373]
Hi, I'm trying to connect the plugin AdvancedAchievements to the mysql but it does not let me get this error.

https://pastebin.com/GURRX6AN

You know some way to fix it, thanks.

**Comment by PyvesB** [comment]
Hello @KriticalPvP1 !

The error message indicates:

> Access denied for user 'root'@'ns510231.ip-192-99-0.net' (using password: NO)

Have you specified the right password in _config.yml_?

Cheers,

Pyves

**Comment by KriticalPvP1** [comment]
Yes, everything is correct.
With the other plugins I have the same configuration.

**Comment by PyvesB** [comment]
Could you please send me your _config.yml_ privately (for instance using the mail on my GitHub profile page), I'll take a look at it.

**Comment by PyvesB** [comment]
Okay, I think I have spotted the problem by using the information you provided by mail. Would you like to give this test version a try and see whether it solves the issue you were previously encountering?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2119150/AdvancedAchievements.zip)

**Comment by KriticalPvP1** [comment]
Thanks, it's already working.

**Comment by PyvesB** [comment]
Awesome! This was actually a very old bug lying around in the plugin since version 1.6.2. No one ever noticed because it would only occur when some specific special characters were used in the database username or password. Thanks for reporting the issue!
