### ISSUE TITLE
aa info permission

### ISSUE THREAD

**Issue by Darkilen** [PyvesB/AdvancedAchievements#376]
Hello,
Can you please add a permission for the commande `/aa info`, she give some "critical" information and all players can run it...

Or at least, hide somes informations for no-op player ? Like `version`, `integration state` or `DB type`

Thanks you

**Comment by PyvesB** [comment]
Hello @Darkilen !

I have hidden the third party plugin integrations and the database type for players who do not have the `achievement.*` permission. 😉 

Cheers,

Pyves
