### ISSUE TITLE
Change GUI color from dark gray

### ISSUE THREAD

**Issue by ModernStyles** [PyvesB/AdvancedAchievements#380]
Hi would it be possible to change the GUI color from dark gray in the config? I tried to find it, I may just be blind. Any help would be appreciated greatly. :)

**Comment by PyvesB** [comment]
Hello @ModernStyles ,

Where exactly do you want to change the gray colour in the GUI?

Cheers,

Pyves

**Comment by ModernStyles** [comment]
@PyvesB Sorry for the late response, but just the titles like "Blocks Placed" "Blocks Broken" "Entities Killed" The category list when doing /aach list basically.

**Comment by PyvesB** [comment]
Well, you can simply tune the `ListAchievementFormat` parameter in _config.yml_ and add the colours you like in there. 😉
