### ISSUE TITLE
Nullpointer on BlockBreak event

### ISSUE THREAD

**Issue by hsombini** [PyvesB/AdvancedAchievements#381]
Server version: 1.8.8 Paperspigot using mySQL

https://hastebin.com/ujaqinepik.vbs

**Comment by supertassu** [comment]
> Caused by: com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving Breaks.stone statistics.

Seems like the plugin can't interact with the database.

**Comment by Rsl1122** [comment]
Very cryptic exception. (Connection is not null and given string can not be null)

Only thing I could find that the underlying JDBC code is running into a NPE and casting it to SQLException.

Might be a problem with installed mysql J/Connector or the mysql version in paper 1.8.8

**Comment by PyvesB** [comment]
Yes, I would tend to agree with @Rsl1122 . @hsombini does this happen on a regular basis or was it a one time error?

**Comment by hsombini** [comment]
On a regular basis after the upgrade to the newest version, I had to removed the plugin for now, I'll update my server from 1.8.8 to 1.13 but it will take a while

Would Hikari prevent this issues and improve the performance?

**Comment by PyvesB** [comment]
What plugin version did you upgrade from?

**Comment by hsombini** [comment]
I have been fixing my flawed config.yml since 5.6.4

So I can't precisely tell you what version it's since the plugin was disabled for a while, sorry, but I can tell that before 5.6.4 I never had this issue.

**Comment by PyvesB** [comment]
That's odd, not much has changed in terms of database handling since version 5.6.4. 

So when you revert back to 5.6.4 with your current configuration, everything works fine? Could you give version 5.7.4 a try and see whether it changes anything?

**Comment by PyvesB** [comment]
No news for over a month, therefore assuming this issue has been resolved.
