### ISSUE TITLE
Advancement gui

### ISSUE THREAD

**Issue by Feerko** [PyvesB/AdvancedAchievements#382]
Hello!

Can you add way to change title of this?
<img width="396" alt="zrzut ekranu 2018-07-08 o 08 18 00" src="https://user-images.githubusercontent.com/16988054/42417317-7b693c72-8287-11e8-9b8f-95426d1ca693.png">

and way to change background? 
<img width="471" alt="zrzut ekranu 2018-07-08 o 08 18 34" src="https://user-images.githubusercontent.com/16988054/42417324-86ef9e06-8287-11e8-98e7-9b433c79a8cf.png">
the background does not look good.

thanks!

**Comment by PyvesB** [comment]
Hello @Feerko,

Yes, okay, I guess this could be added as configuration parameters. :wink:

Cheers, 

Pyves

**Comment by supertassu** [comment]
I'll take a look tomorrow.
