### ISSUE TITLE
GUI customization options

### ISSUE THREAD

**Issue by Tyloonie** [PyvesB/AdvancedAchievements#389]
Hello,

I have a few suggestions for the awesome plugin.

1) Since you can only set the **ListColorNotReceived** in the config.yml as a single color, could you make an option that makes ListColorNotReceived bold? For example **ListColorNotReceivedBold: true**.

2) Is it possible to add lores to the **BackButton,** **PreviousButton** and **NextButton**?

Thank you very much.

**Comment by PyvesB** [comment]
Hello @Tyloonie,

This is not currently possible, but let's keep these suggestions in mind for future plugin updates. 😉 

Cheers,

Pyves

**Comment by Tyloonie** [comment]
Okay!

I believe they should be quite easy to implement since they are not formatting suggestions.

Thanks anyways.

**Comment by PyvesB** [comment]
As per your second suggestion, I have implemented three new options in _lang.yml_, `list-back-lore`, `list-previous-lore` and `list-next-lore`. 😉 

Regarding the first suggestion, I don't think it will be used very much, so I won't be adding it for the time being.
