### ISSUE TITLE
Error on plugin load

### ISSUE THREAD

**Issue by AlChimiK2D** [PyvesB/AdvancedAchievements#393]
Hello, i have a problem with the plugin AdvancedAchievements. It doesnt start at the start of the server  

The console says : 
`14.07 22:46:19 [Server] ERROR [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it: 14.07 22:46:20 [Multicraft] Skipped 61 lines due to rate limit (120/s)`

I can give you my config file if you want.
Can you help me please ?

**Comment by PyvesB** [comment]
Hello @AlChimiK2D ,

Yes, please share your configuration file. You can easily share it using GitHub Gist or Pastebin. 😉 

Cheers,

Pyves

**Comment by AlChimiK2D** [comment]
I give you the new file config i have do with itemsID : 
but ther is a problem when i click on "places" in game it says : [AdvancedAchievements] Invalid item reward for achievement with path "Places.dirt.1.Reward". Please specify a valid Material name.
[config.txt](https://github.com/PyvesB/AdvancedAchievements/files/2195289/config.txt)

**Comment by AlChimiK2D** [comment]
There is a problem about the number of connexions : 
I have 2/2 connections but the achievement is not give ???

**Comment by PyvesB** [comment]
Could you please show me a screenshot of the relevant _/aach give_ category?

**Comment by AlChimiK2D** [comment]
`Connections:
  '1':
    Message: '&4Bienvenue sur le StupServeur !!!'
    Name: connect_1
    DisplayName: nouveau venu
  '2':
    Message: '&4Salut comment ça va ce matin ?'
    Name: connect_2
    DisplayName: revenant
    Reward:
      Money: 42
  '3':
    Message: '&4Toujours là ?'
    Name: connect_3
    DisplayName: insistant
    Reward:
      Money: 93
  '7':
    Message: '&4Eh bien ! On s installe ?'
    Name: connect_7
    DisplayName: persévérant
    Reward:
      Money: 894
  '21':
    Message: '&4OK donc t es définitivement fan du crou ET de minecraft quoi.'
    Name: connect_21
    DisplayName: fataliste
    Reward:
      Money: 1993
      Command:
        Execute: 'say §7ALERTE: §4PLAYER§7 est un gros §4GEEK§7 !'`

![2018-07-15_13 05 43](https://user-images.githubusercontent.com/30317409/42733329-0ae9bacc-8830-11e8-8f6a-5476f3dcc618.png)

**Comment by PyvesB** [comment]
What happens if you disconnect and reconnect about 30 seconds later?

**Comment by PyvesB** [comment]
@AlChimiK2D has the problem since then been solved or are other users facing similar issues?

**Comment by AlChimiK2D** [comment]
Hello. I think i have not configurate the permissions correctly.  I Will see chat

**Comment by PyvesB** [comment]
Assuming everything is now working as expected, closing! Feel free to reopen if you are still facing any issues.
