### ISSUE TITLE
How to get different mob spawners with /give

### ISSUE THREAD

**Issue by TAfirehawk** [PyvesB/AdvancedAchievements#394]
I am using the "/give PLAYER mob_spawner 1 1" but still get little piggies.  I also tried "mob_spawner 1 0 {BlockEntityTag:{EntityId:Horse}}" without success

Is there a meta data format that can be passed to get different mob spawners?

**Comment by PyvesB** [comment]
Hello @TAfirehawk ,

[This Essentials issue](https://github.com/EssentialsX/Essentials/issues/142) suggests that you need to give the _essentials.spawnerconvert.mobtype_ permission to your players. Does this help? 😉 

Cheers,

Pyves

**Comment by TAfirehawk** [comment]
At this time I am not running Essentials, just AACH.

**Comment by PyvesB** [comment]
I don't think you can do that with Vanilla Minecraft in that case.

**Comment by TAfirehawk** [comment]
I got Essentials loaded and it works now plus changes the format to pass meta data to using a ":" instead of being at the end.

**Comment by PyvesB** [comment]
Okay, so am I right in thinking that everything is working fine for you now?

**Comment by TAfirehawk** [comment]
Yes, thank you for the help and the great plugin :)
