### ISSUE TITLE
Project set-up guide for IntelliJ

### ISSUE THREAD

**Issue by Rsl1122** [PyvesB/AdvancedAchievements#396]
Write-up of IntelliJ project set-up for [Developers](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#modifying-the-plugin) page

----

- Fork the repository by clicking on the Fork icon on the top right of the page. You can also simply clone or download it by going to the [main page](https://github.com/PyvesB/AdvancedAchievements).
- In IntelliJ go to *Open..* and open the repository root folder
  - IntelliJ will run Sync on the maven project - if not click the *Configure maven project* pop-up that appears
- If not yet installed, install *Maven Helper*-plugin to run maven goals inside IntelliJ (For next steps)
- To compile the plugin, in *Project* right click *AdvancedAchievements* > :gear: *Run Maven* > *install*, this will run `mvn install:install`
- The plugin will be generated in the target folder of the project.

For easy PRs
- Use tabs: *Settings* > *Editor* > *Code Style* > *Java* > *Tabs and indents* > *Use tab character*
- You can run `mvn formatter:format` with :gear: *Run Maven* > *Plugins* > *maven-formatter-plugin* > *formatter:format*

----

```
- Fork the repository by clicking on the Fork icon on the top right of the page. You can also simply clone or download it by going to the [main page](https://github.com/PyvesB/AdvancedAchievements).
- In IntelliJ go to *Open..* and open the repository root folder
  - IntelliJ will run Sync on the maven project - if not click the *Configure maven project* pop-up that appears
- If not yet installed, install *Maven Helper*-plugin to run maven goals inside IntelliJ (For next steps)
- To compile the plugin, in *Project* right click *AdvancedAchievements* > :gear: *Run Maven* > *install*, this will run `mvn install:install`
- The plugin will be generated in the target folder of the project.

For easy PRs
- Use tabs: *Settings* > *Editor* > *Code Style* > *Java* > *Tabs and indents* > *Use tab character*
- You can run `mvn formatter:format` with :gear: *Run Maven* > *Plugins* > *maven-formatter-plugin* > *formatter:format*
```

**Comment by PyvesB** [comment]
Thanks for this @Rsl1122 ! I've updated the Wiki, let me know what you think. I believe you have sufficient rights to edit it yourself (I'll be notified of any changes afterwards). 😉

**Comment by Rsl1122** [comment]
Ah I did not realize, thanks! :)
