### ISSUE TITLE
How do I properly config MySQL?

### ISSUE THREAD

**Issue by pixxykilljoy** [PyvesB/AdvancedAchievements#397]
What is the proper way to fill out the "database" section in the mysql area? I Know what to put for user/password, but apparently i cant get database filled out properly, because i keep getting " ERROR [AdvancedAchievements] Error while attempting to retrieve a connection to the database:"

**Comment by PyvesB** [comment]
Hello @pixxykilljoy ,

You have to use a parameter such as the following:

> Database: "jdbc:mysql://localhost:3306/minecraft"

Replace "localhost" by the address of your database. Replace "3306" by the port used to connect to your database. Replace "minecraft" by the name of the database you want to connect to. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Assuming everything is now working as expected, closing! Feel free to reopen if you are still facing any issues.
