### ISSUE TITLE
Can't get 5.9 to work with Paper 1.13

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#402]
Good morning,
I'm very excited that there's already a 1.13 version of aach. Thank you for your hard work on this awesome plugin! :)
As I saw that there's an update on SpigotMC I set up a test environment (running latest version of PaperSpigot 1.13) to help you testing if everything works fine so far. 
Unfortunately I can't get it to work - it doesn't start with this exception in console:
https://hastebin.com/zakeqigoru.md

Have a nice day, see you :)

\edit: Got the same problem with official spigot.

**Comment by Platinteufel** [comment]
Update: Just found your testversion [here](https://github.com/PyvesB/AdvancedAchievements/issues/398#issuecomment-408249918). That works for me so far.

**Comment by PyvesB** [comment]
Hello @Platinteufel,

For some weird reason, Maven seemed to have only packaged some of the Dagger classes and not the others. It's the first time I've seen this happening. Re-running the same `mvn clean install` generates a slightly bigger archive, with the expected classes inside. I'll prepare and submit a new version as soon as possible. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
The new version has been uploaded, enjoy!
