### ISSUE TITLE
Aachievements dont want to load

### ISSUE THREAD

**Issue by AviRendall** [PyvesB/AdvancedAchievements#408]
When plugin tries to load, there is error: https://pastebin.com/JxNXkhGh
I use Plugman to load AACHs. It has worked on 1.12 versions.
The same error appears on normal server start.

All of new entities/materials' names was chaged to 1.13

Is that a bug or plugin not compatible with EssentialsX build?

**Comment by PyvesB** [comment]
Hello @AviRendall ,

Could you please try re-downloading the _.jar_ from Spigot/Bukkit, that will hopefully solve the issue you are experiencing.

As far as Minecraft 1.13 is concerned, I suggest you read the [related Wiki page](https://github.com/PyvesB/AdvancedAchievements/wiki/Migrating-to-Minecraft-1.13). 😄 

Cheers,

Pyves

**Comment by AviRendall** [comment]
It works now, Thx

**Comment by PyvesB** [comment]
You're welcome!
