### ISSUE TITLE
lang.yml 5.9.0 Translated to brazilian portugues

### ISSUE THREAD

**Issue by bolodecenora** [PyvesB/AdvancedAchievements#409]
file translated without errors into portuguese from brazil
[lang-BP.zip](https://github.com/PyvesB/AdvancedAchievements/files/2272501/lang-BP.zip)

**Comment by EncryptSL** [comment]
Hi @bolodecenora you can use Pull requests for new changes.

**Comment by bolodecenora** [comment]
I swear I tried

**Comment by PyvesB** [comment]
@bolodecenora does [this piece of documentation](https://help.github.com/articles/editing-files-in-another-user-s-repository/) help? 😄

**Comment by PyvesB** [comment]
I updated the file directly. Thanks for your contribution! 😉
