### ISSUE TITLE
Big Walker shouldn't increase by vertical movement

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#41]
Hey,
after a few days I've just noticed that also vertical movement (e.g. from y=10000 to y=0) increases your DistanceFoot value. That makes it easy to get high values very fast here.

**Comment by PyvesB** [comment]
Hello,

Well this is intended behaviour, why should one dimension be neglected over the others? For instance if the player climbs a mountain, I find it normal that the Y dimension is accounted for, as he is literally walking more than if he has just gone straight on a flat surface. Similarly if once on top of the mountain he decides to take a  minecart roller coaster, I find it normal that the Y dimension is also accounted for, as minecarts usually do have a lot of ups and downs. ;-)

**Comment by Platinteufel** [comment]
Let's think about the following use-case: Stack up to y=256 (max-height). Set your home/respawnpoint there. Jump down again and again .. ;-)

**Comment by Platinteufel** [comment]
Even worse: You have rights for /tppos. Type '/tppos x 10000 z' and let you fall down. Did you really walk 10000 blocks then? ^^

**Comment by PyvesB** [comment]
Well technically speaking yes, you did *travel* 10000 blocks without any vehicle, that is by foot. I could add an option though. ;-)

**Comment by PyvesB** [comment]
Hello,

An option was added in the latest update. Enjoy. ;-)
