### ISSUE TITLE
Advancements generate error

### ISSUE THREAD

**Issue by AviRendall** [PyvesB/AdvancedAchievements#411]
When i try to generate advancements there is error: https://pastebin.com/50aMkL3G

All Goals, Descriptions and Displaynamesin my config are cyrillic, with color codes and more than 16 symbols.
What should i do to generate advancements normally?

**Comment by PyvesB** [comment]
Hello @AviRendall,

Were you facing similar errors with previous versions of Advanced Achievements in Minecraft 1.12? Could you please share your _config.yml_?

Cheers, 

Pyvea

**Comment by AviRendall** [comment]
Yes, the similar errors were in previous versions. Here is config: https://pastebin.com/CRMzHfvE

**Comment by PyvesB** [comment]
I was not properly escaping JSON during generation, so characters such as double quotes in the achievement messages would make the command fail. You should be able to generate everything with the following version:

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2280098/AdvancedAchievements.zip)

To be completely honest though, I'm unsure how the advancement GUI will handle that many advancements. But at least, Advanced Achievements should do its job properly and generate all relevant JSON files on the server. 😉

**Comment by AviRendall** [comment]
Yes. Advancements was generated normally after remove '' from descriptions. Thx
