### ISSUE TITLE
STONE_BRICKS is not recognized by the plugin

### ISSUE THREAD

**Issue by Mario359** [PyvesB/AdvancedAchievements#415]
Unable to make the achievement place stones bricks, the plugin does not seem to know what "STONE_BRICKS" is (the name was changed with Minecraft 1.13)
I use Spigot 1.13
```
Places:
  STONE_BRICKS:
    '2000':
      Goal: Placer 2000 blocs de pierre taillé
      Message: '//set stone_bricks'
      Name: crea_place_pierre_taille_2000
      DisplayName: WorldEdit
      Reward:
        Money: 10
```

**Comment by Mario359** [comment]
No, it doesn't work even in tiny letters
![image](https://user-images.githubusercontent.com/20285750/44268756-c4e1d880-a232-11e8-9110-3e54eb0f997d.png)

**Comment by PyvesB** [comment]
No worries. 😉
