### ISSUE TITLE
Unable to revert IncreaseMaxHealth

### ISSUE THREAD

**Issue by RayisNTDO** [PyvesB/AdvancedAchievements#416]
I was creating achievements that give more max health on my server. after giving one to myself to test, i was unable to revert it. is there any way to remove the increasemaxhealth reward from a player?

**Comment by RayisNTDO** [comment]
Nevermind, I solved this on my own by deleting my playerdata file.

**Comment by PyvesB** [comment]
Glad you solved your issue @RayisNTDO , let me know if you need anymore help. 😉
