### ISSUE TITLE
Not able to click elytra in the GUI

### ISSUE THREAD

**Issue by gameplayerhd** [PyvesB/AdvancedAchievements#417]
Paper version git-paper-1414 1.12.2
Aach version 5.8.1

The achievement for elytra doesn't work, as in you can't click it:
http://prntscr.com/kkdae5

DistanceGliding:
  Item: elytra
  Metadata: 0

Any ideas? Thanks

**Comment by PyvesB** [comment]
Hello @gameplayerhd ,

Are there any errors or warnings in your server's logs? Also please upgrade to the latest version of the plugin. 😉 

Cheers,

Pyves
