### ISSUE TITLE
Can't load GUI

### ISSUE THREAD

**Issue by blijgozertje** [PyvesB/AdvancedAchievements#418]
Error:
https://hastebin.com/luyizorepo.pl

Possible issue:
I upgraded from version 5.2.8 to the latest. (1.8.8 server)

**Comment by PyvesB** [comment]
Hello @blijgozertje ,

The linked page seem to be blank. Please share you configuration files so that I can try to reproduce the error. 😉 

Cheers,

Pyves

**Comment by blijgozertje** [comment]
I have 4 servers so included them all. config-factions.yml was the one that I already updated and had errors with the others are still on 5.2.8

http://www.mediafire.com/file/jpaehaodcgn1e6e/Configs.rar/file

**Comment by PyvesB** [comment]
You configuration file is not valid, a lot of the categories you have specified are incorrectly spelt. Here is the corrected list:
```
DisabledCategories:
- PetMasterGive
- PetMasterReceive
- DistanceLlama
- DistanceGliding
- Connections
- Crafts
- PlayerCommands
- Snowballs
- Eggs
- Fish
- Treasures
- ItemBreaks
- EatenItems
- Shear
- Milk
- LavaBuckets
- WaterBuckets
- Trades
- Beds
- DistancePig
- DistanceHorse
- DistanceMinecart
- ItemDrops
- ItemPickups
- HoePlowings
- Fertilising
- Taming
- Breeding
- Fireworks
- MusicDiscs
- Smeltings
- Commands
- Custom
```

**Comment by blijgozertje** [comment]
Alright that works but now when clicking on a category it has the clickable item on slot 1 looks pretty weird
https://gyazo.com/b159a795239342d8fc56f267b588b92a

**Comment by PyvesB** [comment]
Yes, this is expected behaviour.

**Comment by blijgozertje** [comment]
Oh okay is there any way to disable that or not?

**Comment by PyvesB** [comment]
No, it is not possible to disabled it. 😉
