### ISSUE TITLE
Problem with MySQL Service... Help Me Please!!

### ISSUE THREAD

**Issue by TheSerialKInder** [PyvesB/AdvancedAchievements#421]
Hi, i have a problem with MySQL Service, can anyone help me?
I send the error code on pastebin: https://pastebin.com/bhXLPYaz

**Comment by supertassu** [comment]
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
```

You have too many clients connected to the database server.

**Comment by TheSerialKInder** [comment]
@supertassu how can i resolve it?

**Comment by supertassu** [comment]
Are you using a managed host or is it self managed (vps, dedi, etc)

**Comment by TheSerialKInder** [comment]
Vps

**Comment by Rsl1122** [comment]
If you are using MySQL or MariaDB, you can change `max_connections` variable inside mysql.

```
show variables like "max_connections";
```
```
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 100   |
+-----------------+-------+
```
Change with following query:
```
set global max_connections = 200;
```
https://www.electrictoolbox.com/update-max-connections-mysql/

**Comment by TheSerialKInder** [comment]
I did it this afternoon, but since it was already at 200, I set it at 1450... lets wait and see if it works :)

**Comment by PyvesB** [comment]
One or more of these plugins may not be closing connections to the database properly. If you still encounter any issues even after bumping up the maximum number of connections, I suggest removing them one at a time and see at what point the problem goes away. You'll find the culprit plugin that way! :smile:
