### ISSUE TITLE
Error in lang with underlining

### ISSUE THREAD

**Issue by Nestu14** [PyvesB/AdvancedAchievements#423]
As AlexiMaria mentioned on Spigot, the next message has an error, the space that follows to "hover" and "click" is underlayed
https://github.com/PyvesB/AdvancedAchievements/blob/e35a061fdc7b41b1957eccfa7bb92ff47ebc6926/advanced-achievements-plugin/src/main/resources/lang.yml#L101

[![Screenshot from Gyazo](https://gyazo.com/a15d45a897f9bcbb0ad7f15fa7865b6d/raw)](https://gyazo.com/a15d45a897f9bcbb0ad7f15fa7865b6d)

The text should be changed to`"&lHINT &8You can &7&n&ohover&8 or &7&n&oclick&8 on the commands!"` to fix it.

As long as I have seen, this error is present in multiple lang files.

**Comment by PyvesB** [comment]
Hello @Nestu14,

Thanks for reporting this, I had never noticed. Would you like to submit a pull request to fix it? 😄 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Okay, withdrawing my pull request suggestion, this is now fixed! 👍
