### ISSUE TITLE
Promlem with setting up an icon (Question)

### ISSUE THREAD

**Issue by krutosh2** [PyvesB/AdvancedAchievements#424]
Whatever text I did not write in the settings for the achievement, the icon remains a book.
I tried this:
Item: minecraft:torch
Item: torch
(I found it in source code)
but it didn't work. Server continue send "[AdvancedAchievements] Failed to get internal item name for advancement icon. Using book instead."
My question: Which syntax is correct?
(Sorry, if there are some gramarrly errors, some piece of this text was automacaly translated)

**Comment by PyvesB** [comment]
Hey there, I'm guessing you figured the problem out? 😄
