### ISSUE TITLE
I can't find any errors with this config

### ISSUE THREAD

**Issue by SovietBear** [PyvesB/AdvancedAchievements#425]
I seriously have spent 20+ hours figuring out what is wrong with this now I have hit a stump and can't seem to find what is wrong with this config. https://pastebin.com/Kf0i3v8e

the error is
19.09 23:03:29 [Server] INFO ^
19.09 23:03:29 [Server] INFO - Connections
19.09 23:03:29 [Server] INFO in 'string', line 97, column 1:
19.09 23:03:29 [Server] INFO expected &lt;block end&gt;, but found BlockEntry
19.09 23:03:29 [Server] INFO ^
19.09 23:03:29 [Server] INFO AdvancedAchievements_COMMENT_0: ...
19.09 23:03:29 [Server] INFO in 'string', line 2, column 1:
19.09 23:03:29 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
19.09 23:03:29 [Server] INFO - Connections
19.09 23:03:29 [Server] INFO in 'string', line 97, column 1:

**Comment by PyvesB** [comment]
Hello @SovietBear,

The latest version of Advanced Achievements loads fine with the configuration you shared. Furthermore, the error doesn't seem to be related to this config.

Cheers,

Pyves

**Comment by SovietBear** [comment]
Thanks. I reinstalled it and it seemed to work now.

**Comment by SovietBear** [comment]
Is there anyway I can not have everything under the category of breeding?
