### ISSUE TITLE
Can't look inside any of the categories

### ISSUE THREAD

**Issue by SovietBear** [PyvesB/AdvancedAchievements#426]
The source code is still the same basically excluding the fact everything has a categrory now like deaths and stuff but I can't view inside any of them

**Comment by PyvesB** [comment]
Hello @SovietBear,

Could you please rephrase, or show some screenshots/error logs? I'm unsure what you mean at this point.

Cheers,

Pyves

**Comment by SovietBear** [comment]
The error fixed when I switched hosts from MCPRO to Nitrous. Issue was resolved. Appreciate the response tho. Great plugin.
