### ISSUE TITLE
AdvancedAchievements GUI not working!

### ISSUE THREAD

**Issue by Xubels** [PyvesB/AdvancedAchievements#431]
In "aach list" not all of the item or buttons work.
![image](https://user-images.githubusercontent.com/34733342/46251176-d74a5700-c419-11e8-8de7-98c57b514558.png)

For example, when I click on "Entities Killed" it will not function as intended. But it will give me this error in the console:

`ERROR Could not pass event InventoryClickEvent to AdvancedAchievements v5.9.3 23.09 12:45:51 [Server] INFO org.bukkit.event.EventException: null 23.09 12:45:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2140) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] 23.09 12:45:51 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] 23.09 12:45:51 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/milkbowl/vault/item/Items 23.09 12:45:51 [Server] INFO at com.hm.achievement.utils.RewardParser.getItemName(RewardParser.java:150) ~[?:?] 23.09 12:45:51 [Server] INFO at com.hm.achievement.utils.RewardParser.getRewardListing(RewardParser.java:99) ~[?:?] 23.09 12:45:51 [Server] INFO at com.hm.achievement.gui.CategoryGUI.buildLore(CategoryGUI.java:439) ~[?:?] 23.09 12:45:51 [Server] INFO at com.hm.achievement.gui.CategoryGUI.displayPage(CategoryGUI.java:218) ~[?:?] 23.09 12:45:51 [Server] INFO at com.hm.achievement.gui.CategoryGUI.displayCategoryGUI(CategoryGUI.java:144) ~[?:?] 23.09 12:45:51 [Server] INFO at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:64) ~[?:?] 23.09 12:45:51 [Server] INFO at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source) ~[?:?] 23.09 12:45:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121] 23.09 12:45:51 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121] 23.09 12:45:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-68acb93-7d506c6] 23.09 12:45:51 [Server] INFO ... 15 more`

**Comment by PyvesB** [comment]
Hello @Xubels,

Same as #430. :wink:

Cheers, 

Pyves
