### ISSUE TITLE
Multiple servers support?

### ISSUE THREAD

**Issue by Krosta8** [PyvesB/AdvancedAchievements#432]
Hello guys,
I read the wiki from the top to the bottom and can't find anything about bungeecord, etc.

I don't test it yet, but I want to know, if there is somehow possible to share achievements with multiple servers.
I know, that I can connect all servers to one sql table, but will it work properly?
Example:
On server1 I killed 49 zombies.
On server2 I killed 1 zombie.
Will I get achievement for killing 50 zombies?

If I get it correctly, it should work without any problem, because it will be storted in one sql table = share the progress of achievements.

Sorry, if you don't understand me. English is not my motherlanguage :D 
Thank you very much,
Krosta8

**Comment by PyvesB** [comment]
Hello @Krosta8,

Yes, using a single shared SQL table should do the trick. See #273 sir a similar issue. :wink:

Cheers, 

Pyves

**Comment by Krosta8** [comment]
Oh, sorry, forgot to look thru closed issues.
Thank you a lot! :)
