### ISSUE TITLE
"First" to get the achievement

### ISSUE THREAD

**Issue by TheNickoos** [PyvesB/AdvancedAchievements#433]
Hello,

Can you add a "Reward" or something else who make the achievement no longer available after one player getting it ?
Like "First to join the server", "first to be level 10", ....

Thanks.

**Comment by PyvesB** [comment]
Hello @TheNickoos,

I've got the feeling that this may cause either confusion or frustration. Players would start seeing achievements in the GUI that they can't actually get. It would also defeat the purpose of commands such as _/aach stats_ which would display progress bars that you can't actually fill up unless you're the first one to do everything.

Cheers,

Pyves
