### ISSUE TITLE
generate Language-File

### ISSUE THREAD

**Issue by Sprungente** [PyvesB/AdvancedAchievements#442]
Maybe i'm to stupid or something going wrong

Configsettings:
LanguageFileName: lang-DE.yml
DateLocale: de

Why the plugin generate still the english languagefile?

**Comment by PyvesB** [comment]
Hello @Sprungente,

Historically I've always only packaged the English version in the final _.jar_, so `LanguageFileName` will only work if you copy-paste the translated file to Advanced Achievements's directory. However, now that you're pointing it out, it would probably make more sense to include all files and generate the appropriate one. Let's change this behaviour!

Cheers,

Pyves

**Comment by PyvesB** [comment]
The `LanguageFileName` option was actually not even working properly anymore, so in addition to including all translations, I've fixed it. 😉
