### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by Leomelonseeds** [PyvesB/AdvancedAchievements#443]
Recently, it has come to my notice that the time played and distance ran categories are causing a TON of lag.

Here are my timings reports: https://timings.aikar.co/?id=8e143542a19d477b9011733bf17fdf37#plugins

As you can see the AchieveDistanceRunnable and AchievePlayTimeRunnable tasks are using lots of resources and causing lagspikes.

Is there any way to reduce the lag? I might have to remove these extremely important achievements because of this issue :(

**Comment by PyvesB** [comment]
Hello @Leomelonseeds,

Did this issue happen in previous versions of Advanced Achievements as well? What database type are you using?

Cheers,

Pyves

**Comment by Leomelonseeds** [comment]
Yes it did, I think.

I use the default database (sqlite)

**Comment by PyvesB** [comment]
That's odd, SQLite usually runs smoothly for users. What version of SQLite is installed on your server? Do you happen to have a slow hard disk drive on it?

**Comment by Leomelonseeds** [comment]
I have no idea what version it is sorry. I just use the default database, nothing changed.

And yes I do use an HDD. Does that affect performance? Should I migrate to MySQL and if so how would I migrate all the data?

**Comment by PyvesB** [comment]
I just remembered that CraftBukkit ships SQLite directly, so you _should_ be using a fairly recent version.

Having a HDD does affect performance. Plugins that rely on a database will operate significantly slower than on a server with a proper SSD. You can give MySQL or PostgreSQL a try, they tend to have very good performance when deployed locally. Otherwise we can spend some more time investigating as well, but I'm unsure whether we'll make much progress. 😉

**Comment by Leomelonseeds** [comment]
I will use mysql. How would I migrate the SQLite database into a mysql table?

**Comment by Leomelonseeds** [comment]
Thank you so much! I have one mote question though, I already have a mysql database, would importing this file create a new table in the existing database?

**Comment by Leomelonseeds** [comment]
Thank you so much! I have one more question though, I already have a mysql database for my server, does importing the file create a new table in the existing database?

**Comment by PyvesB** [comment]
The simplest would probably be to create a new database within your MySQL installation:
`CREATE DATABASE databasename;`

But I'm assuming that it would happily handle importing tables in the existing one as well.

**Comment by Leomelonseeds** [comment]
Thanks again! Ill let you know if there are any more problems :D

**Comment by Leomelonseeds** [comment]
Still sightly laggy from the below timings report apparently, but not as much. Not getting lagspikes at least anymore. Should we investigate or not?

https://timings.aikar.co/?id=dbb9033774194cd79a44812e8748e57f#plugins

**Comment by PyvesB** [comment]
To be honest, performance seems reasonable at this point, I doubt we will manage to get anywhere without migrating away from a slow hard disk drive. What you could do though is increase the `PlaytimeTaskInterval` parameter in _config.yml_, larger values will give better performance even though precision may degrade a little. 😉
