### ISSUE TITLE
Error with update config.yml ?

### ISSUE THREAD

**Issue by normanfeltz** [PyvesB/AdvancedAchievements#444]
Hey,

I have a repeated bug on my config.yml :

![2018-10-08_10-45-42](https://user-images.githubusercontent.com/1359159/46599745-69242500-cae8-11e8-8cc4-82f1fb900a02.png)

The file is broken and not loaded (I use MySQL, and i not used).

I have at every update remove the line on the config file.

Cordialy

Norman FELTZ

**Comment by PyvesB** [comment]
Hello @normanfeltz,

There seems to be a weird tabulation character in your configuration file. I suggest simply removing those comment lines or replacing them with the fresh default header from [here](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml). Hopefully the problem will stop happening. 😉 

Cheers,

Pyves
