### ISSUE TITLE
Entity Names

### ISSUE THREAD

**Issue by SirPsycho93** [PyvesB/AdvancedAchievements#447]
Hi, i would know why my custom achievements in "kills" category are unvalid for: ender dragon, cave spider, ghast, shulker and skeleton horse.. I wrote all correctly basing on minecraft entities ID.. no code errors.. those achievements are saved in "list" but don't work
Thanks

**Comment by PyvesB** [comment]
Hello @SirPsycho93,

I'm unclear what the problem is. What is leading you to think that the keys are invalid? Are there any errors/warnings in your server's logs? Could you please share the relevant parts of your configuration?

Cheers,

Pyves

**Comment by PyvesB** [comment]
No news, feel free to reopen it you are still encountering issues.
