### ISSUE TITLE
Colour question

### ISSUE THREAD

**Issue by Auntex** [PyvesB/AdvancedAchievements#448]
It is possible to add formatting codes to lang.yml? Tried with & and §
![image](https://user-images.githubusercontent.com/34576139/46921631-28d71200-cfd4-11e8-9174-150dee653248.png)

**Comment by PyvesB** [comment]
Hello @Auntex,

This should be possible using `§`. See following screenshot:
![colours](https://user-images.githubusercontent.com/10694593/47046134-5ebef680-d18c-11e8-8534-e528637fd74e.png)

Cheers,

Pyves
