### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by InvertedTNT** [PyvesB/AdvancedAchievements#45]
I installed your plugin and got this error immediately
http://pastebin.com/JSCZRYMd

**Comment by PyvesB** [comment]
Hello,

Could you please paste me your configuration file?

Cheers,

Pyves

**Comment by InvertedTNT** [comment]
Sure, but i didnt do anything to it
http://pastebin.com/riz60g9j

**Comment by PyvesB** [comment]
Indeed, there seems to be a bug with the configuration upgrade process from some older versions. Add the new "DisabledCategories: []" parameter to the config, and it should work. ;-)

**Comment by InvertedTNT** [comment]
I get a different error and the plugin disables itself
Pastebin: http://pastebin.com/Zn3qEMHA

**Comment by InvertedTNT** [comment]
Im actually really suprised i was that dumb and i couldnt find the DisabledCategories: [] parmater well its fixed now, Thx for the help
