### ISSUE TITLE
Give kit

### ISSUE THREAD

**Issue by Greenfoot5** [PyvesB/AdvancedAchievements#453]
How would I give a kit to the player who has got the achievement? I can't seems to find a player parameter and just executing '/kit starter' doesn't work.

**Comment by Greenfoot5** [comment]
The reason I would like to do this rather than just giving the item is because I have custom items with lore, stats ect. and it would make my life a whole lot easier to give kits rather than have to mess around with the give command and work out how to apply all the changes to the item I wish to make.

**Comment by Greenfoot5** [comment]
Found the PLAYER is the placeholder for the player who has earnt the achievement.

**Comment by PyvesB** [comment]
Glad you solved your problem, I highly recommend reading the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) as it contains a lot of valuable information. 😉
