### ISSUE TITLE
Better Gui? IDEA

### ISSUE THREAD

**Issue by InvertedTNT** [PyvesB/AdvancedAchievements#46]
I was thinking that you should maybe add like a new and improved GUI with a red stained clay (or any configuarbale block) for the achievements that you haven't completed yellow stained clay for ones in progress and green stained clay for one's you've completed. This would make it easier for players to navigate through achievements

**Comment by InvertedTNT** [comment]
Thanks for reading!

**Comment by PyvesB** [comment]
Hello,

If I've understood your suggestion correctly, I would keep the GUI as is, but when clicking on one of the items, it would make different coloured clays appear, one per achievement in the category?

**Comment by InvertedTNT** [comment]
Yea technically that's correct

**Comment by PyvesB** [comment]
Okay, this seems like a nice idea; I'll keep it in mind for the future, nevertheless it will take some time to implement it, don't expect it too soon. ;-)

**Comment by InvertedTNT** [comment]
Also, can you please make it so you can edit the amount of rows in the GUI because i only want to use a few achievement categories and it doesn't look nice with only 5 categories for 4 rows of a GUI

**Comment by Platinteufel** [comment]
Maybe keep #18 in mind while implementing this. ;-)

**Comment by PyvesB** [comment]
Hello,

I will take care of the two points you mentioned above. I have slowly started the work on the new GUI; would you be opened for some beta testing in the upcoming days/weeks? :-)

**Comment by Devillion** [comment]
@PyvesB I would help beta test this.

**Comment by InvertedTNT** [comment]
I'm sorry that i got this too late. I'd be happy to test it if you want me to.

**Comment by PyvesB** [comment]
Hello,

The beta with the new GUI is finally here! You can download it just here:
[AdvancedAchievements-2.6-Beta.zip](https://github.com/PyvesB/AdvancedAchievements/files/342383/AdvancedAchievements-2.6-Beta.zip)

Please give me feedback about:
- any bugs you may encounter.
- any performance issues you may have with the command.
- what you think about the work, and eventually ideas to improve it.

All the config options are normally functional with the new command, except ListItemSeparator which does not have any effect anymore.

Cheers,

Pyves
