### ISSUE TITLE
ArrayIndexOutOfBoundsException on PlayerBucketFillEvent

### ISSUE THREAD

**Issue by jere62smi** [PyvesB/AdvancedAchievements#461]
Hi, I have an error that spam logs.
Version server: 1.13.2 with Paper
Latest version of the plugin

https://pastebin.com/ZvLcyuph

**Comment by PyvesB** [comment]
Hello @jere62smi,

Could you please share your _config.yml_ file so that I can try to reproduce the error?

Cheers, 

Pyves

**Comment by jere62smi** [comment]
Check your mail for my config 'PyvesDev@gmail.com'

**Comment by PyvesB** [comment]
You have specified some empty categories, but haven't included them in `DisabledCategories`. THe configuration is therefore not valid, I have however fixed a bit of validation at start time which should deal with that automatically in the future. 😉
