### ISSUE TITLE
Idea for a new categorie.

### ISSUE THREAD

**Issue by CielTheNemesis** [PyvesB/AdvancedAchievements#465]
Hello ! I Really love this plugin but one thing miss for the server i want to make :'(
So, the idea is simple : a success when a XY zone is reached.
Like : "You reached the first floor !" and, "1 of 25 Jumps is now finish !"

If you do that. I love u.

**Comment by PyvesB** [comment]
Hello @CielTheNemesis,

You can probably already achieve this by using WordGuard, see [this comment](https://github.com/PyvesB/AdvancedAchievements/issues/412#issuecomment-412651599) in another issue. 😉 

Cheers,

Pyves
