### ISSUE TITLE
Option to see all achievement categories in /aach stats

### ISSUE THREAD

**Issue by Leomelonseeds** [PyvesB/AdvancedAchievements#468]
I believe this command is a bit empty right now, just showing the percentage of achievements completed. It should be showing a list of all the things tracked and how many of it you have done. 

Example:
========Stats========
Playtime: 1h
Blocks Broken:
  - Stone: xxx
  - Brick: xxx
Snowballs thrown: xxx
etc...

I know this would probably be quite difficult because of different categories, but could you please try to implement this so my players won't go asking, "How do I check my playtime" or "How to see how many blocks I walked because the achievement menu says the achievement is already completed."

Thanks in advance :D

**Comment by PyvesB** [comment]
Hello @Leomelonseeds,

The _/aach stats_ gives you an overall summary of how many achievements you've received so far. The _/aach list_ command is intended to track detailed statistics and shows you progress for each category/subcategory. I don't think it's a good idea to overload the stats command with duplicate data from the list command. 😉 

Cheers,

Pyves

**Comment by Leomelonseeds** [comment]
Maybe let us configure what is shown in the stats command. Because looking everythibg up in the GUI is really a hassle.
