### ISSUE TITLE
File "config.yml" line 14

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#47]
> [23:33:25] [Server thread/ERROR]: [AdvancedAchievements] Error while loading configuration file, disabling plugin.
> [23:33:25] [Server thread/ERROR]: [AdvancedAchievements] Verify your syntax using the following logs and by visiting yaml-online-parser.appspot.com
> [23:33:25] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
> found character 	'\t' that cannot start any token
>  in "<string>", line 14, column 78:
>      ... bs for the Kills section_COLON_ 	  hub.spigotmc.org/javadocs/buk ... 
>                                          ^
> 
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
> [23:33:25] [Server thread/WARN]: 	at com.hm.achievement.utils.YamlManager.<init>(YamlManager.java:33)
> [23:33:25] [Server thread/WARN]: 	at com.hm.achievement.utils.FileManager.getNewConfig(FileManager.java:36)
> [23:33:25] [Server thread/WARN]: 	at com.hm.achievement.AdvancedAchievements.configurationLoad(AdvancedAchievements.java:362)
> [23:33:25] [Server thread/WARN]: 	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:166)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
> [23:33:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
> [23:33:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
> [23:33:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
> [23:33:25] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
> [23:33:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
> [23:33:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
> [23:33:25] [Server thread/WARN]: Caused by: while scanning for the next token
> found character 	'\t' that cannot start any token
>  in "<string>", line 14, column 78:
>      ... bs for the Kills section_COLON_ 	  hub.spigotmc.org/javadocs/buk ... 
>                                          ^
> 
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
> [23:33:25] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
> [23:33:25] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
> [23:33:25] [Server thread/WARN]: 	... 16 more

You have to constantly change the word "Kills" on the "Kill's".

**Comment by PyvesB** [comment]
Hello,

If I recall correctly, you are using a very old version of Minecraft? Please upgrade to at least Spigot 1.7.9 in order to have the minimal APIs required to run the plugin correctly.

Cheers,

Pyves

**Comment by LLIaMMaH** [comment]
https://prok.pw/downloads.html#pw.prok:KCauldron
1.7.10-1614.201	10.13.4.1614	March 20th 2016 07:49:51 PM
