### ISSUE TITLE
Crafting Achievements

### ISSUE THREAD

**Issue by osybear1** [PyvesB/AdvancedAchievements#472]
Running 1.13.2. Crafting achievements are not working. When crafting it does not notice that something is crafted.

**Comment by osybear1** [comment]
Looks like when adding a new crafting achievement and then reloading the config. The players that are connected must leave the server in order to be able to earn the achievement

**Comment by PyvesB** [comment]
Hello @osybear1,

I have just tried this out and I am not able to reproduce. Are you using the latest version of the plugin? When you say reloading the condif, is it through the _/aach reload_ command? Are there any errors or warnings in the console? What does your configuration file look like?

Cheers,

Pyves
