### ISSUE TITLE
Jenkins CI

### ISSUE THREAD

**Issue by sgdc3** [PyvesB/AdvancedAchievements#473]
Hello! I just added your project to my public Jenkins build server: https://ci.codemc.org/job/PyvesB/job/AdvancedAchievements/
It will also deploy artifacts to https://repo.codemc.org/repository/maven-public/
If you need to change the build steps you can login into jenkins using your github oauth credentials and customize them as you want ;)

**Comment by PyvesB** [comment]
Hello @sgdc3,

Thanks for your interest in the project! Note that @supertassu already added Travis CI integration in #385 and I've publish artifacts to this [branch](https://github.com/PyvesB/AdvancedAchievements/tree/mvn-repo) which hosts a small Maven repository. However, it doesn't hurt to have things mirrored in other places. 😉 

Cheers,

Pyves
