### ISSUE TITLE
Sub-categories.

### ISSUE THREAD

**Issue by iBazza** [PyvesB/AdvancedAchievements#475]
Hey, I was just wondering if there was any possibility to add sub-categories so when you go into a main category such as blocks placed, you could have different icons based on the achievements. 

For example, if you had a progressive block placing achievement of placing 100 stone blocks could you put that into a separate thing from all the other block placing achievements? 

Sorry if this isn't quite clear, if you don't understand let me know and I'll try to explain it more clearly. 

Thanks!

**Comment by PyvesB** [comment]
Hello @iBazza,

As mentioned in [this comment](https://github.com/PyvesB/AdvancedAchievements/issues/326#issuecomment-433692998), I do not intend on adding new layers of categorisation in the GUI. Please refer to #452 to view discussions on future GUI enhancements. 😉 

Cheers,

Pyves
