### ISSUE TITLE
EndStone

### ISSUE THREAD

**Issue by Atlantiis31** [PyvesB/AdvancedAchievements#476]
Hi,

I have a problem with the ID121 (end_stone)
The id "end_stone" dosent work in breaking block configuration.

Is it the good ID ?

**Comment by PyvesB** [comment]
Hello @Atlantiis31 ,

Which version of Minecraft are you running?

Cheers,

Pyves

**Comment by Atlantiis31** [comment]
> Hello @Atlantiis31 ,
> 
> Which version of Minecraft are you running?
> 
> Cheers,
> 
> Pyves

Hello, 

The server is on 1.12 version.

**Comment by Atlantiis31** [comment]
> Hello @Atlantiis31 ,
> 
> Which version of Minecraft are you running?
> 
> Cheers,
> 
> Pyves



> Hey!
> 
> The Bukkit material mapping for end stone is `ENDER_STORE` in 1.12.

ha, 

Thanks for your help !
Sorry for my error ^^

Have a good day ! ;)

**Comment by PyvesB** [comment]
Glad your problem is solved! I recommend referring to the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Material-names): the material names are documented on a per version basis. :wink:
