### ISSUE TITLE
Help with Wither Boss Achievement 

### ISSUE THREAD

**Issue by fatmanjumprope** [PyvesB/AdvancedAchievements#477]
I have an achievement set up for when a player kills the wither. This is what it looks like in the config.

  '&2Skeletal Knight':
    1:
      Message: You killed the Wither!
      DisplayName: Mythic Killer
      Name: kills_1_wither
      Reward:
        Command:
          Execute: cc give virtual galactic 1 %Player%

When the wither is killed however the achievement isn't rewarded. Does the wither needs to be both spawned and killed in survival mode for this to work or did I just overlook something? Thanks in advance!

**Comment by fatmanjumprope** [comment]
Thank you for the quick reply! I don't have MythicMobs installed so what I was trying to do was just completely change that achievement into just a basic one for killing the wither. I've tried using just Skeletal Knight as the name with no ' or & but after killing the wither it doesn't award the achievement as I have it.

**Comment by PyvesB** [comment]
I suggest looking at the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Entity-names) in that case. Give `wither` alone a try, it will hopefully work. ^^

**Comment by fatmanjumprope** [comment]
Changing the name from skeletal knight to just wither as you suggested fixed the problem! Thank you very much for your help.
