### ISSUE TITLE
Placeholder in Lang.yml don't work

### ISSUE THREAD

**Issue by BijuuKrunos** [PyvesB/AdvancedAchievements#478]
The Placeholders of the Plugin itself do not work in the lang.yml.

In game i just become the Placeholder but not what it should be.

PLAYER is in the game still PLAYER...

tested with lang-DE.yml and with lang.yml.

newest Version of aach on MC 1.13.2 with paperspigot.

Nothing in the console.

**Comment by PyvesB** [comment]
Hello @BijuuKrunos,

Not all fields in _lang.yml_ support the `PLAYER` placeholder. Which specific one are you having trouble with?

Cheers,

Pyves

**Comment by BijuuKrunos** [comment]
Just as I said. Its even in the default lang. I did not changed anything or used it on lines there it wasn't before xD. German lang as well. Nothing changed and the placeholder doesn't work. :)

Greetz,

Krunos

**Comment by PyvesB** [comment]
My above question still stands: which field is causing issues? About 8 of them support the `PLAYER` placeholder.

**Comment by BijuuKrunos** [comment]
Okey fail. now i tested it even more. and yeah it was my failure. for example:
achievement-given
in the default lang.yml: "Achievement given!"
in the lang-DE.yml: "Der Spieler PLAYER hat den Erfolg erhalten!"

the lang-DE.yml is not working xD sry. Just changed it for myself.

#closed
