### ISSUE TITLE
Umm?

### ISSUE THREAD

**Issue by InvertedTNT** [PyvesB/AdvancedAchievements#48]
Im not sure if this is on purpose but i have a brewing stand down in my config under the places section and whenever players placed obsidian they get the brewing stand achivements.

Plz help

**Comment by InvertedTNT** [comment]
The problem isn't the confusion with the brewing stand its that /aach reload doesn't work properly. It says [Config Reloaded] in chat but it doesn't actually reload the plugin.

**Comment by PyvesB** [comment]
Hello,

This is weird, the /aach reload command is supposed to work correctly. I will look into it. ;-)

**Comment by PyvesB** [comment]
Hello,

I have not been able to reproduce the bug, the /aach reload seems to work perfectly with the Places section. Make sure you have correctly saved the new config on your server and that you are using the latest version of the plugin. Also ensure that there aren't any errors logged in the console when reloading the plugin.

Without any further insight on your issue, I am closing this issue for now.

Cheers,

Pyves
