### ISSUE TITLE
Vanilla Advancements and Multiple Server

### ISSUE THREAD

**Issue by BijuuKrunos** [PyvesB/AdvancedAchievements#482]
I want to use this Plugin primary for having advancements synced over my Network. 
Spigot: 1.13.2
aach: 5.11.1

I created in the config command based achievements. and generated them on every server. All connected to the same database. Now I give me on the first Server the advancement /aach give root_abenteuer Krunos
I have this advancement on this server. but if I am going know to the next server i won't get the same advancement again (Not the reward just the Vanilla Advancement). I thought that this worked as I tested this Plugin months ago. But know It is not working. Please fix it, or if this never worked. Make this to a new Feature.

Greetz
Krunos

**Comment by PyvesB** [comment]
Hello @BijuuKrunos,

If you have the exact same achievements configured across multiple servers and you've run _/aach generate_ on the latest version of your configuration on every single server, the advancements should be awarded again when the user connects to a different server. 😉 

Cheers,

Pyves

**Comment by BijuuKrunos** [comment]
Okeydokey now I know what happens. I created my own versions of the advancements and after the generation command i replaced the files. With the /aach add and give commands everything worked fine. (I am using only the customs and command achievements). And I created 2 root advancements wich I imported in the plugin as regular command achievements. So with commands everything is supter. But i don't need the "advanced_achievements_parent" advancement so i deleted it. But yeah bad Idea. The Plugin needs this advancement for the synchronisation. 

Now it works again. I just renamed one of my root advancements to "advanced_achievements_parent.json". 

#closed

**Comment by PyvesB** [comment]
Makes sense, glad you solved your issue!
