### ISSUE TITLE
Add Achievement : GIVE A ITEM (TO PLUGIN) 

### ISSUE THREAD

**Issue by MisterFunny** [PyvesB/AdvancedAchievements#484]
I have need of Achievement that takes determined items

**Comment by PyvesB** [comment]
Hello @MisterFunny,

I'm unsure what you mean, could you please rephrase?

Cheers,

Pyves

**Comment by MisterFunny** [comment]
I'm sorry, I'm italian... I try to rephrase.
The "Challenge" of your plugin don't include the fact that takes the item from player to complete the "Challenge"

**Comment by PyvesB** [comment]
Do you mean a new achievement category in which players would have to give items to other ones?

**Comment by MisterFunny** [comment]
Yes, but the items they must be given to plugin.

A similar thing to "Challenge" of ASkyBlock plugin

**Comment by MisterFunny** [comment]
Ok, thanks.
An other question: Why on category Breaks iron_ore or wheat ecc. don't working?

**Comment by PyvesB** [comment]
Unsure what you mean by "don't working". Are statistics not increasing? Are the achievements not received? Are the rewards not awarded? Something else?

Assuming it's the statistics which aren't increasing. For wheat, if you're using a version of Minecraft prior to 1.13, you have to specify `crops` instead. For the ores, verify the `SilkTouch` configuration parameters. For votes, make sure you're executing the _/aach add_ command correctly.

**Comment by MisterFunny** [comment]
Thanks for response. 
For "don't working" I mean that statistics not increasing (I use the 1.12).
For vote is a default config
