### ISSUE TITLE
Quick question about advancement sounds

### ISSUE THREAD

**Issue by turtlshell** [PyvesB/AdvancedAchievements#487]
Hi there- I was wondering if it was possible to disable the advancement sound from aach achievements? I've reset my config and stuff and nothing's really working.

Thanks in advance!

**Comment by PyvesB** [comment]
Hello @turtlshell,

Could you please be more specific, which sound are you referring to?

Cheers,

Pyves

**Comment by PyvesB** [comment]
Any news @turtlshell ?
