### ISSUE TITLE
I can't make my complete own achievements

### ISSUE THREAD

**Issue by ZaptDev** [PyvesB/AdvancedAchievements#488]
Hello

What I want to do:
I wan't to make my own achievements without the ones that are already in.

My problem:
I can change the already existing ones but when I delete one or create a new one the changes won't work. I can delete all the pre made achievements but then the config gets pretty strange and when I add new ones they won't show up on the GUI or anywhere else in the game. 

My test subject worked when I used it to replace already existing ones (Reward got added) but the 2. one didn't show up bc I can't create new ones.

Deaths:
    1:
      Goal: If you die you will lose some Money.
      Message: You lost some Money!
      Name: deaths_1
      DisplayName: Rest In Peace
      Reward:
         Command: economy take PLAYER 100
    2:
      Goal: If you die you will lose some Money.
      Message: You lost some Money!
      Name: deaths_2
      DisplayName: Rest In Peace
      Reward:
         Command: economy take PLAYER 150

I did not use any tabs.

**Comment by ZaptDev** [comment]
I did write
Command: 
    Execute: economy take PLAYER 150

Idk why it deleted Execute in the post.

**Comment by PyvesB** [comment]
Hello @ZaptDev,

Did you accidentally delete any categories? They're automatically added to the `DisabledCategories` list if you do so.

Cheers,

Pyves

**Comment by ZaptDev** [comment]
Thanks for your fast response!

Yes I did, all of them xD
Everything works now. 

Thanks for your help!

I'm using your Plugin for my own small server where I plan to play with friends.
If you wish to see your plugin in action just hit me up. You seem like a nice guy and one more on the server won't hurt :D

**Comment by PyvesB** [comment]
Glad to hear that your problem was solved! Feel free to star this GitHub repository. 😉 

Thanks for the offer, but to be honest I rarely play Minecraft any more. ^^
