### ISSUE TITLE
AACH listed as disabled when enabled in console

### ISSUE THREAD

**Issue by Janilla** [PyvesB/AdvancedAchievements#489]
I'm not sure what's wrong- I checked the actual code on YAMLlint after I added some new achievements and it was fine. Essentially, the plugin is red when using /pl in game and I cannot use any of the commands. It is definitely enabled in the Multicraft settings. 

config:
[https://pastebin.com/zCVHEefJ](url)

console:
[https://pastebin.com/s6QxAcqH](url)

Thanks.

**Comment by PyvesB** [comment]
Hello @Janilla,

Please read the messages the plugin prints out at startup, they will indicate what the problem is. For instance, the achievement `kills_1_skeletal_night` is duplicated in your onfiguration. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Any luck with the configuration @Janilla ?

**Comment by Janilla** [comment]
Found the error- doubled up on a creeper killing achievement. Thank you for your help!

**Comment by PyvesB** [comment]
You're welcome!
