### ISSUE TITLE
27.05 07:04:22 [Server] ERROR [AdvancedAchievements] Errors while trying to display achievement screen title. Is your server up-to-date?

### ISSUE THREAD

**Issue by Ashrune** [PyvesB/AdvancedAchievements#49]
I run a 1.7 - 1.8 Spigot Minecraft Server and your plugin is meant to be 1.7 compatible. Please take a look:
`27.05 07:04:22 [Server] ERROR [AdvancedAchievements] Errors while trying to display achievement screen title. Is your server up-to-date?
27.05 07:04:22 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.EnumTitleAction
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
27.05 07:04:22 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
27.05 07:04:22 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
27.05 07:04:22 [Server] WARN at java.lang.Class.forName0(Native Method)
27.05 07:04:22 [Server] WARN at java.lang.Class.forName(Class.java:264)
27.05 07:04:22 [Server] WARN at com.hm.achievement.particle.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:415)
27.05 07:04:22 [Server] WARN at com.hm.achievement.particle.PacketSender.sendTitlePacket(PacketSender.java:94)
27.05 07:04:22 [Server] WARN at com.hm.achievement.AchievementDisplay.displayAchievement(AchievementDisplay.java:103)
27.05 07:04:22 [Server] WARN at com.hm.achievement.listener.AchieveKillListener.onEntityDeath(AchieveKillListener.java:63)
27.05 07:04:22 [Server] WARN at sun.reflect.GeneratedMethodAccessor740.invoke(Unknown Source)
27.05 07:04:22 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27.05 07:04:22 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
27.05 07:04:22 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
27.05 07:04:22 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:810)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.EntityMonster.damageEntity(EntityMonster.java:48)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49)
27.05 07:04:22 [Server] WARN at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)`

**Comment by PyvesB** [comment]
Hello,

Please set "TitleScreen" to false in the configuration file; this feature was not available in older versions of Minecraft. Have you got any other issues with Minecraft 1.7.9/1.7.10?

Cheers,

Pyves

**Comment by Ashrune** [comment]
Okay done. Thanks for that.

**Comment by PyvesB** [comment]
Great, issue closed! I might add some extra information in the config or provide a hack to automatically disable this option if older versions are detected.

Cheers, 

Pyves
