### ISSUE TITLE
Console Command After List of Achievements

### ISSUE THREAD

**Issue by justNikolai** [PyvesB/AdvancedAchievements#494]
Is it possible to make it so that after a player achieves a certain LIST of achievements a console will execute a command?  For example:

play 10 hours, 
break 1,000 stone blocks
place chest

Reward: console exectute command

**Comment by PyvesB** [comment]
Hello @justNikolai ,

Unfortunately, this is not currently possible. Issue #82 is closely related as it would allow you to define lists of achievements you would base other achievements and rewards on. Let's keep that issue opened! :wink: 

Cheers,

Pyves

**Comment by justNikolai** [comment]
simpleauthority went ahead and made a hook with LuckyPerms to do what I was
hoping for. Thanks for the awesome plugin!

**Comment by PyvesB** [comment]
Awesome, thanks for pointing that out! 😉
