### ISSUE TITLE
mySQL not working

### ISSUE THREAD

**Issue by Boochan1** [PyvesB/AdvancedAchievements#495]
Hi, 

I am having some issue using MySQL for database while running advanced achiemvnets.
I am getting this error when i restart the server with sql settings in config file 

[AdvancedAchievements] Initialising database...
[ERROR]: [AdvancedAchievements] Error while attempting to retrieve a connection to the database:
java.sql.SQLException: No suitable driver found for sql-us-east.testcraft.com?autoReconnect=true&useSSL=false&user=np2_432ffb32c33e&password=cb17essa1291b23f413f067a

Then it disables the plugin for when the server starts.

I changed the SQL details for the above example to hide my login details. could someone please help me

**Comment by Steeeeeeeeeve** [comment]
I'm getting the same issue

**Comment by Lord-Lofi** [comment]
https://github.com/Lord-Lofi/OHHHH-BAILYN/blob/master/config.yml

**Comment by PyvesB** [comment]
Hello there,

When you say

> I am getting this error when i restart the server

do you mean that the settings work fine when you first launch the server but then it breaks when you restart it, or does MySQL simply not work at all?

Cheers,

Pyves

**Comment by Lord-Lofi** [comment]
For me, it does not work when I launch the server. However when I left the config as default, it worked fine. It was only after adding in lots of more achievements that it stated the plugin is disabled in console after running a command such as /advancedachievements. I ran the edited config against the yaml parser you had recommended and it checked out fine. Thanks for your response and time!

**Comment by PyvesB** [comment]
@Lord-Lofi does the default configuration work when the only thing you change is switching the database type to MySQL?

**Comment by Lord-Lofi** [comment]
yes, it does. So I isolated the plugin on a tester server and I feel like a dumbo, when I read thru the disabling process of it, it was first reading an error in which I had labeled achievements with the same name. I copied them but forgot to edit the name to entity_eat_2 etc. on a few achievements. Sorry for wasting your time with this. My problem is fixed and it runs flawlessly. Not sure about boochan1's problem tho. Thank you for your time and willingness to help. I'll donate sometime this week! Great work on this plugin!

**Comment by PyvesB** [comment]
> yes, it does. So I isolated the plugin on a tester server and I feel like a dumbo, when I read thru the disabling process of it, it was first reading an error in which I had labeled achievements with the same name. I copied them but forgot to edit the name to entity_eat_2 etc. on a few achievements. Sorry for wasting your time with this. My problem is fixed and it runs flawlessly. Not sure about boochan1's problem tho. Thank you for your time and willingness to help. I'll donate sometime this week! Great work on this plugin!

Glad to hear that you solved your problem and thanks for your support!

**Comment by SamLam140330** [comment]
Hi everyone, I have the same problem too. I think my setting is correct but it generate some error.

[18:42:33] [Server thread/ERROR]: [AdvancedAchievements] Error while attempting to retrieve a connection to the database:
java.sql.SQLException: No suitable driver found for localhost:3306?autoReconnect=true&useSSL=false&user=SamLam140330&password=EYSWtaBbhNj4Ukz3

Does anyone know how to fix it?

**Comment by PyvesB** [comment]
Hello @SamLam140330 , what Minecraft version and server version are you using?

**Comment by SamLam140330** [comment]
@PyvesB Minecraft version 1.13.2 and latest api version

[19:35:33 INFO]: This server is running CraftBukkit version git-Spigot-5629554-4c8327f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by PyvesB** [comment]
Could you please share the _config.yml_ section related to the database setup?

**Comment by SamLam140330** [comment]
Sure, thanks for the help!

DatabaseBackup: true
DatabaseType: mysql
TablePrefix: ''
AdditionalConnectionOptions: ''
DatabaseAddress: localhost
DatabaseUser: SamLam140330
DatabasePassword: EYSWtaBbhNj4Ukz3

**Comment by PyvesB** [comment]
The `DatabaseAddress` parameter doesn't seem correct. Use something like `"jdbc:mysql://localhost:3306/minecraft"` by replacing `minecraft` with you database name. 😉

**Comment by SamLam140330** [comment]
It work after change the Database Address. Sorry about my parameter incorrect😓 Thank you for your supprot

**Comment by PyvesB** [comment]
You're welcome, glad it solved your problem! @Boochan1 your issue seems to have the exact same causeway therefore closing this issue. :wink:

**Comment by PyvesB** [comment]
Just pushed a small fix so that the plugin automatically deals with these kind of configuration mistakes in the future.
