### ISSUE TITLE
Setting a place achiement for bedrock and obsidian

### ISSUE THREAD

**Issue by Boochan1** [PyvesB/AdvancedAchievements#499]
I tried to setup an achievment for placing bedrock and obsidian.

The requirements were to place 1 bedrock. 
When i reloaded the plugin i was able to place a piece of bedrock and get the achievemnt
but no other players on the server could. I then op'd a player to test and he was able to get the
Achievment by placing the bedrock

I then tried the same thing with obsidian and replaced bedrcok with obsidian in the config file. 
The same thing occured, only OP players could get the achievment

I then changed the material to stone and every player was able to get the achievment. 

Could you please help wtih this? 

Also when i try to do items that have a underscore in the name like Lapis_Block
The achievment also cant be achieved when that is the only material. 

Please help thank you

**Comment by PyvesB** [comment]
Hello @Boochan1,

Have you set the permissions up correctly? What does your configuration file look like?

Cheers,

Pyves
