### ISSUE TITLE
[suggestion] Seniority in days

### ISSUE THREAD

**Issue by MrMaleficus** [PyvesB/AdvancedAchievements#5]
Hi,

This isn't an issue at all :) Your plugin is great and bugfree on my server !
But I have a suggestion of functionality that would be great : the seniority of players
This achievement is based on the length (in days) the player has joined the server for the first time.
I have no knowledge in java programmation so i can't do a pull request but in think it will be a great functionality .
I hope it will be implanted :+1: 

Sincerely,

**Comment by PyvesB** [comment]
Hello,

If I have understood your request well, this feature is already implemented. Indeed, the Connections category in the configuration file seems to correspond to what you are looking for, "When a player connects during the day.". This parameter increases by one each connection day, and could be used to monitor the seniority of players as you have requested. ;-)
