### ISSUE TITLE
Disable plugin for individual players

### ISSUE THREAD

**Issue by Lord-Lofi** [PyvesB/AdvancedAchievements#500]
Is there a way to disable the plugin for individual players? or disable the notifications to individual players in every way without disabling the notifications for others?

**Comment by PyvesB** [comment]
Hey there,

If you just want to disable notifications, the _/aach toggle_ command may be of help here. The users can choose to disable all notifications from other players, or enable them if you have set `ChatNotify` to `false` in your configuration.

To fine-tune whether statistics should increase for individual achievement categories, you've also got a comprehensive set of [user permissions](https://github.com/PyvesB/AdvancedAchievements/blob/74a985929ceab1413c43e8117bcad22284919928/advanced-achievements-plugin/src/main/resources/plugin.yml#L15). 😉 

Cheers,

Pyves
