### ISSUE TITLE
1.13 command blocks

### ISSUE THREAD

**Issue by MrWonka** [PyvesB/AdvancedAchievements#502]
Using command blocks no longer recognizes calls such as @a or @p. Instead it says "The player @a is offline!"

**Comment by PyvesB** [comment]
Hello @MrWonka,

I have pretty much never used command blocks, I'm probably not going to be of much help here. The plugin hasn't changed any of its reward behaviour for many months (years?), it simply dispatches the commands to the server without any modification. Therefore, my guess is that it's a problem with the server or a change in how command blocks work in recent versions of Minecraft.

Cheers,

Pyves

**Comment by MrWonka** [comment]
Using sign commands fixes the issue.
