### ISSUE TITLE
How to change font??

### ISSUE THREAD

**Issue by mitsui2k** [PyvesB/AdvancedAchievements#506]
When u havent completed the achievement its have like a different font as the normal one... 
The font i want is when u have completed
![image](https://user-images.githubusercontent.com/35619913/55534411-c1e50c80-568a-11e9-83e5-3df673fb2b4f.png)
![image](https://user-images.githubusercontent.com/35619913/55534450-d9bc9080-568a-11e9-9bf3-95da0bc841fa.png)

How to change the font? I want the font of the first picture, no matter if the achievement is completed or not..
Thanks!

**Comment by PyvesB** [comment]
Hello @mitsui2k,

As per the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)#8-why-are-achievement-descriptions-greyed-out-in-the-aach-list-gui), achievements that have not yet been received have a special styling. You can only change the color through the `ListColorNotReceived` configuration parameter. 😉 

Cheers,

Pyves

**Comment by mitsui2k** [comment]
Where is that? Dont tell me i have to know java to modify that? meu deus

**Comment by mitsui2k** [comment]
This is plugin lack of basic configuration, i dont why...

**Comment by PyvesB** [comment]
> Where is that? Dont tell me i have to know java to modify that? 

Not sure what you mean by "that", but if you're referring to the configuration parameter I was describing in my previous message, well it's in [config.yml](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml).

> meu deus
> This is plugin lack of basic configuration, i dont why...

These sentences makes little sense to me, but I'm guessing they aren't very constructive. This is an open-source project that you're using for free, if you want to make a suggestion, please do it in a friendly and clear way. 😉
