### ISSUE TITLE
Placeholder idea

### ISSUE THREAD

**Issue by mitsui2k** [PyvesB/AdvancedAchievements#507]
Hello, thankss for the plugin is awesome... However, u should create some own placeholder in order to use for a menu, or, to those who want to customize the menu to their own personal preference, like, building up with a menu

**Comment by PyvesB** [comment]
Hello @mitsui2k,

I'm not really sure what you mean. Advanced Achievements has extensive placeholder support through the PlaceholderAPI plugin. See the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Placeholders) for more information. There is also a placeholder available with BungeeTabListPlus. 😉 

Cheers,

Pyves

**Comment by mitsui2k** [comment]
I mean, to change the item for every achievements and more, like building a custom menu with deluxe menu... There is no placeholder of this plugin to use with deluxemenu to show up the bar and progression etc

**Comment by PyvesB** [comment]
I'm unsure what "deluxemenu" is or what you mean by "bar and progression". I saw you complaining in other places that you can't customise "how the menu looks", therefore I suggest taking a closer looked at the configuration files and reading the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki). There's an extensive [configuration file](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/gui.yml) to customise the menus, plus several other parameters in the [main configuration file](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml) to tweak their behaviour.
