### ISSUE TITLE
Moving/combining categories

### ISSUE THREAD

**Issue by Riddleart** [PyvesB/AdvancedAchievements#509]
Hey, I love this plugin and sorry if this is a silly question but, how can I for example move all of the distance categories (distance by foot, boat, minecart etc) into one single category called "Distance" that has all those achievements listed?

Thanks!

**Comment by PyvesB** [comment]
Hello @Riddleart,

Unfortunately, this is not currently possible. There is a similar issue opened about "combining" achievements, #82, but nothing has yet been implemented in Advanced Achievements itself.

Cheers,

Pyves

**Comment by Riddleart** [comment]
Ahh that's a shame. Hopefully it will be implemented at somepoint :)

One other question: 

With smelting or potion brewing can I set it to pick up on certain items being smelted/brewed instead of the overall amount? Such as instead of it registering that 100 items have been smelted, it can specifically see that 100 iron ore has been smelted. (and if possible what would the line for that be?)

**Comment by PyvesB** [comment]
That's not possible either, see  #56 where this was suggested as well. 😉
