### ISSUE TITLE
Using Silk Touch to easily get achievement

### ISSUE THREAD

**Issue by imyvm** [PyvesB/AdvancedAchievements#51]
1. Using a Pickaxe with Silk Touch to mining ore
2. Place the ore which you just mined.
3. Mining it again.

Then players will easily get the achievement below.

```
When a specific block is broken (specify material name, lower case).
# Below, the notation log:1 means log item with metadata 1.
Breaks:
  emerald_ore:
    '10':
      Message: 'example'
      Name: '&a example &fLv1'
```

**Comment by Platinteufel** [comment]
Maybe you could check if the players pickaxe contains the silk_touch enchantment and if so the block break for ores doesn't count? But I'm not sure if there's an easy fix for this.

**Comment by PyvesB** [comment]
Hello,

I am aware of this; nevertheless, the plugin just genuinely does its job, it *counts* the number of times your mine the ore. I would have to add some extra functionality to cope with these types of players' behaviours, but I don't think it could be done in an easy way. I'll keep the issue opened as a reminder to give it some thought. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

A new configuration option will be available in version 3.0, which will enable to not increase statistics if blocks are broken with a silk touch enchantment. 

Cheers,

Pyves

**Comment by unholymac** [comment]
how do you enable this?

**Comment by PyvesB** [comment]
Check out the `DisableSilkTouchBreaks` and `DisableSilkTouchOreBreaks` parameters in _config.yml_. 😉
