### ISSUE TITLE
Rockets with Elytra

### ISSUE THREAD

**Issue by Arkobat** [PyvesB/AdvancedAchievements#514]
Minecraft version: Paper 1.12.2
Aach version: 5.11.2

Problem:
Rockets firing does not count when using with an elytra

**Comment by PyvesB** [comment]
Hello @Arkobat,

Good spot, I didn't know you could launch fireworks whilst gliding! However, there is probably also a bug with Spigot here: the `PlayerInteractEvent` is fired as cancelled, but there is clearly a valid interaction which causes the firework to be launched. I have opened a bug report [here](https://hub.spigotmc.org/jira/browse/SPIGOT-4793). 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
The response I got from the Spigot team was not very helpful and the commit that was pushed to the Bukkit API made the documentation even more confusing/less accurate in my opinion. However, I've just committed a workaround in Advanced Achievements directly, it will hopefully solve the fireworks issue. 😉
