### ISSUE TITLE
Nametag plugin integration

### ISSUE THREAD

**Issue by Lord-Lofi** [PyvesB/AdvancedAchievements#515]

**Comment by Lord-Lofi** [comment]
I was wondering if there was a way to integrate this with the nametag plugin so that a player is able to choose an achievements displayname to be a nametag (ie a tag that goes before someone's name in game)

**Comment by Lord-Lofi** [comment]
Thinking about it I could probs have it run a command through execute using luckyperms. The only tricky part would be creating some sort of menu that would allow them to select the nametag.

**Comment by PyvesB** [comment]
Hello @Lord-Lofi,

To be honest, I'm not very familiar with how nametags work. As far as doing something with LuckPerms is concerned, [this third-party plugin](https://www.spigotmc.org/resources/add-group-on-achievement-advanced-achievements-luck-perms-hook.65668/) may be of interest. 😉 

Cheers,

Pyves
