### ISSUE TITLE
Can one also specify minutes at the time?

### ISSUE THREAD

**Issue by TheDarkCookiee** [PyvesB/AdvancedAchievements#516]
Is it also possible that you can specify minutes at the game time and not just hours?

**Comment by PyvesB** [comment]
Hello @TheDarkCookiee,

Currently only hours are supported. The thresholds could be changed to minutes, but that would affect all existing users who would have to update their configuration, so I'm reluctant to doing that. `PlayedTime` is an approximation anyway (the precision depending on the value of `PlaytimeTaskInterval` in the configuration), therefore I don't think we should make the thresholds too granular. 😉 

Cheers,

Pyves
