### ISSUE TITLE
(Suggestion) Add compatibility for QuestCreator

### ISSUE THREAD

**Issue by johnsoncui02** [PyvesB/AdvancedAchievements#517]
Hi, I would like this plugin to be able to detect the quests completed for specific quests and players gain some type of achievements doing that. If you could add the plugin into the list that would be great!

QuestCreator:
https://www.spigotmc.org/resources/questcreator-now-with-client-side-npcs-and-quest-pools.38734/

**Comment by PyvesB** [comment]
Hello @johnsoncui02,

I'm not willing to implement this myself, especially as it's a paid plugin I do not own. But do feel free to contribute or get someone you know to do so. Interestingly, QuestCreator does seem to be integrated with Placeholder API, therefore if #365 was landed, support would be automatic. 😉 

Cheers,

Pyves

**Comment by johnsoncui02** [comment]
Thanks for your replies!
