### ISSUE TITLE
Idea: Achievement for visiting a location/landmark

### ISSUE THREAD

**Issue by Dystify** [PyvesB/AdvancedAchievements#518]
Heya,
I've been thinking for a while that it'd be really cool if there was the possibility to give an achievement when a user visits specific locations. For example a landmark somewhere, or for finding a hidden area, or for finishing a special adventure map. Right now one can give out achievements manually, but it would be cool if this could happen automated, for example when a user clicks a sign or a specific block at a specified location.

Thank you in advance.

**Comment by PyvesB** [comment]
Hello @Dystify,

You can probably already set this up quite easily: simply run an `/aach give` command when a user enters a specific region or location, for instance using the World Guard plugin. 😉 

Cheers,

Pyves

**Comment by Dystify** [comment]
Hello,

I tried this with WorldGuard and the WorldGuard Extra Flags plugin.

The command was:
/rg flag TestRegion console-command-on-entry /aach give Test %username%, effect give %username% minecraft:speed 999 2

However, it does not give the achievement, while it does give the speed boost. 
Error I get: The specified achievement was not found in Commands category. Did you mean Test?

This is strange, because the achievement called Test definitely exists. I do not have this issue with other commands. Thanks in advance.

**Comment by PyvesB** [comment]
Could I please see your Advanced Achievements configuration for the Commands category?

**Comment by Dystify** [comment]
I tested the achievement in-game and here with both upper and lower caps. Not sure if it matters.

> # A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
> # yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
> Commands:
>   yourAch1:
>     Message: You took part in the special event!
>     Name: yourAch1
>     DisplayName: Special Event Achievement!
>   yourAch2:
>     Message: You took part in the special event!
>     Name: yourAch2
>     DisplayName: Special Event Achievement!
>   test:
>     Message: Testing
>     Name: test
>     DisplayName: Test Achievement!

**Comment by PyvesB** [comment]
Well, it should be `test` in lower-case based on the above configuration. I'm quite surprised the error message suggest `Did you mean Test?`. What happens if you put `/aach give yourAch1` instead?

**Comment by Dystify** [comment]
I have tested more and it does not seem to work with WorldGuard regions, but it does work with command signs and NPCs, so I will be using those instead. Thanks a lot for the help!
