### ISSUE TITLE
New wood sorts aren't be counted for Item-Breaks -> Wood

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#52]
For the "Item-Breaks -> Wood" achievement only blocks with id 17:\* be counted. The new wood sorts, 162:\* (Acacia Wood & Dark Oak Wood), don't count. Seems like this is because the "old" sorts are `minecraft:log` and the new sorts `minecraft:log2` .. but that's a bit confusing for my players. Is there anything that I can do?

**Comment by PyvesB** [comment]
Hello,

Unfortunately, I don't think there is anything you can do, maybe give the achievements names in the plugin, such as "New Wood", "Wood Family 1", or so. Mojang just decided to name and deal with the wood types by using two different categories. I guess we're pretty much powerless when it comes to their choices for the API.

Cheers,

Pyves

**Comment by Platinteufel** [comment]
It would be an easy solution if you could combine ids that are counting for the same achievement, like "break wood -> new wood, old wood", "break ores -> diamond, emerald, ..."

**Comment by PyvesB** [comment]
Closed as #92 is more general.
