### ISSUE TITLE
[Feature Request] Arrow hits category

### ISSUE THREAD

**Issue by Leomelonseeds** [PyvesB/AdvancedAchievements#520]
Hey there!

I think a good idea would be to add an "arrows hit" category. This category would replace the "arrows" category as players would actually have to shoot entities in order to count towards the achievement.

Thanks for reading!

**Comment by PyvesB** [comment]
Hello @Leomelonseeds,

Not all users would be happy if we were to replace the existing arrows category. Maybe we could have something along the lines of  `ProjectileTargets`, which would encompass any type of projectile (eggs, snowballs, arrows, fish hooks, etc.), but count for specific targeted entities. What do you think?

Cheers,

Pyves

**Comment by Leomelonseeds** [comment]
I was thinking of an achievement along the lines of "Hawkeye" where you would have to hit an entity from a certain amount of blocks away, But ProjectileTargets would be cool :D

**Comment by PyvesB** [comment]
The issue with a category such as the "Hawkeye" one you described is that there isn't really anything you can progress towards. Server owners will set achievements for 10, 20, 30, etc. meters away, but if a player does a long shot on first attempt, he might unlock all achievements in one go, which isn't a great player experience.

I've implemented the other category we discussed, I called it  `TargetsShot` in the end. You can give it a try with the following test version:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3149059/AdvancedAchievements.zip)

In addition to entities, you can also set blocks as targets:
````
TargetsShot:
  villager:
    10:
      Goal: Throw things at villagers.
      Message: You lapidated villagers 10 times.
      Name: targetsshot_10_villager
      DisplayName: The Stoner
  glass:
    100:
      Goal: Try to break granny's windows.
      Message: You shot 100 projectiles at glass blocks!
      Name: targetsshot_100_glass
      DisplayName: Window Breaker
````

Note that this category will only work on Minecraft 1.11 or more recent versions of the game. 😉
