### ISSUE TITLE
[Support] How to show available achievements to players?

### ISSUE THREAD

**Issue by mrfloris** [PyvesB/AdvancedAchievements#523]
Maybe I am missing something, but could you perhaps explain how I can disclose to players which achievements, or even ach- categories are available to them?

**Comment by PyvesB** [comment]
Hello @mrfloris,

Available categories and achievements are available via the `/aach list` command. You've got a number of configuration options to customise the display, such as `ObfuscateNotReceived`, `HideNotReceivedCategories`, etc. 😉 

Cheers,

Pyves
