### ISSUE TITLE
Cannot read database, plugin disabled.

### ISSUE THREAD

**Issue by Leomelonseeds** [PyvesB/AdvancedAchievements#525]
Hello there!

Recently, I have been getting a strange error upon server start, with the plugin disabling itself. It seems like the database file is too large?

The paste is here: https://pastebin.com/pYVQhhmr

I've never gotten this error before, so I do not know what to do to fix it. Any suggestions?

Thanks for your help.

**Comment by PyvesB** [comment]
Hello @Leomelonseeds,

The database file is probably corrupted. Did your server suddenly crash or something similar? Another user of the H2 database has reported a similar problem [here](https://github.com/h2database/h2database/issues/541). This seems to have been fixed [here](https://github.com/h2database/h2database/pull/1812), however there isn't yet a new release containing the patch.

I suggest simply restoring your latest database backup. Alternatively H2 provide a recovery tool, I guess you could give it a try.

Cheers,

Pyves

**Comment by Leomelonseeds** [comment]
Hey there! How would I restore the latest backup?

**Comment by PyvesB** [comment]
Simply copy over the AdvancedAchievements plugin folder and replace the files.

**Comment by Leomelonseeds** [comment]
It appears that I do not have a backup of the database. Which version of h2 does this plugin use? It would be helpful to know in order to use the recovery tool.

**Comment by PyvesB** [comment]
It seems quite careless not to have any backups of your server. If there's a disk failure, if someone hacks it, if data gets corrupted or if there's any other hiccup, you'll pretty much lose your entire server and have to start again from scratch. 😕 

Is there no _.bak_ file in the AdvancedAchievements folder either? You could just try swapping that one around with the main database file.

The H2 version used in Advanced Achievements is the latest, 1.4.199.

**Comment by Leomelonseeds** [comment]
Hey! I do have server backups, but unfortunately they were all too recent and all contained the database corruption. I will try to use the repair tool to repair the database.

As for the .bak files, only the config files were backed up. The database file wasn’t for some unknown reason.

**Comment by Leomelonseeds** [comment]
I ended up resetting the database, because the repair tool couldn't fix it either. Not much data was lost anyways. Thanks for helping!
