### ISSUE TITLE
Achievements not Showing and Error in console (Spigot 1.8.8 and Aach 5.12.0)

### ISSUE THREAD

**Issue by Tanguygab** [PyvesB/AdvancedAchievements#526]
Hello ! I've got an error with AdvancedAchievements...
When I get an Achievement, it doesn't show it (titles) and It give me an error in the console

https://hastebin.com/oxurugisoy.makefile Config
https://hastebin.com/fehocupula.md Error (if you need log tell me)

**Comment by PyvesB** [comment]
Hello @Tanguygab,

You're missing the `Message` parameters in some of the achievements you've defined. 😉 

Cheers,

Pyves

**Comment by Tanguygab** [comment]
Ah thanks ! x)
