### ISSUE TITLE
Updating Hooks and current maven info

### ISSUE THREAD

**Issue by Ironic8b498** [PyvesB/AdvancedAchievements#527]
I can't seem to find Maven info on the latest version AdvancedAchievements-5.11.2

and need to update this

    public boolean hasAchievement(UUID uuid, String achievementName) {
        return !this.isAvailable() ? false : this.advancedAchievements.getDatabaseManager().hasPlayerAchievement(uuid, achievementName);
    }

    public int getNumberOfAchievements(UUID uuid) {
        return !this.isAvailable() ? -1 : this.advancedAchievements.getDatabaseManager().getPlayerAchievementsAmount(uuid);
    }

**Comment by PyvesB** [comment]
Hello @Ironic8b498,

Have you had a look at the [developer documentation](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#api)?

Cheers,

Pyves

**Comment by Ironic8b498** [comment]
no I'm kinda new to dev and must of missed the link
Thanks

**Comment by PyvesB** [comment]
No worries! Let me know if you need any help. :wink:

**Comment by Ironic8b498** [comment]
still couldn't get maven info to work for 5.11.2, and if I use the jar I have above two lines with errors.

**Comment by PyvesB** [comment]
There is no API "5.11.2". The API is versioned separately, you simply have to add the following to your _pom.xml_ for Maven to pick things up:
```
<repository>
  <id>advanced-achievements-repo</id>
  <url>https://raw.github.com/PyvesB/AdvancedAchievements/mvn-repo/</url>
</repository>
<dependency>
  <groupId>com.hm.achievement</groupId>
  <artifactId>advanced-achievements-api</artifactId>
  <version>1.2.0</version>
  <scope>provided</scope>
</dependency>
```
