### ISSUE TITLE
Everything lost and reset on leave and join

### ISSUE THREAD

**Issue by vass88** [PyvesB/AdvancedAchievements#528]
Hi, 1.13.2 with the extra file run to fix name changes has been run.
Everyone on server is getting the welcome for first time message on rejoining and have lost their achievements, the leaderboard has no memory of those not logged in.

**Comment by vass88** [comment]
Edit,  we think it's after the daily server restart now but not sure

**Comment by PyvesB** [comment]
Hello @vass88,

Please refer to #467, this is probably another case of database misconfiguration. 😉 

Cheers,

Pyves
