### ISSUE TITLE
MySQL database issue

### ISSUE THREAD

**Issue by Daxxas** [PyvesB/AdvancedAchievements#534]
Hello,
I posted this on the spigot discussion but you don't look very active on it, so I'm posting this here hoping having support D:

AdvancedAchievements throws this error when it boots : https://hastebin.com/ukedipayub.css
and I don't know what's the problem, here's my config : https://hastebin.com/hufecugopi.bash

I looked into the MySQL and there are tables with aach_ prefix

what can I do ?

PS : French is my first language if you want to use french

**Comment by PyvesB** [comment]
Hello @Daxxas,

This is probably an issue with your MySQL setup. Another user was having similar issues a while back in #471, maybe you can try what he did there?

Cheers,

Pyves

**Comment by Daxxas** [comment]
latin1 doesn't support accent.
I had a previous database with the same settings previously that worked fine with aach, but it was on a previous version of aach, did you changed something on your side maybe ?

**Comment by Daxxas** [comment]
I just checked the old config, and there some minor changes the main one being `AdditionalConnectionOptions: "&useUnicode=yes&characterEncoding=UTF-8"`
I put the one in commentary to test but it didn't worked too.

I'm using MySQL with other plugins and I'm not having issues with MySQL at all with them. I don't see why it would be because of our MySQL setup since the problem is occuring only with aach :(

**Comment by PyvesB** [comment]
Do you know in which precise plugin version things stopped working? It would really help a lot with debugging the issue.

**Comment by Daxxas** [comment]
It worked well in 2.5.3 (according to the config.yml's commentary)
I don't know in which version exactly it stopped working, but I can say that in 2.5.3 it worked well

The database config part looked like that `
#  Make a daily backup of your local database (if sqlite).
DatabaseBackup: false

#  Database type, sqlite or mysql.
DatabaseType: mysql

#  Settings to link with MySQL database (ignore if sqlite).
MYSQL:
  Database: jdbc:mysql://192.168.20.206:3306/minecraft
  User: minecraft
  Password: XXXXXX`

**Comment by Daxxas** [comment]
Any news on this @PyvesB ? :(

**Comment by PyvesB** [comment]
Well, you haven't really answered my question above, saying " it worked 70 releases back over 3 years ago" doesn't help much. Yes, that's how antique 2.5.3 is. I suggest trying out different plugin versions between 2.5.3 and 5.12.1; by using a binary-style search, you should pinpoint the faulty version pretty quickly. 😉

**Comment by Daxxas** [comment]
Ok! You should have told me this earlier haha, I didn't realized how old 2.5.3 is :x

**Comment by Daxxas** [comment]
Alright ! The last version that loads up properly is the 5.7.0, every version above doesn't load when the config is set up to have a mysql database.
Here is the changelog of the 5.7.1 : https://www.spigotmc.org/resources/advanced-achievements.6239/update?update=217117
To test this I always deleted both the config folder & the plugin .jar to test a new version, I load the server to generate the config file, shut it down, change the config to set up the mysql, boot it up again and see if it loads. Every version above 5.7.0 doesn't work. Here is an error I can have : https://pastebin.com/6ddBVrEj (I didn't saved all of them for every version)

And here is the config I used : https://pastebin.com/dvCXm00X
(I guess using the '' instead of "" doesn't matter ? Since it worked in 5.7.0 with '' instead of "")
Please keep me up to date for this :) !

**Comment by PyvesB** [comment]
Shall we double-check things to make sure we're on the right path? Let's forget about version 5.7.0, as it was bogus anyway. Could you please try with both 5.6.5 and 5.7.1 by deleting both the config folder as you've been doing, but also resetting the MySQL database each time? Like that we can make sure that it's indeed a change between version 5.6.5 and 5.7.1 that started causing this issue on your side.

**Comment by Daxxas** [comment]
So with a clean MySQL, in 5.6.5, and this config : https://pastebin.com/SR4mwmyN
The plugin couldn't enable itself... Removing every table of the MySQL is very long to do, please tell me if you still need me to do the same for 5.7.1 since 5.6.5 doesn't work

**Comment by Daxxas** [comment]
I tested in 5.7.1 with a clean MySQL & clean config, and it works. Then I tried to upgrade directly to 5.12.1 but it didn't worked (as expected).
So then I tested 5.8.2 with clean DB & clean config, and it worked too.
For 5.9.3 in the same conditions, it worked too.
For 5.10.1, same conditions, I had no problems with it.
Then I tested 5.11.2, same conditions, BUT this time it didn't worked, I looked at the changelogs of those versions, https://www.spigotmc.org/resources/advanced-achievements.6239/update?update=253487
https://www.spigotmc.org/resources/advanced-achievements.6239/update?update=271249
and this may be why ?
Here the config I had : https://pastebin.com/rqn5G4bd
and here is the error I got : https://pastebin.com/C8wrUV5W
@PyvesB

**Comment by PyvesB** [comment]
I suspect that 5.10.2 is the first version that didn't work - though it would be nice if you could confirm that. 
What version of MySQL are you using?

**Comment by Daxxas** [comment]
The MySQL version is 5.5.50 and I confirm I do have the error with 5.10.2

**Comment by PyvesB** [comment]
Does this test version work?
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3317958/AdvancedAchievements.zip)

(as usual, fresh database and install please! 😁)

**Comment by Daxxas** [comment]
Yes it works :)

**Comment by PyvesB** [comment]
So basically, when using UTF-8, there's a limit of 191 bytes for the size of the sub-category names on old versions of MySQL. The current value selected by the plugin was 192, so I reduced it by one to work around this limitation. However, this should no longer be an issue in more recent versions of MySQL (5.7+, 8.0+), I also recommend upgrading your 3+ years old MySQL installation at some point. 😉
