### ISSUE TITLE
Custom at the bottom of Config File

### ISSUE THREAD

**Issue by JMCY26** [PyvesB/AdvancedAchievements#535]
At the bottom of the Config file I can get custom achievements to show up in-game:

Custom:
  carrot:
    '1':
      Goal: TEST
      Message: 1
      Name: break_1_carrot
      DisplayName: §aCarrot!

But how do I define this custom achievement to be considered a Break, Place, Kill etc?

**Comment by PyvesB** [comment]
Hello @JMCY26,

The `Custom` category works with the `/aach add` command. The above achievement will only be received if you run `/aach add 1 carrot PLAYER`. 😉 

Cheers,

Pyves

**Comment by JMCY26** [comment]
Would it be possible in future to allow within custom achievements listed how they are obtained? 
Carrot: 
'1' 
Style: break
GOAL: TEST 

As an example? I know it's not that simple but I wanted to make a farming category that uses breaking blocks. But breaking blocks already has a category and I don't want to have it all in one. 

Regards

**Comment by PyvesB** [comment]
Closing in favour of #536.
