### ISSUE TITLE
Reward based on achievements received.

### ISSUE THREAD

**Issue by iFreezey** [PyvesB/AdvancedAchievements#537]
Hey!

I'm sure you've been asked this before but is it possible to reward a player based on how many achievements one has completed? For example, if the player have completed 5/50 achievements the player will recieve a reward and another reward at 10/50 etc...

If this is not possible, is this something that might be added if possible to do?

Thanks for your time!

**Comment by PyvesB** [comment]
Hello @iFreezey,

It's currently only possible to give an extra reward when all achievements are received. There were discussions aabout making things more flexible in #340, however, the work has not progressed since.

Cheers,

Pyves
