### ISSUE TITLE
Advancements Map

### ISSUE THREAD

**Issue by lukaskabc** [PyvesB/AdvancedAchievements#538]
Hi,
Advanced achievments is amazing plugin, but I have question (or idea for update)...
Is it possible to generate advancement map from advanced achievements?

advancement map = in game > esc > advancements (sorry if it has some other name :D )

**Comment by PyvesB** [comment]
Hello @lukaskabc,

Generating AdvancedAchievements-based advancements is possible using the _/aach generate_ command. Please refer to the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Commands-and-permissions#commands) for more information. 😉 

Cheers,

Pyves
