### ISSUE TITLE
Configurable GUI Items

### ISSUE THREAD

**Issue by i9hdkill** [PyvesB/AdvancedAchievements#54]
hi,
right now the gui items are hardcoded, we aren't able for example to change the "deaths" icon to a flower.
A config option like this would be helpful:
list-connections: "grass"
list-places: "dirt"

**Comment by PyvesB** [comment]
Hello,

Thanks for the suggestion, I might include its when the new GUI is finished; neverthelees, 36 new options in the config is quite a lot, and I would have to add support for metadata, standard item names is not enough, so it may be messy. ;-)

Cheers,

Pyves
