### ISSUE TITLE
My players can't see some categories in their /aach list

### ISSUE THREAD

**Issue by Daxxas** [PyvesB/AdvancedAchievements#543]
So here is how my /aach list looks : 
https://i.imgur.com/qZK1Cvf.png

And here's how their /aach list looks : 
https://i.imgur.com/MOFMfux.png

I noticed that every categories with things like `dirt|grass|podzol|mycelium` doesn't display for them
I don't understand, they still do gets the achievements, they only can't see it here

**Comment by PyvesB** [comment]
Hello @Daxxas,

That's odd. Have you specified any special achievement permissions for your players, or is everything set as default?

Cheers,

Pyves

**Comment by Daxxas** [comment]
I changed nothing, I only tried to give a permission to count to true to some categories to test if it was because of that, but everything is set as default.

**Comment by PyvesB** [comment]
By the way is this still happen using the latest version of the plugin (or the test version I shared the other day)?

**Comment by Daxxas** [comment]
I use the test version you shared :)

**Comment by PyvesB** [comment]
I'm unable to reproduce. Could you please share your full configuration file?

**Comment by Daxxas** [comment]
Here it is : https://pastebin.com/iGA8Y28i

**Comment by PyvesB** [comment]
Does this version look any better?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3336604/AdvancedAchievements.zip)

**Comment by Daxxas** [comment]
Yes it works now !
