### ISSUE TITLE
 font size

### ISSUE THREAD

**Issue by llronaldoll** [PyvesB/AdvancedAchievements#544]
is there any way to change the font size shown in DisplayName? because I'm having problem where the message does not fit the screen

or who knows how to write in 2 lines

**Comment by PyvesB** [comment]
Hello @llronaldoll,

Fonts are managed by Minecraft directly, you can only modify them statically via a resource pack. I don't believe it's possible to break titles lines either from within a plugin. 😉 

Cheers,

Pyves
