### ISSUE TITLE
Add Pet Support for MyPet

### ISSUE THREAD

**Issue by HansscMe** [PyvesB/AdvancedAchievements#545]
Hello,everyone

This plugin is pretty great.I have a new idea about pet.
There are many people using MyPet Plugin.
Could you please add pet support for MyPet?(just like PetMaster)

[https://www.spigotmc.org/resources/mypet-premium.17566/]

Thank you!

**Comment by PyvesB** [comment]
Hello @HansscMe,

Would you want to contribute this change or do you know someone who will?

Cheers,

Pyves
