### ISSUE TITLE
Unable to parse JSON message. Got null

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#549]
Paper dev 123 (Spigot 1.14.3)
AdvancedAchievements dev 53

Config
https://paste.ubuntu.com/p/9KqvNKpVsj/

```
[00:22:03] [Server thread/INFO]: [AdvancedAchievements] Player UnknownEvil received the achievement: craft_1_diamond_sword (Advanced Weaponry)
[00:22:03] [Server thread/INFO]: Unable to parse JSON message. Got null
[00:23:39] [Server thread/INFO]: [AdvancedAchievements] Player UnknownEvil received the achievement: anvilsused_1 (First Repair)
[00:23:39] [Server thread/INFO]: Unable to parse JSON message. Got null
```

**Comment by PyvesB** [comment]
Hello @mibby,

Do you happen to be using the [Remain library](https://github.com/kangarko/Remain) or have a plugin that uses that library? The issue seems to be coming from there, not Advanced Achievements.

Cheers,

Pyves

**Comment by mibby** [comment]
I do use ChatControlPro & Boss from @kangarko.

**Comment by PyvesB** [comment]
Probably something to flag up with him then. 😉

**Comment by kangarko** [comment]
Hey,

in ChatControl we send Toast notifications using the advancement system to show "the bubble" on the top right corner of the screen. The advancement is then quickly erased.

Not really sure what to do, maybe you can get the namedspaced key and ignore if it is coming from ChatControl?

Full source: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/Remain.java#L1859

**Comment by PyvesB** [comment]
> you can get the namedspaced key and ignore if it is coming from ChatControl

@kangarko Advanced Achievements is not listening to any advancements emitted by ChatControl. Advanced Achievements itself is emitting well-formed advancements, but ChatContol/something else based on Remain chokes downstream when added to servers.

**Comment by kangarko** [comment]
Are you seeing anything wrong with the code above? How were you able to discover that is came from Remain? We are now only using the Foundation library that has Remain as a part of it.

The code has changed but just search for AdvancementAccessor in that class, thanks.

Can this be the Bukkit.getUnsafe().removeAdvancement(key) method?

**Comment by PyvesB** [comment]
> Are you seeing anything wrong with the code above? 

This [method](https://github.com/kangarko/Remain) is apparently bogus. The comments claim that it throws a `InteractiveTextFoundException`, but actually isn't as all exceptions are being caught immediately, producing the exact log messages reported by @mibby.  Following several Java anti-patterns such as exceptions as control flow and catching `Throwables` probably led to this error.

**Comment by kangarko** [comment]
Good spot, thanks I will fix that!

**Comment by PyvesB** [comment]
Thanks @kangarko! Will close this issue for now, feel free to reopen @mibby if you spot anything else unexpected! :+1:

**Comment by mibby** [comment]
Will do, thanks!
