### ISSUE TITLE
Achievement categories with progressbar

### ISSUE THREAD

**Issue by i9hdkill** [PyvesB/AdvancedAchievements#55]
Hey,
currently we have one gui full of items, it's not very clear.
Some config options to create categories would be nice.

Example:
categories:
  PvP:
   gui_positionx: 3
   gui_positiony: 3
   Itemname: stone

Enchantments:
  '5':
    Message: 5 objects enchanted!
    Name: '&5Wizard'
    category: PvP

Let's say we have 6 achievements in the PvP category and we did 5 of them, when you hover over the PvP category item, there is a 5/6 in the Item lore.
When you click the PvP category item, you open a menu with these 6 achievements.

**Comment by PyvesB** [comment]
Hello,

This is planned and the work is currently ongoing, slowly but surely. ;-)

#46 #18 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

The beta with the new GUI is finally here! You can download it just here:
[AdvancedAchievements-2.6-Beta.zip](https://github.com/PyvesB/AdvancedAchievements/files/342383/AdvancedAchievements-2.6-Beta.zip)

Please give me feedback about:
- any bugs you may encounter.
- any performance issues you may have with the command.
- what you think about the work, and eventually ideas to improve it.

All the config options are normally functional with the new command, except ListItemSeparator which does not have any effect anymore.

Cheers,

Pyves
