### ISSUE TITLE
Selector support

### ISSUE THREAD

**Issue by timvango** [PyvesB/AdvancedAchievements#550]
Hello,

Selectors were removed from Spigot, rendering the custom achievements nearly useless for me as they can no longer be used in command blocks.
Would it be possible to add support for selectors from the plugin?

**Comment by PyvesB** [comment]
Hello @timvango,

I don't know what selectors are. Would you like to submit a pull request? 😉 

Cheers,

Pyves

**Comment by timvango** [comment]
It has been a while, but I just created pull request #710 for this ;)
