### ISSUE TITLE
Adding Enchantments to rewarded items?

### ISSUE THREAD

**Issue by Coneter** [PyvesB/AdvancedAchievements#556]
Is it possible to add Enchantments to items rewarded from the completion of achievements?
Thanks for your time! Sorry for being a bother.

**Comment by PyvesB** [comment]
Hello @Coneter,

You can run [custom command](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards#custom-commands) as rewards for completing achievements. Simply run a `give` command with enchantments specified (this [thread](https://gaming.stackexchange.com/questions/185451/how-do-you-enchant-and-name-items-with-give-using-command-blocks) may be of interest). 😉 

Cheers,

Pyves

**Comment by Coneter** [comment]
Thanks for the reply @PyvesB 

I tried this code and it only gives the player a stick without any enchantments.
I also tried this code with reward:command:execute as well with no prevail.

I appreciate the help

Crafts:
  pumpkin_pie:
    '320':      
      Goal: Craft 320 pimpkin pies.
      Message: 320 pumpkin pies crafted!
      Name: craft_320_pumpkinpie
      DisplayName: PUUUUUUUUMPKIN 
      Reward:
        Command: give PLAYER stick 1 0 {display:{Name:"Test Name"},ench:[{id:19,lvl:1}]}

**Comment by Coneter** [comment]
Alright.

The problem is something with my server. /give @p stick{Enchantments:[{id:knockback,lvl:1000}]} works in single player, but not on my 1.14.3 server. I will try to find the issue, but if anyone else can help I'd appreciate it.

I would assume it is something to do with my plugins.

**Comment by Coneter** [comment]
**I HAVE FIGURED IT OUT!!! (After many stupid hours).**
If you are using the essentials plugin, the in-game command will be /give (Player Name) stick 1 knockback:1000

More info here for anyone that needs it: [](http://wiki.mc-ess.net/wiki/Item_Meta)

**Comment by PyvesB** [comment]
Nice! Glad you solved your issue, and thanks for sharing. :wink:
