### ISSUE TITLE
Problem - Brewing Stand and Achievements

### ISSUE THREAD

**Issue by RenaWevin** [PyvesB/AdvancedAchievements#559]
If we put **any kind of potion** on brewing stand and take it back,
it'll count in brewing achievement's counter.
It means we don't really need to make potions to get this type of achievements.

Plugin version: 5.12.3
Minecraft version: 1.14.3

**Comment by PyvesB** [comment]
Hello @RenaWevin,

This is a known limitation, you have to rely on the cooldown instead. See #239, #276 and others. 😉 

Cheers,

Pyves
