### ISSUE TITLE
TargetsShot

### ISSUE THREAD

**Issue by Buchcikk** [PyvesB/AdvancedAchievements#560]
Hello
Can someone help me?

Is it possible to set a goal as a specific player in the "targetsShot" category?
i try use:
"specificplayer-uuid" 
"specificplayer-nick"
"player-nick"

"specificplayer-uuid" works in the "kill" category.

Thank you in advance for your help

**Comment by PyvesB** [comment]
Hello @Buchcikk,

This is not currently possible with the `TargetsShot` category. 😉 

Cheers,

Pyves
