### ISSUE TITLE
Plugin Support Request

### ISSUE THREAD

**Issue by LadyHaley** [PyvesB/AdvancedAchievements#561]
Could you please add support for the following plugins?

- WorldGuard
- Magic

Worldguard isnt that importand but I wanna give an achievement for entering a region

Magic for getting certain spells, wands, and wand buffs

**Comment by PyvesB** [comment]
Hello @LadyHaley,

As far as WorldGuard is concerned, see #465 and other related issue. 😉 

Would you want to contribute Magic support or do you know someone who will?

Cheers,

Pyves
