### ISSUE TITLE
Custom GUI

### ISSUE THREAD

**Issue by JustinSaenCity** [PyvesB/AdvancedAchievements#563]
Hey there,
I am trying to make a custom achievement system for my bungeecord server. Altough I don't really know yet how to use certain features yet.
When I delete achievements completely they come back in the server altough they arent in teh config and I can't seem to find an option to put achievements into a custom category in the GUI.
When I change the GUI file nothing changes, but when I change achievements they do. (not teh categories tho)
Are these things possible?
If more information is needed, I'm happy to provide it!

Regards,
Justin

**Comment by PyvesB** [comment]
Hello @JustinSaenCity,

> they come back in the server

Could you please clarify, what do you mean precisely?

> When I change the GUI file nothing changes

How have you tried to change it? Have you run _/aach reload_?

Cheers,

Pyves
