### ISSUE TITLE
Achievements with MythicMobs not working

### ISSUE THREAD

**Issue by Mielsch** [PyvesB/AdvancedAchievements#564]
Hey,

first of all great plugin :)
But I have a Problem with Achievements with MythicMobs. I tried the SkeletalKnight Quest you created by killing some SkeletalKnights and I dont get the achievement.
Using latest version of Advanced Achievements and 4.7.0 (newest) of Mythic Mobs

**Comment by PyvesB** [comment]
Hello @Mielsch,

Are you referring to [this achievement](https://github.com/PyvesB/AdvancedAchievements/blob/7a58496e04b881f14152c8eaf6b02aa94a024f66/advanced-achievements-plugin/src/main/resources/config.yml#L334)? Have you changed it in any way?

Cheers,

Pyves

**Comment by PyvesB** [comment]
See tips in linked issue.
