### ISSUE TITLE
Can't re-add Categories 

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/AdvancedAchievements#565]
I can't get 'arrows' to show up in the gui using paper 1.13.2

I removed it awhile ago and now trying to add it back and it's not working 
here's the line:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3504793/AdvancedAchievements.zip)

# When an arrow is shot.
[code]Arrows:
  50:
    Goal: Shoot 50 arrows.
    Message: 50 arrows shot!
    Name: arrows_50
    DisplayName: Arrows Around the Place[/code]

**Comment by PyvesB** [comment]
Hello @BobbyMere,

The _Arrows_ category is specified twice in the configuration! One of the duplicated categories is empty, remove it and everything should work as expected. 😉 

Cheers,

Pyves
