### ISSUE TITLE
2 Categories in 1 

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#566]
Hello, is it possible to make 2 categories in 1?

I mean like combine "Blocks placed " and "Blocks broken" only in "Blocks"

**Comment by PyvesB** [comment]
Hello @R4zzerYT,

No, this is not currently possible with Advanced Achievements. 😉 

Cheers,

Pyves

**Comment by R4zzerYT** [comment]
Can you add this feature? Or a feature to make his own gui design?

**Comment by PyvesB** [comment]
To be honest, I don't have enough bandwidth to work on such a feature at the moment, but I'm happy to review pull requests from external contributions!

**Comment by R4zzerYT** [comment]
I asked that same thing a few months (or years?) ago..
