### ISSUE TITLE
Advanced Achievements lagging

### ISSUE THREAD

**Issue by rosiejane** [PyvesB/AdvancedAchievements#567]
Hello. This plugin has been causing lag on my server for quite a few weeks now and i have had no response from anywhere. We only have about 20-30 players.

Do you have any ideas?

We are now running spigot 1.14.4

Thank you

![aaa](https://user-images.githubusercontent.com/54243352/63226786-7e70e200-c1d6-11e9-856f-992426408b5e.png)

**Comment by rosiejane** [comment]
![aaaa](https://user-images.githubusercontent.com/54243352/63302279-9f1f6180-c2d4-11e9-9a06-78075bd8e643.png)

**Comment by supertassu** [comment]
Can you post a link to the full timings report?

**Comment by rosiejane** [comment]
Sure thing

**Comment by rosiejane** [comment]
Are there any achievements i can remove to stop the lag at all?

**Comment by PyvesB** [comment]
Hello @rosiejane,

What database type are you using?

Cheers,

Pyves

**Comment by rosiejane** [comment]
@PyvesB 

DatabaseType: sqlite

**Comment by PyvesB** [comment]
I would recommend giving H2 a try, it will probably improve performance quite a bit!

**Comment by rosiejane** [comment]
Okay thank you i will change it,.

Would MySQL better better than H2 ?

I tried MySQL a long time ago but it would not connect

I will use H2 for now though

Thank you.

**Comment by PyvesB** [comment]
I wouldn't say that MySQL is better than H2: they're quite different underneath the hood, it depends on the versions used, the configurations, etc.

Do let us know if H2 helps with the performance. 😉

**Comment by rosiejane** [comment]
Just checking. There is no H2 option in the config. But if i type H2 i assume it will still work correct?

# Database type, sqlite, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: sqlite

**Comment by PyvesB** [comment]
Make sure you're using the latest version of Advanced Achievements and specify `h2`.

**Comment by rosiejane** [comment]
I am using 5.12.3

I will give it a day or 2 and let you know how it goes.

Thank you

**Comment by rosiejane** [comment]
@PyvesB 

Is there any way to load the old database now im using h2? As currently everyone has to start fresh. ugh!

![dat](https://user-images.githubusercontent.com/54243352/63551389-f586dd00-c52c-11e9-93c9-b24c8496fee1.png)

**Comment by PyvesB** [comment]
There are probably migration tools available, however, I've never tried using one.

**Comment by rosiejane** [comment]
I have tried to convert the database but it does not work. Ugh that is so disappointing. 

We have over 450 Achievements and so many players have put a ton of effort in to them .Hours and hours. 

Using h2 is just not an option, but i will use it for a day or so just see see if it lags, i gues sits a good test while all players achievmeents have reset.

**Comment by PyvesB** [comment]
Send the old SQLite database by mail, I can give converting it a quick try. Though I'm not guaranteeing success!

**Comment by rosiejane** [comment]
I will do this soon. Thank you

**Comment by rosiejane** [comment]
@PyvesB 

Email has been sent

**Comment by PyvesB** [comment]
Okay, will try it out sometime this week!

**Comment by PyvesB** [comment]
I sent you my attempt back by mail. It wasn't easy as SQLite and H2 use completely different date formats, but hopefully I've gotten it right. Let me know if it works as expected! 😉

**Comment by PyvesB** [comment]
How are things looking @rosiejane ?

**Comment by rosiejane** [comment]
It seems to be looking great so far. Ive ran a couple of timigns reports and they seem fine with acheivements. I will continue to check it when the server is busy as well.

**Comment by PyvesB** [comment]
It's been roughly a month since since the database type switch and there haven't been any complaints about performance, I believe it's safe to assume things are going well. Closing. 😉
