### ISSUE TITLE
AACH doesn't work

### ISSUE THREAD

**Issue by TheYaya77** [PyvesB/AdvancedAchievements#57]
Hello, I create some Achievements for my minecraft server buy they doesn't work.

I give you my config.yml file: https://mega.nz/#!k8RBWDKT!I-pbrL_5HBiFO7skD3z4jzTxlZt6HtdNhczuWtXNb-I

He's in UTF-8 (without BOM)

I think it's a permission problem, can you give me an example of permission for the Kill Achievement please ?

Thank you.

**Comment by PyvesB** [comment]
Hello,

What permissions plugin are you using? Permissions are supposed to bet set to true by default.

For instance for kills: achievement.count.kills.player: true

Cheers,

Pyves

**Comment by TheYaya77** [comment]
I'll try this and tell you. I'm using GroupManager.

**Comment by PyvesB** [comment]
Hello,

Sorry for the delayed response. Have you been able to solve your issue? Is the plugin logging any errors or warning in the console? Also I recommend not using GroupManager, support has been dropped for years and users have been reporting multiple problems on  more recent versions of the game. 

Cheers, 

Pyves
