### ISSUE TITLE
Suggestion for item pickup

### ISSUE THREAD

**Issue by Kaymend** [PyvesB/AdvancedAchievements#570]
Currently, there's only a placeholder for the amount of items picked up, which is the total I assume. It would be nice to branch out to the specific items picked up
Eg:

%aach_itempickups_[itemname/id]%

Further item pickup achievement idea:
Mainly for items collected upon mining a block or killing a mob, such as the amount of iron collected from iron ore; amount of cobble obtained from mining stone; rotten flesh looted from zombie (items from custom mobs maybe). Counter would not increase if picked up by players or from external sources (dropped items/ dispensers/ etc).
Eg:

%aach_itemcollected_[itemname/id]%

**Comment by PyvesB** [comment]
Hello @Kaymend,

This has already been suggested and is tracked by #56. 😉 

Cheers,

Pyves
