### ISSUE TITLE
IslandWorld Plugin Achievement Integration

### ISSUE THREAD

**Issue by Feglord** [PyvesB/AdvancedAchievements#572]
Hey man!

Just looking to set up a server using your plugin, among others, and have some cool ideas for some cross-plugin integration that i'm not entirely certain how I might go about setting up. 

I've currently got a skyblock server that is running IslandWorld 1.14.4, and I was looking at plugins that I could use to integrate a sort of "progression" system, through giving people items and blocks they may need after reaching a certain checkpoint in terms of 'Island Level'

For example, I wanted to have it so that once a player is a part of or owns an island that has moved from level 0 to level 1, then it would grant them an extra water bucket allowing them to further improve on their island by creating an infinite water source.

I assumed that this might be possible due to both your plugin and IslandWorld supporting PlaceholderAPI, in which one of the placeholders (%islandworld_level%) would need to be used.

But I can't seem to understand how I might add this type of thing into the configuration.

As a side note, I have also found that, while the wiki explains very well how to edit the existing categories and/or achievements, it has proven to be a bit unclear on directly explaining how to, for example, change the amount of stones placed requirement from 100 to 200. 

Simple enough to figure out after a bit of testing and changing some things, but I found that it was nearly impossible to find any resource that fully explains if it is possible to, and then HOW to actually create fully new categories and put within them entirely new achievements.

As you could probably tell I have some interesting plans for what I'd like to do with the server, but as it stand I have been struggling to wrap my head around it, and am just hoping to either get some help into what the limits of this plugin are and how I might go about implementing some things, or some clarity into how much of a silly I am for either missing something or not understanding something that is clear.

Either way, a response with some help would be very greatly appreciated!
Thank you!

**Comment by PyvesB** [comment]
Hello @Feglord,

Advanced Achievements provides statistics corresponding to the built-in categories as placeholders, but there currently is no way of doing the reverse, i.e. building new categories based on custom placeholders. That idea was suggested in #365, but unfortunately development has stalled on that one. Unless I'm missing something, there won't be a way to integrate with IslandWorld without getting your hands dirty and writing some additional code. 😉 

Hope this helps!

Cheers,

Pyves

**Comment by Feglord** [comment]
Awesome thanks mate!

**Comment by PyvesB** [comment]
No worries, let me know if you need anything else!
