### ISSUE TITLE
1 question and a problem

### ISSUE THREAD

**Issue by pluttotv** [PyvesB/AdvancedAchievements#573]
i have few questions:
1. can i create new tab in the advancement by my plugin with custom background ?
2. for some reason when i started using the plugin, i could see the new achievements tab in the advancement
but now i cant. plugin works ok -> no errors, and also i tried to run it alone (to check maybe it get conflicts with another plugin -> but no!!!)
i searched all the config to find something that mention that, the closest one was HideAdvancements: false , i tried both true and false and nothing trigger the tab of this amazing plugin on the advancement tab.

running 169v+ papermc 1.14.4

**Comment by PyvesB** [comment]
Hello @pluttotv,

Have you tried running the _/aach generate_ command again?

Cheers,

Pyves

**Comment by pluttotv** [comment]
thanks i did it and restart the server and it works!
if i add more achievements would it fuck it up? or only if i dont implament them good?
cuz i did a manage to load a config with my own achievements without any errors - its only that it didn't show up in the tab up in the advancement.

beside that if i may:
1. can you edit the background of this tab? (like change the book?)
2. can i create a new tab? with other achievements?
its maybe also for development purposes - as i want to use this plugin to create my own achievements based on mini games people play throe a plugin i made.

thanks!

**Comment by PyvesB** [comment]
If you add new achievements, simply run the command again, it should do the trick! To modify the background, the `AdvancementsBackground` configuration parameter can be used. However, you can't add a separate tab to the listing, unless you manually modify the generated advancement files on your server. 😉

**Comment by pluttotv** [comment]
thanks i see, im gona play with it next week, im looking into implement another advancement with custom listeners and i want the plugin i make for it to use ur AdvancedAchievments so i can run another tab from the plugin i code.
