### ISSUE TITLE
Problem with MythicMobs achievements

### ISSUE THREAD

**Issue by AIphaDragon** [PyvesB/AdvancedAchievements#574]
Hello,
So, I've got the problem with achievement goals on killing MythicMobs similar to #564 . It just doesn't complete.
Here are the pastebins:
Achievement config: https://pastebin.com/NTze0XG0
MM mobs: https://pastebin.com/UmsfJiiS
AACH version: 5.12.3
MM version: v4.7.0
Spigot version: 1.13.2

As you can see I tried 3 examples with achievements and any of them do not work. Hope you will help me to solve this problem.

I am looking forward to your answer

**Comment by PyvesB** [comment]
Hello @AIphaDragon,

Could you please try something like this instead:
```
Kills:
  '§eСтог сена':
    '10':
      Goal: Get 10 wheat.
      Message: '&1Some text.'
      Name: kills_10_farmwheat
      DisplayName: Wheat
      Reward:
        Item: diamond_sword 1
  Dinnerbone:
    '10':
      Goal: Get 10 carrots or potatos.
      Message: '&1Some text.'
      Name: kills_10_farmcarrot_or_potato
      DisplayName: Carrot Or Potato
      Reward:
        Item: diamond_sword 1
```

`FarmCarrot` and `FarmPotato` have the same display name in Mythic Mobs' configuration, so I don't think there's a way to differentiate them in Advanced Achievements.

Cheers,

Pyves

**Comment by AIphaDragon** [comment]
Oh wow, yes it helped! Thank you so much!
Sad to know, I can't differentiate them, but I will try something else.

Sorry for asking a question in inappropriate topic, but is there a placeholder in AACH for MythicMobs killed? Like %aach_kills_skeletal_knight% ?

Thank you in advance for your answer.

**Comment by PyvesB** [comment]
You're welcome!

Try with the subcategory name directly: `%aach_kills_§2Skeletal Knight%`. Though I'm not sure that will be valid from PlaceholderAPI's point of view. 😕

**Comment by AIphaDragon** [comment]
Good.
May I write tomorrow as I will test it?
Now I don't have access to the computer

**Comment by PyvesB** [comment]
> May I write tomorrow as I will test it?

Sure, there's no rush!

**Comment by AIphaDragon** [comment]
Welp, my colleague test it out for me. PAPI doesn't recognise this type of placeholders indeed.
That's it, thank you so much for your help! :)

**Comment by PyvesB** [comment]
You're welcome!
