### ISSUE TITLE
How do i integrate the achievements. 

### ISSUE THREAD

**Issue by LucidAPs** [PyvesB/AdvancedAchievements#575]
I want to integrate the achievements into the vanilla game's advancements tab but i am not sure how. Also i want to disable the custom category for the voting achievement because it doesn't recognize the voting plugin i am using. Votifier and VotingPlugin. I also don't know how to do that.

I am using latest paper build and MC 1.14.4
Let me know if more info is needed.

**Comment by PyvesB** [comment]
Hello @LucidAPs,

I suggest reading the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki), it should answer your questions. 😉 

Cheers,

Pyves
