### ISSUE TITLE
Question: Do I need to do /aach upgrade13 on a new 1.14 installation?

### ISSUE THREAD

**Issue by s1h4d0w** [PyvesB/AdvancedAchievements#577]
Simple question, and it might be dumb but I'm a bit confused by https://github.com/PyvesB/AdvancedAchievements/wiki/Migrating-to-Minecraft-1.13

I've never used the plugin before and am running a Paper 1.14.4 server, if I install the plugin do I need to run the `/aach upgrade13` command or will the plugin detect the version and load the correct format for the config?

**Comment by PyvesB** [comment]
Hello @s1h4d0w,

If you've never used the plugin before, no need to do anything! I added some extra clarification to that Wiki page, hopefully it helps! 😉 

Cheers,

Pyves

**Comment by s1h4d0w** [comment]
Thanks, after using the plugin for a day I've noticed that it functions just fine!
