### ISSUE TITLE
Offline player support

### ISSUE THREAD

**Issue by Lemrigue** [PyvesB/AdvancedAchievements#58]
Hello, some of my achievements have to be given to the player when they are offline. But when the command "/aach give ach name " is executed it says the player is offline, so I would had like to know if you could add an offline player support (a line in the config like "offline-player-can-get-achievements : true/false for example)

Thanks

**Comment by PyvesB** [comment]
Hello,

The plugin uses UUIDs to store achievement information. I cannot retrieve an UUID if the player is online just be having his pseudo. Unless there is some easy alternative I don't know of, support will unfortunately not be added.

Cheers,

Pyves

**Comment by Lemrigue** [comment]
Ok I understand but then, isn't it possible to link a player to his UUID when they first join the server ? If it is done, when you give the achievement to the player, it will look for the UUID linked and give it to the player linked. 
I don't know if it is possible but If it is, it would be appreciate if you can do it. If not, then never mind, thanks

**Comment by PyvesB** [comment]
Well, I could store extra information, but this would lead to problems if the player decides to changes his name (currently in that case all his achievements are automatically "transferred"). I would have to do checks and update the database at each player connection, so this isn't great. I'll check if there isn't a general library that can get the UUID from a pseudo in a clean and efficient way. ;-)
