### ISSUE TITLE
Sub Categories for Eaten Items

### ISSUE THREAD

**Issue by AlwaysAllstar25** [PyvesB/AdvancedAchievements#580]
I have an achievement set up for player kills under the multiple action achievments section in the config:
https://gyazo.com/0ab455e529902e9cb4030dae69c9fd4c
I am trying to do something similar for Eaten Items with the following but it does not work no matter what I do, it either gives me an internal error message, or the achievement just doesn't show up in /aach list.
https://gyazo.com/511d5df3986d69b93e5709debf46b35c
I tried putting it in both the multiple actions and normal actions section but neither works. Is it even possible to have Eaten Items as a multiple action achievement?

**Comment by PyvesB** [comment]
Hello @AlwaysAllstar25,

See #56 . This is also outlined in the documentation.

Cheers,

Pyves
