### ISSUE TITLE
At $ after the amount

### ISSUE THREAD

**Issue by ManuXzUWM** [PyvesB/AdvancedAchievements#586]
Hey,
is it possible to at a $ behind the Money announcement seen in this picture:

https://i.postimg.cc/TP2C9QSW-/Unbenannt.png

**Comment by PyvesB** [comment]
Hello @ManuXzUWM,

Yes, it's possible. If you're using Essentials for instance, modify the `currency-symbol` configuration value. If you're using another economy plugin, there should be a similar configuration option there as well. 😉 

Cheers,

Pyves

**Comment by ManuXzUWM** [comment]
I have configured it like this: currency-symbol: '$'
The $ symbol works fine but the Money Announcement from Advanced Achivement won't show the $ symbol.

**Comment by PyvesB** [comment]
What economy plugin are you using?

**Comment by ManuXzUWM** [comment]
Essentials+Vault

**Comment by PyvesB** [comment]
So, I've just installed the latest versions of Vault, EssentialsX and Advanced Achievements with fresh configurations, and I can indeed reproduce the issue. However, after a bit of digging, this seems like a [missing feature in Essentials](https://github.com/EssentialsX/Essentials/issues/2401). There's nothing much I can do on my side - I'm not keen on implementing a hacky workaround, this really ought to be implemented in Essentials directly. I suggest adding a thumbs up and/or commenting on the linked issue to increase the chances of it getting tackled!

**Comment by PyvesB** [comment]
Nothing much to add here, closing.. Of course, as a workaround, you can explicitly add the `$` in _lang.yml_.
