### ISSUE TITLE
Command rewards dont run.

### ISSUE THREAD

**Issue by arizrain1** [PyvesB/AdvancedAchievements#587]
I'm using 1.14.4 and have 5.12.3 on and all of it works fine, except running a command to give a permission from console.

Can you check my setup for giving out a reward command?    It just wont run the command.
             https://pastebin.com/gUj6zBeZ

**Comment by PyvesB** [comment]
Hello @arizrain1,

The parameter for command rewards is `Command`, with a capital C, as showcased [in the Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards#custom-commands). Let me know if this helps. 😉 

Cheers,

Pyves
