### ISSUE TITLE
config

### ISSUE THREAD

**Issue by Gamepl1** [PyvesB/AdvancedAchievements#589]
When I change the text in the config to my native language, then after starting the server writes me an error.

![image](https://user-images.githubusercontent.com/55554727/65791234-fc2af480-e169-11e9-8cf5-47dd540a236a.png)

What am I doing wrong?

**Comment by PyvesB** [comment]
Hello @Gamepl1 ,

Have you tried running your configuration through yaml-online-parser.appspot.com beforehand? 😉 

Cheers,

Pyves
