### ISSUE TITLE
[Help] Something is wrong with my config?

### ISSUE THREAD

**Issue by DavidBorisK** [PyvesB/AdvancedAchievements#59]
The default config loads fine, but mine doesn't work even though it's valid YAML. When I tried booting it up, I had commented out the sections for PlayedTime and some other ones, it deleted those sections of the config and told me to add them to the "Disabled Categories" section of the config, which I did. Here is the error I get on start up:
[http://pastebin.com/6Nvs29N1](http://pastebin.com/6Nvs29N1)

Here is my config:
[http://pastebin.com/LZ0WbBuB](http://pastebin.com/LZ0WbBuB)

**Comment by PyvesB** [comment]
Hello,

Have a look at the DistanceMinecart category, you messed up in there. ;-)

Cheers,

Pyves

**Comment by DavidBorisK** [comment]
Holy moly thank you so much!

**Comment by PyvesB** [comment]
No problem. Feel free to star the project if you wish. ;-)
