### ISSUE TITLE
Customizing GUI pages

### ISSUE THREAD

**Issue by FlowerOLife** [PyvesB/AdvancedAchievements#591]
I have been trying to add some new categories to the GUI, however, what I'm coming to understand is that the categories are pre-determined by an action (places, breaks, etc) and the lang.yml simply changes the name within the GUI, taking the listed action from the bottom of the list and ignoring all above it with the same category name. Is it possible to add additional subcategories of these, such as within "breaks" subcategorize as "mining, forestry, crops, etc" so they maintain the same function, but that different materials can be added to the various subs? Thanks for any help, and if this is not currently possible, might I make a suggestion for any future updates? ;)

**Comment by FlowerOLife** [comment]
Sorry I figured out the GUI.yml file was in the directory shortly after posting this question.  I'm still curious if it possible to add additional categories and pages to the yml without conflict? I have also been having difficulty with certain achievements registering in game, possibly because I have too many in one category? What is the maximum number of achievements in a category? I cannot open the category in GUI with 16 achievements. Any help is appreciated. Ran it through YAML parser and has no issues there, and was working fine with a fewer number of achievements, thus why I was hoping I could add more categories and pages.

**Comment by FlowerOLife** [comment]
I have been trying to add some new categories to the GUI, however, what I'm coming to understand is that the categories are pre-determined by an action (places, breaks, etc) and the lang.yml simply changes the name within the GUI, taking the listed action from the bottom of the list and ignoring all above it with the same category name. Is it possible to add additional subcategories of these, such as within "breaks" subcategorize as "mining, forestry, crops, etc" so they maintain the same function, but that different materials can be added to the various subs? Thanks for any help, and if this is not currently possible, might I make a suggestion for any future updates? ;)

**Comment by PyvesB** [comment]
Hello @FlowerOLife,

I believe this is very similar to #536. My answer from ~3 months ago still stands. 😉 

Cheers,

Pyves

**Comment by FlowerOLife** [comment]
Understandable response. If you do decide to upload the plug-in this way, I
will be sure to make a donation or purchase it. Thanks for your response.
