### ISSUE TITLE
Advancements don't match Achievements

### ISSUE THREAD

**Issue by MrXuiryus** [PyvesB/AdvancedAchievements#592]
Hi there. I have an issue where the advancements being shown in the in-game tab don't match what is configured in the config file.

I can confirm that the achievements do show up when I type /aach list

Also I have ran /aach generate and rebooted the server which didn't fix it.

Okay so it seems to be intentionally hiding them on the advancements tab and doesn't show them until I unlock a previous one. Which doesn't make any sense because I have all the hide/obfuscate settings disabled, unless there's another mechanic/setting at play?

**Comment by PyvesB** [comment]
Hello @MrXuiryus,

I may be mistaken, but I believe this is just down to how the advancement tree works in Minecraft. Unsure whether there's much I can do to change it in Advanced Achievements.

Cheers,

Pyves
