### ISSUE TITLE
Sub Categories for GUI

### ISSUE THREAD

**Issue by KlayaR** [PyvesB/AdvancedAchievements#593]
Hello,
Is there a way to have sub categories for blocks placed? And by that I mean, I have 4 levels of achievement for several blocks, so the GUI is getting pretty full. I would love to just click on the "blocks placed" categories, then click on the type of block, then see the different levels

Best Regards,
Damien Petit, Insanity Craft

**Comment by PyvesB** [comment]
Hello @KlayaR,

Please see https://github.com/PyvesB/AdvancedAchievements/issues/326#issuecomment-433692998 and other similar issues. 😉 

Cheers,

Pyves
