### ISSUE TITLE
Plugin Disabled

### ISSUE THREAD

**Issue by FlowerOLife** [PyvesB/AdvancedAchievements#599]
Hello. I am still working on setting up my server, and had Advanced Achievements working fine, but tried to run a aach command and got an internal error. The console is saying the plugin is disabled. My config.yml has no parsing issues. Any ideas what may be disabling it?

16.10 12:33:51 [Server] INFO FlowerOLife issued server command: /aach reload
16.10 12:33:51 [Server] ERROR null
16.10 12:33:51 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'aach' in plugin AdvancedAchievements v5.12.5 - plugin is disabled.
16.10 12:33:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-192]
16.10 12:33:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by PyvesB** [comment]
Hello @FlowerOLife!

Have you checked the log messages when the server is starting up? They _should_ indicate why Advanced Achievements was disabled. 😉 

Cheers,

Pyves

**Comment by FlowerOLife** [comment]
Hey thanks for getting back with me. I just realized the problem has something to do with my SQL database. I use Apex Minecraft Hosting, and they automatically set a database up, but it seems anything I link to the database fails to load. Sorry to bother you. Hopefully I can figure that problem out next.

**Comment by FlowerOLife** [comment]
I removed the database settings and everything is working again btw.

**Comment by PyvesB** [comment]
> I removed the database settings and everything is working again btw.

Yes, by default it will use `h2` as an embedded database. That generally just works without any problems.

**Comment by FlowerOLife** [comment]
Ok, good to know. I do have one more question. I am making my own custom achievements and rewarding multiple different items for certain advancements, but the yml parsing is throwing errors for several of the multi-item rewards saying "found character '\t' that cannot start any token". There is no indentation, and I can't figure out what is causing the parsing issue. Is there a certain way I need to format this, such as a semi-colon between items, or do I make a separate "item:" line?

**Comment by FlowerOLife** [comment]
Ok final question, I have a list of 15 achievements for one category, but it seems the GUI does not like that many as it will not open the menu for that category. Is there a way to expand the menu pages or is there ultimately a cap on how many achievements can be in one category?

**Comment by PyvesB** [comment]
Normally the GUI resizes dynamically. Are there any errors in the logs when you try opening it?

**Comment by PyvesB** [comment]
No worries. Feel free to open new issues if you need more help. 😉
