### ISSUE TITLE
Naming Player Item Rewards

### ISSUE THREAD

**Issue by FlowerOLife** [PyvesB/AdvancedAchievements#600]
I'm trying to add named items as trophy to players, and was trying to add color codes as well as the player name, but the item given never represents the code's input:

Item: gold_hoe 1 &6PLAYER&d&nFarmer&r &6Trophy

It shows up how I want it to look in the aach GUI, but the item name shows the full code when the item is given. Is there any way to make the item name show as I'd like? I would like for it to display the player's name as well...

**Comment by PyvesB** [comment]
Hello @FlowerOLife,

I don't think you can user `PLAYER` or similar placeholders in custom item names. However, it's something I can add in a future version. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
I've added support for placeholders for custom item names in the linked commit. As far as colours are concerned, I suggest using `§` instead. 😉

**Comment by FlowerOLife** [comment]
This is excellent news! Thanks for the addition. So do I simply download the latest version of the plugin, and the placeholders will work? Or do I need to add a special syntax or string to the skript? Sorry, I know very little about reading Java. Slowly learning though...

**Comment by PyvesB** [comment]
Simply download latest and placeholders will work. The Wiki was also updated with the these new features. :wink:
