### ISSUE TITLE
Help In Customizing

### ISSUE THREAD

**Issue by MommaJibi** [PyvesB/AdvancedAchievements#601]
Hey there! I'm new to AACH and would really like to set up custom achievements for our new Minecraft community server, but I'm very new-ish to coding and I don't know if anything I input is even going to work. I've looked online for videos, but it's mainly all tutorials on working with the GUI, which I can do. What I want to do is set up custom ones for our server from my spreadsheet and implement them into the game through AACH.

**Comment by PyvesB** [comment]
Hello @MommaJibi,

The existing `Custom` category may come in handy. If you want more flexibility, simply implement new categories in the code. The [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#implementing-new-categories) provides information about how to achieve this! :wink:

Cheers,

Pyves

**Comment by MommaJibi** [comment]
I mean how do I write the code? What exactly do I put where? I'm really new to that entire bit, lol. Or is there someone I could perhaps pay to write it for me? I just want to be able to get this done for all my players.

**Comment by PyvesB** [comment]
Have you actually read my previous message? The link tells you exactly what code you have to put where. 😄

**Comment by MommaJibi** [comment]
It talks about binding methods and programming jargon that I don't understand.

"Add a new listener class to the com.hm.achievement.listener.statistics package. DropsListener.java is a very simple example you can use as a reference.
Add a new binding method in ReloadableModule.java, similar to the existing ones."

Again, I'm not a programmer, I don't want to mess it up. There is no need to be rude.

**Comment by PyvesB** [comment]
Just to clarify a couple of things:
* none of my messages were intended to be rude, sorry if they came across as that - I realise in retrospect that the friendly smiley I put in the last one may actually be understood as "mocking".
* I was not aware you were not a programmer. As you were talking about code, implementations, etc., I thought you were a student or had some sort of  programming background (hence, the "new-ish").

Was is you current setup? Have you opened the project in an IDE (Eclipse, IntelliJ, etc.)?
