### ISSUE TITLE
Command Reward

### ISSUE THREAD

**Issue by SskyWorms** [PyvesB/AdvancedAchievements#603]
Can you check why command not work ?
MaxLevel:
  '2800':
    Goal: Reach level 2800.
    Message: Lên Rank !
    Name: maxlevel_2800
    DisplayName: §aLên Rank !
    Rewards:
      Command:
        Execute: nick PLAYER viet123

**Comment by SskyWorms** [comment]
![image](https://user-images.githubusercontent.com/54969382/67763750-fed77d00-fa7a-11e9-8280-3f58b94bad85.png)

**Comment by PyvesB** [comment]
Hello @SskyWorms,

The keyword is `Reward`, without the 's', as documented in the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards). :wink:

Cheers,

Pyves
