### ISSUE TITLE
Support Ultimate statistics to auto rank people

### ISSUE THREAD

**Issue by FrozenBeard** [PyvesB/AdvancedAchievements#604]
Ahoy!
Im looking for a better Stats+Autorank solution! 

I think you may have the answer! If you use Ultimate statistics API to grab their stats.
https://www.spigotmc.org/resources/ultimate-statistics.60868/

Would it be possible to make a linear auto ranking system? 

Get X & X & X stats from Ultimate statistics > Rank 1, which then you can go for Rank 2 and so on.

**Comment by PyvesB** [comment]
Hello @FrozenBeard,

Advanced Achievements does not provide any ranking concepts and relies on its own statistics system. I'm unsure what you're suggesting.

Cheers,

Pyves
