### ISSUE TITLE
Error with version 5.13.0

### ISSUE THREAD

**Issue by jere62smi** [PyvesB/AdvancedAchievements#605]
http://bin.mc-imperia.fr/Xttu5BK7IV

**Comment by PyvesB** [comment]
Please share your configuration, nothing much I can do to reproduce this error without it. 😉

**Comment by jere62smi** [comment]
I sent it to you in private message mail for more security.

**Comment by PyvesB** [comment]
> I sent it to you in private message mail for more security.

Did you use my dev email listed on my GitHub profile? I haven't received anything yet.

**Comment by jere62smi** [comment]
Yes at PyvesDev@gmail.com

**Comment by PyvesB** [comment]
> Yes at [PyvesDev@gmail.com](mailto:PyvesDev@gmail.com) Because unfortunately, we can no longer mp you on spigot

Git it, it was flagged as a dangerous mail by Google (single link spooked their systems off I guess). And yes, Spigot PMs were 95% spam, so figured out it was better to just disable them.

**Comment by PyvesB** [comment]
Okay, this should be fixed by the above commit! Here's a test version:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3791416/AdvancedAchievements.zip)

Please confirm whether the plugin loads for you as well. Also, let me know if you spot anything else unexpected. :wink:

**Comment by jere62smi** [comment]
Good evening, sorry for the late response, it works fine with the new version.
Thank you.

**Comment by kacperleague9** [comment]
Can you update the plugin with this fix?

**Comment by PyvesB** [comment]
I submitted the update to Bukkit yesterday - still waiting for their approval and will then release to Spigot and GitHub.
