### ISSUE TITLE
Why not?

### ISSUE THREAD

**Issue by asdasasf1** [PyvesB/AdvancedAchievements#609]
Hello! i would like to suggest a simple idea.

The option to add per achievement id logo. 

For example if the achievement is TNT, it will show an icon of a tnt instead of the only 2 defaults blocks.

That would be more cool, as its more nicier and friendly. Instead of all repetitive blocks...

Thanks

**Comment by PyvesB** [comment]
Hello @asdasasf1 !

It could very easily look like a mess and be confusing for players, and wouldn't fit well in the current config.yml/guy.yml layout of the plugin's configuration files. I'm more in favour of #452 which would allow some further customisation whilst still ensuring a sensible organisation within the GUI. :wink:

Cheers,

Pyves

**Comment by asdasasf1** [comment]
> Hello @asdasasf1 !
> 
> It could very easily look like a mess and be confusing for players, and wouldn't fit well in the current config.yml/guy.yml layout of the plugin's configuration files. I'm more in favour of #452 which would allow some further customisation whilst still ensuring a sensible organisation within the GUI. 😉
> 
> Cheers,
> 
> Pyves

Well, thats up to the customer... This plugin lucks of customazation in terms of the gui. Its horrible by itself... And the letters ugg, u cant change nothing.. but whatever
I can give u way better ideas still u wouldnt agree
see ya
