### ISSUE TITLE
[ADD] placeholder support

### ISSUE THREAD

**Issue by asdasasf1** [PyvesB/AdvancedAchievements#610]
Hello, it would be very useful, to add placeholder like:
%aaach_progress_NameOfTheAchieve%

This is basically to be able, to create your own menu with deluxemenu

**Comment by PyvesB** [comment]
Hello,

The plugin already has placeholder support. Please check out the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Placeholders).

Cheers,

Pyves

**Comment by BobbyMere** [comment]
How do you make them work though? I can't figure out how to make progress bars work at all

**Comment by PyvesB** [comment]
@BobbyMere what have you tried so far? What versions of Advanced Achievements, PlaceHolder API and Minecraft server are you using? There's not much we can do with just a "I can't figure out". :wink:
