### ISSUE TITLE
Create new achievements

### ISSUE THREAD

**Issue by XiaoQwQ** [PyvesB/AdvancedAchievements#612]
How to define the number of times to harvest some crops? For example, harvest 10 times of Wheat

**Comment by PyvesB** [comment]
Hello @XiaoQwQ!

The plugin doesn't currently feature a category for harvesting crops. Feel free to contribute by following the [tutorial](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#implementing-new-categories). 😉 

Cheers,

Pyves
