### ISSUE TITLE
Boss Plugin Support

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/AdvancedAchievements#613]
Hello, I'm requesting an alt to mythicmobs by adding support for [Boss](https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/)

Thank you

**Comment by PyvesB** [comment]
Hello @BobbyMere, sure, feel free to submit a pull request. :wink:

**Comment by BobbyMere** [comment]
How would I go about doing that?

**Comment by PyvesB** [comment]
Have you checked out the [contributing guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md)?

**Comment by BobbyMere** [comment]
Shame I don't know how to code
