### ISSUE TITLE
Progress placeholders?

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/AdvancedAchievements#614]
How do you do progress placeholders? 

&a%progress_percentage_{aach_arrows}_m:100% <--- this show up in game exactly as displayed here

Edit: now nothing is showing up. Can I please get one example of a working placeholder?

**Comment by PyvesB** [comment]
Hi @BobbyMere , percentages are not currently supported, so nothing will show up in game if you try to use `_m` suffixes. :wink:
