### ISSUE TITLE
PlaceholderAPI issues with current placeholders

### ISSUE THREAD

**Issue by rocky143** [PyvesB/AdvancedAchievements#615]
Hello, 
I wanted to report that most of block name do not work as placeholders.
For example, if I use %aach_breaks_dirt% or %aach_breaks_andersite%, I do not get a return with them. Some blocks work, some don't and the same thing goes for block placement placeholders.

Another issue is as the placehodlers above can be used to output info for a single block, there is currently no way to output achievement that contain multiple blocks for example stone|cobblestone|dirt. As per suggestion, it would make more sense if a placeholder could be added to use the achievement unique name like %aach_achievement_<name>% something like this: %aach_achievement_break_1_stone%.

Any help would be appreciated, thank you in advance!

**Comment by PyvesB** [comment]
@Phoetrix any chance you could look into the issues with the `Breaks` placeholders? :wink: 

@rocky143 please indicate Advanced Achievements plugin version, Placeholder API plugin version and detailed server version.

**Comment by rocky143** [comment]
I wanted to ask if it is possible to use a placeholder to display a combined result of block places/breaks count for a combined achievement? Same goes for Multiple Achievement Placeholders since all the actions can be combined like for kills, how would I display a combined result for zombies and creepers killed or item crafts?

Here is the info for you asked for:
Server version: Paper build 209 (MC version 1.14.4-R0.1)
AdvancedAchievements version 5.13.1
PlaceholderAPI version 2.10.4

Here is an example of issue with the placeholders:
![8afc1897a691f019968bd8e4a4254e8d](https://user-images.githubusercontent.com/1215622/69383210-0ad3ea80-0c87-11ea-8784-ac6206f7c7fc.png)

**Comment by PyvesB** [comment]
I'm still unclear about this issue. Could you please give an example of placeholder that isn't working, alongside the relevant _config.yml_ section?
