### ISSUE TITLE
Aach commands bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [PyvesB/AdvancedAchievements#624]
Not too sure what the exact issue is, but whenever I use commands like "/aach top" or "/aach list", it gives me an internal error has occurred.

Console error logs.
https://pastebin.com/89SiCGH2

Server Type: PaperSpigot 1.13.2
Plugin Version: 5.13.1

**Comment by PyvesB** [comment]
Hello @BboyZeroOne! Have you tried doing a full server restart (stop and start the server process from scratch, not just a reload)? Do you happen to use any other plugins that rely on the H2 database?

**Comment by BboyZeroOne** [comment]
Yes, I did a full server restart. Yes, my luck perms is using H2 database.

**Comment by PyvesB** [comment]
Are you using the latest version of Luck Perms? I suggest trying with version 5.0.21, which you can download from the [website](https://luckperms.net/).

**Comment by BboyZeroOne** [comment]
Sorry, just saw your reply. Yes its the latest version on their spigot site.

Based on their website, the latest version is v5.0.23, should I use this instead or v5.0.21 that you suggested? Thanks!

**Comment by BboyZeroOne** [comment]
I've checked again, somehow the issue fixed itself tho, without changing the version of luckperms.

**Comment by PyvesB** [comment]
Okay, awesome! I'll close this issue, feel free to reopen if this starts happening again though 😉
