### ISSUE TITLE
MythicMobs name handling

### ISSUE THREAD

**Issue by gominecraft** [PyvesB/AdvancedAchievements#626]
The mythicMobs API offers up an internal name instead of using the display name.

I would recommend switching to this method for user-friendliness.

```
MythicMob mm = MythicMobs.inst().getAPI().getMobAPI().getMythicMobInstance(entity).getType();
mm.getInternalName();
```

**Comment by PyvesB** [comment]
Hello @gominecraft !

The main reasons for using the display name is that there is no need to add a dependency on the API and it just works out of the box with no additional code to maintain and execute in Advanced Achievements.

Reading  #622, I'm also unsure whether using the internal API name would provide as much flexibility (e.g. parasite with specific levels).

Admittedly, the user experience is not as good with the display name, as it feels like the less obvious choice for users and is easier to get wrong. If you feel strongly about this and can provide a patch that adds little complexity to the code and has negligible performance impact, I'll be happy to review it. 😉

**Comment by gominecraft** [comment]
What about stripping the color codes? 

I'd be all over a PR if I was anywhere near approaching competent with java.

**Comment by PyvesB** [comment]
> What about stripping the color codes?

Colours codes are supported with the current approach, for example `§2Some coloured mob`.

**Comment by PyvesB** [comment]
If someone wants to have a go at this, feel free to reopen. Given the added complexity and potential performance impact, it's not something I'm keen on tackling myself at this point in time.
