### ISSUE TITLE
Multiple Achievements

### ISSUE THREAD

**Issue by Razesk** [PyvesB/AdvancedAchievements#63]
Ok while editing the config.yml i am having the issue where 

  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: Cobble!
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
        Money: 5
        
this achievement is working fine but below this line i have attempted to add a second condition for the achievement below this line. 

  stone:
    '10':
      Message: '&1The tenth time you went mining!'
      Name: Mr Mine!
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
        Money: 15

the .YML checker is showing nothing wrong with this block of code and i was wondering if this is something that i am doing incorrectly or whether it is simply a feature that is not implemented into the plugin. I would greatly appreciate the feedback thank you for your time.

**Comment by PyvesB** [comment]
Hello,

Don't repeat the name of the sub-category (the "stone:"); as shown in the default config file, you must just write it once and then list the different thresholds. ;-)

Cheers,

Pyves

**Comment by Razesk** [comment]
Hello, 

I have just tried out the suggested formatting for the issue i am having regretfully the issue remains that after 10 stone is broken the achievement is not being received. Thank you for the speedy reply and here is the entire break section of the code thanks again for your assistance. 

Breaks:
  gravel:
     '1':
       Message: '&2The first time you collected gravel!'
       Name: Grafter!
       Reward:
         Command: give PLAYER 158 10; give PLAYER 126 5
         Money: 5
         
  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: Cobble!
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
        Money: 5
    
    '10':
      Message: 'Ten cobblestone collected'
      Name: Mr Mine
      Reward: 
        Command: give PLAYER 158 10; give PLAYER 126 5
        Money: 10
        

  log:1:
    '100':
      Message: '&2You have cut dark oak 100 logs!'
      Name: Dark Oak Cutter
      Reward: 
        Money: 5

**Comment by PyvesB** [comment]
Could you please paste your full config on GitHub Gist or Pastebin, the snippets you pasted here are not easily readable as all the indentation is removed. :-)

**Comment by Razesk** [comment]
Ok no worries, here is the pastebin http://pastebin.com/sSG4VgDH

**Comment by PyvesB** [comment]
Hello,

I tried your config, everything works fine with the 2.5.6 version of the plugin, I managed to get both achievements. Did you add the second achievement later? In that case you might have already reached the '10' threshold, and therefore you will not be able to receive the achievement. There's a question in the FAQ giving some additional information about this. ;-)
