### ISSUE TITLE
Idea: Tracking Achievements per life

### ISSUE THREAD

**Issue by JoshTrebilco** [PyvesB/AdvancedAchievements#634]
Hi @PyvesB 

Thanks for making an awesome plugin and maintaining it for all these years.

I'm working on an idea where players have to collect all the achievements within a single life, and all of their achievements get reset if they die. It would also be nice to be able to track all the previous attempts that the player has made. ie. track all the achievements a player managed to get in a single life (preferably in the DB so we can show it on a website's leaderboard or something).

If we just want to reset the players achievements without regard to tracking previous attempts, this should be fairly straight forward? I assume we'd just hook into the player death event and remove all the player's records from the DB that match their UUID.

Tracking the previous attempts is where I'm a bit stuck... my current thought on how to implement this would be to create a new table that tracks the sessions (lives) that a player has attempted to get all the achievements. The session id would increment each time the player respawns and would be paired with the player's UUID to determine which life/session the player is currently on therefore uniquely tracking a player's life with the achievements they collected. Then I'd add the session id to every table that has the player's UUID and pair the session with the player UUID when tracking the players achievements. This would mean that all achievements are tracked by player UUID AND session instead of just the player UUID.

In reviewing the code it seems as though this is achieveable, and I'm happy to fork the project and maintain this independently, however, I'd prefer to come up with a solution that was able to be compatible with future changes you make to this plugin so would like to hear your thoughts on some solutions that you'd recommend.

Thanks, Josh

**Comment by PyvesB** [comment]
Hello @JoshTrebilco,

This sounds like a good idea! However, I don't think adding a session id to every single database table would be achievable. Last time I checked, a SQLite database on a mid-size Minecraft server can easily grow to ~50 MB after using Advanced Achievements for a couple of years. If you use a combination of UUID + session id as the primary key for your data, you're basically adding a new row to every table each time a player dies. This would lead to an explosion of data, the database could quickly reach several gigabytes under normal usage. Even limiting the amount of tracked sessions would have an impact on size and performance.

I think it would be more practical to forget about precise statistics and only focus on the main `achievements` table, which contains information about received achievements, in particular the date of reception. You could then create a separate table which keeps track of the start and end times of a player's session. It's then a simple SQL query to figure out which achievements were received during a given session, using these reception dates.

You could also simplify things further by only considering two elements, "present session" and "past sessions". You could keep an in-memory hash map indicating when the player started their current session. You could then query (or filter directly in Java code) which achievements were received before that time and which achievements were received after. No changes to the database and few changes to the plugin. Sessions would be reinitialised if ever the server restarted though.

Let me know if this helps/makes sense! :wink:

**Comment by JoshTrebilco** [comment]
Thanks for the feedback, I'll see how I get on with those changes you suggested!
