### ISSUE TITLE
Plugin resets after server restart

### ISSUE THREAD

**Issue by Tradie18** [PyvesB/AdvancedAchievements#635]
After the server is restarted, all player progress with the achievements is reset. I'm currently running the latest version of your plugin on a 1.14.4 spigot server. 

plz halp

**Comment by PyvesB** [comment]
Reading the [contribution guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md#help-and-issues) may help. 😉
