### ISSUE TITLE
Achievement kills does not work anymore

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#637]
Hi,

With the last version of this plugin (5.13.3) and Paper 1.15.1 the kills achievement no more progress. In my server players must kill zombies and drowned but we just noticed that in both cases the counter no longer increased.

Thank you in advance.

**Comment by PyvesB** [comment]
Hi @aurel85 !

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4048278/AdvancedAchievements.zip)

Any better? 😄

**Comment by aurel85** [comment]
it's perfect :D 

Merci !
