### ISSUE TITLE
aach with command block

### ISSUE THREAD

**Issue by GroentandGames** [PyvesB/AdvancedAchievements#638]
Hello,

When I would like to give a player an achivement with a command block I need to fill in a player name.
In 1.12 it was posible to do "aach give (name achivement) @p.  
Now in 1.14.4 I need to do "aach give (name achivement) (name player).
Is there a possibility to gave the achivement at the nearest player with the @p command?

Greetz GroentandGames

**Comment by PyvesB** [comment]
Hi @GroentandGames ! Yes, it's probably possible, have you checked out the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards#custom-commands) to configure the reward command? 😉

**Comment by GroentandGames** [comment]
Hi @PyvesB ,

We have try this things, but this is not what we look for.
When we put it in a command block and go on a pressure plate, nothing wil happen.
Only when i fill in the name of a player, that player earn it.
We are looking for a command that gave it to the player on the presure plate.
Hope you can help us.

**Comment by PyvesB** [comment]
I think I misread the original message, basically you want the command block to be giving a command-based achievement if I'm understanding things correctly. To be honest, I know pretty much nothing about command blocks, so I'm afraid I won't be of much help. As long as a command such as `aach give yourAch1 DarkPyves` is dispatched to the server, Advanced Achievements should pick it up.

**Comment by GroentandGames** [comment]
Indeed, when you use the username in the command it works.
But when there are more players i can not put a command block for each player.
I hope you guys will come with a sollution.
We have an amusement park where everyone can join.
Greetz

**Comment by PyvesB** [comment]
If it's a new limitation/bug with command blocks in Minecraft 1.14.4, there's unfortunately not much I can do on my side! 😕
