### ISSUE TITLE
incompatibility with other plugin

### ISSUE THREAD

**Issue by plebexer** [PyvesB/AdvancedAchievements#639]
hey i think i found an incompatibility with a plugin called advancedabilities , i bought that plugin and when i started using i noticed some achievements stopped working

**Comment by PyvesB** [comment]
Hi @plebexer, I suggest flagging this up with the author of the Abilities plugin, there's not much I can do with so little information and without even being able to test that plugin. 😉

**Comment by plebexer** [comment]
i sent  message to him, he is not responding, but i wil wait

**Comment by plebexer** [comment]
hey, i removed the plugin advanced abilities, but the plugin is istill not eorking, for example, when i kill a skeleton it wont appear that i killed him, and the plugin stopped working since i started using advanced abilities so i dont think it could be anything else

**Comment by plebexer** [comment]
i realised there is a new file generated in the plugin folder that has an error inside:  https://pastebin.com/sas4C5xQ

**Comment by PyvesB** [comment]
Could you please list all the files in you `AdvancedAchievements` folder?
