### ISSUE TITLE
more list of achievments, bungeecord support

### ISSUE THREAD

**Issue by alexhyperlapse** [PyvesB/AdvancedAchievements#640]
I can't find a way to set up one memory (mysql) connections but achievments are collected from more than one. I am using bungeecord. And i want to have achievments from another server (games) in lobby. Can i collect achievments from for example pvp and show that in statistics of that game in lobby somehow ? and almost same thing on lobby when i wanna have all achievments in one item, i have plugin for custom item and i want to have all achievments sorted by games but in one gui. I also have plugin for custom gui so i can set that there. Sorry for my really bad english

**Comment by PyvesB** [comment]
Hello @alexhyperlapse,

You can share achievements and statistics by either setting up a MySQL or PostgreSQL database table. You can simply configure the plugin using [this section of the configuration](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml#L206). 😉 

Hope this helps!

**Comment by alexhyperlapse** [comment]
I want to make more achievment gui, for more games if u understand. i have pvp so i want to have gui for pvp where will be kills death wins and more i have skywars so i want to have another gui...and more.. and have those guis on lobby but also on each game separately

**Comment by PyvesB** [comment]
Sorry, I don't understand what you're trying to achieve.

**Comment by alexhyperlapse** [comment]
I want to have for example 3 guis with statistics from games.
For example i am on pvp lobby and i can see my stats from pvp game
i am on skywars lobby so i can see statistics from skywars
i am on bedwars so i can see stats from bedwars
but i am on lobby and i can see statistics from pvp and skywars and bedwars at once in one gui or in more gui which I can put into another gui.

**Comment by PyvesB** [comment]
The statistics themselves have to be shared between the servers, as you're using a unique database table. But you can configure the plugin to have different achievements on each server. In the lobby's configuration, you simply include all the achievements listed in all other server configurations. 😉

**Comment by alexhyperlapse** [comment]
Yes I am using MySQL. Can u send me some tutorial how do it? Because I
really don't know how can I make more gui on lobby for each stats.

**Comment by PyvesB** [comment]
You can only have one GUI which will include all achievements specified in your lobby's configuration.

**Comment by alexhyperlapse** [comment]
Oh thats problem i want to have it sorted by each games
