### ISSUE TITLE
Chat message at new Achievement

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#642]
How can i disable it? I only want the titlebar with the advancement.

**Comment by PyvesB** [comment]
Hello @R4zzerYT, it's not possible to disable the chat message, as players would not have information about the objectives of the achievements nor the rewards. 😉

**Comment by R4zzerYT** [comment]
My players find this message annoying, they love the way with titlebar & advancement. 

You can see in /aach list what you have to do for it. Why not this way? I would LOVE this feature to disable it. :) And i think other people too

**Comment by R4zzerYT** [comment]
btw i mean the "Achievement unlocked:" message in the chat.

**Comment by PyvesB** [comment]
Well, I guess it wouldn't hurt to add a configuration parameter to disable it!

**Comment by R4zzerYT** [comment]
Nice, thank you!
