### ISSUE TITLE
v3.0: NPE + annoying mouse jump

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#65]
First of all, really nice update, altough I miss the old gui (R.I.P). ^^

1.) NPE InventoryClickEvent
In the new GUI I can't use the category "Other achievements/Command achievements". If I click on it, nothing happens and the server throws a NPE: http://pastebin.com/Dnng2SVK
I think this wasn't in 3.0-Beta, but I'm not sure at all.

2.) Annoying mouse jump:
After a click on a category the mouse always jumps to the middle of the screen. I don't know if this is intened, but it's quite annoying.

Cheers and thank you for your hard work! :)

**Comment by PyvesB** [comment]
Hello,

Glad you mostly enjoy the update! :-)

Thanks for the reports, I'll look into them, and try to issue an update quickly.

Cheers,

Pyves
