### ISSUE TITLE
When changing the order of categories, the GUI doesn't update after /aach reload; only after reboot. 

### ISSUE THREAD

**Issue by MCHalfAssed** [PyvesB/AdvancedAchievements#650]
Not sure if this is intended - Just something I noticed.

After changing the order of categories in the GUI.yml, /aach reload doesn't update the order in the in game GUI. It does however update the Items used to represent the categories.

Only after a server reboot does it take effect.

**Comment by PyvesB** [comment]
Hello @MCHalfAssed, thanks for reporting. No, this isn't intended. I'll see whether I can fix it! :wink:

**Comment by PyvesB** [comment]
Any better?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4145232/AdvancedAchievements.zip)

**Comment by MCHalfAssed** [comment]
Nope, still the same.

**Comment by PyvesB** [comment]
Hmmm, I'm under the impression that it's a limitation in the configuration file classes provided by the Bukkit API. Will do a bit more digging, but may simply end up putting a notice in _gui.yml_ saying that modifying the ordering requires a full restart.

**Comment by MCHalfAssed** [comment]
That sounds fine to me. I'll close the issue for now then.

**Comment by PyvesB** [comment]
Okay, I've given it another go and I think I've got a workaround. Would you mind trying out this new version?
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4150487/AdvancedAchievements.zip)
