### ISSUE TITLE
Achievements based on money (vault / economy)?

### ISSUE THREAD

**Issue by SubBass100** [PyvesB/AdvancedAchievements#652]
having over a certain dollar amount will trigger achievements. For example, you sell some blocks and make over 100 bucks (achievement is for over 100) Achievement: "Hundredaire!"

Sorry if this already exists but I've not seen anything other than Money "rewards" in the documentation.

Thank you!

**Comment by PyvesB** [comment]
Hello @SubBass100,

This was suggested a few years back (#39), but not implemented. It would be extremely easy to abuse such a category: a rich player could award all achievements to another player by transferring money with a single command. This defeats the point of a money-based category.
