### ISSUE TITLE
BossShopPro error with Advanced Achievement

### ISSUE THREAD

**Issue by ajves** [PyvesB/AdvancedAchievements#653]
Hello. I've got problem with AA and BSP, cuz when install AA then BSP menu immediately crash.

**Comment by PyvesB** [comment]
Hi @ajves , I suggest going through the [contribution guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md). 😉

**Comment by ajves** [comment]
Okay, u can close this topic, thanks
