### ISSUE TITLE
Cant add multiple lines for goal in command achievements

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/AdvancedAchievements#654]
It would be nice if you could add multiple lines to the goal in command achievements so you can write a bit about how to get the achievement. Or maybe a lore section

**Comment by PyvesB** [comment]
Hello @JHarris12345, done! Using `\n` will display multiple lines in _/aach list_. Note that the advancement descriptions created with _/aach generate_ will only appear on one line, with spaces. This is a Minecraft limitation I can't do anything about. 😉

**Comment by JHarris12345** [comment]
It doesnt work in the latest

**Comment by PyvesB** [comment]
Just double-checked - works fine for me. Please make sure you're actually using version 5.14.1 of the plugin and check out the example in the default configuration!
