### ISSUE TITLE
updated to latest version and console being spammed

### ISSUE THREAD

**Issue by Shewolf1896** [PyvesB/AdvancedAchievements#657]
`WARN [AdvancedAchievements] Task #88 for AdvancedAchievements v5.14.0 generated an exception
12.02 14:04:30 [Server] INFO java.lang.NoClassDefFoundError: com/hm/achievement/db/CachedStatistic
12.02 14:04:30 [Server] INFO at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:122) ~[?:?]
12.02 14:04:30 [Server] INFO at com.hm.achievement.runnable.AchieveDistanceRunnable.updateDistance(AchieveDistanceRunnable.java:141) ~[?:?]
12.02 14:04:30 [Server] INFO at com.hm.achievement.runnable.AchieveDistanceRunnable.validateMovementAndUpdateDistance(AchieveDistanceRunnable.java:106) ~[?:?]
12.02 14:04:30 [Server] INFO at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_222]
12.02 14:04:30 [Server] INFO at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_222]
12.02 14:04:30 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_222]
12.02 14:04:30 [Server] INFO at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:63) ~[?:?]
12.02 14:04:30 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-102]
12.02 14:04:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**Comment by PyvesB** [comment]
Hello @Shewolf1896, did you not follow the [update instructions](https://github.com/PyvesB/AdvancedAchievements/wiki/Updating-the-plugin)? These kind of errors typically happen when you're messing around with plugin files on a running server. 😉
