### ISSUE TITLE
Question - Achievements runs over 100%

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#659]
I have

3 Spigot-Servers (Every Server has this plugin and uses the same database)

But every server has different disabled categories. I thought that these successes would not be counted in the percentage.

Can you add this?

**Comment by PyvesB** [comment]
Hi @R4zzerYT , I don't understand what the problem is. Could you please clarify?

**Comment by R4zzerYT** [comment]
The disabled categories are still included at /aach stats.

Example:
I have 2 servers, on Server-1 is it possible to get Build and Break Achievements.

I completed all challenges from the Build and Break Categories on Server-1.

But on Server-2 (The Lobby) are these categories deactivated at "Disabled Categories" in the config.

If i want to see my Achievement-Stats with /aach stats, are the disabled categories still included: https://imgur.com/xGMc6LU

**Comment by PyvesB** [comment]
_/aach stats_ simply issues a database query that counts all achievements of a given player UUID. Most commands operate like this and are really fast as they operate at the SQL level with no knowledge of the configuration file. The purpose of having a shared database it to share statistics and achievements; it seems like you want to do the exact opposite, i.e. having different sets of categories achievements on each server, therefore it makes sense to let each server use a dedicated database. 😉
