### ISSUE TITLE
Im Making a new translate

### ISSUE THREAD

**Issue by PokeMy14** [PyvesB/AdvancedAchievements#660]
I making a new translated archives ENGLISH to SPANISH. How can i give you.
![Captura](https://user-images.githubusercontent.com/58641360/74433627-0f143c00-4e61-11ea-9997-2a542956aed5.JPG)

**Comment by PyvesB** [comment]
Hello @PokeMy14 ! Thanks for this! @arciniegasdiaz happens to have submitted an update to the Spanish translation as well in #661. Maybe you could take a look and review his changes? 😄

**Comment by PyvesB** [comment]
The aforementioned pull request has been merged, feel free to open a new one to propose changes (see the [GitHub documentation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) on how to raise PRs).

**Comment by PokeMy14** [comment]
Thanks Pierre Yves.

Maybe the next time.
