### ISSUE TITLE
Kills not going up

### ISSUE THREAD

**Issue by AlwaysAllstar25** [PyvesB/AdvancedAchievements#662]
My kills aren't increasing when I kill a player. I made sure I have the 'permissionachievement.count.Kills.player'. Even when I'm OP my kills aren't going up so I know permissions aren't the problem. 
Here's my config: https://pastebin.com/t1riqruE
I also just updated to the most recent version (5.14.1)
I'm using paper 1.14.4
Nothing comes up in log when I kill someone. 
Here's my log when my server starts up if that helps: https://pastebin.com/bqjuLD9H
Thank you!

**Comment by PyvesB** [comment]
Hi @AlwaysAllstar25 , are `Slayer_I`, `Slayer_II`, etc. player names or something? Your configuration is basically stating "you need to kill 50 things called Slayer_I to get the achievement Slayer I". 😉

**Comment by AlwaysAllstar25** [comment]
Thank you @PyvesB. Dumb mistake on my part, I got it working now when I am OP but the kills don't go up when I'm not OP. I'm guessing that must be the cause of permissions. Is 'achievement.count.Kills.player' the correct permission? My config is now: https://pastebin.com/kfc5pbeY

**Comment by PyvesB** [comment]
@AlwaysAllstar25 no worries!

Have you tried the permission without the capital `K`: `achievement.count.kills.player`?

**Comment by AlwaysAllstar25** [comment]
I just did, still doesn't seem to be working.

**Comment by PyvesB** [comment]
Have you simply tried giving the parent permission, `achievement.count.kills`?

**Comment by AlwaysAllstar25** [comment]
@PyvesB I solved the issue. I had achievements.* set as false and then added the permissions I wanted to include. I removed achievements.* and just set all the ones I wanted disabled to false individually. In the end the permissions to everything stayed the same, just it was a lot more work having to set each one to false individually rather than just setting achievements.* to false and adding the ones I wanted. I believe this is a bug where achievements.* being set to false disables counting of player kills even when they're allowed separately with the permission achievement.count.kills.player, or it may just be my permission plugin acting weird. Thank you! :)

**Comment by PyvesB** [comment]
Glad to hear that you've found a solution!

Could you please try the following though: set both `achievement.count.kills` and `achievement.count.kills.player` to true, but `achievement.*` to false?

**Comment by AlwaysAllstar25** [comment]
@PyvesB I did as you said and it did work. Thank you! :)

**Comment by PyvesB** [comment]
Awesome! As everything is solved, I'll go ahead and close this issue. Feel free to star the repository. 😉
