### ISSUE TITLE
Error with the A Placeholder for PlaceholderAPI (at Updating)

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#665]
%aach_achievements_percentage%

- Spigot Paper 1.15.2 (b102)

Error (Spamming, too much for upload my completly log): https://pastebin.com/U8Q8euiT

Versions:

PlaceholderAPI - 2.10.4
AdvancedAchievements - 5.14.1
TabList - 5.1 (Link: https://www.spigotmc.org/resources/animated-tab-tablist.46229/)

**Comment by PyvesB** [comment]
Hi @R4zzerYT, thanks for reporting, this should now be fixed!

**Comment by R4zzerYT** [comment]
Where can i download the patch? Because that bug greatly affects server performance.

**Comment by PyvesB** [comment]
You can build the plugin from source as described [here](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#setting-your-own-working-copy-of-the-project).

By the way I strongly doubt an occasional error when a player disconnects would affect performance in any noticeable way. Exception handling is fast in Java nowadays, unless TabList is doing something weird on the back of the exception.

**Comment by R4zzerYT** [comment]
TabList spammed many times in a second this error from the first line

**Comment by R4zzerYT** [comment]
Thank you!
