### ISSUE TITLE
Assemble categories

### ISSUE THREAD

**Issue by Bleache7500** [PyvesB/AdvancedAchievements#667]
Hello,
I recently download the plugins, it work perfectly. I just want to know if there is a way to combine two categories. For example, is there a way to have a categories where we can find a challenge where I have to break stone and one where I have to place dirt. Something like :

  #Name of the gui
  Name : Place/Break
      
      #Name of the challenge 
      Quest_ID : break_stone_100
      #Every classic settings here
      Goal: Break 100 Stones.
      Message: One hundred breaked stones!
      DisplayName: Stone Addict
      #And here the type of the challenge like place, break ....
      Type : Break
      #And the block_id
      block_id : stone

#And here we can add an another challange

      #Name of the challenge 
      Quest_ID : place_dirt_100
      #Every classic settings here
      Goal: Place 100 Dirt.
      Message: One hundred placed stones!
      DisplayName: Dirt Addict
      #And here the type of the challenge like place, break ....
      Type : Place
      #And the block_id
      block_id : dirt

And in game we can see something like in the screen : 
![Capture](https://user-images.githubusercontent.com/61255856/74887154-6d1db380-537a-11ea-9cb5-588daf668b36.PNG)
![Capture1](https://user-images.githubusercontent.com/61255856/74887153-6d1db380-537a-11ea-855f-c577e0939306.PNG)

Thank you and good luck :) !

**Comment by PyvesB** [comment]
Hi @Bleache7500 , unfortunately this isn't possible. The GUI can only display one item per category, there is now way to combine several categories in one. 😉
