### ISSUE TITLE
Bug with death achievement

### ISSUE THREAD

**Issue by JohOply** [PyvesB/AdvancedAchievements#67]
Hi guys,

I think there is a bug with death achievement: i obtain first achievement for each new type of death (first time with /slay command, next time with a fall down, another time when a zombie killed me...)

It's really interesting to have achievements for each type of death, but for now seems be a bug

I use AACH 3.0 and Spigot 1.10.2

**Comment by PyvesB** [comment]
Hello,

Death achievements do not currently support different types, only Kills, Places, Crafts and Breaks do. ;-)

Cheers,

Pyves

**Comment by JohOply** [comment]
Yeah i understand that. But the problem seems be here! I will try to explain: i tried the plugin today, and i kill myself many times. First i used /slay, i got achievement. Next /slay, no achievement, next the same, etc.
Some time later, on the same session, i dead because of a zombie. Achievement appear (there is only an achievement for the first death in config).
Some time later again, i fall on the ground and i was dead. Achievement appear again.

**Comment by PyvesB** [comment]
I have not been able to reproduce this bug.

- What version of the plugin are you using?
- What database type?
- Can you show me the Deaths section of your config?
- Have you got any plugin errors or warnings in the console?
- Did you change anything in the config between two same achievement receptions?

**Comment by JohOply** [comment]
- Plugin version 3.0.2
- Mysql
- http://pastebin.com/133uPVhy (i'm not sure that was the config when the problem happen :/)
- I don't remember any error (i can't check right now)
- I don't remember, BUT if it is the case, what happen? :)

**Comment by PyvesB** [comment]
I do currently not have enough spare time, but I'll look into it again eventually with the information you added. ;-)

**Comment by JohOply** [comment]
Mhhh, i think there is the same with other achievements.. i will investigate too ^^

**Comment by JohOply** [comment]
Yesterday i got "first hour" achievement. Today, i joined the server, a few time later : got achievement again

Here 2 books: i got one yesterday, another today
http://i.imgur.com/WJ65OKO.png
http://i.imgur.com/8w2P7Vg.png

**Comment by PyvesB** [comment]
Did any errors appear in the console yesterday or today? Could you please send me your full config?

**Comment by JohOply** [comment]
Oh wait, lot of errors

> The last packet successfully received from the server was 102,347 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
> [18:57:44] [Server thread/INFO]: [AdvancedAchievements] Player JohOply received the achievement: playedtime_1 (First Hour)
> [18:58:06] [Server thread/INFO]: JohOply issued server command: /aach book
> [18:58:06] [Server thread/ERROR]: [AdvancedAchievements] SQL error while retrieving achievements: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
> [19:04:32] [Craft Scheduler Thread - 1127/ERROR]: [AdvancedAchievements] SQL error while handling play time registration: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure. The last packet successfully received from the server was 379,150 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.

**Comment by PyvesB** [comment]
Okay, no wonder you are having issues. This is weird though, I have never encountered this type of errors before. Most related topics I found generally point out to a problem on the client side. Could you make sure you are using the latest version of the MySQL JDBC driver? Also, can you try restarting your database service. If you still have problems after this, there are additional steps you can try out, described in the top answers of the following links:  [link 1](http://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai), [link 2](http://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql)

**Comment by PyvesB** [comment]
Hello,

As it has been more than two weeks, I'm assuming you managed to solve the issue with the links I gave you, and am therefore closing the issue.

Cheers,

Pyves
