### ISSUE TITLE
I dont get my rewards

### ISSUE THREAD

**Issue by MysticCity** [PyvesB/AdvancedAchievements#672]
Paper 1.14.4
Config: https://pastebin.com/vMkiP8Cd

I dont get Rewards
Only for 1 Time Achievements
Multi Achievements dont work for me.

**Comment by PyvesB** [comment]
Hello @MysticCity,

The key is `Reward`, not `Rewards`. I suggest[ reading the Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards) for more information. 😉

**Comment by MysticCity** [comment]
OMG im so )(/&%()/&%$& thx
