### ISSUE TITLE
Player hearts

### ISSUE THREAD

**Issue by nintendnerd** [PyvesB/AdvancedAchievements#674]
There doesn't seem to be a way to reset a players extra hearts once earned.  I've even tried editing the player nbt data to no avail.

**Comment by PyvesB** [comment]
Hi @nintendnerd , does #416 help?

**Comment by nintendnerd** [comment]
It did, but that seems pretty drastic

**Comment by PyvesB** [comment]
An alternative could be to allow users to specify negative values (if that's not already the case, I can't quite recall). You could then specify a command-based achievement with a negative reward to compensate the excess. 😉

**Comment by nintendnerd** [comment]
okay that helps.  I'm having an issue getting extra air to work at all.  I gave like 300 and noticed no change to the time you can spend underwater.  Is there a trick to this?
