### ISSUE TITLE
Placeholder for Leaderboard

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#675]
Hey, can you add placeholders for the /aach top list?

**Comment by PyvesB** [comment]
Hello @R4zzerYT, probably won't be added as computing the _/aach top_ list is quite performance intensive and I can foresee some third-party plugins hammering placeholder requests at an unreasonable rate. This would bring any server down to its knees. Also, the PlaceholderAPI integration is not one that I wrote myself, yet I'm having to maintain it and provide support to unhelpful users (see #669 for example). I'm not planning on expanding it any further, sorry.
