### ISSUE TITLE
Trying to add new achievements

### ISSUE THREAD

**Issue by unholymac** [PyvesB/AdvancedAchievements#676]
i've been trying to add the new achievements like RaidsWon & Advancements Completed and they're still disabled, i can't find i guide anywhere!

Please Help!

RaidsWon: 
  RaidsWon_1:
    Goal: Complete 1 Raid.
    Message: You Completed Your First Raid!
    Name: RaidsWon_1
    DisplayName: First Raid Complete
    Reward:
      Experience: 100
  '5':
    Goal: Complete 5 Raids.
    Message: You've Won 5 Raids!
    Name: RaidsWon_5
    DisplayName: Villager's Guard
    Reward:
      Experience: 500
  '10':
    Goal: Complete 10 Raids.
    Message: You've Won 10 Raids!
    Name: RaidsWon_10
    DisplayName: You're a Hero!
    Reward:
      Command:
        Execute: cc give physical basic 1 PLAYER
        Display: 1 &fIron Key!
  '25':
    Goal: Complete 25 Raids.    
    Message: You've Won 25 Raids!
    Name: RaidsWon_25
    DisplayName: Way better than a Iron Golem
    Reward:
      Command:
        Execute: cc give physical classic 1 PLAYER
        Display: 1 &6Gold Key!
  '50':
    Goal: Complete 50 Raids.
    Message: You've Won 50 Raids!
    Name: RaidsWon_50
    DisplayName: Village Protector
    Reward:
      Command:
        Execute: cc give physical Galactic 1 PLAYER
        Display: 1 &aEmerald Key!
  '100':
    Goal: Complete 100 Raids.
    Message: You've Won 100 Raids!
    Name: RaidsWon_100
    DisplayName: Winner Winner Village Dinner
    Reward:
      Command:
        Execute: cc give physical crazy 1 PLAYER
        Display: 1 &bDiamond Key!
AdvancementsCompleted:
  '1':
    Message: Completed 1 Advancement!
    Name: AdvancementsCompleted_1
    DisplayName: First Advancement!
    Reward:
      Experience: 10
  '10':
    Message: Completed 10 Advancement!
    Name: AdvancementsCompleted_10
    DisplayName: Tenth Advancement!
    Reward:
      Experience: 100
  '20':
    Message: Completed 20 Advancement!
    Name: AdvancementsCompleted_20
    DisplayName: Twenty Advancements!
    Reward:
      Command:
        Execute: cc give physical basic 1 PLAYER
        Display: 1 &fIron Key!
  '30':
    Message: Completed 30 Advancement!
    Name: AdvancementsCompleted_30
    DisplayName: Thirty Advancements!
    Reward:
      Command:
        Execute: cc give physical classic 1 PLAYER
        Display: 1 &6Gold Key!
  '40':
    Message: Completed 40 Advancement!
    Name: AdvancementsCompleted_40
    DisplayName: Forty Advancements!
    Reward:
      Command:
        Execute: cc give physical classic 3 PLAYER
        Display: 3 &6Gold Keys!
  '50':
    Message: Completed 50 Advancement!
    Name: AdvancementsCompleted_50
    DisplayName: Fifty Advancements!
    Reward:
      Command:
        Execute: cc give physical Galactic 1 PLAYER
        Display: 1 &aEmerald Key!
  '60':
    Message: Completed 60 Advancement!
    Name: AdvancementsCompleted_60
    DisplayName: Sixty Advancements!
    Reward:
      Command:
        Execute: cc give physical Galactic 3 PLAYER
        Display: 3 &aEmerald Keys!
  '70':
    Message: Completed 70 Advancement!
    Name: AdvancementsCompleted_70
    DisplayName: Seventy Advancements!
    Reward:
      Command:
        Execute: cc give physical crazy 1 PLAYER
        Display: 1 &bDiamond Key!

**Comment by PyvesB** [comment]
Hi @unholymac, you seem to be missing the statistic threshold for `RaidsWon_1`. 😉

**Comment by unholymac** [comment]
I had that there because I tried both numbers and name_number and neither on them worked

**Comment by PyvesB** [comment]
Are the categories included in `DisabledCategories` by any chance?

**Comment by unholymac** [comment]
when i load up the server it says its a Disabled Category in the console

**Comment by PyvesB** [comment]
Problem solved then?

**Comment by unholymac** [comment]
nah I did reply saying when I load up the server it says it's a disabledcatagory and doesn't work

**Comment by PyvesB** [comment]
I'm confused - I told you which configuration parameter to check, and you confirmed that it was indeed disabled there. It you want to _enable_ the category, you have to remove it from the _disabled_ categories list. 😉

**Comment by unholymac** [comment]
ah sorry i didn't understand what you meant, i will give it a go now

**Comment by unholymac** [comment]
Yeah that worked :D sorry about that i didn't realise there was a disabled catagory in the config

**Comment by PyvesB** [comment]
That's okay! I strongly recommend going through the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki), the behaviour of that parameter is mentioned a few times in there! :)
