### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by fuzzybear3232** [PyvesB/AdvancedAchievements#677]
Uploaded the .jar into my FTP, fails on launch. 

[https://pastebin.com/R08eMNf2](https://pastebin.com/R08eMNf2)
please help
if you need to see the ".,, 12 more" me too pal don't know how to see them.

**Comment by PyvesB** [comment]
Hello @fuzzybear3232,

This seems to be a configuration issue with your Unix system: your server is not allowing Advanced Achievements to create any of its configuration files. 😉

**Comment by fuzzybear3232** [comment]
Well I'm happy you could identify the problem but I have no clue how to go about fixing that. Any tips, I'm intuitive but not experienced :)

**Comment by PyvesB** [comment]
Two things I would check:
* what are the permissions on the `plugins/AdvancedAchievements` folder? You can type `ls -l` in a Unix command prompt to display them.
* what user is the server process running as? You can type `ps -ef | grep java` or `ps -ef | grep spigot` in a Unix command prompt to display it.

**Comment by PyvesB** [comment]
Any luck with the above @fuzzybear3232 ?
