### ISSUE TITLE
My config is not working

### ISSUE THREAD

**Issue by FraazT0** [PyvesB/AdvancedAchievements#68]
I have really no clue why. Two achievements of those I added that crash the plugin. Removing them makes the plugin work fine.
First one:
http://pastebin.com/bXPp5eh5
Second one;
http://pastebin.com/G7XZYYQ9
Any clue about what makes them crash the plugin?

**Comment by PyvesB** [comment]
Hello,

In the first one, try to double the apostrophes and remove the backslashes ('&8Rock ''n'' roll'). In the second one you forgot an apostrophe at the end of the Message parameter. ;-)

Cheers,

Pyves
