### ISSUE TITLE
Question - Normal/Goal/Challenge

### ISSUE THREAD

**Issue by LegalSmeagol** [PyvesB/AdvancedAchievements#680]
Hello.

For my question, please refer to: https://minecraft.gamepedia.com/Advancements.

Default advancements display different shaped backgrounds depending on if they're a normal, goal or challenge achievement. In AdvancedAchievements, I believe it shows the icon as "normal" when completed and "challenge" when it's the next achievement. It would be nice to choose whether to show "Advancement Made" or "Goal Reached" or "Challenge Complete" depending on certain variables set in the config.

Two questions I have:
A) Is there anyway to change this background shape on achievements?
A) Is there anyway to organise the custom advancement tab for AdvancedAchievements to organise it a little better?

**Comment by PyvesB** [comment]
Hello @LegalSmeagol,

> In AdvancedAchievements, I believe it shows the icon as "normal" when completed and "challenge" when it's the next achievement. It would be nice to choose whether to show "Advancement Made" or "Goal Reached" or "Challenge Complete" depending on certain variables set in the config.

Actually not quite:
* the root achievement is of type "goal".
* the last achievement of category or sub-category (i.e. the ones with the highest threshold) is of type "challenge".
* all other achievements are "normal".

> Two questions I have:
> A) Is there anyway to change this background shape on achievements?
> A) Is there anyway to organise the custom advancement tab for AdvancedAchievements to organise it a little better?

One thing you could do is modify the JSON files generated by the plugin on your server. :wink:
