### ISSUE TITLE
It is possible for a player to get the items from the GUI

### ISSUE THREAD

**Issue by Saphirrcr** [PyvesB/AdvancedAchievements#684]
Hello,
I encountered an issue that led me to temporarly disable the plugin: under one condition I succeeded to get the content of the plugin's GUI (/aach list).

**In 4 steps:**
- Use 1.15.2 Spigot / AdvancedAchievements v5.15.1
- Set game time at night, then enter a bed
- As you sleep execute the command "/aach list"
- Shift-left-click the GUI items to retrieve the items (such as Elytra) before the night ends, then close the GUI

![2020-03-19_13 28 24](https://user-images.githubusercontent.com/29708237/77152285-ed2d5b00-6a97-11ea-9d9e-4b5362850eae.png)

**Comment by PyvesB** [comment]
Hi @Saphirrcr, that's an interesting bug, thanks for reporting it! Will look into it. 😉

**Comment by PyvesB** [comment]
This seems to be a bug with Spigot: when a player is in a bed, `InventoryClickEvent`s are not fired, therefore there is no way for Advanced Achievements to say "hang on, this is an Advanced Achievements inventory, you are not allowed to take this item out of it".

Could you please report a bug on the [Spigot issue tracker](https://hub.spigotmc.org/jira/secure/Dashboard.jspa)?

**Comment by metalshark** [comment]
@PyvesB I cannot see any handlers for InventoryDragEvent? Are you 100% that InventoryClickEvent is enough here?

**Comment by metalshark** [comment]
> @PyvesB I cannot see any handlers for InventoryDragEvent. Are you 100% that InventoryClickEvent is enough here?

Yup, I was wrong. Have submitted a pull request with a workaround. Couldn't find a bug report in Spigot, so am raising one now.

**Comment by Saphirrcr** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5637?focusedCommentId=36433&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36433

Here is the answer from md_5 :
> "Basically intended, players aren't meant to be able to do anything aside from chat when sleeping"

**Comment by metalshark** [comment]
Ah @Saphirrcr sorry, didn't find that when searching. Submitted a pull request with a fix:
https://github.com/PyvesB/AdvancedAchievements/pull/702

**Comment by PyvesB** [comment]
Thanks both for raising the issues! Let's see where we get with them. 😉

**Comment by PyvesB** [comment]
By the way, if you haven't done so already, it may be worth voting on the Spigot issue. Not sure how much attention they pay to votes, but it can't hurt!

**Comment by metalshark** [comment]
> By the way, if you haven't done so already, it may be worth voting on the Spigot issue. Not sure how much attention they pay to votes, but it can't hurt!

The day after (in Paper at least)
https://github.com/PaperMC/Paper/commit/d847d336843e40deb5202956868a50a65e12ca85

**Comment by PyvesB** [comment]
> The day after (in Paper at least)
> [PaperMC/Paper@d847d33](https://github.com/PaperMC/Paper/commit/d847d336843e40deb5202956868a50a65e12ca85)

Good to hear. Paper has generally been more open to admitting and fixing issues.
