### ISSUE TITLE
Log Names 1.12.2

### ISSUE THREAD

**Issue by iRobSch** [PyvesB/AdvancedAchievements#686]
Hello everyone,

I am having an issue with the 1.12.2 material list. I was playing on a server and I saw that they had AdvancedAchievements installed, on 1.12.2, and had multiple challenges like 'Placed x Oak Logs' and 'Placed x Birch Logs', so I knew this would be possible to do through configuration.

In the 1.12.2 list, it does not say 'oak_log' and 'birch_log', but just 'log'. In-game, you can 'log:2' to get birch logs, but when I put this into the configuration, it broke it: when a birch log is placed, it adds up to the birch log achievements, but also to the oak log achievements. 

Does anyone here know what ID(s) to use to do this with? I know it's possible, as it's used on another server, but I don't know how exactly.

Thanks in advance,
iRobSch.

**Comment by PyvesB** [comment]
Hi @iRobSch, 

> Does anyone here know what ID(s) to use to do this with? I know it's possible, as it's used on another server, but I don't know how exactly.

Is this other server also 1.12 or older?

Old versions of Minecraft handle wood really poorly, there are only two material types, `log` and `log2`, and the IDs have something to do with the log orientation and positioning if I remember correctly. Things would really be easy in Minecraft 1.13 or newer, I would definitely recommend updating as soon as possible. 😉

**Comment by iRobSch** [comment]
The client's server is located on 1.12.2 and cannot change. I saw a server have the different wood type achievements, so I know it's possible. Even if it's hard, what options do I have to introduce these challenges?

**Comment by PyvesB** [comment]
> Even if it's hard, what options do I have to introduce these challenges?

The only option the plugin provides in this area is to use IDs, so it's a matter of getting those IDs right. I'll see if I can get an old 1.12 server running, but let me know if you manage to sort things out in the meantime!

**Comment by iRobSch** [comment]
Thanks a lot. I have another question if that wouldn't be too much to ask:

I'm trying to make an achievement in the break section for the crops. I put 'wheat:', but it's not working.
Configuration:
  wheat:
    10:
      Goal: Break 10 wheat.
      Message: §fYou have harvested 10 wheat!
      Name: break_10_wheat
      DisplayName: Wheat Farmer I
      Reward:
        Command:
          Execute: "addlevels PLAYER herbalism 5; btc give PLAYER 5"
          Display: +5 Herbalism McMMO Levels and +5 BTC Currency

**Comment by PyvesB** [comment]
I've just successfully tested things out on an old 1.12 server, using `log:2|log:6|log:10|log:14` should cover all orientations of birch logs, but not any other kind of wood.

As far as wheat is concerned, if you want to track harvesting fully-grown wheat, you need to specify `crops:7` rather than `wheat`. If I remember correctly `wheat` is the material name for already harvested wheat once you hold it in hand, therefore it's not something you can break. :wink:

Hope this helps!

**Comment by iRobSch** [comment]
Thanks for the response, the crops:7 works! Now, I have one last issue: carrots and potatoes don't work.

Current configuration for carrots:
`  carrots:7:
    '10':
      Goal: Harvest 10 carrot.
      Message: §fYou have harvested 10 carrot!
      Name: harvest_10_carrot
      DisplayName: Carrot Farmer I
      Reward:
        Command:
          Execute: addlevels PLAYER herbalism 5; btc give PLAYER 5
          Display: +5 Herbalism McMMO Levels and +5 BTC Currency`

**Comment by iRobSch** [comment]
Anything regarding this?^^

**Comment by PyvesB** [comment]
Try out `carrot:7`, without the `s`! Similarly, `potato:7`. `sugar_cane_block` for sugar cane.

This [Wiki page](https://github.com/PyvesB/AdvancedAchievements/wiki/Material-names), even though imperfect, should help getting the names right. 😉

**Comment by PyvesB** [comment]
@iRobSch did the above help?
