### ISSUE TITLE
Server delay with AdvancedAchievements

### ISSUE THREAD

**Issue by jere62smi** [PyvesB/AdvancedAchievements#687]
Hello,

I noticed that with a huge number of players (From 40), AdvancedAchievements seems to cause the server to drop, TPS drop.
I contested that in my timings.
http://img.scalebound.club/51qzuc2t.png

I use paper 1.15.2

**Comment by PyvesB** [comment]
Hi @jere62smi, does #567 help?

**Comment by jere62smi** [comment]
Precisely I have already looked at this one, my server is divided into 2 servers for more performance so I use as MySQL database.

**Comment by PyvesB** [comment]
Could you please temporarily try running H2 on a single server and see whether the performance is any better after a few hours/days?

**Comment by jere62smi** [comment]
It's not possible, unfortunately I cannot allow my players to have unsynchronized achievements.

**Comment by PyvesB** [comment]
If you're unwilling to try things out to assist with debugging, there's nothing much I can do to help out. The only thing I could suggest based on the very limited timings extract you shared would be to disable the `PlayedTime` achievements category.
