### ISSUE TITLE
reset the hearth who Aach give

### ISSUE THREAD

**Issue by zephirox58** [PyvesB/AdvancedAchievements#688]
hello I have a little problem, some basic achievement give more hearts to the days, is it possible to remove them? I can't find the solution

**Comment by PyvesB** [comment]
Hi @zephirox58, please see #674 for the solution. 😉

**Comment by zephirox58** [comment]
actually I uninstall the plugin to put it back in a few months, but the hearts are staying, I have to uninstall the plugin, create an achievement with a negative reward and then uninstall the plugin?

**Comment by PyvesB** [comment]
> actually I uninstall the plugin to put it back in a few months, but the hearts are staying, I have to uninstall the plugin, create an achievement with a negative reward and then uninstall the plugin?

No need to uninstall the plugin, but yes, create an achievement with a negative reward.

**Comment by zephirox58** [comment]
ok thanks you =)

**Comment by zephirox58** [comment]
ok .. i was tried it but ... player with 23 hearth and player with 20 hearth accepte the achievment and now they have 18 .... :'( no way to reset to 20 for all ?
