### ISSUE TITLE
General error: "java.lang.IllegalStateException: Unable to read the page at position

### ISSUE THREAD

**Issue by EmpathyHeals** [PyvesB/AdvancedAchievements#689]
i deleted some plugins off my server to troubleshoot lag, but i did not touch advanced achievements. unfortunately it won't load now after i restarted and get a General error: "java.lang.IllegalStateException: Unable to read the page at position 156699098656097097 [1.4.200/6]" [50000-200]. 

log: https://pastebin.com/qj6xaxyf

from researching this online i suspect my h2 database is corrupt, and to fix the problem i would need to restore from backup. the thing is, i have backups, but i'm unsure how to conduct a restore that works. i turned the server off and replace the corrupt one with a backup copy, but after i reboot the the server, the database size changes and the plugin still doesn't load. 

any help is appreciated.

**Comment by EmpathyHeals** [comment]
bump

**Comment by PyvesB** [comment]
> bump

Bump after barely a day? That seems pretty abusive.

**Comment by EmpathyHeals** [comment]
i just want to restore my database and was hoping there is a way to do it without anything needing to be fixed in the code or troublehshooted extensively. maybe i'm being eager but i thing calling a bump on a forum abusive is about as exaggerated, if not more, as my hopes for a quick answer. you can just let me know if it's going to take some time or it's complicated, i can wait and i'm friendly and patient. last thing i want to be is abusive, but what i can't do is change people's interpretation.

**Comment by PyvesB** [comment]
Try replacing the _achievements.db_ file from a working backup and delete any other database files that may have crept in the _plugins/AdvancedAchievements_ folder. Also, the following log line seems fishy:

> [08:20:08] [Server thread/WARN]: [AdvancedAchievements] Loaded class org.hsqldb.jdbc.JDBCDriver from AdvancedBan v2.1.6 which is not a depend, softdepend or loadbefore of this plugin.

Please disable AdvancedBan when you do that operation as well.

**Comment by EmpathyHeals** [comment]
thank you for replying. when i delete all database files (it's h2 by the way) and copy a backed up achievements.db, it creates a achievements.mv.db and says "you connected to our server for the first time! when logging in. when copying a backed up achievements.mv.db instead, the plugin does not load (gives that error and is red in /plugins).

**Comment by PyvesB** [comment]
Could you please upload and share the oldest backup you have, I'll see whether I can get it to run locally?

**Comment by EmpathyHeals** [comment]
[EmpathyHeals_AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4400074/EmpathyHeals_AdvancedAchievements.zip)
That's my backup folder

**Comment by PyvesB** [comment]
I highly doubt that's a backup from when the plugin was still working properly on your server. It's not even a H2 database, it's a perfectly working SQLite database, but only containing data for player with UUID `e9920ad3-f957-4873-8559-6c60c0547714`.

**Comment by EmpathyHeals** [comment]
there are two database files in there, [![Screenshot from Gyazo](https://gyazo.com/ffaa4fc41a4ddccb6287f3122e567197/raw)](https://gyazo.com/ffaa4fc41a4ddccb6287f3122e567197)

achievements.db and achievements.mv.db

i don't know why two were made. it's the second, achievements.mv.db file that has the data for all the players. not the first one. but anyway, someone on spigot replied after i shared my boot up log with them and they said: "well i indentified ur problem.
your Sql driver updated. or the developers updated.
the database file u try to use is not made or readable in the same version of yours on your server.
Make sure that your programs and drivers on your server are up 2 date. and not beyond that.
the database file is intact its just made for a newer or older version of the H2 Driver.
you can ask the dev what version he uses and adjust the db file to it by using a DB editor or manager using the correct driver.

or whats more easy just wipe that db and give players their requested achievements back or let them get them again."

does that help? can you help me figure out what i need to do to a) have just one database and b) get the database to be read?

**Comment by metalshark** [comment]
Ran an [H2 Database Recovery](http://www.h2database.com/javadoc/org/h2/tools/Recover.html) on your attached database:
[achievements.mv.db.zip](https://github.com/PyvesB/AdvancedAchievements/files/4409614/achievements.mv.db.zip)
Looks like data up until the 18th of March has been recovered:
![image](https://user-images.githubusercontent.com/146708/78036976-d376f800-7362-11ea-81bc-0592f5275b4c.png)

**Comment by PyvesB** [comment]
Nice! I had only tried analysing the main _achievements.db_ and hadn't understood that the other one was actually the backup!

**Comment by EmpathyHeals** [comment]
thank you!!
