### ISSUE TITLE
Block break achievements not counting with AutoSell plugin

### ISSUE THREAD

**Issue by download042** [PyvesB/AdvancedAchievements#692]
Latest AutoSell
https://www.spigotmc.org/resources/autosell.2157/
Lates ACH
Paper 1.15.2

No error in console.

Example config section: https://pastebin.com/LzrnPGBt

**Comment by PyvesB** [comment]
Hello @download042,

This is a known problem with AutoSell misbehaving and emitting invalid _BlockBreakEvents_ on servers. As previously explained in  #229 and #216, there's nothing much that can be done on Advanced Achievements' side. 😉

**Comment by download042** [comment]
Thank you for your answer.

**Comment by download042** [comment]
I can't find it, but, is there any option to se the priority of the listeneres in AACH? The AutoSell support team told me 
"It sets the block to AIR to clear the block drops when using /autosell
If you have the AACH listener above autosell, it should work fine
Does AACH allow you to change the priority of the listener?"

**Comment by PyvesB** [comment]
There is no way to change the priority of the listeners in Advanced Achievements, and it would be incorrect to modify the current setting. According to the [Bukkit API reference](https://bukkit.gamepedia.com/Event_API_Reference) for events:

> If you want to act when an event happens, but not change the outcome, use MONITOR. It's really really important that you use MONITOR, or an event might get cancelled after you've acted on it [...]

All achievements listeners are set to `MONITOR` priority, in accordance with the Bukkit API. 

Here's a simple example of what could go wrong if Advanced Achievements stopped complying with the API. The Bukkit/Spigot ecosystem has hundreds of plugins that offer some form of block protection, for instance WorldGuard, Factions, GriefPrevention and many many others. If the priority of listeners was changed to anything else than `MONITOR`, Advanced Achievements would start incorrectly counting some block break events that are cancelled by these other plugins. Players could then repeatedly try breaking blocks in a protected zone and collect all `Breaks` achievements without even using up their tools. This is just one plugin abuse scenario, but you can probably imagine many more and for pretty much every achievement category.

> It sets the block to AIR to clear the block drops when using /autosell

The correct way to do that using the Bukkit API would be to use `setDropItems(false)` (see [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockBreakEvent.html#setDropItems-boolean-)).

**Comment by PyvesB** [comment]
@download042 any news on this one? I'm not sure there's much value in keeping this issue opened on the Advanced Achievements repository. 😉

**Comment by download042** [comment]
nothing. close it if u want..
