### ISSUE TITLE
Suggest: Reset stats command

### ISSUE THREAD

**Issue by Atlantiis31** [PyvesB/AdvancedAchievements#693]
Hi,

Can you add a reset stats/achivements command, to reset all achievements of a player in one command?

Thanks for the plugin ! :)

**Comment by PyvesB** [comment]
Hi @Atlantiis31, sounds like a reasonable request, still unsure how much work it would be and whether I'll be able to get round to it anytime soon. Contributions welcome! :wink:

**Comment by Atlantiis31** [comment]
Thank you for your very quick reply !

I think this command would be a big plus for the plugin. :)
(Or a userdata file system)

Thanks for this great plugin and your working ! ;)

**Comment by PyvesB** [comment]
I had a bit of time to work on this feature this afternoon! Wildcards are now supported for the _/aach delete_ and _/aach reset_ commands (for example, _/aach delete * DarkPyves_). Here's a test version, let me know if you spot anything unexpected. 😉 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4434597/AdvancedAchievements.zip)
