### ISSUE TITLE
Customization Request

### ISSUE THREAD

**Issue by TheCashFire** [PyvesB/AdvancedAchievements#699]
The plugin, just to start, is working fine. Just as intended.

My issue is that the ability to customize the plugin is severely limited. I even looked into the GUI class files and found that some of the entries for the lore in the GUI is hard coded to be the way it is. My request is to add more variation to the GUI, specifically please either add a toggle or remove the forced italicization on non-completed achievements. I don't want non completed achievements showing up without their formatting.

Another request is for the node that numbers the achievements to be fixed, so heres an example: I have an achievement string that is Kill 50 Bats, then 100 Bats, then 150 Bats. I also have a string that says Kill 50 Bees, kill 100 Bees, and kill 150 Bees. If I toggle the achievement counting on, it counts all 6 of these achievements in order 1 - 6. I would like to request a toggle that makes it so that it counts it by the class or mob, so 1-3 for Bats and 1-3 for Bees. It doesn't make much sense to have an achievement counter for something that can only count in one string.

My last request is to add some information into the config file, such as the other placeholders besides AMOUNT and ITEM, and where and how they will work. I was looking to see if there were any other placeholders that would work in the lang file and it was a very difficult process.

Thanks!

**Comment by TheCashFire** [comment]
Also, found another thing. The list-reward-command: node only allows you to indicate one thing for ALL ACHIEVEMENTS. Could you make the reward node individual for each achievement? It would allow more diverse rewards to be shown, instead of just having to say 'Special Item'.

**Comment by PyvesB** [comment]
Hi @TheCashFire 

> The plugin, just to start, is working fine. Just as intended.

Good to hear.

> My issue is that the ability to customize the plugin is severely limited. I even looked into the GUI class files and found that some of the entries for the lore in the GUI is hard coded to be the way it is. My request is to add more variation to the GUI, specifically please either add a toggle or remove the forced italicization on non-completed achievements. I don't want non completed achievements showing up without their formatting.

If you've already looked into the relevant classes, why not submit a pull request? A toggle would probably be the right thing to do, as a vast majority of users appreciates the current styling for non-completed achievements.

> Another request is for the node that numbers the achievements to be fixed, so heres an example: I have an achievement string that is Kill 50 Bats, then 100 Bats, then 150 Bats. I also have a string that says Kill 50 Bees, kill 100 Bees, and kill 150 Bees. If I toggle the achievement counting on, it counts all 6 of these achievements in order 1 - 6. I would like to request a toggle that makes it so that it counts it by the class or mob, so 1-3 for Bats and 1-3 for Bees. It doesn't make much sense to have an achievement counter for something that can only count in one string.

I'm unclear what you're asking, could you please clarify?

> My last request is to add some information into the config file, such as the other placeholders besides AMOUNT and ITEM, and where and how they will work. I was looking to see if there were any other placeholders that would work in the lang file and it was a very difficult process.

Placeholders for rewards in _config.yml_ are all documented [here](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards). Placeholders for _lang.yml_ are self-documented in the [default language file](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/lang.yml), i.e. if one of the entries supports a placeholder, it will use it in a self-explaining way.

**Comment by TheCashFire** [comment]
Pardon my inexpertise, but what is a pull request?

In relation to the counter, hopefully I can clear it up. The counter counts every achievement in its section regardless of similarity, meaning if you had achievements to kill Bats, Bees, Pillagers, Dolphins, etc it would count all those achievements, in order, from the first achievement at the very top of the list to the very bottom of the list. My request is for it to count achievements based on creature killed, ie 'You have achieved the first Bat Achievement' or 'You have achieved the fourth Pillager Achievement' instead of counting them all in order as if they were all the same creature.

Ah, yes. I had just been wondering if there were any other placeholders not immediately used. Thank you for clarifying.

**Comment by PyvesB** [comment]
> Pardon my inexpertise, but what is a pull request?

Basically a code contribution. GitHub has some documentation [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests).

> In relation to the counter, hopefully I can clear it up. The counter counts every achievement in its section regardless of similarity, meaning if you had achievements to kill Bats, Bees, Pillagers, Dolphins, etc it would count all those achievements, in order, from the first achievement at the very top of the list to the very bottom of the list. My request is for it to count achievements based on creature killed, ie 'You have achieved the first Bat Achievement' or 'You have achieved the fourth Pillager Achievement' instead of counting them all in order as if they were all the same creature.

Do you mean the number enabled by the `NumberedItemsInList` configuration parameter?

> Ah, yes. I had just been wondering if there were any other placeholders not immediately used. Thank you for clarifying.

That's okay!
