### ISSUE TITLE
Buggy descriptions

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#7]
Hey,

for some reasons the descriptions at /aach list are very buggy. Would be awesome if you could fix it!

![2016-01-17_03 33 13](https://cloud.githubusercontent.com/assets/13700636/12375632/94be291e-bccb-11e5-87d3-c65c7aa39440.png)

**Comment by PyvesB** [comment]
Hello,

You should press F3 + H to get rid of the extra data related to Minecraft (the ID numbers, "minecraft:stonebrick" and "NBT: 1 tag(s)". Also il you don't like the obfuscate effect, you can turn ObfuscateNotReceived to false in the configuration file. ;-)

**Comment by Platinteufel** [comment]
Thank you :)

**Comment by PyvesB** [comment]
You're welcome, have fun using the plugin, and don't hesitate to star the project!
