### ISSUE TITLE
Decrease MaxHealth 

### ISSUE THREAD

**Issue by jusobreira** [PyvesB/AdvancedAchievements#703]
I'm heaving a issue to decrease the maxhealth once i increase it.. 
I want to be able to set the maxhealt back to the vanilla default, is there a command to do it or do i have to delete player data every time i want to cancel it?

![image](https://user-images.githubusercontent.com/10175304/78308074-d833db80-751d-11ea-8936-cb0b41ee309a.png)

**Comment by PyvesB** [comment]
Duplicate of #674, #688 and possibly others.
