### ISSUE TITLE
specific player killed = achivement+reward not working

### ISSUE THREAD

**Issue by ottarorri** [PyvesB/AdvancedAchievements#707]
So I wanted to make an achivement so that if you kill me on the server you get an achievment and a reward but when I put in the uuid and changed everything around and players kill me they don't get the achievement which is weird.  This is the code https://ibb.co/h2kjrhV 

hope you can help me out, thanks!

**Comment by PyvesB** [comment]
Hello @ottarorri!

I'm unable to reproduce. A few questions to help investigate:
* does the achievement appear as expected in the _/aach list_ UI?
* have you overridden any of the plugin's permissions?
* are the two other `Kills` achievements working as expected?
* are you running the server in offline or online mode?

**Comment by ottarorri** [comment]
Hello thanks for replying, yes the  achievement appears as expected in the list UI, and no i have not overwritten anything as far as im concerned,  and the other kill achievement with the zombie is working, but the mythic killer skeletal knight is not working currently, And I have the server as online mode: false because i have a bungeecord server. Hope this helps


Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by PyvesB** [comment]
Are you sure you're using the right UUID ? When the server is in offline mode, the UUID is not necessarily the same one as your official Minecraft one.

**Comment by ottarorri** [comment]
Oh ok, how do I know the fight uuid for offline servers then ? Wouls be great to know!

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by PyvesB** [comment]
Doesn't the UUID appear in the server logs when you connect?

**Comment by ottarorri** [comment]
It does and i tried using that uuid and it still doesnt work for some reason :/

Sent frá Póstur<https://go.microsoft.com/fwlink/?LinkId=550986> fyrir Windows 10

________________________________
Frá: Pierre-Yves B. <notifications@github.com>
Sent: Wednesday, April 15, 2020 7:54:58 PM
Til: PyvesB/AdvancedAchievements <AdvancedAchievements@noreply.github.com>
Afrit: ottarorri <ottarorri@hotmail.com>; Mention <mention@noreply.github.com>
Efni: Re: [PyvesB/AdvancedAchievements] specific player killed = achivement+reward not working (#707)


Doesn't the UUID appear in the server logs when you connect?

**Comment by PyvesB** [comment]
Okay, here's a custom debug build to help us out. When someone gets killed on your server, `For this EntityDeathEvent, the config.yml key should be ...` will be displayed in the server's logs. If nothing appears or if the achievements are still not given, something else is wrong... :)

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4488953/AdvancedAchievements.zip)

**Comment by ottarorri** [comment]
hey so i tested it and Changed the specific player uuid to the same as cam in the concole with no luck 😕 heres the screenshot though if that helps

________________________________

**Comment by PyvesB** [comment]
I don't see the screenshots you mentioned.

Here's a slightly different version. Do you see a log message `The player does have permissions for ...` directly following `For this EntityDeathEvent, the config.yml key should be ...`?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4518034/AdvancedAchievements.zip)

**Comment by ottarorri** [comment]
when I make someone kill me, this is the message that pops up in console:

[16:19:36] [Server thread/INFO]: []
[16:19:36] [Server thread/INFO]: [AdvancedAchievements] For this EntityDeathEvent, the configuration key should be specificplayer-8a5fdf14-7b97-4de8-9525-ee6d420f9431

________________________________

**Comment by PyvesB** [comment]
Seems to be a permissions problem then. Please double check that you havent set any permissions starting with `achievement.` anywhere.

**Comment by ottarorri** [comment]
I mean I gave the default group all Tracking achievement. perms to track their permissions and thats about it, should I not have or ?

**Comment by PyvesB** [comment]
Another user was having trouble with their permissions plugin not properly propagating wildcard permissions. Does #662 help?
