### ISSUE TITLE
'TargetsShot' achievement not counting with crossbow firework

### ISSUE THREAD

**Issue by download042** [PyvesB/AdvancedAchievements#714]
Probably not an issue, but this feature would be amazing.

**Comment by PyvesB** [comment]
Hello @download042, unfortunately this seems to be a Spigot limitation, `ProjectileHitEvents` are not called when a firework hits an entity or a block. Unsure whether this is intended behaviour or a bug, could you please raise an issue on the [Spigot tracker](https://hub.spigotmc.org/jira/secure/Dashboard.jspa)?
