### ISSUE TITLE
All achievement data reset on server restart???

### ISSUE THREAD

**Issue by MrNaspo** [PyvesB/AdvancedAchievements#716]
Hello, I woke up this morning to find many of my players complaining of all their achievement data reset. I came online to find out that this had been the case. How could this happen? Is there anything I can do to fix this or maybe revert this? Please help thanks.

**Comment by PyvesB** [comment]
Hello @MrNaspo! What version of the plugin are you using? Did this happen just after an upgrade or a configuration change? What database type are you using? Are there any errors in the server's logs?

**Comment by MrNaspo** [comment]
I’m running version 5.16.0. (I updated to the lastest today after it happened). The database is H2.

**Comment by MrNaspo** [comment]
I’ve also reached out to my server hosting company to retrieve the achievements.db file from a recent server backup in order to restore the player data. Keep in mind that it didn’t just reset player data, it reset all files so I had to redo my configuration.

**Comment by PyvesB** [comment]
> Keep in mind that it didn’t just reset player data, it reset all files so I had to redo my configuration.

Advanced Achievements does its own backups as well by appending a `.bak` extension to all configuration and database files. Did those disappear as well?

**Comment by MrNaspo** [comment]
There is a .bak file for config, gui, and lang. Not for the player database.

**Comment by PyvesB** [comment]
> There is a .bak file for config, gui, and lang. Not for the player database.

Do those contain your old configurations prior to the incident?

The backup for the database was fixed in version 5.16.0, that's why you probably didn't have one.

**Comment by MrNaspo** [comment]
Hmm okay. I got the backup from my hosting company and uploaded the latest version of the plugin. Hopefully it doesn't happen again on the restart that it's supposed to update.

**Comment by MrNaspo** [comment]
Also one more thing, unrelated. You should really really offer more customization options for the plugin. I can't even change the prefix, and much  more...

**Comment by PyvesB** [comment]
> Also one more thing, unrelated. You should really really offer more customization options for the plugin. I can't even change the prefix, and much more...

Which prefix are you referring to?

> Hmm okay. I got the backup from my hosting company and uploaded the latest version of the plugin. Hopefully it doesn't happen again on the restart that it's supposed to update.

Okay, let me know if it happens again. To be honest, I don't think Advanced Achievements is at fault here, the plugin is really prudent in the way it deals with files and doesn't even have the ability to delete or reset configurations/databases. This sounds more live a problem with the provider, a server bug or simply a user mistake.

**Comment by MrNaspo** [comment]
The clover in brackets before every message from the plugin.

**Comment by PyvesB** [comment]
> The clover in brackets before every message from the plugin.

The brackets themselves, their styling and colour can be changed via the `ChatHeader` configuration parameter in _config.yml_. The clover itself can be changed via the `Icon` configuration parameter in _config.yml_.

There are hundreds of configurations parameters broken down in three configuration files, from experience users who complain about lack of customisation have generally not gone through these files properly. I would really encourage you to take the time to do so and give [the Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) a read as well. :wink:

**Comment by MrNaspo** [comment]
Ah okay, my bad then. Apologies

**Comment by PyvesB** [comment]
Probably nothing much to add on the original issue for now, closing! Let me know if anything unexpected comes up.
