### ISSUE TITLE
HideProgressiveAchievements

### ISSUE THREAD

**Issue by IronDirt** [PyvesB/AdvancedAchievements#717]
(Excuse my English)
It would be nice if the plugin hides the successive missions.
For example:
kill 10 zombies (this one sees it)
Kill 20 zombies (she doesn't see it until she completes the 10 zombie mission)
Kill 30 zombies (she doesn't see it until she completes the 20 zombie mission)

the plugin now I only allow to blur the title, but the mission appears in the list and I do not like it

**Comment by PyvesB** [comment]
Hello @IronDirt! The idea seems sensible, but if I'm not mistaken, it's the first time someone has requested this over the years, so I'm not convinced it would be a very popular feature. However, if you or others feel strongly about it, I'm happy to review a pull request. 😉

**Comment by IronDirt** [comment]
Aaah okey
I'm willing to pay you to add this option, which is fundamental to my SkyBlock

**Comment by PyvesB** [comment]
I don't formally accept paid work as such, however, using the "sponsor" button at the top of the page can act as a similar incentive, and also get your server's name on the plugin's Bukkit & Spigot homepages! :)

**Comment by IronDirt** [comment]
Va bene, inizierò con una piccola donazione e poi magari altro :D

**Comment by PyvesB** [comment]
Sounds fair - will have a look at the implementation over the weekend!

**Comment by PyvesB** [comment]
Done in the above commit, will aim to release sometime next week! `HideProgressiveAchievements` is in essence a mixture of the existing `ObfuscateProgressiveAchievements` and `HideNotReceivedCategories` parameters! 🎆

**Comment by PyvesB** [comment]
Bukkit have mistakenly rejected my resource update. I've opened a support case but the new version will be postponed for now.
