### ISSUE TITLE
suggestion: create custom achievments

### ISSUE THREAD

**Issue by ProSharkyt** [PyvesB/AdvancedAchievements#718]
maybe in the config you can add a custom achievement. like this:
-(achievement name)
 -item: (the item it will show on gui)
 -mob: ZOMBIE:15 (kill 15 zombies)
 -blocks: DIAMOND:100 (required to mine 100 diamond)
 -walk: 1,000 (walk 1000 blocks)
 
something like that?

**Comment by PyvesB** [comment]
Hello @ProSharkyt, this is in essence similar to #82 or #616. Contributions are welcome! 😉
