### ISSUE TITLE
Death's and potions not being logged

### ISSUE THREAD

**Issue by danyaelgaina** [PyvesB/AdvancedAchievements#719]
Config : 
https://telegra.ph/Here-04-30

**Comment by danyaelgaina** [comment]
Yes latest version

**Comment by PyvesB** [comment]
Hello @danyaelgaina, I cannot reproduce the problem with your configuration file. Please double check your permissions. If that doesn't help, it could be another plugin misbehaving, for example by suppressing or altering the `PlayerDeathEvents` and `PlayerItemConsumeEvent ` events that Advanced Achievements listens to. Simple way to find out: temporarily remove all plugins apart from Advanced Achievements and see if the problem persists. 😉

**Comment by PyvesB** [comment]
Given the lack of news, I'm assuming that my above message was helpful and that your problem is now solved! Closing.
