### ISSUE TITLE
Earliest supported version?

### ISSUE THREAD

**Issue by Zilacon** [PyvesB/AdvancedAchievements#721]
Hello, i got servers ranging from 1.5.2 to 1.15.2, i was wondering how far back in version support this plugin goes?

Were already working on making hundreds of achievements for it running on our 1.15.2 server. Just wanted to know how far back i can use it on my servers when we finish the configs.

**Comment by PyvesB** [comment]
Hello @Zilacon, as indicated on the Bukkit and Spigot homepages, the earliest Minecraft version that is expected to work with the plugin is 1.7.9. :wink:

**Comment by Zilacon** [comment]
Darn, was hoping it went lower then that...
Alright, thanks.

**Comment by PyvesB** [comment]
Worth noting that version 1.7.9 is over 6 years old now, with 1.16 coming out soon the plugin will support 10 major Minecraft releases (~40 total Minecraft releases if you include the smaller ones)! For a plugin as complex as Advanced Achievements, that's quite an achievement and is significant maintenance overhead to keep everything still supported! :)
