### ISSUE TITLE
Improving Taming Achievements

### ISSUE THREAD

**Issue by HeavenCrafter** [PyvesB/AdvancedAchievements#722]
I unsure whether this is already a thing and I'm just stupid and configured it wrongly or this just wasn't a thing in the first place, though I feel like it'd be cool to have.

Almost like the killing specific mobs achievement category, taming should have the option to be specific as well.

What I mean is creating a mob taming achievement for specific mobs.

> Taming:
>   wolf:
>     10:
>       Goal: Tame 10 Wolves!
>       Message: You must really love dogs huh?
>       Name: taming_10_wolves
>       DisplayName: The Top Dog!

I did try this on the latest version and it doesn't seem like its possible so I thought it'd be pretty cool to have!

I have dozens of ideas to improve this plugin but sadly I'm no developer and don't exactly have the time to learn Java to make this into reality so I hope someone could help out!

**Comment by PyvesB** [comment]
Hello @HeavenCrafter , unfortunately this is not currently possible. This has already been reported in #56. :wink:

**Comment by HeavenCrafter** [comment]
> Hello @HeavenCrafter , unfortunately this is not currently possible. This has already been reported in #56. 😉

o i see, thank you for the quick response tho, still kinda sucks, had another dozen more achievements i wanted to make with that functionality but thanks for the response non the less!

**Comment by PyvesB** [comment]
No worries! The plugin would definitely benefit from more developers, but that's the case of a lot of open source projects after all, especially when these are lacking proper sponsorship/support!
