### ISSUE TITLE
The job of placing planks does not work

### ISSUE THREAD

**Issue by MaxIsV** [PyvesB/AdvancedAchievements#725]
Hello. Such a problem has existed for a long time, the achievement to place the planks doesn't work, that is, progress does not count.

Video: https://imgur.com/70j25lY

The video shows the achievement of "поставить 100 досок", which means "place 100 planks", I place planks, but progress does not count. And the same thing happens with all other players.

My config.yml: https://pastebin.com/abeG87TA
Aach version: 6.0.0

Screenshot of the required section in config: 
![image](https://user-images.githubusercontent.com/58142896/81013530-f31ea600-8e63-11ea-9cb0-965e6e1bfe67.png)

**Comment by PyvesB** [comment]
Hello @MaxIsV ,

`planks` is not a valid material name. See the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Material-names) for more information. 😉

**Comment by MaxIsV** [comment]
Sorry, I don’t know what material I should use instead of “planks”. In the list that you sent, I did not find any replacement. Other sources say that in version 1.12.2, it is “planks” that is the correct identifier

**Comment by PyvesB** [comment]
Have you given `wood` a try?

**Comment by MaxIsV** [comment]
It works, thanks
