### ISSUE TITLE
Custom Achievements

### ISSUE THREAD

**Issue by OYTSUI** [PyvesB/AdvancedAchievements#726]
Is there option to create custom achievements and custom category? like:

```
CUSTOM1:
  USE:
    Goal: Use special time once to get this achievement!
    Message: GRATZ! U USE SPECIAL ITEM!
    Name: specialitem1
    DisplayName: USE LEGENDARY SPECIAL ITEM
```

I want to create many custom achievements with special category, plugin don't show me any errors with this but i don't see this on list with other categories :///

And can i name this specified category?

**Comment by PyvesB** [comment]
Hello @OYTSUI,

I'm somewhat unsure about what you're trying to achieve. Custom categories are possible through the following structure in the configuration:
https://github.com/PyvesB/AdvancedAchievements/blob/24f428e27577b4a240236158879a1194c6e3b05c/advanced-achievements-plugin/src/main/resources/config.yml#L797

Hope this helps!

**Comment by OYTSUI** [comment]
> Hello @OYTSUI,
> 
> I'm somewhat unsure about what you're trying to achieve. Custom categories are possible through the following structure in the configuration:
> https://github.com/PyvesB/AdvancedAchievements/blob/24f428e27577b4a240236158879a1194c6e3b05c/advanced-achievements-plugin/src/main/resources/config.yml#L797
> 
> Hope this helps!

Like, when you use command /aach list you see all categories, i mean to create ALL CUSTOM categories with custom things [ probably only can get by used command by other plugin ]

**Comment by PyvesB** [comment]
The `Custom` category currently appears as one category in _/aach list_.
