### ISSUE TITLE
NULL text string

### ISSUE THREAD

**Issue by Feeriix** [PyvesB/AdvancedAchievements#73]
I am getting few NULL strings from various parts of the plugin.

http://i.imgur.com/dqklAX9.png
http://i.imgur.com/06uN5yy.png

Tried saving the config with ASCII and UTF-8 with no changes.
Using v3.0.2 with Spigot 1.10.2

**Comment by PyvesB** [comment]
Hello,

This is weird, you seem to have issues with the plugin's colours. Are there any errors/warnings in the console? Do you know what is the default encoding of your system? What is the language you are using (sorry if I can't tell based on the screens)? What is the value of the parameter "Color" in your config? Is this the official version of the plugin or have you recompiled it yourself?

Cheers,

Pyves

**Comment by Feeriix** [comment]
I found the issue. It was the the color config option, I removed & and it was fixed.
Thank you for your time. I better read the defaults next time :p

**Comment by PyvesB** [comment]
Great! Issue closed, have fun using the plugin!

Cheers,

Pyves
