### ISSUE TITLE
Huge Lag Spike

### ISSUE THREAD

**Issue by Dragonox77** [PyvesB/AdvancedAchievements#733]
:information_source: **Basic information**
I'm using this plugin with MySQL.

* Advanced Achievements version: 6.0.0
* Minecraft version: 1.14.4
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

Hi,
I'm experiencing some huge lag spike on my server (~25 players) because of this plugin.
Here is the timings report https://prnt.sc/serb44 .
Maybe I missed something in the configuration file. I don't know what to give more that can help you.

:page_facing_up: **Server logs**
https://prnt.sc/serb44

**Comment by PyvesB** [comment]
Hello @Dragonox77,

What database type are you using?

**Comment by Dragonox77** [comment]
Mysql

**Comment by PyvesB** [comment]
I would suggest try switching to H2 and see if that helps!
