### ISSUE TITLE
custom doesn't work

### ISSUE THREAD

**Issue by Phaired** [PyvesB/AdvancedAchievements#736]
Hello !
`Custom:
  easters:
    '7':
      Goal: Découvrir les 7 Divinitées
      Message: Tu as découvert tous les Easters Eggs, voici 1000s Moonshards pour récompense
      Name: customs_easters_7
      DisplayName: Chercheur d''Easter egg
      Reward:
        Command:
          Execute: "pa add PLAYER 1000"`
this doesn't work when I do "aach add 1 easters PLAYER" the achievement isn't reconized
https://pastebin.com/wvqhgR4r full config
thanks

**Comment by PyvesB** [comment]
Hello @Phaired,

`Custom` is listed in `DisabledCategories`, you have to remove it from there. 😉

**Comment by Phaired** [comment]
I’m dumb sorry dude

**Comment by PyvesB** [comment]
It's okay!
