### ISSUE TITLE
how to re enable plugin after it disables

### ISSUE THREAD

**Issue by ca9an** [PyvesB/AdvancedAchievements#737]
i cant figure out how to re enable plugin without closing the server after its disabled by false config.
the reasın why i need is when i want to add new achievemnts constantly to my server  and i dont want to restart it when players playing also its deletes all playerdata when deleting config how can i prevent this?

**Comment by PyvesB** [comment]
Hello @ca9an ,

Not sure Spigot/Bukkit support re-enabling plugins like that, maybe there's a third-party plugin that allows it. As far as bogus config is concerned, as advised in the documentation you should validate your configuration with an online tool (for example http://yaml-online-parser.appspot.com). That will cover a lot of cases of broken configurations, whether it be with Advanced Achievements or other plugins. 😉
