### ISSUE TITLE
Little error with the "big" achievements

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#741]
Hi,

I made some achievements with a very long name because I put a lot of blocks in it. I have this error which appears as soon as a player has obtained a success in related with these extended names : https://pastebin.com/2BK4Y3KM

I am currently in sqlite, if i switch to mysql, will it work or will it be worse ? Because in the game there is no problem, the player gets his reward well and success advances.

I use the latest version of the plugin (6.1.0) and Paper 1.15.2.

**Comment by PyvesB** [comment]
Hello @aurel85, it seems that you're using H2 and not SQLite? I would not expect this to be a problem with SQLite. The reason why the keys must be at most 191 characters long is because that was the maximum allowed in older version of MySQL.  I don't intend on increasing the value until February 2021, when MySQL 5.6 goes out of support. See https://github.com/PyvesB/AdvancedAchievements/issues/668#issuecomment-590099032 😉

**Comment by aurel85** [comment]
Ok thank you for your answer and I use SQLite I don't even know H2 ^^.

**Comment by PyvesB** [comment]
FYI, the next version of the plugin will include a configuration parameter to configure the maximum size. 😉

**Comment by PyvesB** [comment]
@aurel85 by the way, would you be interested in beta testing the next version of the plugin?

**Comment by aurel85** [comment]
> @aurel85 by the way, would you be interested in beta testing the next version of the plugin?

Yes, why not

**Comment by Walitam** [comment]
yeah i would love doing some beta testing

**Comment by PyvesB** [comment]
Here you go:
[AdvancedAchievements.zip](https://github.com/PyvesB/advanced-achievements/files/5914555/AdvancedAchievements.zip)

Some things to keep in mind:
* this version is still labelled 6.7.2 at this point, but will ultimately become 7.0.0.
* there have been some changes to the database tables. You will not be able to go back to the previous version of the plugin unless you also restore a backup of your database performed before launching the new version.
* `list-potions` has been renamed to `list-consumedpotions` in _lang.yml_.
* if you spot any bugs, please open [a new issue](https://github.com/PyvesB/advanced-achievements/issues/new?assignees=&labels=bug&template=1_Bug_report.md). GitHub issues are free, so don't hesitate to create one issue per bug. :)

Quick outline of what's changed so far:
* big parts of the code have been rewritten or reorganised to make contributions and ongoing maintenance easier.
* performance has been improved quite significantly.
* memory usage should have gone down as well, in particular some memory leaks were fixed.
* configuration file handling is more robust. If you've been using the plugin for a long time, you may have noticed that it occasionally messes up comments and adds whitespaces in random places. This should no longer happen.
* the GUI for each category has been visually improved (previous and next buttons are now only displayed when relevant, navigation items are now part of a separate row, the category block is no longer displayed in the first inventory slot but can instead be used as the back button).
* some new config options are supported: `OverrideBackButtonBehaviour`, `BackButtonIsCategoryItem`, `TableMaxSizeOfGroupedSubcategories`.
* the API has some richer methods available, which will help third-party integrations.
* the JAR size has been reduced and remapped a little to reduce risk of conflicts with other plugins.
* the plugin is now available in Danish thanks to @Tobi-Jakka.

@n54b, @Tobi-Jakka and anyone else, feel free to give it a spin as well! 😄

**Comment by Tobi-Jakka** [comment]
Thanks, I will do some testing as well! :)

**Comment by PyvesB** [comment]
I intend on releasing soon, do let me know if you spot anything unexpected. :)
