### ISSUE TITLE
Kicks from the server

### ISSUE THREAD

**Issue by X-Viktor** [PyvesB/AdvancedAchievements#743]
* Advanced Achievements version: 6.1.0
* Minecraft version: 1.15.2
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes
**Description**
After the player opens the list /aa list, he kicks from the server and he cannot log in again for some time. After it enters again, the list works fine.
In this case, nothing is displayed in the logs.

![image](https://user-images.githubusercontent.com/56266601/83225888-b3758080-a1bb-11ea-88bb-f275b05a2800.png)

![image](https://user-images.githubusercontent.com/56266601/83225350-8aa0bb80-a1ba-11ea-9809-b816f826abea.png)

**Comment by PyvesB** [comment]
Hello @X-Viktor,

Hmmm, that's strange, it's the first time I'm hearing of such an issue with the plugin. Could you please translate the "Internal Exception" message from the first screenshot?

**Comment by X-Viktor** [comment]
"Remote host forcibly terminated existing connection"

**Comment by PyvesB** [comment]
Which database type are you using? Is there any evidence of the plugin being slow to collect statistics and other stored data?

**Comment by X-Viktor** [comment]
MySQL

**Comment by PyvesB** [comment]
Does the problem still occur if you switch to another database type, for example H2?

**Comment by X-Viktor** [comment]
Yes

**Comment by X-Viktor** [comment]
The problem is solved when I delete all the data of the players. But after a while she reappears. And you need to delete again.

**Comment by PyvesB** [comment]
Maybe it's worth sharing a H2/SQLite database file for which the problem occurs, so that I can take a look at it.

**Comment by X-Viktor** [comment]
[achievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4739796/achievements.zip)

**Comment by PyvesB** [comment]
> 
> 
> [achievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4739796/achievements.zip)

Will have a look sometime during the weekend.

**Comment by X-Viktor** [comment]
Ok, thanks.

**Comment by PyvesB** [comment]
I had a quick browse through your database data, I did not spot anything unexpected.

I also launched a local server with it, I am not able to reproduce the issue. Maybe worth sharing your configurations files as well.

**Comment by X-Viktor** [comment]
Yes, when I run the database on the local server, everything is fine.

**Comment by X-Viktor** [comment]
[config.zip](https://github.com/PyvesB/AdvancedAchievements/files/4742020/config.zip)

**Comment by PyvesB** [comment]
If neither of us can reproduce the problem on local servers, it may be something misconfigured or a conflicting plugin on your other server. I would suggest temporarily running the server with _just_ the Advanced Achievements enabled and see if the problem persists.
