### ISSUE TITLE
Repeatable Achievements

### ISSUE THREAD

**Issue by KData010** [PyvesB/AdvancedAchievements#746]
Hi, i was wondering if it's possible to do repeatable achievements kind of like how you can do repeatable quests in RPGs? Is it possible to do that using a command in Advanced Achievements when the achievement requirement(s) are met without it going in an infinite loop?

**Comment by PyvesB** [comment]
Hello @KData010,

Repeatable achievements aren't really possible directly, but one workaround would consist in running an _/aach reset_ command as the reward to an achievement. This would effectively reset progress for an achievements, but would admittedly be a bit clunky. :wink:
