### ISSUE TITLE
Breaks: redstone_ore

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#75]
Today I tried to add redstone_ore to my break achievements - without success so far.
All other ores like lapis_ore, coal_ore, emerald_ore, diamond_ore [...] work without any problem.
I've also tried to change `redstone_ore` to `lit_redstone_ore`, because it glows when you break it, but that also doesn't help. I made sure that the pickaxe doesn't have the silk_touch enchantment.
Do you have any idea what could be wrong here?

**Comment by PyvesB** [comment]
Hello,

Try using glowing_redstone_ore. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Works, thank you! But the `DisableSilkTouchOreBreaks: true` option doesn't work for it. :/

**Comment by PyvesB** [comment]
You're perfectly right now that I think of it! Will be corrected in the future. ;-)
