### ISSUE TITLE
Integration with Autosell Plugin

### ISSUE THREAD

**Issue by arciniegasdiaz** [PyvesB/AdvancedAchievements#751]
Hi **PyvesB**, I wanted to ask you, or rather, suggest, what would be the possibility that in the future, you add an integration to the Plugin of Clip, **Autosell**, which in one of its sections, **drop2inv**, does not work correctly with the **AACH**, since that having the drop2inv mode activated does not increase the statistics.

I don't know what chance there is that you can do it.
Thank you for reading

P.S.
I will update the **lang.yml Spanish** in future days

**Comment by PyvesB** [comment]
Hello @arciniegasdiaz, this is a known issue with the AutoSell plugin which incorrectly uses the Bukkit API. There's unfortunately not much I can do on my side. See #692 for more information.

**Comment by PyvesB** [comment]
Hopefully the AutoSell author was pinged again about this problem. Will close for now. :wink:
