### ISSUE TITLE
Failed to register events

### ISSUE THREAD

**Issue by Tatado2020** [PyvesB/AdvancedAchievements#754]
:information_source: **Basic information**

* Advanced Achievements version: <6.1.0>
* Minecraft version: <1.14.4>
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: <yes>
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: <yes>

:beetle: **Description**

<The following error occurs when the server starts running:>
[AdvancedAchievements] Plugin AdvancedAchievements v6.1.0 has failed to register events for class com.hm.achievement.listener.statistics.WinRaidListener because org/bukkit/event/raid/RaidFinishEvent does not exist.
My game version is 1.14.4,has a Raid mechanism.
And  when the player wins the Raid, the progress of the corresponding achievement does not increase.
 Can you tell me how should I solve this problem?

:page_facing_up: **Server logs**

````

````

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @Tatado2020, have you checked out #608?

**Comment by Tatado2020** [comment]
> Hello @Tatado2020, have you checked out #608?

Well... I read this, but I have to admit I didn't understand it after read...
Should I update Paper.jar？

**Comment by PyvesB** [comment]
> > Hello @Tatado2020, have you checked out #608?
> 
> Well... I read this, but I have to admit I didn't understand it after read...
> Should I update Paper.jar？

Yes, pretty much :)

**Comment by Tatado2020** [comment]
> > > Hello @Tatado2020, have you checked out #608?
> > 
> > 
> > Well... I read this, but I have to admit I didn't understand it after read...
> > Should I update Paper.jar？
> 
> Yes, pretty much :)

 The problem has been solved, thank you! :)

**Comment by PyvesB** [comment]
Great to hear that, thanks for confirming! Fee free to leave a star on the repo or a review on Spigot. 😉
