### ISSUE TITLE
Ability to link with regular Minecraft Achievements?

### ISSUE THREAD

**Issue by Konsider** [PyvesB/AdvancedAchievements#757]
Hi there :)

I am not sure if this is possible, but could AdvancedAchievements recognise somebody completing a regular Minecraft achievement and issue a reward? 

For example, a player completes the achievement "The End" by killing the Ender Dragon. Could Advanced Achievements then reward that player with items, etc?

Thanks!

**Comment by PyvesB** [comment]
Hello @Konsider, vanilla Minecraft achievements were removed in version 1.12 of the game, I don't plan on adding support as it would only be useful in very old Minecraft versions. :wink:

**Comment by Konsider** [comment]
Hey @PyvesB thanks for the reply :D Ah yes, sorry, I mis-spoke - I meant vanilla "advancements" :D

**Comment by PyvesB** [comment]
There are two currently supported features that link Advanced Achievements with the Vanilla advancement system:
* creating one advancement per achievement through the _/aach generate_ command (this was added when Minecraft 1.12 was released).
* awarding achievements based on the total number of advancements completed (this was contributed recently by @CrabMustard).

There's no way to track specific Vanilla advancements and award achievements based on them.
