### ISSUE TITLE
Time played (in hours)

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#76]
Seems like the achievement or the progress bar of `Time played (in hours)` doesn't work at the moment. Some players report that the color keeps red after hours, other players reporting a full progress bar, but don't get the achievement. Would be nice if you could take a look into it. :)

Cheers

**Comment by PyvesB** [comment]
Hello,

I'll look into it. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

The progress bar was indeed not working correctly for this achievement. Should now be fixed by commit 6eb23015592f13a4c6aa1415318670b621043a52 .

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Seems to work fine now, thank you!
