### ISSUE TITLE
Adding a .jar file to the GitHub Releases page

### ISSUE THREAD

**Issue by Zegameus** [PyvesB/AdvancedAchievements#760]
Hello, good afternoon, I would like very much that in the releases page, when you publish a new one, you would be so kind to put the .jar file to be able to download it more easily. 
Thank you for your attention.

**Comment by PyvesB** [comment]
Hello @Zegameus, thanks for the suggestion. I've included a Spigot link in the latest release to directly downloadthe .jar file. I think it's better than offering a separate .jar here as it will still keep track of download statistics in a centralised manner and avoid me having to reupload it multiple times (which takes a long time on my extremely slow connection!). :wink:
