### ISSUE TITLE
/aach toplevels

### ISSUE THREAD

**Issue by comonier** [PyvesB/AdvancedAchievements#761]
any command to check a top levels list ?
top levels is a achievement for who have playing most time on server.
but on most servers there is another tag like, vips, staffs, replacing the Level player tag from plugin.
So there is a good if we have a command to check it, typing /aach toplevels
and a Discord Support can be a good idea also.
ty

**Comment by PyvesB** [comment]
Hello @comonier, I don't really understand what you're asking, however, you can read about all existing commands in the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Commands-and-permissions). 😉
