### ISSUE TITLE
Kills achievements with MythicMobs

### ISSUE THREAD

**Issue by Threshian** [PyvesB/AdvancedAchievements#763]
Hi,

First i would like to say that your plugin is awesome and very to use, you did a great job !

I need your help to know if it's possible to get the achievements on killing mobs from MythicMobs without any order in the config?
What i would like is to kill mobs at any time and not be forced to kill the first in the list then the second ect.

Thanks.

Best regards.

**Comment by PyvesB** [comment]
Hello @Threshian, thanks for the kind comments about the plugin. The order of Mythic Mobs specified in the configuration shouldn't matter, as kill statistics for each one of them is tracked independently. :wink:

**Comment by Threshian** [comment]
Thanks for the response, i assume that i wrote wrongly the mobs in the config ^^'

**Comment by Threshian** [comment]
May i ask you one last thing ? ^^'

Are you seeing something wrong because i have the achievment for the first mob but not the others :/

![notepad++_OEFy4UNAGA](https://user-images.githubusercontent.com/67510777/86152604-be943700-bb00-11ea-9efd-2d9e05f40ac6.png)

**Comment by PyvesB** [comment]
Nothing looks obviously wrong. Could you please share the actual text of the screenshot so that I can have a closer look?

**Comment by Threshian** [comment]
[https://www.mediafire.com/file/t2uxvfqj6ig0mkr/config.yml/file](url)

**Comment by PyvesB** [comment]
The configuration looks good from what I can tell. Are you sure you're using the right Mythic Mob values? As indicated [in the default configuration](https://github.com/PyvesB/AdvancedAchievements/blob/9035a9a8d506082a8a306aa5ec43fbcf2de9c5fe/advanced-achievements-plugin/src/main/resources/config.yml#L333), you have to use the `Display` name of the mob.

**Comment by Threshian** [comment]
For the Water boss it looks like that, what should i take for the displayname ?
https://i.imgur.com/NLNxIJc.png

**Comment by PyvesB** [comment]
Try `§1Gardien de l'eau`. That's the `Display` name, with & changed to §.

**Comment by Threshian** [comment]
I'm sorry, i gave up on Mythic Mobs achievment. The §1Gardien de l'eau work now, i apply and fix the display of every mobs but only 4 work. I will make normal mobs, i take the easy way.

Thanks a lot for the support, you are great ! <3

**Comment by PyvesB** [comment]
No worries, will close the issue then!
