### ISSUE TITLE
Achievement Hover Text

### ISSUE THREAD

**Issue by JamGallant** [PyvesB/AdvancedAchievements#765]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.2
* Minecraft version: 1.16.1 git-Spigot-ad703da-d77f4d9
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes

:beetle: **Description**

Hover text not working for awarded achievement. Tested as well for default config achievements. 

:page_facing_up: **Server logs**

````
28.06 21:42:34 [Server] Server thread/INFO [AdvancedAchievements] Player BeratZengin received the achievement: kills_1_zombie (The Walking Dead)
28.06 21:42:34 [Server] Server thread/WARN [AdvancedAchievements] Failed to display hoverable message for achievement reception. Displaying standard messages instead.
````

:wrench: **Configuration**

````
N/A
````

**Comment by PyvesB** [comment]
Hello @JamGallant, thanks for the report, I'll check this out. 😉
