### ISSUE TITLE
Getting an Error for unknown reason...

### ISSUE THREAD

**Issue by CloudeLecaw** [PyvesB/AdvancedAchievements#768]
maybe  simple error but we dont see the reason for it on console.
We are using paper 1.16.1 Build 24

**] Cloude_Lecaw: [19:35:27] [Server thread/WARN]: [AdvancedAchievements] Failed to display action bar message for cooldown.**

**Comment by Baterka** [comment]
Duplicate of what issue? I still have this error.

**Comment by PyvesB** [comment]
See  #765.

**Comment by Baterka** [comment]
Problem still persist in 5.13.2

**Comment by PyvesB** [comment]
Action bar messages for cooldown work flawlessly for me, I am not able to reproduce any errors. See following screenshot:
![2020-11-20_13 25 17](https://user-images.githubusercontent.com/10694593/99805268-2a208480-2b34-11eb-92b8-ac46dfed633b.png)

No one else has reported this problem in the past 5 months, whether it be on Advanced Achievements or on [Pet Master](https://github.com/PyvesB/PetMaster) where the same code is being used, I would be surprised if there was still a problem with Advanced Achievements.

Spigot/Paper version 1.16.1 had _a lot_ of bugs when it was released back in June, and it took several weeks for them to sort things out. Make sure you're using the latest 1.16.4 version available, that may help. Also try with all configuration files reset to default, just in case. 😉
