### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by Elmo337** [PyvesB/AdvancedAchievements#770]
Is is possible to check the money value?

Like

```
Custom:
  money:
    5:
      Message: You arned 5 Money at alltime
      Name: customs_money_5
      DisplayName: First Money
      Reward:
        Money: 5

```

**Comment by PyvesB** [comment]
Hello @Elmo337,

If you've got an economy plugin that can run a command when money is obtained, yes you could wire things up with the `Custom` category. Otherwise, there is no dedicated money achievement category in Advanced Achievements. 😉

**Comment by Elmo337** [comment]
Hey @PyvesB 

does it work with essentials? and witch command i need to use, money does not work :(

**Comment by PyvesB** [comment]
I don't know. Can Essentials Economy run a command when money is obtained by a player?

**Comment by Elmo337** [comment]
Yea, with /money u can see ur balance or /balance but i tried both and it didnt work

**Comment by PyvesB** [comment]
Those commands must be manually run by players, they aren't executed automatically by the Essentials plugin.

**Comment by PyvesB** [comment]
Nothing much to add on my side, feel free to reopen if you're still having issues!
