### ISSUE TITLE
Removing Generated Advancements

### ISSUE THREAD

**Issue by Isaiah-labs** [PyvesB/AdvancedAchievements#772]
Hi!

I was just wondering if there was currently any way to remove advancements that we've generated! I haven't been able to find the generated advancements (I generated while using defaults) in my map files or datapacks, and removing the plugin doesn't seem to remove them either.

Is this possible at the moment?

**Comment by PyvesB** [comment]
Hello @Isaiah-labs,

Previously generated advancements will get deleted when running _/aach generate_ again. However, if you want to completely remove all advancements without generating new ones, this is the path where they get created on my server: _Serveur\world\datapacks\bukkit\data\advancedachievements\advancements_. I think you can simply delete the files, though probably best to do that when the server isn't running. :wink:

**Comment by PyvesB** [comment]
No news, good news! Assuming the above helped and therefore closing this issue.
