### ISSUE TITLE
Adding Multiple Item Rewards to One Achievement

### ISSUE THREAD

**Issue by meowsome** [PyvesB/AdvancedAchievements#774]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.2
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes

:question: **Help request**

How can I add multiple item rewards to a single achievement in config.yml? I tried putting a semicolon between them like this:

```
Reward:
  Item: item num; item num
```

and adding a new line between them like this:

```
Reward:
  Item: item num
  Item: item num
```

Of course, I replaced "item" and "num" with a Minecraft item and a number, like 1. Neither of these methods worked for me, and I can't find anything in the wiki about it. I know I can achieve this using command rewards, but I think it would be cool to do it the built in way instead. Awesome plugin, I love it a lot, sorry to bug you with something simple like this.

**Comment by PyvesB** [comment]
Hello @meowsome,

> Awesome plugin, I love it a lot, sorry to bug you with something simple like this.

No worries! ❤️ 

Unfortunately, multiple reward items for one achievement is not currently possible with the `Item` parameter. However, as a workaround you could run several _/give_ commands, for example:
````
Command:
  Execute: give PLAYER 158 10; give PLAYER 126 5
  Display:
    - Award: ten droppers!
    -Award: five beautiful wood slabs!
````

I'm also happy to review a pull request if someone is willing to expand the capabilities of the `Item` section. 😉 

Hope this helps!

**Comment by meowsome** [comment]
That works, thank you. I don't have any experience programming Minecraft plugins or I'd look into that too.

**Comment by PyvesB** [comment]
Okay! As you seem content with the workaround, I'll just go ahead and close this issue. If someone else wants to pick up the aforementioned improvements with `Item`, feel free!
