### ISSUE TITLE
Break All Blocks

### ISSUE THREAD

**Issue by DeadIntermediate** [PyvesB/AdvancedAchievements#776]
:information_source: **Basic information**

* Advanced Achievements version:  6.1.2
* Minecraft version: 1.15.2 (For now)
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes
:question: **Help request**

Hello, I was wondering, instead of placing specific materials to break blocks, is there a way to do all blocks? It'll be quite a big list if I want to list all of the blocks to break in minecraft.

**Comment by PyvesB** [comment]
Hello @DeadIntermediate, Short answer: no. Please see #753 and other closes issues. 😉
