### ISSUE TITLE
Crafting netherite items not recognized in advanced achievements

### ISSUE THREAD

**Issue by Camillo82** [PyvesB/AdvancedAchievements#781]
* Advanced Achievements version: 6.1.2
* Minecraft version: Paper 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

The plugin does not recognize crafting of netherite sword or pickaxe that is possible to made using smithing table.

Creating an example section as below has no effect, while it works fine with other swords like diamond:

  netherite_sword:
    '1':
      Goal: Craft a netherite sword.
      Message: You have crafted a netherite sword! Keep it up.
      Name: craft_1_netherite_sword
      DisplayName: §4[Ancient Blade]
      Reward:
        Experience: 10
    '5':
      Goal: Craft 5 netherite swords.
      Message: You have crafted 5 netherite swords! Keep it up.
      Name: craft_5_netherite_sword
      DisplayName: §4[Ancient Bladecraft]
      Reward:
        Experience: 100
    '15':
      Goal: Craft 15 netherite swords.
      Message: You have crafted 15 netherite swords - final achievement!
      Name: craft_15_netherite_sword
      DisplayName: §4[Ancient Bladesmith]
      Reward:
        Experience: 1000

Am I doing something wrong or the plugin does not count smithing table as "crafting"? If so, can it be fixed?

**Comment by PyvesB** [comment]
Hello @Camillo82,

Hmmm... Let me check and get back to you.

**Comment by Camillo82** [comment]
Hey @PyvesB 
Any news or chances to fix it? :)
I guess this is because technically crafting netherite sword or tool is more like "upgrading" on smithing table rather than crafting it and this is possibly why the plugin cannot recognize it as crafted item. Any chances to make it counted as crafted by the plugin?

**Comment by PyvesB** [comment]
Following up again after only a few hours seems abusive.

**Comment by Camillo82** [comment]
It is another day (17 hrs later), but sorry, I apologize :(
Just was curious if you see any chances to make it working.

**Comment by PyvesB** [comment]
Netherite swords **cannot** be crafted, Advanced Achievements correctly doesn't increase craft statistics when using a smithing table. It would make little sense to change that behaviour in my opinion.

There is currently no achievement category that tracks smithing. Spigot does not currently provide an API to track smithing events, so such an achievement category would be difficult to implement. Someone did however raise a feature request with Spigot [here](https://hub.spigotmc.org/jira/browse/SPIGOT-5950), maybe it will get implemented one day.

**Comment by Camillo82** [comment]
All right, that is what I was affraid of :(
Looks like we cannot create achievements for crafting/smithing netherite items.
Thank you very much for your efforts :)

**Comment by PyvesB** [comment]
No worries! Hopefully someone will submit a pull request if ever Spigot gets round to implementing tha aforementioned API! In the meantime I'll close this issue. :)

**Comment by Baterka** [comment]
Sorry for commenting on closed issue, but to me it seems like Spigot track crafted netherite items. In json inside `world/stats` folder is every crafted item. Any possibility that plugin can use this file?

**Comment by rosiejane** [comment]
Did anything come of this?

@PyvesB  <3 <3

**Comment by PyvesB** [comment]
After checking, my two previous messages still summarise the current state of affairs.
