### ISSUE TITLE
Changement de pseudo

### ISSUE THREAD

**Issue by organizatsiya** [PyvesB/AdvancedAchievements#782]
Bonjour,

Je ne sais pas si c'est déjà possible car je n'ai rien trouvé dans les commandes.
Pouvoir transférer l'ensemble des challenges d'un pseudo vers un autre serait une évolution très utile.

**Comment by PyvesB** [comment]
Bonjour @organizatsiya,

Si c'est seulement un changement de pseudo avec le même compte, le transfert n'est pas nécessaire, le plugin utilisant l'identifiant de compte pour stocker les données. :wink:

**Comment by organizatsiya** [comment]
Je viens de mettre mon serv en production.
En effet , le plugin prend en compte l'uuid du compte mais quand un joueur joue en version crack, cette fonctionnalité ne fonctionne pas bien évidemment
