### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by Bestagent29** [PyvesB/AdvancedAchievements#785]
Is it possible to do the following: I want to have close to 50 achievements but to unlock achievements 10-19 you first need to complete achievements 1-9. Then to unlock achievements 20-29 you first need to complete achievements 10-19 and so on...

I look forward to hearing your response!

**Comment by PyvesB** [comment]
Hello @Bestagent29 , this is not currently possible, see #82. 😉

**Comment by Bestagent29** [comment]
Perfect this seems like it could help. Follow up question if you dont mind.
This add on will allow me to give a player a permission if they have completed tasks 1-9. Is it then possible to restrict tasks 10-19 behind a permission (a permission that this add-on will grant them once they have completed the previous tasks).

**Comment by PyvesB** [comment]
To be honest, I'm not sure how that plugin Luck Perms Hook works. Probably best to ask the author directly! :)

**Comment by Bestagent29** [comment]
I will speak with the author of the add-on but what i as asking in my last response was, is it possible to lock certain achievements behind permissions with your plugin?

**Comment by PyvesB** [comment]
It's not currently possible to lock specific achievements, only categories and sub-categories. Shouldn't be too hard to implement though, this is the kind of feature that could be picked up by a new contributor! :)

**Comment by PyvesB** [comment]
Any luck with the author of Luck Perms Hook?

**Comment by PyvesB** [comment]
All achievements now have their dedicated permission, for example `achievement.place_100_stone`. Here's a test version, please give it a try and report back on any issues:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/5012024/AdvancedAchievements.zip)

Nothing much to add for now, therefore closing this issue. :)
