### ISSUE TITLE
Why not? 

### ISSUE THREAD

**Issue by msmanui** [PyvesB/AdvancedAchievements#786]
Goal: §7Recibis §955555 bitcoin
      Message: §1Primera vez minando!
      Name: break_350_stone
      DisplayName: §7Recibis §e1 bitcoin

The Colors are not working... I've tried btwn "" or '' but not... They are still showing the color defined in the config

**Comment by PyvesB** [comment]
Hello @msmanui , have you tried `&7` instead of `§7`?

**Comment by msmanui** [comment]
> Hello @msmanui , have you tried `&7` instead of `§7`?

Nope.
Ive tried with § or & and btwn '' or "" but no. It wont change of color. It will always have the default color of the config "Color:"

**Comment by msmanui** [comment]
> Hello @msmanui , have you tried `&7` instead of `§7`?

The message in the chat when i win, its fine, its in the color i settle but in the gui it doesnt refresh somehow

**Comment by msmanui** [comment]
> Hello @msmanui , have you tried `&7` instead of `§7`?

Btw, its somehow to change the display item of each achievement, so when people are browing arround the gui, they can understand better as for example: Mine 10 stone, then 100, then 1000 etc.. but all those will have a pickaxe diamond.

**Comment by msmanui** [comment]
![fefe](https://user-images.githubusercontent.com/63617395/87272498-c6fb5300-c4ac-11ea-86a9-05725f3b2d8a.png)

Here is an example of changing each display item of each achivement.

**Comment by msmanui** [comment]
Also being able to modifiy the Progress Bar

////////////////////////// 0/100 /////////////////////

It could be 0/100 and less spammy

**Comment by msmanui** [comment]
Sum up:
This pugin would be 10/10 if u could:
1) Add option to represent each achivement with a different items. In brock brake i want to represent "Break diamond" = Using diamond ore, "Break gold" = Using gold ore, etc etc

2) Instead of having "Goal: Mine 5 diamond ore"

Having this:

"Goal:"
- "&eMine 5 diamond ore'
- "&eIts automatic"
- "&9&lHi"

3) This similar to 2 but in Rewards:

Reward:
- "You will recive 5 money"

4) Being able to change the progress progress bar. This could be modify in the config with a
progress-bar-design:

Instead of : ############ 0/100 ####################
Resume to: 0/100

**Comment by PyvesB** [comment]
Well, well, well. I noticed that you were user [Mitsu2k](https://www.spigotmc.org/members/mitsu2k.513183/) on spigotmc.org. You've been regularly leaving poor reviews on Advanced Achievements in the past months. On several occasions, I pointed out that the reviews contained incorrect information and linked to supporting documentation by replying to said reviews. On several occasions, you deleted both your review and my response, and immediately left a new poor review again. This behaviour was flagged up with moderation which I believe removed one of your reviews and told me sanctions would be more severe if you continued. By engaging in this kind of attitude you're putting yourself at risk of getting your account and IP address banned from Spigot, with no possibility of coming back even with a new account.

By leaving poor reviews, you're not encouraging me to improve the plugin. You're also driving potential new users away who will notice the poor reviews on the plugin. Less usage further discourages me from maintaining the plugin. This all falls back onto users, as new features and improvements will no longer be developed and quality support won't be provided. You're pretty much shooting yourself in the foot.

You're not even showing basic courtesy. Not even a "hello" or "thanks in advance".

Unless a complete change in attitude, I'm not interested in helping you.

**Comment by msmanui** [comment]
> Well, well, well. I noticed that you were user [Mitsu2k](https://www.spigotmc.org/members/mitsu2k.513183/) on spigotmc.org. You've been regularly leaving poor reviews on Advanced Achievements in the past months. On several occasions, I pointed out that the reviews contained incorrect information and linked to supporting documentation by replying to said reviews. On several occasions, you deleted both your review and my response, and immediately left a new poor review again. This behaviour was flagged up with moderation which I believe removed one of your reviews and told me sanctions would be more severe if you continued. By engaging in this kind of attitude you're putting yourself at risk of getting your account and IP address banned from Spigot, with no possibility of coming back even with a new account.
> 
> By leaving poor reviews, you're not encouraging me to improve the plugin. You're also driving potential new users away who will notice the poor reviews on the plugin. Less usage further discourages me from maintaining the plugin. This all falls back onto users, as new features and improvements will no longer be developed and quality support won't be provided. You're pretty much shooting yourself in the foot.
> 
> You're not even showing basic courtesy. Not even a "hello" or "thanks in advance".
> 
> Unless a complete change in attitude, I'm not interested in helping you.


Look, i will be straight honest. 

1) Leaving bad reviews or deleting them is not illegal. I wouldnt leave bad reviews if u could customize everything, well not everything but at least the display item or the lores. 

2) Im not the only one complaiming about this, there is tons of users that has already written several times that u cant customize nothing but u still answring them "yes u can!!". U cant even change the display item of each achivement or making your own layout of each achievement... SO NO. 
 
3) Do whatever u want, im not using this plugin anymore, as i did this same suggestion like 1 year ago but u still didnt add some basic stuff like that, so i guess you are not planning to add.

HUGS.
