### ISSUE TITLE
Rollback command /aach generate

### ISSUE THREAD

**Issue by NoilMax** [PyvesB/AdvancedAchievements#787]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: https://github.com/PyvesB/AdvancedAchievements/wiki/Commands-and-permissions

:question: **Help request**

How rollback command "/aach generate"?

**Comment by PyvesB** [comment]
Hello @NoilMax, what exactly do you mean by rollback? Removing generated advancements?

**Comment by NoilMax** [comment]
Yes

**Comment by jusobreira** [comment]
I just did this command expecting some answer and it lagg my server a lot, but i didn't understand what you mean by this:
![image](https://user-images.githubusercontent.com/10175304/87255396-c210b200-c460-11ea-8557-f8758a9becff.png)

**Comment by NoilMax** [comment]
You must remove the generated achievements from the client.
Leave only the command on the server.

**Comment by NoilMax** [comment]
Pls help. Me need helping

**Comment by PyvesB** [comment]
I noticed that you sneakily removed the "Existing issues searched:" from the issue template. Funnily enough, there's already an issue open about this, clearly named "Removing Generated Advancements".

**Comment by NoilMax** [comment]
Сам решил проблему.
Если нужна помощь по аналогичному вопросу, писать в ЛС.
