### ISSUE TITLE
Idea - floating objects

### ISSUE THREAD

**Issue by Elioz** [PyvesB/AdvancedAchievements#79]
Hi There!

I have an idea for feature, the players will be able to show thier achievement for other player by placing block on the ground, put sign on and write something like [aach:1] in the first line and then a item will float on the block, the item represent the achievement that the player earn and other players will be able to see that,

what do you think?

**Comment by PyvesB** [comment]
Hello,

Thank you for your interest in the project.

I'm not sure I really understand what you are requesting. Would you want one floating object for each achievement?

Cheers,

Pyves

**Comment by Elioz** [comment]
I added a picture from shop plugin ^^, just replace the sign with the achievement like
"Killed 50 Zombies"
and replace the chest with any block.
and a user defined item will float, the user will have the option to add this in config.yml or he can not enter so he can do this for only important achievements.
http://imgur.com/YMdUhDr

**Comment by PyvesB** [comment]
Hello,

I've given it some thought, and I don't think this is a good idea. Here's why:
- from a server's administrator point of view, the configuration would get more complicated, with new options to set the type of the floating object for each achievement, the name that must be placed on the sign to link with a given achievement, and some other new general options. Configuring the plugin with many achievements already takes a long time and is confusing for some users, I don't want to make things more tedious.
- what would be written on the sign? One line would be used for the header, another one for the player's name. A lot of achievement names will simply not have enough space to fit in the two remaining lines. And even if all do, the sign wouldn't be very informative or useful.
- how would a player know what to place on his sign to display a specific achievement? The administrator would have to provide him with a list of all the names to link with the achievements, or some sort of new listing command would have to be created. Again, this is not practical for the user.

Thanks for sharing your idea though! ;-)

Cheers,

Pyves

**Comment by Elioz** [comment]
I see... can you program this addon as private plugin? on payment ofcurse?

**Comment by PyvesB** [comment]
Unfortunately I do not make private plugins, so this will probably not happen. Sorry.

Cheers,

Pyves

**Comment by Elioz** [comment]
Thanks for the help.
