### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by Ampu99** [PyvesB/AdvancedAchievements#790]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16.1

:question: **Help request**

I´m having some trouble trying to setup the configuration for a mysql database. I´m not sure what is the appropriate for the config file.

**Comment by PyvesB** [comment]
Hello @Ampu99,

Does the example in the default configuration shed any light?
https://github.com/PyvesB/AdvancedAchievements/blob/8339169e1edb09c422a67234df2ab907aa56e526/advanced-achievements-plugin/src/main/resources/config.yml#L235
