### ISSUE TITLE
Progressbar does not show

### ISSUE THREAD

**Issue by PortableGames** [PyvesB/AdvancedAchievements#791]
Version : Advanced Achievements 6.1.3
Spigot : Spigot 1.16.1 Build 2830

the progressbar is not shown for most tasks, only for some

Imgs:
 YES : https://ctrlv.cz/mrzE
 NO : https://ctrlv.cz/IlTx
 NO : https://ctrlv.cz/WfX9

**Comment by PortableGames** [comment]
I also tested a clean installation of the server and plugin, and the progressbar still doesn't show it

**Comment by PyvesB** [comment]
Hello @PortableGames,

Thanks for the report! This problem seems to have been introduced in version 5.14.0 of the plugin around 6 months ago, I'm surprised no one, including myself, noticed it. Will look into it. 😉

**Comment by PyvesB** [comment]
Actually no, the latest version of the plugin works fine with older Minecraft versions (any version from 1.7.9 to 1.15.2). I've raised an issue on the [Spigot JIRA](https://hub.spigotmc.org/jira/browse/SPIGOT-6010) to track this.

**Comment by PortableGames** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-6010

So according to this. There is an error on the part of the spigot (lore limit)
So do I have to wait for the spigot core to be fixed?

sry for my bad english

**Comment by PyvesB** [comment]
Yes, the best is to wait for now. Hopefully won't be too long. :)

**Comment by PortableGames** [comment]
And you don't want to solve that problem yourself? Reduce that LORE size?
maby from this:
itemMeta.setLore(Arrays.asList("§8[§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8| §8§o0/100 §8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5]"));
to this:
itemMeta.setLore(Arrays.asList("§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8| §8§o0/100 §8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|§8|§5|]"));

and solve this problem:
"It's still at the original 8192, the JSON text of this lore has a length of 8441"

**Comment by PyvesB** [comment]
Yes, it's possible to improve the progress bar rendering code and remove some of the redundant colour definitions. However, that's work on my side and I haven't had much spare time to allocate to this project recently. Spigot have broken something that had worked for years and seem to have acknowledged the problem, I'm really hoping they can deliver a fix soon. That will also have the nice side effect of making older versions of the plugin work again (for example users who have not yet upgraded to version 6.0+ due to the breaking changes).

**Comment by PortableGames** [comment]
its no problem only with your plugin [Netty Epoll Server IO #1/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 36050 bytes encoded, max 32767)
if i write /pl

**Comment by PyvesB** [comment]
Workaround implemented in linked commit.
