### ISSUE TITLE
Placeholders enabled in lang.yml

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/AdvancedAchievements#792]
Is it possible to allow placeholders int he lang.yml so my achievements menu title can include how many achievements they have completed?

**Comment by PyvesB** [comment]
Hello @JHarris12345,

You were quite rude in the two previous issues you raised, #654 and #740, in particular the latter for which I have yet to see any form of apology. Once again, there is not basic courtesy in your message, and you failed to use the issue template and follow the contributing guidelines. Furthermore, I've seen no evidence of you supporting the project in any way through either a donation, a positive review, starring the repository or simply constructive feedback.

Unsurprisingly, I'm not interested in helping someone who isn't thankful nor respectful.
