### ISSUE TITLE
Essentials Integration doesn't work.

### ISSUE THREAD

**Issue by Zegameus** [PyvesB/AdvancedAchievements#793]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: CraftBukkit version git-Spigot-8918ad0-0fa2eec (MC: 1.16.1)
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

Hello good afternoon, today I've updated the plugin to the latest available version 6.1.3, and when using /aach info, it shows me that Essentials integration is not available (it shows a red x). I use the last version of EssentialsX, the 2.18.0.5
:page_facing_up: **Server logs**

````
It doesn't show anything.
````

**Comment by PortableGames** [comment]
I use the same version 6.1.3 and EssentialsX, the 2.18.0.5 and Spigot 1.16.1 Build 2831
I have same error but no with Essentials only with PlaceholdersAPI..

Essentials: ✔
PlaceholderAPI: ✘

**Comment by Zegameus** [comment]
I'll try to upgrade Spigot, It's just a late version.

**Comment by Zegameus** [comment]
The only thing I've found is from worldguard:
````
[WorldGuard] Cargado class org.h2.Driver de AdvancedAchievements v6.1.3 el cual no es un dependes, softdependes o loadbefore de este plugin.
````

**Comment by Zegameus** [comment]
Hello, good afternoon, I closed the server and deleted all the configuration (first I made a backup, of course), and I let the plugin generate the files again and it still didn't work, so I decided to disable the plugin (delete it from the plugins directory) and restart the server, once I did this, I put it back with the files I had. And suddenly it worked.

**Comment by PyvesB** [comment]
Okay, thanks for coming back to us @Zegameus ! To be honest all of this is a bit odd, but if it's now working, that's what matters. 😉
