### ISSUE TITLE
Operators error PlayerJoinEvent Achievements ?

### ISSUE THREAD

**Issue by Bonnydust** [PyvesB/AdvancedAchievements#8]
Receiving this error when a player who is Operator joins the server.

24.01 21:20:56 [Multicraft] bonnydust ran command Message of the Day
24.01 21:20:56 [Connect] User bonnydust, IP 180.181.147.167
24.01 21:20:56 [Server] INFO ... 14 more
24.01 21:20:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
24.01 21:20:56 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
24.01 21:20:56 [Server] INFO at sun.reflect.GeneratedMethodAccessor427.invoke(Unknown Source) ~[?:?]
24.01 21:20:56 [Server] INFO at com.hm.achievement.listener.AchieveConnectionListener.onPlayerJoin(AchieveConnectionListener.java:35) ~[?:?]
24.01 21:20:56 [Server] INFO Caused by: java.lang.NullPointerException
24.01 21:20:56 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
24.01 21:20:56 [Server] INFO org.bukkit.event.EventException
24.01 21:20:56 [Server] ERROR Could not pass event PlayerJoinEvent to AdvancedAchievements v2.3.1
24.01 21:20:56 [Server] INFO UUID of player bonnydust is 7871ce06-f8a5-4bff-90ae-12acec0932fa

**Comment by PyvesB** [comment]
Hello Bonnydust ,

Indeed, there was an obvious mistake in the code that I had not payed attention to. It is now corrected in the latest commits, and I will issue an official update by next Friday. In the meantime, I recommend setting CheckForUpdate to true in the configuration and reloading the plugin, this should fix the issue.

Thank you for your report! ;-)

**Comment by Bonnydust** [comment]
Thank you I appreciate the quick reply. That worked. However I now receive the following console spam instead and more often.


25.01 16:06:14 [Server] INFO ... 3 more
25.01 16:06:14 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.01 16:06:14 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
25.01 16:06:14 [Server] INFO at com.hm.achievement.db.PooledRequestsSenderAsync.run(PooledRequestsSenderAsync.java:24)
25.01 16:06:14 [Server] INFO at com.hm.achievement.db.PooledRequestsSenderAsync.sendRequests(PooledRequestsSenderAsync.java:52)
25.01 16:06:14 [Server] INFO Caused by: java.lang.NoSuchMethodError: java.util.Map.remove(Ljava/lang/Object;Ljava/lang/Object;)Z
25.01 16:06:14 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.01 16:06:14 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
25.01 16:06:14 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
25.01 16:06:14 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
25.01 16:06:14 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AdvancedAchievements v2.3.2 generated an exception while executing task 8660
25.01 16:06:14 [Server] WARN Exception in thread "Craft Scheduler Thread - 1316" 

Could you shed any light on this?

Thanks

Bonnydust

**Comment by PyvesB** [comment]
Hello,

This issue was previously explained in the plugin documentation (it came from older Java versions), and there was a simple step to avoid it. However, I am currently pushing a new update which doesn't require tweaks from the user anymore, you should simply upgrade and it will hopefully solve your issue! ;-)

**Comment by Bonnydust** [comment]
What exactly is the step? Or what should be upgraded?

**Comment by PyvesB** [comment]
You should upgrade to version 2.3.3 of the plugin (awaiting approval on Bukkit, if you're in a hurry download on Spigot). ;-)

**Comment by PyvesB** [comment]
The initial problem was solved, I'll close issue. Feel free to star the project and don't hesitate to give any feedback in the future! :-)
