### ISSUE TITLE
Help - color usage

### ISSUE THREAD

**Issue by DutchUser** [PyvesB/AdvancedAchievements#80]
Can you add colors to it? Like &2 &5 etc,

Sorry if there are allready color support. If it do how work it?

**Comment by PyvesB** [comment]
Hello,

As stated in the header of the configuration file, _You can use Minecraft chat colors in Message|DisplayName|Goal, but include '' around the whole text: '&4Color'._ If you want to change the global color of the plugin (dark purple by default), just modify the Color option in the config.

Cheers,

Pyves

**Comment by DutchUser** [comment]
I dont really understand how it works the... I just tryit and failed in it. Can you give an example to have multple colors in an message please>?

**Comment by PyvesB** [comment]
Do you want to put colours in the message of an achievement? There are examples in the default config, under the Places section. ;-)

**Comment by DutchUser** [comment]
In both if it can. And also second, I have every file 2 times one has the normal name and the other have .bak

When i remove the .bak they are back after en restart or an plugin reload.

**Comment by PyvesB** [comment]
The .bak files are backup files, this is handled automatically by the plugin. They should not be modified or deleted unless you break the main configuration file.

**Comment by DutchUser** [comment]
So is it normal if they come when i dont have any error in console?

**Comment by PyvesB** [comment]
Yes, the backups happen automatically when the plugin is loaded and when changes are detected. Therefore you always have a copy of your previous config available.

**Comment by DutchUser** [comment]
But to come back to the color thing. What if i want "&2Nieuwe &eAchievement&2:" how do i need to fix that?

**Comment by PyvesB** [comment]
Is this in the language file? What parameter?

**Comment by DutchUser** [comment]
Its normal "New Achievement" but we are an dutch server.

**Comment by PyvesB** [comment]
This is not a parameter that is intended to be changed. If you want to nevertheless override that, you can use the _§_ instead of _&_ for the color.

**Comment by DutchUser** [comment]
I found an bug i think. Players cant unloack "Dark Oak Cutter" (default ach)

I tested myself and found out that its not working. Also something else where i place an ? to.

I checked the config and found "RestrictCreative:" default to "false" but why ist default false? Witch creative server will let this to false at all? Can not maybe set it default to true?

**Comment by PyvesB** [comment]
One issue at a time please. Have you managed to get colors working as you wanted?

**Comment by DutchUser** [comment]
Yes.

**Comment by DutchUser** [comment]
I found out how it works.
