### ISSUE TITLE
Able to retrieve items with chestsort plugin from GUI

### ISSUE THREAD

**Issue by thekyt78** [PyvesB/AdvancedAchievements#800]
Hello,

I am using a plugin called ChestSort which allows me to double click RMB to quickly pull all items from the chest into my inventory or double click LMB to push items back in.

The bug appears when I am able to do the same with the GUI items for this plugin which means I get a free elytra if I have that as a representative item. For now, I am planning to change the items to something with less worth so it doesn't matter, however, I am still able to push items back into the GUI if there are empty spaces and cause them to disappear if I close it. I believe neither of these are supposed to happen.

I have tested this with other plugins with a GUI system and this issue does not persist for them which is why I am opening an issue here. May I ask if there is anything I can do or is this a known bug?

**Comment by thekyt78** [comment]
Contacted ChestSort's dev and they managed to solve this issue!

**Comment by PyvesB** [comment]
Hello @thekyt78, glad to hear that it was promptly fixed! I would be curious to know exactly what they did to handle this, but the commit doesn't yet seem to be available on the [repository](https://github.com/JEFF-Media-GbR/Spigot-ChestSort/commits/master). 😉 

Closing as no further action is needed.
