### ISSUE TITLE
How do either of the mythic mobs spawn?

### ISSUE THREAD

**Issue by R4LS3I** [PyvesB/AdvancedAchievements#804]
You might just call it a question but i am trying to get all the achievements on a friends server and neither he, myself or anyone i know can figure out how they spawn, any tips or clues will be greatly appreciated,

Sidenote: love this plugin awesome job

**Comment by PyvesB** [comment]
Hello @R4LS3I,

You must have the Mythic Mobs plugin installed. If you don't want to use it, feel free to simply delete the achievements. 😉

**Comment by R4LS3I** [comment]
Oh awesome, since it was an achievement by default i thought it was already in the plugin

**Comment by PyvesB** [comment]
No, no, all the achievements, including the default ones, can be deleted or changed! :)
