### ISSUE TITLE
Unicode characters question

### ISSUE THREAD

**Issue by DXUltimate** [PyvesB/AdvancedAchievements#805]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Mostly, I might have missed a section if there's a Unicode character section.
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Putting in the title in did not automatically pop up related searches or issues previously put in, so I am going to presume that this minor question hasn't been asked.

:question: **Help request**

So, in the section of the config, there is a unicode character option, which clearly states the code, and then it being a shamrock clover. I was wondering if there is somewhere I could go to see all available unicode characters as I would like to change it to a heavy heart, or something else. If this is an invalid request, please feel free to close/delete this. =)

:wrench: **Configuration**

````
# Set the icon of the plugin (default: shamrock, \u2618).
Icon: \u2618
````

**Comment by PyvesB** [comment]
Hello @DXUltimate,

You can check out the unicode character codes on Wikipedia for example: https://en.wikipedia.org/wiki/List_of_Unicode_characters

Note that you don't have to use escaped unicode (i.e. `\uxxxx`), you can use a heart (💓) or any symbol directly if you've got it in your clipboard or know how to type it using your keyboard. The default config uses escaped unicode to avoid people messing things up, for example if they modify the config with a Latin-1 editor but then use it on a server which parses it as UTF-8. If you use the same encoding throughout, you shouldn't have any problems. :wink:

**Comment by DXUltimate** [comment]
You are legitimately the best. Thank you!!

**Comment by PyvesB** [comment]
> You are legitimately the best. Thank you!!

You're welcome! :)
