### ISSUE TITLE
Advancement support

### ISSUE THREAD

**Issue by deeprobin** [PyvesB/AdvancedAchievements#809]
:clipboard: **Description**

I would have suggested that if desired, in the configuration file, you can select that the advancement Packets are sent to the user and thus, the plugin, new users who are more familiar with the advancement gui also have a chance to look up their advancements.

[Minecraft Wiki: Advancement](https://minecraft.gamepedia.com/Advancement)

**Comment by PyvesB** [comment]
Hey @deeprobin,

I'm not exactly sure what you're suggesting. The _/aach generate_ command already allows generating advancements for every single achievement configured in the plugin, is that not what you're looking for?

**Comment by deeprobin** [comment]
Oh. Right. 
Thank you.
