### ISSUE TITLE
Achievements resets

### ISSUE THREAD

**Issue by blueawp** [PyvesB/AdvancedAchievements#810]
* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:question: **Help request**

So I love this plugin a lot and I added it to my server and I notice every time I restart my server the Achievements that you've done gets reset I don't know what's causing this and I'm not using a MySQL but if that's the problem I can use one.

:wrench: **Configuration**

**Comment by PyvesB** [comment]
Hi @blueawp,

Are there any errors in your server's logs?

**Comment by blueawp** [comment]
not really the only ones i can find are these
[02:00:10 WARN]: [AdvancedAchievements] Overriding configuration: disabling PetMasterGive and PetMasterReceive categories.
[02:00:10 WARN]: [AdvancedAchievements] Ensure you have placed Pet Master with a minimum version of 1.4 in your plugins folder or add PetMasterGive and PetMasterReceive to the DisabledCategories list in config.yml.

**Comment by PyvesB** [comment]
Have you checked out #802?

**Comment by blueawp** [comment]
yes my server isn't whitelisted and I'm using pterodactyl but every time I restart my server some stuff saves but everything in the Achievementsgui doesn't saves.

**Comment by PyvesB** [comment]
Normally the server logs your player UUID when you log in. Worth checking if it's the same after a restart.

**Comment by blueawp** [comment]
I restart my server my UUID still is the same maybe I should try using a database?

**Comment by PyvesB** [comment]
By default Advanced Achievements uses a H2 database which is store to disk. Maybe pterodactyl prevent that? Unsure given that it's the first time I've even heard of it.

**Comment by blueawp** [comment]
I'm looking in the config I notice that there's no database: "name" in the there?

**Comment by PyvesB** [comment]
What is the value of `DatabaseType` in Advanced Achievement's _config.yml_?

**Comment by blueawp** [comment]
its H2 but im trying to change it to MySQL

**Comment by blueawp** [comment]
Okay I fixed it thanks,  I love your plugin

**Comment by PyvesB** [comment]
Glad to hear that it's fixed! Feel free to leave a review on Spigot or star the repository 😉
