### ISSUE TITLE
Brew potion - get all achievements in seconds

### ISSUE THREAD

**Issue by R4zzerYT** [PyvesB/AdvancedAchievements#817]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes 

:beetle: **Description**

You can get all brew potion achievements very fast, if you place the brewed potions in a brew stand, pick it up and place it in the brew stand again and pick it up etc. etc. etc.

:page_facing_up: **Server logs**

````
/
````

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @R4zzerYT,

>     * [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

Are you sure? See #742 and other issues mentioning this. :wink:
