### ISSUE TITLE
Idea - meta-achievements

### ISSUE THREAD

**Issue by zquirrelz** [PyvesB/AdvancedAchievements#82]
I don't currently see a way to create achievements that require other non linear achievements.

What I mean by this is obviously break 500 stone requires that you first had to break 100 stone. What I would like to do is make a "Breaker" meta achievement that requires you complete all of the breaker category. Same could be done for the builder and other categories. I'm imagining something that looks like the below. I feel like these could fit into the "special" category in the GUI so no changes there would be needed. 

```
Meta:
   Breaker:
      RequireAch: break_stone_1,break_log_1
      Message: '&5You are a great Breaker of Things!'
      Name: breaker_meta
      DisplayName: Breaker of Things
      Reward: 
   Traveller:
      RequireAch: distancegliding_100,distanceboat_200,distanceminecart_100,<additional_required_ach>
      Message: '&5You are well Travelled'
      Name: traveller
      DisplayName: Traveller
```

**Comment by PyvesB** [comment]
Hello zquirrelz,

Thank you for your message. This feature has been requested a few times in the past and would need to be added to the plugin at some point, but it's not a straightforward task. I'm putting it on standby at the moment but keeping the issue opened as a reminder.

Cheers,

Pyves

**Comment by PyvesB** [comment]
This [third-party plugin](https://www.spigotmc.org/resources/add-group-on-achievement-advanced-achievements-luck-perms-hook.65668/) may be of interest. 😉

**Comment by PyvesB** [comment]
All achievements now support individual permissions, which means you can set one achievement's permission to false, and as another achievement's reward you switch that permission to true for a given player. For more versatility, you can use the aforementioned third-party plugin.

Considering this feature as implemented, therefore closing. 😉
