### ISSUE TITLE
Command achievements

### ISSUE THREAD

**Issue by CeleDKo** [PyvesB/AdvancedAchievements#85]
Hello, Pyusb! Such problem at me ... I did Command achievements:

> Commands:
  goodwytka:
    Message: Хорошая шутка
    Name: Вам выдан гаджет &4Веселая пушка!
    Reward:
      Command: pex user PLAYER add ultracosmetics.gadgets.fungun

Hoping that he was after the issuance of this achievement I automatically be given and the right of the gadget ultracosmetics plugin, but unfortunately for some reason this does not work.

**Comment by PyvesB** [comment]
Hello,  

Is the achievement correctly given (firework, message, etc.)? Are there any errors in the console? Does the plugin say that the reward command was processed when giving the achievement? 

Cheers, 

Pyves
