### ISSUE TITLE
Option to disable metrics.

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#87]
Would it be possible to toggle metrics disabled?

i.e. this commit from a fork.
https://github.com/AddstarMC/AdvancedAchievements/commit/c2d20341ffc10f0c42f692e309a9063af3da3afd

**Comment by PyvesB** [comment]
Hello,

You can already disable Metrics via _plugins/PluginMetrics_ if you really need to, or recompile the plugin yourself.

The data collected by Hidendra's system is anonymous and has proven useful to me on several occasions (release day planning, Minecraft versions to support for instance in release 3.0.5, popular languages to know which translators I should chase up for updates, maintaining support for Java 7 for instance in release 2.3.3, server systems to support, etc.). Wanting to disable this is simply acting against this project in my opinion, therefore I do not wish to provide an option to do that.

Cheers,

Pyves
