### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by Omanoctoa** [PyvesB/AdvancedAchievements#90]
Coming here from Spigot to suggest an idea directly...

Any chance of adding a command to show statistics for each achievement category? Basically, players are able to earn achievements based on various categories, but are not able to track progress. There is no way to list how long they have played for, for instance. We use another plugin (Statz) to track play-time, but it is off by about 3 hours and is messy, which is very confusing to players, not to mention means yet another tracking plugin using server resources. Can you create a command such as: /aach progress (category) [player] - to show how long they have played, etc?

Example commands: /aach progress playtime DarkPyves - /aach progress fishing Omanoctoa
Would show a simple breakdown of hours played for the defined player (optional). I imagine implementing proper time breakdown (days/weeks/etc) would be more of a challenge. Even just being able to see the number of hours played would be very useful though. This wouldn't need to be 100% accurate or updated constantly, as that would lead to performance issues.

Cheers!

**Comment by PyvesB** [comment]
Hello,

I will add this to a future update. Potentially I might include it directly into the _/aach list_ GUI and not as a separate command. ;-)

Cheers,

Pyves
