### ISSUE TITLE
Is it possible to define what is restricted when a player is in creative?

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#93]
I'd like to restrict achievements primarily for players only in survival mode only, but there are some achievements that I don't want to limit due to players being in creative mode, such as PlayedTime. Is it possible to be able to define which specific categories players in creative aren't allowed to be tracked in?

**Comment by PyvesB** [comment]
Hello,

This is currently not possible. In the latest GitHub revision, the _RestrictCreative_ parameter is intended as a global switch. Anyway, I think it would be confusing for players if server administrators start disabling some categories and not others in creative mode or blocked worlds.

Cheers,

Pyves
