### ISSUE TITLE
Pagination for 'top' commands.

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#94]
Possible to implement pagination for the top commands to view more than the set number in the config?

**Comment by PyvesB** [comment]
Hello,

The _TopList_ configuration parameter already brings significant flexibility on what you can see in the list. The _/aach top_ is intended to display the names of the best players on the server, and not to give a full server ranking.

For instance on my server which is relatively small, there are a total of almost 20000 players registered in the database, having this available in thousands of paginated results in the game chat would be useless for a player and unnecessarily heavy for the server.

Cheers,

Pyves

**Comment by PyvesB** [comment]
@mibby this has since then been implemented as part of #344!
