### ISSUE TITLE
Possible to define 'x' as an amount for an end-tier achievement to calculate on-going / infinite progress?

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#95]
Would it be possible to have an achievement number type to calculate on-going / infinite progress? For example;

```
Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice - I
  '5':
    Message: You connected to our server five time!
    Name: connect_5
    DisplayName: Good Choice - II
  '10':
    Message: You connected to our server ten time!
    Name: connect_10
    DisplayName: Good Choice - III
  'x':
    Message: Number of connections.
    Name: connect_x
    DisplayName: Good Choice - X
```

That way you could see your current total progress for a specific achievement category / type and compare with others. Bragging rights per say. So you could see your total playtime or number of connections. Or perhaps a command to see the number rather than in the GUI?

**Comment by PyvesB** [comment]
Hello,

What you are asking for has been requested for in a slightly different form in issue #90. The current total progress will be directly included in the GUI in a future update. 

Recurring achievements would be a dangerous way to implement the same feature, as you do not have any control over what the plugin is doing. If you set a recurring achievement that is too easy to get, you can significantly increase the load on the database and the server, and completely fill up and saturate the _/aach list_ command for a given category. The _/aach stats_ would also no longer be available.

Cheers,

Pyves
