### ISSUE TITLE
Is there a full list of all item/entity definitions that can be used?

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#96]
Is there a full list of all usable variables that can be used for every achievement category type? For example, every material name, every entity specific name, what can be used (such as 'player' to track player kills?), etc.

**Comment by Platinteufel** [comment]
# Possible items for rewards/Crafts/Places/Breaks: hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Possible mobs for the Kills section: 	  hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Default config.yml file:  github.com/PyvesB/AdvancedAchievements/blob/master/src/main/resources/config.yml
# Visit the wiki for some additional documentation: github.com/PyvesB/AdvancedAchievements/wiki

**Comment by PyvesB** [comment]
Hello,

Thanks for pointing to the relevant parts of the documentation Platinteufel!

Cheers,

Pyves
