### ISSUE TITLE
Issue with connections

### ISSUE THREAD

**Issue by SamB440** [PyvesB/AdvancedAchievements#97]
So I was trying to add an achievement for when the player connects for the tenth time, the achievement shows, but I log in and out and it shows no progress. 

> Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice
  '10':
    Message: You connected to our server for the tenth time!
    Name: connect_10
    DisplayName: Are you insane?
    Reward:
      Money: 100

**Comment by PyvesB** [comment]
Hello, 

Connections achievements are accounted for the player connects sometime during the day. To see progress, you will have to connect again the next day. ;-) 

Cheers, 

Pyves

**Comment by SamB440** [comment]
Oh okay thanks! :)

**Comment by PyvesB** [comment]
You're welcome, feel free to open a new ticket if you encounter any other issues or have any other questions. ;-)
